### ISSUE TITLE
TextClip Doesn't work at all

### ISSUE THREAD

**Issue by NewWheat** [Zulko/moviepy#1003]
When I use moviepy to create textclip, it doesn't work at all. 
My code is:

```
text_clip1 = TextClip('test', fontsize=30, color='white')

It raises OSError on both my mac and my windows computer.
OSError: MoviePy Error: creation of None failed because of the following error:

[Errno 2] No such file or directory: 'unset': 'unset'.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

I add the following code before I import moviepy:
from moviepy.config import change_settings
#change_settings({"IMAGEMAGICK_BINARY": "D:\\Program Files\\ImageMagick-7.0.7-Q16\\magick.exe"})
IMAGEMAGICK_BINARY = os.getenv ('IMAGEMAGICK_BINARY', "/usr/local/Cellar/imagemagick/7.0.8-56/bin/convert")

But I doesn't work at all. 
Any HERO can help me ?

**Comment by brainstormot** [comment]
I had same issue. But I uninstalled moviepy. And then, I cloned this repo, edit `moviepy/config_defaults.py` as **README.MD** describes and installed this library via command lines.

**Comment by narayanPCMR** [comment]
It seems to work for me

I have ImageMagick 7.0.9 Q16 x64 (Windows) installed, and while installing it, I checked the "Add application directory to your system path" option, and everything worked out

from moviepy.editor import TextClip (etc)
text_clip = TextClip("Hello", font='Arial', color='white', fontsize=72)
...

**Comment by tburrows13** [comment]
Closing as this won't be relevant in future releases
