### ISSUE TITLE
How to resize ImageClip?

### ISSUE THREAD

**Issue by NewWheat** [Zulko/moviepy#1004]
Previously ImageClip has an attribute of 'resize'. But it doesn't work now, Any one knows how to  resize now ?

AttributeError: type object 'ImageClip' has no attribute 'resize'

Thank you.

**Comment by PaperBag42** [comment]
The `resize` function is added as an attribute to `VideoClip` only when using the `moviepy.editor` module:
```py
from moviepy.editor import ImageClip

original = ImageClip('img.png')
resized = original.resize(0.5)
```

However, you can import it directly from the `moviepy.video.fx.resize` module and use it like so:

```py
from moviepy.video.VideoClip import ImageClip
from moviepy.video.fx.resize import resize

original = ImageClip('img.png')
resized = resize(original, 0.5)
```

**Comment by keikoro** [comment]
@ArturoHULK You're commenting on a 6-year-old, long closed issue. If you have a question about or are experiencing an issue with the latest MoviePy version, please open a new issue.
