### ISSUE TITLE
Audio glitches when using concatenate_videoclips.

### ISSUE THREAD

**Issue by josewails** [Zulko/moviepy#1005]
I have written a function that creates a bunch of video clips and then finally combines them into one. 

`
    def process_video(self):

        """

        This combines the text and audio into a video

        """

        intermediate_clips = list()

        n = len(self.audio_paths)

        first_clip = self.make_first_clip()
        last_clip = self.make_last_clip()

        for i in range(1, n - 1):
            self.current_index = i

            intermediate_clips.append(self.make_sliding_video_clip())
            intermediate_clips.append(self.make_video_clip())

        self.current_index = 0
        final_clips = [first_clip] + intermediate_clips + [last_clip]

        final_clip = concatenate_videoclips(final_clips, method='compose')
        final_clip.write_videofile('final.mp4', fps=60, codec='mpeg4')
`

However, the resulting clip has some audio glitches. 

Here is the resulting video. [https://www.youtube.com/watch?v=QYURIo3dWPk](url). If you watch it, you will realize there are a couple of glitches at the end of the clips. Doesn't happen all the time but sometimes. 

Any ideas on how to avoid those glitches?

**Comment by Zulko** [comment]
I can't hear much glitching, but the best way to remove it would be to add a 0.01 second audio fade-in/fade-out in all your clips:

```python
final_clips = [
    clip.audio_fadein(0.01).audio_fadeout(0.01)
    for clip in ([first_clip] + intermediate_clips + [last_clip])
]
```

**Comment by josewails** [comment]
@Zulko. Thanks a lot for this. The audio_fade effect did the trick.

**Comment by jake-nz** [comment]
This problem has been reported many many times.
https://github.com/Zulko/moviepy/issues/1854
https://github.com/Zulko/moviepy/issues/1005
https://github.com/Zulko/moviepy/issues/1717
https://github.com/Zulko/moviepy/issues/1710
https://github.com/Zulko/moviepy/issues/1936

Here's the root cause: https://github.com/Zulko/moviepy/issues/1936#issuecomment-1740785869
