### ISSUE TITLE
Problem using .avi file

### ISSUE THREAD

**Issue by mcdonasd** [Zulko/moviepy#1009]
clip_1 = VideoFileClip("c:/sandbox/out1.avi")

OSError: MoviePy error: failed to read the duration of file c:\sandbox\out1.avi.

also tried

clip_1 = VideoFileClip("c:\sandbox\out1.avi",audio=False, fps_source='fps')

same error... 

what am I missing?

Python 3.7

**Comment by keikoro** [comment]
I think we are missing too much info here, like an example file with which we could try to reproduce the issue with (or more code). Closing this also as it's older than 2 years.
