### ISSUE TITLE
Problem with importing VideoClip

### ISSUE THREAD

**Issue by vic1309** [Zulko/moviepy#1010]
When I try to

    from moviepy.editor import VideoClip

I get the following error message:

```
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'
```

I have already installed imageio-ffmpeg but the issue persists.

Python version: 3.7.3

**Comment by arianaa30** [comment]
I have the same problem.

**Comment by arianaa30** [comment]
The error was gone when I installed from GIT source code!

`python install setup.py`

**Comment by sarahdays** [comment]
try the following instead: 

`from moviepy.editor import *`

**Comment by keikoro** [comment]
@vic1309 @arianaa30 Did the suggestion in the thread help you resolve your problem? Looking to close this issue.

**Comment by mondeja** [comment]
This was an error produced by imageio update from [v2.4.1 to v2.5.0](https://github.com/imageio/imageio/blob/master/CHANGELOG.md#250---2019-02-06), reported [here](https://superuser.com/questions/1402892/runtimeerror-imageio-ffmpeg-download-has-been-deprecated-use-pip-install-im). Current dependent version is greater than v2.5.0, so I'm closing this...
