### ISSUE TITLE
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'

### ISSUE THREAD

**Issue by arianaa30** [Zulko/moviepy#1011]
I'm simply trying to do 

`from moviepy.editor import VideoFileClip`

But I get this error:

`RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'`

People say I have to downgrade to previous version of imageio. But `pip install imageio==2.4.1` also doesn't work as moviepy relies on it:

`ERROR: moviepy 1.0.0 has requirement imageio<3.0,>=2.5; python_version >= "3.4", but you'll have imageio 2.4.1 which is incompatible.`

What should I do?!

**Comment by HyperOs89** [comment]
I am having the exact same problem.

**Comment by Danmou** [comment]
Use `pip install 'imageio==2.4.1' 'moviepy<1.0'`. I don't know why the developer hasn't fixed this yet, it looks like a very simple fix.

**Comment by tburrows13** [comment]
This has now been fixed.
