### ISSUE TITLE
write_gif() using ImageMagick fails silently

### ISSUE THREAD

**Issue by Tempest3** [Zulko/moviepy#1012]
### Expected Behavior
Using write_gif() on a VideoFileClip or a CompositeVideoClip with the parameters program='ImageMagick' and either proc='optimizeplus' or proc='optimizetransparency' parameters should output a GIF to the specified location.

### Actual Behavior
Program indicates that file has been created successfully, but no file has been generated.

```MoviePy - Building file  G:\outfile\GIF_1.gif
MoviePy - - Generating GIF frames.
MoviePy - - Optimizing GIF with ImageMagick.
MoviePy - - File ready: G:\outfile\GIF_1.gif.
```
(No file of that name appears in the outfile folder. Using default write_gif parameters generates a gif, although the file size is atrociously large)

### Steps to Reproduce the Problem

Simply pass in arguments to generate a gif using ImageMagick, and the bug will occur.
```
#videoFileLoc, srtFileLoc & outFileLoc defined elsewhere, all confirmed to work
generator = lambda txt: TextClip(txt, font='Impact', fontsize=36, color='white')
video = VideoFileClip(videoFileLoc)
sub = SubtitlesClip(srtFileLoc, generator).set_position(("center", "bottom"), relative=True)	
composite = CompositeVideoClip([video, sub])
composite = composite.subclip(startTime, endTime)
composite.write_gif(outFileLoc, program='ImageMagick', opt='optimizeplus')
```
### Steps Taken to Troubleshoot
 - I've modified the appropriate config file to point to the ImageMagick binary.
 - I've run the version of the write_gif() function which uses temp files, and encountered exactly the same behavior.
 - I've tested modifying the moviepy write_gif() function to print where it thinks the ImageMagick binary is located and to print all the arguments being passed.
 + Result: The ImageMagick binary is being pointed to in the subprocess call, and the arguments appear well formed?
 - I've tested writing my own subprocess call to launch ImageMagick and optimize the gif produced by the default write_gif() function.
 ```
#arguments for ImageMagick systemcall
args = []
args.append(IMAGEMAGICK_BINARY)
args.append(outfile)
args.extend(("-fuzz","10%","-layers","optimizeplus","-colors","24"))
args.append(outfile)
proc = subprocess.Popen(args)
print("Compressing GIF, please wait...")
proc.wait()
```
 + Result: The subprocess call works perfectly, but is not a favorable solution due to writing and reading to disk multiple times (write_gif() saves to disk, then I read from that file with ImageMagick and write back, faster if done in memory).

### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.0 (tested from github and pip)
  - Platform Name: Windows (and Ubuntu)
  - Platform Version: 10 (and 19.04 Ubuntu)

### Update:
After messing around with various versions of the gif_writers.py file, I was able to concoct a version which would display error messages from ImageMagick, at which point the following error message was displayed each time I tried to generate a gif as described above:
```
magick.exe: length and filesize do not match `C:/Users/konra/AppData/Local/Temp/magick-142683rGz9WOnTEqj' @ warning/bmp.c/ReadBMPImage/834.
magick.exe: improper image header `C:/Users/konra/AppData/Local/Temp/magick-142683rGz9WOnTEqj' @ error/bmp.c/ReadBMPImage/952.
magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560.
```

**Comment by Oj18** [comment]
I also have this problem, and have had it my entire time using `moviepy`. Even using `v1.0.1` which is supposed to fix some `ImageMagick` bugs, still says it's generating and gives a progress bar but no GIF is made. Checked everywhere on my disk for the output to make sure it wasn't saving it somewhere else, still can't anything.

**Comment by Tempest3** [comment]
Upon further testing/editing/tweaking, I've discovered that using other formats shared between ffmpeg's muxer and imagemagick _does_ work. Ones I've tested successfully so far are avi and gif. The issue appears to be something with the default command (below)
`proc1 = sp.Popen(cmd1+ ['-f', 'image2pipe', '-vcodec', 'bmp, '-'],
                         **popen_params)`

Working code:
` proc1 = sp.Popen(cmd1+ ['-f', 'gif', '-'],
                         **popen_params)`

**Comment by tburrows13** [comment]
We'll be removing the ImageMagick write_gif option in v2.0 as it is more trouble than it is worth.
