### ISSUE TITLE
CUDA / NVENC / HEVC Anyone?

### ISSUE THREAD

**Issue by AIT-OLPE** [Zulko/moviepy#1014]
Hello,

Have anyone got this to work with CUDA? In more detail, has anyone got FFMPEG NVENC with MoviePy as a wrapper to work? I create some videos daily that takes hours to create with normal CPU usage. Cuda would be great in this case, but I love MoviePy as a simple wrapper.

**Comment by AndersonBY** [comment]
modify \site-packages\moviepy\video\io\ffmpeg_writer.py
insert: '-hwaccel', 'cuvid' in cmd like this

        cmd = [
            get_setting("FFMPEG_BINARY"),
            '-hwaccel', 'cuvid',
            '-y',
            '-loglevel', 'error' if logfile == sp.PIPE else 'info',
            '-f', 'rawvideo',
            '-vcodec', 'rawvideo',
            '-s', '%dx%d' % (size[0], size[1]),
            '-pix_fmt', 'rgba' if withmask else 'rgb24',
            '-r', '%.02f' % fps,
            '-i', '-', '-an',
        ]

then you can use codec='h264_nvenc' when write_videofile

**Comment by oe19fyfa** [comment]
Hey guys, the fix didnt help :( 

I have:
ffmpeg version 4.2 
python version 3.7

After adding the '-hwaccel', 'cuvid' to the ffmpeg_writer.py and calling:
`out_video.write_videofile(output_video_path, fps=self.frames, codec='h264_nvenc')`
I still can observe that the video encoding runs on CPU instead of gpu...

**Comment by tburrows13** [comment]
Do the suggestions at #790 help?

**Comment by oe19fyfa** [comment]
@tburrows13 nope, while the command `ffmpeg -hwaccel cuvid -c:v h264_cuvid -i heavy_load.mp4 -c:v h264_nvenc -preset slow heavy_out.mp4` does work for me in the anaconda environment, and i can see its correspondingly running on the gpu

**Comment by keikoro** [comment]
Closing this as a solution was proposed to OP's question; the user asking a follow-up question does not exist anymore, so we can't follow up on their issue.

**Comment by MASSKAgithub** [comment]
loooserrsss

Using moviepy but almost nobody tried to do it with gpu acceleration? what a joke

**Comment by raniaamina** [comment]
i just add this to work with NVIDIA GPU;

from moviepy.config import change_settings
change_settings({"FFMPEG_BINARY":"ffmpeg"})

final_clip.write_videofile(combined_video_path, threads=thread_count, codec="h264_nvenc")

**Comment by AhanR** [comment]
> i just add this to work with NVIDIA GPU;
> 
> from moviepy.config import change_settings change_settings({"FFMPEG_BINARY":"ffmpeg"})
> 
> final_clip.write_videofile(combined_video_path, threads=thread_count, codec="h264_nvenc")

So, I'm using this code inside google colab but this code does not work for me. The processing speed remains the same.

**Comment by Goosegit11** [comment]
Yep, there's no way to get MoviePy to work with GPU.
All this cope with `codec="h264_nvenc"` only worsens the quality and speed is always the same.

Use ffmpeg, it's a lot faster.
