### ISSUE TITLE
Need example source code for logo with a moving shadow

### ISSUE THREAD

**Issue by davyzhen** [Zulko/moviepy#1015]
Hi,
Anyone has this example source code ?

https://zulko.github.io/moviepy/examples/logo.html

Thanks,

**Comment by nb-programmer** [comment]
Of course, it's present in the /examples folder:
https://github.com/Zulko/moviepy/blob/master/examples/logo.py

Edit: since the upgrade to v2.0, some examples were removed. The same example is now in the v1.0 branch:
https://github.com/Zulko/moviepy/blob/v1.0.x/examples/logo.py

**Comment by keikoro** [comment]
@davyzhen closing this as it sounds like @nb-programmer answered your question (thanks!).
