### ISSUE TITLE
Can we get the timing from audioClip while in preview?

### ISSUE THREAD

**Issue by sunilk-n** [Zulko/moviepy#1024]
I'm wondering if the audioFileClip when previewing, can we get the timing to display?
If we can get the current timing while preview is running. It will be a plus point

**Comment by tburrows13** [comment]
Hi, thanks for the suggestion. Its a good one, however the previewing code is pretty basic at the moment so there's no way to display timings in the PyGame display. It probably wouldn't be that hard for someone familiar with PyGame though.

In the video preview we have a feature where if you click on the window it prints the position and time of the click to the console. I've just gone through the audio code and hacked together a quick equivalent for the audio: https://github.com/tburrows13/moviepy/tree/preview-update
On macOS, a PyGame program opens up when you import moviepy, so you can just click on the program to give it focus whilst an audio file is playing, press space and it will print the current time.

Let me know if it works, however, I'm not sure it should be merged to the main repo.

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.
