### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by arianaa30** [Zulko/moviepy#1026]
This is another error I get on my Windows. Sometimes it runs, next time it fails for the same code.

What's the problem? Am I doing anything wrong?! 
```
        for f in os.listdir(dirname):
            fn = dirname+'/'+f
            print("filename: "+fn)
            c = VideoFileClip(fn) #this line causes problems
            duration = c.duration
            print("duration: "+str(duration))
            if int(duration) > float(length/parts):
                # do some stuff
            c.close()
```

```
Traceback (most recent call last):
  File ".\mycode.py", line 136, in <module>
    test_api(filename, duration)
  File ".\mycode.py", line 90, in test_api
    c = VideoFileClip(fn)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\moviepy\video\io\ffmpeg_reader.py", line 69, in __init__
    self.initialize()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\moviepy\video\io\ffmpeg_reader.py", line 104, in initialize
    self.proc = sp.Popen(cmd, **popen_params)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 664, in __init__
    _cleanup()
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 228, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1216, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
```

**Comment by tburrows13** [comment]
Unfortunately this error is part of a larger problem in moviepy to do with opening and closing files. There is no easy fix that works across windows and unix, so it needs someone to really dig in and understand what we are doing wrong.

**Comment by arianaa30** [comment]
Yeah only on Windows. And apparently when I reset machine, it runs. Linux is working fine though.

**Comment by tburrows13** [comment]
Linking #1066.

**Comment by inimaz** [comment]
This might be related to a bug in Python --> https://bugs.python.org/issue37380
it has been solved for Python 3.9, Python 3.8, Python 3.7.

For me there was no need to migrate to those Python versions, I just applied the changes from the PR they mention --> https://github.com/python/cpython/pull/15707/files
And now the error is displayed, but it keeps working and runs smoothly, so it acts more like a warning.

**Comment by tburrows13** [comment]
I'm closing this as it should be fixed in v1.0.3, and is definitely fixed in Python 3.7 as @inimz says. Please create a new issue if you are still experiencing this problem.

**Comment by qris** [comment]
> This might be related to a bug in Python --> https://bugs.python.org/issue37380

For posterity, https://github.com/python/cpython/issues/81561 is a better reference for this issue.

**Comment by MohamedIburahim** [comment]
My_code:-

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec

# Setup WebDriver
def init_driver():
    driver_ = webdriver.Chrome()
    driver_.get("https://www.lea-uitgevers.be/")
    return driver_

def process():
    driver_ = init_driver()
    #hamburger click
    hamburger_xpath = '//*[@id="top_menu_container"]/div[1]/button/span'
    hamburger_link = driver_.find_element(By.XPATH,hamburger_xpath)
    hamburger_link.click()
    print("Hamburger clicked")

    #boeken click
    boeken_xpath = '//*[@id="top_menu"]/li[2]/a'
    boeken_link = WebDriverWait(driver_,10).until(ec.presence_of_element_located((By.XPATH,boeken_xpath)))
    driver_.implicitly_wait(10)
    boeken_link.click()
    print("Boeken link clicked")

    driver_.close()

#Run the script
if __name__ == "__main__":
    process()


Error:-
Hamburger clicked
Boeken link clicked
Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Mohamediburahim.p\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mohamediburahim.p\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1688, in terminate
    _winapi.TerminateProcess(self._handle, 1)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid


Is anyone solve this error

**Comment by tburrows13** [comment]
@MohamedIburahim are you even using moviepy…?

**Comment by OsaAjani** [comment]
I just deleted this trash of a comment...
