### ISSUE TITLE
loop for concatenate_videoclips

### ISSUE THREAD

**Issue by arianaa30** [Zulko/moviepy#1027]
How can I do the following command in a for loop? Right now it is hardcoded for only 4 subs. I need to extend it to **n** subs.

`    final = concatenate_videoclips([sub[0], sub[1].crossfadein(.5), sub[2].crossfadein(.5), sub[3].crossfadein(.5)], padding=-1, method="compose")`

Any subs after [0] need to have a crossfadein effect.

**Comment by tburrows13** [comment]
I think this does what you're looking for:

```
crossfadedsub = []
for clip in sub[1:]:  # Iterate over the list except for the first item
    crossfadedsub.append(clip.crossfadein(0.5))
final = concatenate_videoclips([sub[0]] + crossfadedsub, padding=-1, method="compose")
```

**Comment by Zulko** [comment]
Rah Tom beat me to it but here is an alternative with list comprehensions:

```python
faded_clips = [sub[0]] + [clip.crossfadein(0.5) for clip in sub[1:]]
final = concatenate_videoclips(faded_clips, padding=-1, method="compose")
```

Note that, as this is more a Python question than a Moviepy question, you'd get faster answers by posting a question on Stackoverflow or Reddit/Python.
