### ISSUE TITLE
BLANK VIDEO?

### ISSUE THREAD

**Issue by sarahdays** [Zulko/moviepy#1031]
hi there i'm new to programming. 
I had a hard time installing moviepy successfully 

I am trying to make something similar to this: 
https://zulko.github.io/moviepy/examples/compo_from_image.html

I modified this source code, but when i output my video, its just a black video. I added print statements and everything runs with no errors. 

This is my code: 

```
from moviepy.editor import *
from moviepy.video.tools.segmenting import findObjects

# Load template
im = ImageClip("circletemplate.jpg")
print("template loaded")

# Locate template areas where video will be placed
regions = findObjects(im)
print("regions found")

#select video
clips = [VideoFileClip(n,audio=False).subclip(1,9) for n in
        ["clipa.mp4","clipb.mp4" , "clipc.mp4" , "clipd.mp4"]]

print("clips placed in list")






# fit each clip into its region
comp_clips =  [c.resize(r.size).set_mask(r.mask).set_pos(r.screenpos)
                  for c,r in zip(clips,regions)]


print("clips are being placed on template")

cc = CompositeVideoClip(comp_clips,im.size)
cc.resize((360, 180))
print("video is resized")

cc.write_videofile("/home/pi/Desktop/video1.mp4")
```

**Comment by gintdm** [comment]
try cc.write_videofile("video.mp4")

**Comment by phani12321** [comment]
Hi 
I am running into the same issue. Is there any solution yet ? For some reason I am unable to view the above bug.

**Comment by bpops** [comment]
Also same issue here. v1.0.3.

**Comment by aorhancom** [comment]
Hello there,

I tried too, but it didn't work. I am using the same code as in the example. Even the picture is the same, only the video is different, but it still gives the result of blank video. There is no error. I added different videos to see if it was from the video, but the result is the same.

Can you help me ?

**Comment by keikoro** [comment]
Closing this issue as it's old and missing information we request when creating new issues. It also hasn't seen any reaction from OP in several years.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
