### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by CtrlAlt-Delete** [Zulko/moviepy#1048]
I am having some trouble running 
`from moviepy.editor import VideoFileClip, concatenate`
where I get the error 
`python3: Relink /home/jonathan/.local/lib/python3.6/site-packages/PIL/.libs/./liblzma-6cd627ed.so.5.2.4' with /lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol clock_gettime
Segmentation fault (core dumped)`

What could be the issue here? I am somewhat new to this, I only have basic knowledge from one course in uni. 

Thanks in advance

**Comment by makelove** [comment]
same problem
when I am building docker with  ubuntu:18.04
history:
```
    1  apt-get update
    2  apt-get -y install locales tzdata
    3  apt-get install python3-pip
    4  python3
    5  pip
    6  pip3
    7  vi requirements.txt
    8  apt install nano
    9  nano requirements.txt
   10  pip3 install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --no-cache-dir -r requirements.txt
   11  apt-get -y install imagemagick
   12  ipython
```

```
root@43ffc12d6d7d:/# ipython
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from moviepy.editor import TextClip
/usr/bin/python3: Relink `/usr/local/lib/python3.6/dist-packages/PIL/.libs/./liblzma-6cd627ed.so.5.2.4' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
root@43ffc12d6d7d:/#
```

**Comment by makelove** [comment]
docker run --name movie19 -it -v `pwd`:/test ubuntu:19.04

is ok
didn't show that error

**Comment by makelove** [comment]
error is caused by opencv

Fixed
pip3 uninstall opencv-contrib-python

welcome to use my docker
https://hub.docker.com/r/play4fun/moviepy_chinese_font

**Comment by CtrlAlt-Delete** [comment]
I tried that but had no luck. What I did was reset Ubuntu (I use the terminal on Windows), and then got all necessary packages and it worked. A pretty ugly solution but effective

**Comment by kurkurzz** [comment]
I am using moviepy in AWS Lambda and got this similar error. What is the solution?
