### ISSUE TITLE
Is there a way to convert a VideoClipFile() to a binary stream in memory?

### ISSUE THREAD

**Issue by exnx** [Zulko/moviepy#1049]
Hi, I am trying to convert a VideoClipFile that's already loaded into memory and convert to a binary stream so that I can save it to a cloud storage system.  However, the cloud storage system only accepts binary streams, so I can't just use the normal save.  The other option is to write the binary stream to file, then open it as a binary stream, but if I have thousands of videos that's going to be too costly.  Thanks for the help.

**Comment by OD1995** [comment]
@exnx Did you find a solution for this?

**Comment by keikoro** [comment]
@exnx Were you asking for a new feature to be added? Closing until we hear back.
