### ISSUE TITLE
Audio details using get_frame

### ISSUE THREAD

**Issue by amanvars** [Zulko/moviepy#1050]
HI,
I have a sound with some beeps of 0.10 second at fixed intervals and I want to extract that particular time audio details as I will be using these details to compare with other sound files.
I am using below code to get frames details.

```
video = VideoFileClip('test_video3.mp4')
audio = video.audio
# audio.write_audiofile('custom.wav')
duration = video.duration # == audio.duration, presented in seconds, float
print(duration)
#note video.fps != audio.fps
step = 0.1
f = open("aframe.txt", "a")
for t in range(int(duration / step)): # runs through audio/video frames obtaining them by timestamp with step 100 msec
    t = t * step
    t = round(t,2)
    print(t)

    if t > audio.duration or t > video.duration: break
    audio_frame = audio.get_frame(t) #numpy array representing mono/stereo values
    f.write(str(audio_frame)+"\n")
	# print(audio_frame)
    if audio_frame[0] > 0 or audio_frame[1]>0:
	    video_frame = video.get_frame(t) #numpy array representing RGB/gray frame
	    video.save_frame("pics/"+str(t)+".png", t=t)
	    filename = "pics/"+str(t)+".png"
	    text = pytesseract.image_to_string(Image.open(filename))
	    print(text)

f.close()
```
Kindly help me.

Thanks in advance.
Aman

**Comment by keikoro** [comment]
Closing this issue as it's old and missing specs we ask for in our issue templates. It's also unclear to me which part exactly you were struggling with.

When you've tried again with the latest master (not the last PyPI release) and continue to have problems, do let us know, and please update the issue with the required details.
