### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jv80** [Zulko/moviepy#1055]
### Expected Behavior
Concatenate two videos using moviepy module.

### Actual Behavior
I got a  **ModuleNotFoundError: No module nameed 'moviepy'**

![error2](https://user-images.githubusercontent.com/33995055/71635445-848dbb00-2bd9-11ea-9013-9d0eb37f8ace.PNG)

### Steps to Reproduce the Problem

Details:

- The methodology of installation:

1. I Created an environment using Anaconda Navigator 1.9.7
2. Using a terminal of the environment created, I installed moviepy. The installation of moviepy was successful.
3. I opened a jupyter lab notebook and I ran the following sentences:

```
from moviepy.editor import VideoFileClip, concatenate_videoclips

clip1 = VideoFileClip("myvideo1.avi")

clip2 = VideoFileClip("myvideo2.avi")

final_clip = concatenate_videoclips([clip1,clip2])

final_clip.write_videofile("my_concatenation.avi")
```

4.-I obtained the error showed above.

- I created different environments and I used different ways to install moviepy, in order to discard any installation issues that could produce the error (**ModuleNotFoundError: No module nameed 'moviepy'**):

     1. pip install moviepy

     2.conda install moviepy

     3.pip install --trusted-host pypi.python.org moviepy

     4.conda install -c conda-forge moviepy

     5.conda install -c conda-forge/label/gcc7 moviepy

I obtained the same error **ModuleNotFoundError: No module nameed 'moviepy'**.

### Specifications

  - Python Version: 3.7.0
  - Moviepy Version: 0.2.3.5
  - Platform Name: Anaconda
  - Platform Version: 1.9.7

**Comment by gintdm** [comment]
Were you able to resolve this issue on your own?

**Comment by jv80** [comment]
Hi! No, I am still having this issue.

**Comment by naman23awasthi** [comment]
Try seeing if the jupyter notebook you access has the same environment as the environment you installed moviepy. Usually, when jupyter notebook is not installed on the environment, it is called from the default (base) environment and it accesses python packages in base environment.  A quick way to check this is
on your terminal, 
$ conda activate <your env name>
(your env name)$ python
(This would open python on terminal)
(Now try importing moviepy in this terminal python. If you can open it, your jupyter is unable to access moviepy. A simple fix is to close python terminal by exit() and then installing jupyter notebook in the current environment)

**Comment by tburrows13** [comment]
This isn't really a moviepy related problem, so I'm closing this.

**Comment by tburrows13** [comment]
This isn't really a moviepy related problem, so I'm closing this.
