### ISSUE TITLE
imageio has permission problems as WSGI user on Amazon Web Server

### ISSUE THREAD

**Issue by amalgamatedclyde** [Zulko/moviepy#106]
everything was running great but imageio killed me! (not that i am ungrateful for your excellent module!!!)

**Comment by almarklein** [comment]
I fixed this by resorting to `/var/tmp` when `~/` is not possible. I plan to release a new version next week.

**Comment by amaglamatedclyde** [comment]
excellent!


-------- Original Message --------
Subject: Re: [moviepy] imageio has permission problems as WSGI user on
Amazon Web Server (#106)

**Comment by kerstin** [comment]
Looks like this was solved on imageio's side. Closing.
