### ISSUE TITLE
FIX: OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by shin-illua** [Zulko/moviepy#1066]
If you every encounter this error in the future, you can try this tweak and see if it works for you. You basically have to edit the subprocess module. NOTE: This is only for windows, haven't tested it on linux. AND USE IT AT YOUR OWN RISK! 

* Open subprocess.py (C:\Python\Python37\Lib\subprocess.py) 
* Find the class definition of Popen: 
![image](https://user-images.githubusercontent.com/44135157/73137177-5db78d00-4090-11ea-82e0-fae76bfc7987.png)
* go to `def __init__(....):` and comment this code:
![image](https://user-images.githubusercontent.com/44135157/73137199-8fc8ef00-4090-11ea-9739-524c7424a7b6.png)

Furthur reference: https://bugs.python.org/issue37380

**Comment by tburrows13** [comment]
Thanks for noting this. I managed to get around it in versions of Python before v3.7 by adding in `self.proc.wait()` in #1185, so hopefully this issue does not reappear.
