### ISSUE TITLE
Ability to set fps of VideoFileClip

### ISSUE THREAD

**Issue by garyo** [Zulko/moviepy#1069]
FFMPEG supports a "video file name" of `image-%04d.png`, and moviepy accepts this in `VideoFileClip()` which is great. But unfortunately it assumes 25 fps, and I don't see any way to change that. I can call `clip=clip.set_fps(24)` but that doesn't change the duration - I think it just skips frames.

It would be great if `VideoFileClip` could accept an optional `fps` arg for this case.

**Comment by tburrows13** [comment]
As a workaround until this feature is added you can use `.speedx()` in conjunction with `.set_fps()`.

E.g. 
`clip = clip.speedx(24/25).set_fps(24)`

**Comment by tburrows13** [comment]
For reference for anyone wanting to implement this, I'd suggest a new optional parameter in `.set_fps()` called something like `change_duration` set to False by default. Then if it is true call `speedx` as I suggested above.

**Comment by badsketch** [comment]
I'd like to give this a shot 🙂

**Comment by tburrows13** [comment]
Thanks for offering however in this case I think that @mxbi may have already done it. No PR yet though...
