### ISSUE TITLE
Why the output size cannot be odd?

### ISSUE THREAD

**Issue by CachCheng** [Zulko/moviepy#1072]
### Specifications

  - Python Version:
  - Moviepy Version:
  - Platform Name:
  - Platform Version:

**Comment by tburrows13** [comment]
Most media players won't be able to cope with a video of odd dimensions. You can use the moviepy fx `even_size()` to resize your video before writing it out to a file to ensure that it has even dimensions (note that in versions before v2.0, `even_size()` always returns a video with *odd* dimensions).
