### ISSUE TITLE
unable to create video from images

### ISSUE THREAD

**Issue by inzack** [Zulko/moviepy#1074]
### Expected Behavior

video should be created successfully with all images 

### Actual Behavior

video is created with first image, it is not going to other images.

### Steps to Reproduce the Problem

import moviepy.editor as mp
from moviepy.editor import *

data_path = os.path.join("\\images\\",'*g')

fps1 = [ImageClip(m)
         for m in glob.glob(data_path)]

merged_clip = mp.concatenate_videoclips(fps1, method="chain")

audioclip = AudioFileClip("\\alisha.mp3")
videoclip = merged_clip.set_audio(audioclip)
videoclip.write_videofile("test4.mp4",fps=28)

i tried with the below link its not working out.
https://github.com/Zulko/moviepy/issues/285

### Specifications

  - Python Version: python 3.8.1
  - Moviepy Version: 1.0.1
  - Platform Name: windows
  - Platform Version: 10

**Comment by inzack** [comment]
The issue is fixed.

The issue was images i used, earlier the images were 200kb, 1mb etc but later i understood that all images should be below 28KB and possibly jpg files.

Other changes were as follows
 clips.append(VideoFileClip("E:\\images\\"+ file).set_duration(10))
video = concatenate_videoclips( clips,method='compose')


Please let me know how to increase the image size

**Comment by chitpohtoo20-a11y** [comment]
from moviepy.editor import ImageClip, concatenate_videoclips

# File paths for the images (user would need to upload these for local execution)
image_path_black = "/mnt/data/black_tshirt.jpg"

# Create a clip for the black t-shirt image
clip_black = ImageClip(image_path_black).set_duration(4)  # Show for 4 seconds

# Create the final video (only black image slideshow as requested)
final_video = concatenate_videoclips([clip_black], method="compose")

# Export the video
output_path = "/mnt/data/black_tshirt_slideshow.mp4"
final_video.write_videofile(output_path, fps=24)
