### ISSUE TITLE
URGENT - Documentation is inaccessible

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1086]
I successfully built an updated version of the documentation, and committed it to a new `gh-pages` branch. It wouldn't let me merge the branch onto the master `gh-pages` branch because they didn't share a commit history, so I deleted the master `gh-pages` branch and pushed directly to a new `gh-pages` from my own.

The correct html is now in branch `gh-pages` but for some reason it does not show up at http://zulko.github.io/moviepy/
This might be to do with the GitHub Pages settings inside of Settings being reset when I deleted the `gh-pages` branch. Only @Zulko has access to these settings.

Sorry to spring this on you, hopefully it is a quick fix!

**Comment by Zulko** [comment]
Looks like it's fixed. For the record I changed the documentation branch to master, waited a bit, then changed it back to gh-pages. Maybe simply pushing a new commit would have fixed it too. Gh-pages are always slow to update btw sometimes you only see your changes after a.few minutes. Thanks for all your efforts. I handed over many projects last week, and may have more time to look into issues in the future.

**Comment by tburrows13** [comment]
Thank you for your prompt response! Hopefully no one noticed the down time :) I'll try a less destructive method next time.

While we're on the topic, it would be nice if you could "Enforce HTTPS" in the GitHub Pages settings and change the link in the project description to use https.
