### ISSUE TITLE
Invalid buffer size, packet size < expected frame_size

### ISSUE THREAD

**Issue by elondon** [Zulko/moviepy#109]
Python 3.4.2
Mac OSX Yosemite 10.10.1
MoviePy 0.2.2.02 with numpy, decorator, imageio, tqdm

See this zip:

https://drive.google.com/open?id=0B9OPimizVkkIMUlWZTVCRXlVQzA&authuser=0

When concatenating the jpg with a 7 second duration to the MOV file, result.mp4 is produced.

With a log indicating:

rawvideo @ 0x7fdfbc000000] Invalid buffer size, packet size 22063104 < expected frame_size 23970816
Error while decoding stream #0:0: Invalid argument

Script used is:

```
from moviepy.editor import *

before = (ImageClip('3_my-new-mug-warmer_photo.jpg')
          .set_duration(7.0))

video = VideoFileClip("2_dog-still-scared_video.MOV") 

final_clip = concatenate_videoclips([before, video])
final_clip.write_videofile('story.mp4', fps=30, bitrate='8000k', write_logfile=True)
```

**Comment by kerstin** [comment]
The file provided by OP is not accessible anymore and there haven't been any updates on this issue in 2+ years, so I'm closing it.

Please consider reopening it if the problem persists.
