### ISSUE TITLE
FFMPEG Installation on VPS

### ISSUE THREAD

**Issue by cilusmedia** [Zulko/moviepy#1094]
Hello Guys,

Please I need support for the following Issues...

I got VPS from bluehost with assuarance they were going to help me set it up...
I wanted to Install OSSN on the VPS.

But they couldn't give me the assisstance I wanted, some how I managed to install OSSN...
Now my issues are:

The OSSN application needs me to install FFMPEG on my VPS to enable the video component work very well.

I need assisstance on how to install ffmpeg on my VPS.
Thanks allot.

**Comment by tburrows13** [comment]
Are you trying to use moviepy itself? If you are just looking for help with FFMPEG, this is the wrong place to ask. Try https://www.ffmpeg.org/contact.html#Forums or https://superuser.com/questions/tagged/ffmpeg.
