### ISSUE TITLE
Formatting code with Black

### ISSUE THREAD

**Issue by mgaitan** [Zulko/moviepy#1097]
I propose to enforce code formatting with [Black](https://github.com/psf/black)

Consider the arguments developed in https://github.com/django/deps/blob/master/accepted/0008-black.rst

- There's no debate about the usefulness of readable code formatting. 
- With automated code formatting, this workload can be transferred to computers, saving human bandwidth for higher value-added activities.
- It's about making our Python code look as much as possible like what everyone else in the Python community writes.

**Comment by tburrows13** [comment]
Yes please! I suppose the best way would be to run it on the entire project locally and submit that as a PR. Then use some tool like https://github.com/marketplace/actions/black-code-formatter to keep it consistent?

**Comment by mgaitan** [comment]
Implemented here https://github.com/mgaitan/moviepy/pull/1

I'll open the proper PR after #1077 be merged.
