### ISSUE TITLE
Cannot create TextClip

### ISSUE THREAD

**Issue by jossiekat** [Zulko/moviepy#1099]
I was able to use moviepy with no problems.
I tried to overlay text using textclip and got errors
I have image click installed.
```
from moviepy.editor import *

clip = TextClip("Hello !", fontsize=70, color="black")


```

### Actual Behavior
```
OSError: convert: unable to read font `Courier' @ warning/annotate.c/RenderType/960.
convert: unable to read font `Courier' @ error/annotate.c/RenderFreetype/1391.
convert: no images defined `PNG32:/var/folders/6k/5s73_x7s0y3bv81fvrvp3pzc0000gn/T/tmpkp0ue1mo.png' @ error/convert.c/ConvertImageCommand/3282.
```

also:
```
TextClip.list('font') 
```
returns []

### Specifications

  - Python Version:3.7
  - Moviepy Version:1.0.1'
  - Platform Name:mac os catalina

**Comment by tburrows13** [comment]
Presumably you don't have the font Courier installed on your system. Try creating TextClip with the `font` argument set to a font you do have.

`TextClip.list('font')` seems to be a bit strange on my Mac as well. It only returns ['ArialUnicode'], even though Courier (the default font for TextClips) works fine.
