### ISSUE TITLE
NO chinese subtitle

### ISSUE THREAD

**Issue by 33RoboTcan** [Zulko/moviepy#1112]
Hi,i'am chinese,sorry for my poor english at first
this is a code to add chinese subtitle,but after i set right font and successful create my video,chinese don't have,it just have "english letters,Special symbols（ASCII）"
After looking for help form internet,other's chinese problem show "????"(I know this mean wrong font,but i had set it right)

Environment:
------------------------------------------------

version = ImageMagick-7.0.10-Q16
moviepy = 1.0.2(I had try 1.0.0 and 1.0.1,but they didn't work)
python = 3.6.4
working_IDE = spyder (belong to anaconda3)

next is my code:
----------------------------------------

```
# -*- coding: utf-8 -*-
#encoding=utf-8
"""
Created on Fri Mar 27 18:13:04 2020

@author: HPN
"""

# Import everything needed to edit video clips
from moviepy.editor import *

screensize = (1280,720)


txt_clip = TextClip("你好asd123!@#",font = 'Agency-FB',fontsize=100,color='white')
txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = '幼圆',fontsize=100,color='red')

txt_clip = txt_clip.set_pos('center').set_duration(10)
txt_clip2 = txt_clip2.set_pos('bottom').set_duration(10)
cvc = CompositeVideoClip( [txt_clip.set_pos('center'),txt_clip2],
                        size=screensize)
cvc.write_videofile("chinese_no.mp4",fps = 24)
```
------------------------------------------
next is my true get:
-------------------------------------
![图片](https://user-images.githubusercontent.com/50979817/77771830-30805e80-7082-11ea-987d-c7325dddb3a4.png)
--------------------------------------
Thank you for your help!!!
Thank you for your help!!!
Thank you for your help!!!
（In china,important thing need to speak three times）

**Comment by gepcel** [comment]
In addition to using a font by its name "幼圆", you can also use a font file. If you copy the font file (probably c:\windows\fonts\simyou.ttf) to the current working directory and change the code to:
```
txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = 'simyou.ttf',fontsize=100,color='red')
```

will get:
![image](https://user-images.githubusercontent.com/4179106/77816289-93aed700-70fc-11ea-9eb7-95cd466d235f.png)

It's supposed to work by using the absolute directory of a font file, but I cannot make it work.

**Comment by 33RoboTcan** [comment]
Thany you very much !I use 'siimhei'font to make it and it can work!Remember wear mask and keep healthy!!!
have a good time!
have a good time!
have a good time!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WANG Aiyong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 下午2:03
收件人:&nbsp;"Zulko/moviepy"<moviepy@noreply.github.com&gt;;
抄送:&nbsp;"郝培宁"<1156635730@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zulko/moviepy] NO chinese subtitle (#1112)





 
In addition to using a font by its name "幼圆", you can also use a font file. If you copy the font file (probably c:\windows\fonts\simyou.ttf) to the current working directory and change the code to:
 txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = 'simyou.ttf',fontsize=100,color='red')  
will get:
 
 
It's supposed to work by using the absolute directory of a font file, but I cannot make it work.

**Comment by mgaitan** [comment]
I close this because seems fixed.

**Comment by Danee-wawawa** [comment]
Hi, I use your way, But it still not support, the result like this:
![image](https://user-images.githubusercontent.com/24379250/161379242-f266806e-0388-44b0-a824-d115c7f9536b.png)
Can you help me, thank you very much.

**Comment by rozbo** [comment]
搜到了这个issue，其实真正的原因是个边界问题
moviepy是通过命令行调用 imagemagick的，而imagemagick要求字体的路径必须是转义的。
具体见：https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=34768

在当前目录工作的很好，因为不需要转义，而在其他目录则会因为转义导致字体丢失，所以为了解决这个问题你需要

```
txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = 'c:\\\\bbb\\\\simyou.ttf',fontsize=100,color='red')

```

即多加一层转义

**Comment by HoveyChenB612** [comment]
> 搜到了这个issue，其实真正的原因是个边界问题 moviepy是通过命令行调用 imagemagick的，而imagemagick要求字体的路径必须是转义的。 具体见：https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=34768
> 
> 在当前目录工作的很好，因为不需要转义，而在其他目录则会因为转义导致字体丢失，所以为了解决这个问题你需要
> 
> ```
> txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = 'c:\\\\bbb\\\\simyou.ttf',fontsize=100,color='red')
> ```
> 
> 即多加一层转义

非常感谢，您的方法解决了困扰我一整天的问题

**Comment by sunyq1995** [comment]
> 搜到了这个issue，其实真正的原因是个边界问题 moviepy是通过命令行调用 imagemagick的，而imagemagick要求字体的路径必须是转义的。 具体见：https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=34768
> 
> 在当前目录工作的很好，因为不需要转义，而在其他目录则会因为转义导致字体丢失，所以为了解决这个问题你需要
> 
> ```
> txt_clip2 = TextClip("我爱你中国大苏打！！！！！123",font = 'c:\\\\bbb\\\\simyou.ttf',fontsize=100,color='red')
> ```
> 
> 即多加一层转义

it works, really thanks for this answer!!!
