### ISSUE TITLE
Assertions in tests are very fragile

### ISSUE THREAD

**Issue by mgaitan** [Zulko/moviepy#1114]
Doing tests for #1076 I've realized most of the tests that currently exists are very naive and just verify general conditions of the result, like "result is a file" or, worse, that the executed code doesn't  fail (doesn't raise an exception) without any assertion on the result. 

We should improve this by checking actual values of the result. Most of the time, this is possible comparing frames as numpy arrays. For example, to check a "time mirror" effect, the first frame of the input clip should be the last one in the output one.

**Comment by tburrows13** [comment]
I've been thinking exactly the same thing. Something to get round to at some point (I'm happy to do it).

**Comment by tburrows13** [comment]
I'm working on a framework for this now, I'll open a WIP PR soon.
