### ISSUE TITLE
multi-colored text? (question)

### ISSUE THREAD

**Issue by ghistes** [Zulko/moviepy#1123]
Hi,

what I would like to do is some text-animation, but with the complication that some letters of the text would have different colors.

Is that possible?

It seems a TextClip can only have text of one color, so in case I would have to create several TextClips, how would I go about aligning them in such a way that they would appear as one word?

Many thanks!

**Comment by keikoro** [comment]
I think you'd have to dig deeper into fonts in general, or ImageMagick, specifically, to figure out how to align individual letters properly. Which is out of scope for this project -> closing.

**Comment by keikoro** [comment]
Linking #1228 because it has a bit more info on TextClip.
