### ISSUE TITLE
I concatenated the videos, and all except the first video are super glitchy.

### ISSUE THREAD

**Issue by bigshirtjonny** [Zulko/moviepy#1135]
### Expected Behavior
All the videos to be working correctly and concatenated. 

### Actual Behavior
All the videos after the first video are messed up. They are messed up because of each video after the first is super glitchy.

### Steps to Reproduce the Problem
```
    for count in range(len(videoFileClips)):
        videoFileClips[count] = VideoFileClip(videoFileClips[count])
    finalRender = concatenate_videoclips(videoFileClips)
    finalRender.write_videofile('/Users/jonathanraskauskas/Desktop/test/render.mp4',
                         codec='libx264',
                         audio_codec='aac',
                         temp_audiofile='temp-audio.m4a'
                         )
```
### Specifications

  - Python Version: 3.7
  - Moviepy Version: Most Recent
  - Platform Name: Mac OSX
[render.mp4.zip](https://github.com/Zulko/moviepy/files/4435223/render.mp4.zip)

**Comment by bigshirtjonny** [comment]
Didn't mean to close it :)

**Comment by bigshirtjonny** [comment]
Fixed! I added `method = "compose"` to concatenate and downgraded moviepy to 1.0.0.

**Comment by tburrows13** [comment]
Was downgrading to 1.0.0 actually necessary? If so, then that is worthy of a separate bug report.

**Comment by bigshirtjonny** [comment]
Yes, downgrading to 1.0.0 was necessary for me, iirc when I only did `method = "compose"` my code erred. However, after downgrading it no longer erred.

To downgrade in terminal just do: pip install moviepy==1.0.0

**Comment by Ziao** [comment]
Confirmed. Had the same issue, adding `method = "compose"` to `concatenate_videoclips()` did the trick for me. No need to downgrade. I'm at 1.0.3.
