### ISSUE TITLE
BlockingIOError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by bigshirtjonny** [Zulko/moviepy#1136]
### # Expected Behavior
All the videos to be working correctly and concatenated. 

### Actual Behavior
I get an error in the for loop, with the write_videofile(). I get this error: `BlockingIOError: [Errno 35] Resource temporarily unavailable`

I am only trying to concatenate ~5 mp4 files.

### Steps to Reproduce the Problem
```
    for count in range(len(videoFileClips)):
        videoFileClips[count] = (VideoFileClip(videoFileClips[count]))
    finalRender = concatenate_videoclips(videoFileClips, method="compose")
    finalRender.write_videofile('/Users/--/Desktop/test/render.mp4', codec='libx264',audio_codec='aac', temp_audiofile='temp-audio.m4a', remove_temp=True)

```
### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.0.0
  - Platform Name: Mac OSX

**Comment by tburrows13** [comment]
Thanks for writing up this bug report. Would you be able to provide the full error trace that you get?

**Comment by bigshirtjonny** [comment]
Hmmm, after sleeping on this error. There doesn't seem to be an issue! I will comment and provide a full error trace if I get again.
