### ISSUE TITLE
Any Plan to Support Saving as wmv Format?

### ISSUE THREAD

**Issue by riven314** [Zulko/moviepy#1142]
currently moviepy supports saving audio of a mp4 video as a mp3 file. However, saving as a wav file is currently not supported. 
I see wav files are pretty common in audio processing, would you plan to add such support in the future?

**Comment by tburrows13** [comment]
Hello! You should be able to save audio as a .wmv file if you specify the codec that you want ffmpeg to use. I tried it with `codec="wmav2"` and it seemed to work. This could be added to the [extensions dictionary](https://github.com/Zulko/moviepy/blob/master/moviepy/tools.py#L133) in the future if you like?

**Comment by riven314** [comment]
@tburrows13  thanks for the prompt address! 
I later found that I have mistaken the extension ("wmv" v.s. "wav"). I could save "wav" file now by ```video.audio.write_audiofile('filename.wav')```.
