### ISSUE TITLE
Missing documentation on composition.crossfade

### ISSUE THREAD

**Issue by Kaszanas** [Zulko/moviepy#1156]
While looking for a way to easily apply crossfade as a transition between clips I have stumbled upon some old reddit post which states that using crossfade is possible.

On the other hand while browsing the documentation I am not able to find any real implementation of this code.

The official Moviepy documentation states that there should be a composition.crossfade somewhere but it is not.

> For cross-fading (progressive appearance or disappearance of a clip over another clip, see ``composition.crossfade``

This issue persists in two places:

https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.fadein.html?highlight=composition%20crossfade

https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.fadeout.html?highlight=composition%20crossfade

**Comment by tburrows13** [comment]
Thanks for spotting that. It is probably just a very outdated docstring that should now point to `transfx.crossfadein` and `transfx.crossfadeout`.

**Comment by Kaszanas** [comment]
@tburrows13 I am actively working with Moviepy code so I tend to spot different kind of inconsistencies (because I am using older version of the package).

I will be sure to report as soon as I spot anything more.

**Comment by tburrows13** [comment]
Fixed in #1159.
