### ISSUE TITLE
How to synchronize audio and video stream from different sources exactly in [ms]?

### ISSUE THREAD

**Issue by spfeifer222** [Zulko/moviepy#1167]
### Expected Behavior
Receive synchronized video clip (accuracy in ms).

### Actual Behavior

Unsynchron video clips:

 - first try: audio 1.5 s late
 - 2nd try: audio 2.5 s late

### Steps to Reproduce the Problem

```python
from moviepy.editor import VideoFileClip, AudioFileClip

VIDEOFILE = 'video_with_good_quality.mp4'
AUDIOFILE = 'video_with_origin_language.mp4'
OUTPUTFILE = 'video_with_good_quality+origin_language.mp4'
TEST_DURATION = 215.0 # sec
AUDIO_DELAY = -1.5


# from audio attribute of the VideoFileClip object
audio2 = VideoFileClip(AUDIOFILE).audio
# video including original audio
video_a = VideoFileClip(VIDEOFILE)

#create test clips (short)
# FIRST TRY (without delay correction)
audio2_test = audio2.subclip(t_start=audio2.duration-TEST_DURATION, t_end=audio2.duration)
video_a_test = video_a.subclip(t_start=video_a.duration-TEST_DURATION, t_end=video_a.duration)

# combine test clips
video_va_a2 = video_a_test.set_audio(audio2_test)

# show
video_va_a2.ipython_display(maxduration=250, width=640)

#video_a_test.ipython_display(maxduration=250, width=640)  # proofed, but not synchronized: audio -1500 ms to correct

# close all instances
audio2.close()
video_a.close()
```

With mpv video player I found out that the audio stream is 1500 ms late. This was OK, because it was only a guess to get a synchonized file. Thus, I introduced a correction factor `AUDIO_DELAY = -1.5`  in [s]. to create the test clips:

```

# 2nd try (with delay correction)
audio2_test = audio2.subclip(t_start=audio2.duration-TEST_DURATION+AUDIO_DELAY, t_end=audio2.duration+AUDIO_DELAY)
video_a_test = video_a.subclip(t_start=video_a.duration-TEST_DURATION, t_end=video_a.duration)
```
### Specifications

  - Python Version: 3.8
  - Moviepy Version: 1.0.2
  - Platform Name: Linux Mint Mate
  - Platform Version:  19.3

**Comment by tburrows13** [comment]
Sorry, I don't quite understand what the problem is. Are you saying that `.subclip()` is not doing what it is supposed to be doing? Or are you looking for an automated solution for the problem so that you don't have to manually work out what `AUDIO_DELAY` is?

**Comment by spfeifer222** [comment]
I don't looking for an automated solution, but I expect that the code works with the given parameters. For the second try I expected to recieve a synced  video, but in the viedeo the audio is about 1 s more delayed. Now I realize that I forgot to write that in the second clip the audio is 2500 ms delayed (I found out with mpv player, too). I reckon the reason is a either a bug or it hast to do something with like the data are processed. I hope it's the latter and the processing could be controlled in a way to get the expected result.

**Comment by tburrows13** [comment]
Ok, so just to clarify, you're saying that:

After the first try, it was off by 1.5 seconds, so you added an `AUDIO_DELAY` to counteract that. However, instead of reducing the 1.5s to 0s, it instead increased it to 2.5s.

Are you able to post the 2 input files (either publicly or send them to me privately)? Its not essential but it would make the debugging easier.

**Comment by spfeifer222** [comment]
That's correct. That are 740 MB. Any preference to send that files? By the way, I like to send it in private.

**Comment by tburrows13** [comment]
Sure, how about a private dropbox link (or any file sharing service really), sent to tom@tpmb.uk, or through Gitter.

**Comment by spfeifer222** [comment]
in progress... thanks for your help! ;)

**Comment by ribeirompl** [comment]
```python
audio2_test = audio2.subclip(t_start=audio2.duration-TEST_DURATION-AUDIO_DELAY, t_end=audio2.duration-AUDIO_DELAY)
```
Isn't it just the case of subtracting the `AUDIO_DELAY` instead of adding it, since the audio is delayed?

**Comment by spfeifer222** [comment]
Yes, but it's a negative value. It's Mathematical correct, isn't it? However, I tried to use a posive value, but failed.

**Comment by amirothman** [comment]
is this issue resolved? i'm curious how you came to the value of `AUDIO_DELAY` because from your description, it is just assumed that this value is correct. I would double-check this value first before jumping to conclusion that there is a bug with `.subclip()`

**Comment by spfeifer222** [comment]
My intention was to combine the audio stream of one and the video stream of another file. I observed that only the beginning seems to differ. I realized my assumption that only the beginning of the files differ was not precise enough to get a synchonous result. Therefore I added the `AUDIO_DELAY` in order to create a short testfile, determine the delay and process the files again with that `AUDIO_DELAY'. This failed for a not exactly known reason.

Because this approach was too complicated I changed my workflow to like this:

1. determine the times of the first synchronous scene in `AUDIO_FILE` and `VIDEO_FILE`: `AUDIO_SYNCPOINT` and `VIDEO_SYNCPOINT`
2. caluclate the `AUDIO_DELAY` by `AUDIO_SYNCPOINT` - `VIDEO_SYNCPOINT`
3. in order to set `VIDEO_START` = `VIDEO_SYNCPOINT`  and
`AUDIO_START` = `VIDEO_START` + `AUDIO_DELAY`
4. process everything

complete code example:

```python
from moviepy.editor import VideoFileClip, AudioFileClip

VIDEOFILE = 'video_with_good_quality.mp4'
AUDIOFILE = 'video_with_origin_language.mp4'
OUTPUTFILE = 'video_with_good_quality+origin_language.mp4'

AUDIO_SYNCPOINT = 114.781333
VIDEO_SYNCPOINT = 115.782515
AUDIO_DELAY = AUDIO_SYNCPOINT - VIDEO_SYNCPOINT

VIDEO_START = VIDEO_SYNCPOINT   # assume to start video at VIDEO_SYNCPOINT
AUDIO_START = VIDEO_START+AUDIO_DELAY

# from audio attribute of the VideoFileClip object
audio2 = VideoFileClip(AUDIOFILE).audio
# video including original audio
video_a = VideoFileClip(VIDEOFILE)

#create trimmed clips
audio2_test = audio2.subclip(t_start=AUDIO_START)
video_a_test = video_a.subclip(t_start=VIDEO_START)

# combined trimmed clips
video_va_a2 = video_a_test.set_audio(audio2_test)

# close all instances
audio2.close()
video_a.close()
```
__The good news:__ This resulted in a synchonous file.
__The bad news:__ This file is huge. (1.1 GB)

Applying this approach with `python-ffmeg` I get the same synchronus result, but the file is only 533 MB which is approximately the same as the `VIDEO_FILE`.

**Comment by Josep-DA** [comment]
Thanks. This worked out for me.
