### ISSUE TITLE
converting video mp4 to audio mp3

### ISSUE THREAD

**Issue by Shahin82** [Zulko/moviepy#1168]
### Expected Behavior
Hello. It was supposed to exctract the audio from video file and write it.

### Actual Behavior
It runs well, but in the end it returns an error saying:

```
ValueError: MoviePy couldn't find the codec associated with the filename. Provide the 'codec' parameter in write_audiofile.
```

Without GUI it works if you show the exact location of the video file and the destination file. But, then I have to show the file name and extension of the output file and the input file.

### Steps to Reproduce the Problem

```
from tkinter import *
from os import path
from tkinter import messagebox
from tkinter import filedialog
import imageio

imageio.plugins.ffmpeg.download()

import moviepy.editor  

window  = Tk()
window.geometry("300x200")
window.title("Welcome to MIAMI")
window.resizable(width = False, height = False)

# Functions

def pp ():
    global a
    a = filedialog.askopenfilename(filetypes = (("MP4 Files", "*.mp4"),("All Files", "*.*")))
    messagebox.showinfo("Status", "MP4 File has been selected")
    

def pb ():
    global c
    c = filedialog.askdirectory()
    messagebox.showinfo("Status", "Location is set")
    

def convert():
    p = moviepy.editor.VideoFileClip(a,)
    b = p.audio
    d = b.write_audiofile(c,)
    messagebox.showinfo("Status", "Convertion is completed")


# First Row

lbl1 = Label(window, text = "MP4 File", bg = "Grey", fg = "Black")
lbl1.grid(column = 0, row=0)

#lbl2 = Label(window, text="", bg = "Grey", fg = "Black"   )
#lbl2.grid(column = 3, row = 1)

btn1 = Button(window, text = "Select", command=pp)
btn1.grid(column = 1, row = 0)

#entry1 = Entry(window, width = 16)
#entry1.grid(column = 3, row = 0)
#entry1.focus()

# Second Row

lbl3 = Label(window, text = "MP3 File", bg = "Grey", fg = "Black")
lbl3.grid(column = 0, row=2)

#lbl4 = Label(window, text="", bg = "Grey", fg = "Black"   )
#lbl4.grid(column = 3, row = 3)

btn2 = Button(window, text = "Destination", command=pb)
btn2.grid(column = 1, row = 2)

btn3 = Button(window, text = "Convert", command=convert)
btn3.grid(column = 0, row = 3)

#entry2 = Entry(window, width = 16)
#entry2.grid(column = 3, row = 2)
#entry2.focus()

window.mainloop()
```

### Specifications

  - Python Version: 3.7.4
  - Moviepy Version:1.0.2
  - Platform Name: Win 10
  - Platform Version:

**Comment by tburrows13** [comment]
Your issue is that the argument `c` to `write_audiofile()` does not have an extension like `.mp3`, so MoviePy does not know what codec to use. Either ensure that `c` has a proper audio extension such as `.ogg`, `.mp3` or `.wav`, or use `codec="libmp3lame"` in `write_audiofile()` to force it to use the `.mp3` codec even if the file doesn't end in `.mp3`.

**Comment by Shahin82** [comment]
Thank you. I have done as you said, forced it to accept the mp3 codec, but now it raised another error:

MoviePy - Writing audio in %s
chunk:   0%|                                                                         | 0/840 [00:00<?, ?it/s, now=None]Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\Desktop\tko\tko\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 74, in write_frames
    self.proc.stdin.write(frames_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

Any suggestion?

**Comment by Shahin82** [comment]
I have removed the unused variable in the method "convert" and run it. Not it says the following:

"At least one output file must be specified"

Thanks in advance...

**Comment by tburrows13** [comment]
What is your updated code then? If you just remove `d`, then it should work as it did before. If you’re still getting the broken pipe error, try testing it by running just those 3 lines outside of tkinter and tell me how that goes.

**Comment by Shahin82** [comment]
here is the complete text of the error:

[m4v @ 000d7f00] Format m4v detected only with low score of 1, misdetection possible!
[m4v @ 000d7f00] Could not find codec parameters for stream 0 (Video: mpeg4, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, m4v, from 'C:/Users/User/Desktop/dolbycanyon.mp4.m4v':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mpeg4, none, 25 tbr, 1200k tbn, 25 tbc

At least one output file must be specified

**Comment by tburrows13** [comment]
And what is the exact code that causes that? Preferably without any tkinter stuff (unless it only happens when you're using tkinter).

**Comment by Shahin82** [comment]
Without Tkinter it does work, but in this case, I have to show the name and the location of the converter file and as well the original. But, when I make GUI in Tkinter and use filedialog library it does not work as it was supposed or as it did without Tkinter.

**Comment by Shahin82** [comment]
It works now. The problem was with the format of the file, you were right, it was not mp4. It works as hell. The following is the final code. Thank you Tim, thank you for everything.

# Here comes the code:

from tkinter import *
from os import path
from tkinter import messagebox
from tkinter import filedialog
import imageio

imageio.plugins.ffmpeg.download()

import moviepy.editor  

window  = Tk()
window.geometry("300x200")
window.title("Welcome to MIAMI")
window.resizable(width = False, height = False)

# Functions

def pp ():
    global a
    a = filedialog.askopenfilename(filetypes = (("MP4 Files", "*.mp4"),("All Files", "*.*")))
    messagebox.showinfo("Status", "MP4 File has been selected")
    

def pb ():
    global c
    c = filedialog.asksaveasfilename()
    messagebox.showinfo("Status", "Location is set")
    

def convert():
    p = moviepy.editor.VideoFileClip(a,)
    b = p.audio
    b.write_audiofile(c,codec="libmp3lame")
    messagebox.showinfo("Status", "Convertion is completed")


# First Row

lbl1 = Label(window, text = "MP4 File", bg = "Grey", fg = "Black")
lbl1.grid(column = 0, row=0)

#lbl2 = Label(window, text="", bg = "Grey", fg = "Black"   )
#lbl2.grid(column = 3, row = 1)

btn1 = Button(window, text = "Select", command=pp)
btn1.grid(column = 1, row = 0)

#entry1 = Entry(window, width = 16)
#entry1.grid(column = 3, row = 0)
#entry1.focus()

# Second Row

lbl3 = Label(window, text = "MP3 File", bg = "Grey", fg = "Black")
lbl3.grid(column = 0, row=2)

#lbl4 = Label(window, text="", bg = "Grey", fg = "Black"   )
#lbl4.grid(column = 3, row = 3)

btn2 = Button(window, text = "Destination", command=pb)
btn2.grid(column = 1, row = 2)

btn3 = Button(window, text = "Convert", command=convert)
btn3.grid(column = 0, row = 3)

#entry2 = Entry(window, width = 16)
#entry2.grid(column = 3, row = 2)
#entry2.focus()

window.mainloop()

**Comment by tburrows13** [comment]
Good to know. By the way, you no longer need the `imageio.plugins.ffmpeg.download()`. We've solved that problem from within moviepy now :).
