### ISSUE TITLE
audio of MP3 is unclear but,audio of wav is clear after adding them in vedio

### ISSUE THREAD

**Issue by 33RoboTcan** [Zulko/moviepy#1169]
Thank you for your help at first!
### Expected Behavior
1,When i get the vedio,the vedio should have same audio liked the MP3FILE I added in code.
2,I think maybe my mp3file is bed,so i try wavfile again,then,i find it cannot add wavfile.I had seen this problem can be solved by install moviepy 1.0.0 or set argument else,but i don't how to set the argument. 

### Actual Behavior
1,The vedio have the audio of mp3,but it's unclear.
(here is the video and mp3 file)
[audio-unclear.zip](https://github.com/Zulko/moviepy/files/4561039/audio-unclear.zip)

2,AttributeError: 'NoneType' object has no attribute 'stdout'.
![图片](https://user-images.githubusercontent.com/50979817/80756472-2a8c0a80-8b65-11ea-82ba-df7e0d496dd6.png)

### Steps to Reproduce the Problem

```
movie_name = 'test.mp4'
mp3Name = os.path.join('MP3','4日工人1588213538962.mp3')
mp3Clip = AudioFileClip(mp3Name)
#vedioClip = VideoFileClip('./345.mp4')
compose_image = ImageClip('final.jpg',duration = 5).set_pos('center')
vedioClip = CompositeVideoClip([compose_image.without_audio().set_audio(mp3Clip)],size = (1280,720))
movie = concatenate_videoclips([vedioClip])
movie.write_videofile(movie_name,fps = 24)

movie_name = 'test.mp4'
mp3Name = os.path.join('MP3','这是一个测1588278391615.wav')
mp3Clip = AudioFileClip(mp3Name)
#vedioClip = VideoFileClip('./345.mp4')
compose_image = ImageClip('final.jpg',duration = 5).set_pos('center')
vedioClip = CompositeVideoClip([compose_image.without_audio().set_audio(mp3Clip)],size = (1280,720))
movie = concatenate_videoclips([vedioClip])
movie.write_videofile(movie_name,fps = 24)
```

### Specifications

  - Python Version:3.6.4
  - Moviepy Version:1.0.2
  - Platform Name:spyder
  - Platform Version:3.2.8

**Comment by tburrows13** [comment]
Yeah the way to fixed that is to install version 1.0 with `pip install moviepy=1.0.0` or go to `E:\anaconda3\lib\site-packages\moviepy\audio\io\AudioFileClip.py` and delete line 89 (as seen https://github.com/Zulko/moviepy/pull/1059/files#diff-2b5c494ba3a48ff925aca6438d9847a7L90)

**Comment by 33RoboTcan** [comment]
Hi,thank you,the wav file can be add and the audio effect is good,Thank you!

**Comment by tburrows13** [comment]
Great. I think I will actually push out a v1.0.3 with just this change because it seems so widespread.
