### ISSUE TITLE
TextClip.list('font') raises TypeError in Python 3

### ISSUE THREAD

**Issue by mncharity** [Zulko/moviepy#117]
TextClip.list('font') raises "TypeError: startswith first arg must be bytes or a tuple of bytes, not str" under moviepy-0.2.2.04, Python 3.4.0, linux x64.

TextClip.search('Courier','font') calls TextClip.list('font'), so it also fails.

In VideoClip.py, TextClip.list uses Popen.communicate, which in Python 3 apparently returns bytes, not strings.  So also in TextClip.list, l.startswith("  Font:") would not be str.startswith, but bytes.startswidth, which doesn't accept a str arg.

**Comment by Gloin1313** [comment]
Related to https://github.com/Zulko/moviepy/issues/371

**Comment by earney** [comment]
this seems to be fixed with the current repo.   Please reopen if you have the issue again.
