### ISSUE TITLE
Add conda installation steps to readme

### ISSUE THREAD

**Issue by mjmikulski** [Zulko/moviepy#1171]
I tried installing with `pip` as suggested in the readme, but I got an error. Conda was not mentioned, by I tried and it worked fine. So it seems that it can be installed with `conda`.

**Comment by tburrows13** [comment]
You're right, it does appear to be in `conda-forge`: https://anaconda.org/conda-forge/moviepy. However, that version is not quite up-to-date and wasn't put there by any of the MoviePy maintainers so we have no control over it. So I don't think that it's a good idea to point users to it as an 'official' way of installing MoviePy. I'd be interested in seeing what error you got with pip though, as that really should work, and if it doesn't, we'd like to fix it.

**Comment by mjmikulski** [comment]
Yes, indeed, anaconda version is `1.0.1`.

I didn't want to make it a bug report, but if you ask, this is my story:

specs: 
macOS Catalina 10.15.4
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

So I had 3 approaches:
1. Create conda env with python 3.6 (this is the latest python listed on [pypi](https://pypi.org/project/moviepy/))
```bash
conda create -c anaconda -n movie python=3.6  scipy scikit-image  pillow
conda activate movie
pip install moviepy
```
and it failed with:
```bash
Collecting moviepy
  Downloading moviepy-1.0.2.tar.gz (7.8 MB)
     |████████████████████████████████| 7.8 MB 1.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/maciejmikulski/miniconda3/envs/movie/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/92/08kb1wpn597blvy8lsvnry8r0000gn/T/pip-install-qt3806rt/moviepy/setup.py'"'"'; __file__='"'"'/private/var/folders/92/08kb1wpn597blvy8lsvnry8r0000gn/T/pip-install-qt3806rt/moviepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/92/08kb1wpn597blvy8lsvnry8r0000gn/T/pip-install-qt3806rt/moviepy/pip-egg-info
         cwd: /private/var/folders/92/08kb1wpn597blvy8lsvnry8r0000gn/T/pip-install-qt3806rt/moviepy/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/maciejmikulski/miniconda3/envs/movie/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
      Reason: image not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```


2. I tried (in the same conda env):
```
conda install -c anaconda moviepy
```
and it worked surprisingly. But then when I run a simple script (modified version of [this](https://zulko.github.io/moviepy/examples/ukulele_concerto.html)), python crashed with `mkl-service` problem (I cannot find the log now, I run it in pycharm).

3. I thought that if conda works, maybe I try with python 3.7 and install all together:
```bash
conda create -n movie2 python=3.7 scipy moviepy
```
and the installation worked as a charm and the script seems to work. It is still processing on `write_videofile`, so I cannot be sure, but it loads video at least.

**Comment by tburrows13** [comment]
From a quick google, I think that it is more of an issue with conda/pip or one of moviepy's dependencies (possibly opencv?). No idea how to go about fixing it though, but your solution seems to have worked.
