### ISSUE TITLE
Making my own progress bar

### ISSUE THREAD

**Issue by el07694** [Zulko/moviepy#1180]
Hello,

I just want to know if is possible to make my own progress bar using:
1) chunksize in file ffmpeg_audiowriter.py (line 175)
2) total size (i don't know where to search for it.

Thanks in advance.
Chris Pappas

**Comment by tburrows13** [comment]
I'm not sure entirely what you mean... you can pass a ProgLog logger object into `write_audiofile()` using `logger=` and customise that however you want.

**Comment by tburrows13** [comment]
Feel free to reopen if you need further clarification.
