### ISSUE TITLE
I am not able to re-position imageClip

### ISSUE THREAD

**Issue by MohnishMagesh** [Zulko/moviepy#1182]
I have been trying to re-position my image with this code,
```
audio = AudioFileClip(path_of_sub_audio)
image=ImageClip(path_of_sub_image).set_duration(audio.duration).set_fps(5).set_audio(audio).set_position('center','top')
```
I've tried all possible methods by viewing the documentation, like .set_position((0,0)) , etc. but none of them seem to be working. 
No matter what I try, the image seems to be stuck at the center of the clip.
Is there something I am missing here?

**Comment by tburrows13** [comment]
`set_position` only has effect if you are using the clip as part of a composition (ie in CompositeVideoClip).
You could do e.g. `final_clip = CompositeVideoClip([image], size=(1200, 800), bg_color=(0, 0, 255)`. This would place your image at the center-top of a larger blue video.

**Comment by MohnishMagesh** [comment]
Perfect, it works. Thanks man!
