### ISSUE TITLE
can't get the example on the mixing clips moviepy documentation to work

### ISSUE THREAD

**Issue by maikeeb** [Zulko/moviepy#1184]
### Expected Behavior

the result is on the website, but it is just the same clip 4 times at the same time and the bottom right one is slightly smaller

### Actual Behavior
```
Moviepy - Building video my_stack.mp4.
MoviePy - Writing audio in %s
chunk:  42%|████▏     | 152/363 [00:19<00:00, 398.10it/s, now=None]

```

### Steps to Reproduce the Problem

I copy and pasted the tutorial for mixing clips from [here](https://zulko.github.io/moviepy/getting_started/compositing.html) and it just got stuck on writing the audio

```
from moviepy.editor import VideoFileClip, clips_array, vfx

clip1 = VideoFileClip("myvideo.mp4").margin(10)  # add 10px contour
clip2 = clip1.fx(vfx.mirror_x)
clip3 = clip1.fx(vfx.mirror_y)
clip4 = clip1.resize(0.60)  # downsize 60%
final_clip = clips_array([[clip1, clip2],
                          [clip3, clip4]])
final_clip.resize(width=480).write_videofile("my_stack.mp4")

```

### Specifications

  - Python Version: 3.7.6
  - Moviepy Version: 1.0.0
  - Platform Name: windows 10
  - Platform Version: 1909

**Comment by tburrows13** [comment]
I've just tested on my computer (admittedly a MacBook) and it works fine. Would you mind testing it on version 1.0.3 with this file? https://github.com/Zulko/moviepy/blob/master/media/big_buck_bunny_432_433.webm

Thanks

**Comment by maikeeb** [comment]
Thank you, that worked. Do you know why that bug occurred. 
The original clip I used was 1920x1080, 30 fps and 30 seconds long.

**Comment by maikeeb** [comment]
if I don't name the file "myvideo.mp4"  it works

**Comment by tburrows13** [comment]
So the exact same file behaves differently when it has a different filename? That sounds very unusual.

**Comment by keikoro** [comment]
Closing this due to a lack of response by OP since 2020.
