### ISSUE TITLE
Performance related query!

### ISSUE THREAD

**Issue by sahils2410** [Zulko/moviepy#1187]
I am looking out for some answers.

Given following scenario, which approach would be more resource friendly?

### Concatenate **Clip1** to **ClipN** where each clip is created on the fly with for loop example:
**Clip1 = CompositeVideoClip of VideoFlipClip , ImageClip, TextClip
Clip2 = CompositeVideoClip of VideoFileClip, ImageClip, TextClip
.
.
.
ClipN = CompositeVideoClip of VideoFileClip, ImageClip, TextClip**

_Final video will be concatenation of **Clip1** to **ClipN** ._ 

### My question is

Should I keep doing 

> write_videofile

 for each **Clip**, and close the clip before trying to create next CompositeVideoClip. And then finally concatenate & write_videofile to get final result.

OR

Should I keep **Clips** from each iteration in the memory, create final clip by concatenating each CompositeVideoClip and then finally write_videofile?

**Comment by tburrows13** [comment]
Option 1 will be a lot slower, but option 2 will require a lot more memory. I would try option 2 first, but if you have a lot of clips or you run out of memory, I would recommend a balance between the two: concatenate several (ie 20?) clips together, write the concatenation to disk, close all clips and continue. Then load the concatenations back again at the end and concatenate those together.

**Comment by tburrows13** [comment]
Feel free to reopen if there is more to discuss :)
