### ISSUE TITLE
Warnings are suppressed by moviepy

### ISSUE THREAD

**Issue by fepegar** [Zulko/moviepy#1191]
Hi,

Thanks for the library, I think it's great.

My warnings are being suppressed/captured after I import certain `moviepy` modules. I suspect it's caused by this line:
https://github.com/Zulko/moviepy/blob/4d70eabd784a73c16ab91bc90914df99fa9cc322/moviepy/video/io/ffmpeg_reader.py#L19

### Steps to Reproduce the Problem

```
iPython 3.8.2 (default, May  6 2020, 02:49:43)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import warnings

In [2]: import moviepy

In [3]: warnings.warn('x')
<ipython-input-3-5759b8345431>:1: UserWarning: x
  warnings.warn('x')

In [4]: from moviepy.video.io.VideoFileClip import VideoFileClip

In [5]: warnings.warn('x')

In [6]:
```

### Specifications

  - Python Version: `3.8.2`
  - Moviepy Version: `1.0.3`
  - Platform Name: `macOS`
  - Platform Version: `Catalina 10.15.4`

**Comment by tburrows13** [comment]
Hey, thanks for the report. That is definitely not ideal, and should be looked at before the release of v2.0.

In the meantime, it looks like if you call `logging.captureWarnings(False)` after importing moviepy, then it should go back to the default behaviour.
