### ISSUE TITLE
text needing duration !? Error: Attribute 'duration' not set.

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1193]
I tried inserting some text onto an image clip.  However i get an error message preventing me from using moviepy text.

### Expected Behavior
text to show up

### Actual Behavior
If i use this line of code 
```
text = mped.TextClip("Hello", fontsize=10, stroke_width=5)
```
i get the following error message:-    Attribute 'duration' not set

However, if I set 
```
text = mped.TextClip("Hello", fontsize=10, stroke_width=5, duration = 3)
```
I get the following error: -   __init__() got an unexpected keyword argument 'duration'

### Steps to Reproduce the Problem
```
import moviepy.editor as mped
import sys
import numpy as np
print("Python Version", sys.version) 

baboon = mped.ImageClip("baboon.png", duration=3)
text = mped.TextClip("Hello", fontsize=10, stroke_width=5)
stacked_clips = mped.CompositeVideoClip([baboon, text]) stacked_clips.write_videofile('text_on_baboon.mp4', fps=5)
```
How can i combine a text clip with the others, and have its background transparent, so that it works without error ?

### Specifications
  - Python Version: 3.7.3
  - Moviepy Version: 1.02
  - Platform Name: Windows
  - Platform Version:10

**Comment by tburrows13** [comment]
To be honest, I think that the API should probably be changed to allow what you tried (the `duration` (and `fps` while we are at it) keyword in all clip definitions). For now though, do 

    text = mped.TextClip("Hello", fontsize=10, stroke_width=5).set_duration(3)

You might need to do

        text = mped.TextClip("Hello", fontsize=10, stroke_width=5).set_duration(3).set_fps(30)

instead if it complains about a missing fps as well.
