### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'write_audiofile'

### ISSUE THREAD

**Issue by neongreen13** [Zulko/moviepy#1198]
Hi! Thanks for this awesome package.

I used the following code a few days ago, and it worked perfectly to extract an audio (.wav) file from video (.mp4). Today I'm getting the error below. Did something change? Suggestions on how to solve? Thanks in advance :-)

```
videoclip = VideoFileClip(path + 'match_video.mp4')

audioclip = videoclip.audio

audioclip.write_audiofile(path + "match_audio.wav")
```
```
Error:
AttributeError: 'NoneType' object has no attribute 'write_audiofile'
```

**Comment by tburrows13** [comment]
That's interesting, it means that for some reason MoviePy is not reading any audio from `match_video.mp4`. Do other video players play sound with it? If they do, then this is a bug in MoviePy.

**Comment by neongreen13** [comment]
@tburrows13 thanks for the speedy reply! Indeed, the video i was using for some reason had cut off the audio. I switched to another video and it is working now. Sorry to bother with this issue. Thanks for a wonderful package :-)
