### ISSUE TITLE
The problem of the  example of Clip.fl  

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1213]
but I excute the flowing scripts:

```
    clipVideo = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4")
    h = int((clipVideo.size[1])/2)
    newclip = clipVideo.fl(lambda gf,t : gf(t)[int(t):int(t)+h, :]  , apply_to='mask').set_duration(clipVideo.duration)
    newclip.write_videofile(r"F:\video\WinBasedWorkHard_new.mp4")
```
Why the new video file's contents  are the top half of the original video file,not a scroll effect?

**Comment by tburrows13** [comment]
Thanks for the report. This seems to be part of a larger problem with `vfx.scroll` not working either.

**Comment by tburrows13** [comment]
After more investigation, it is actually working as intended. However, with the example that you've used from `Clip.fl`, it is scrolling by 1 pixel a second, which is not really noticeable.

Use this line instead (notice the added '50's):

    newclip = clipVideo.fl(lambda gf, t: gf(t)[int(50*t):int(50*t) + h, :], apply_to='mask').set_duration(clipVideo.duration)

I've changed the example in #1214.
