### ISSUE TITLE
writing clip with waterplay always results in broken clip 

### ISSUE THREAD

**Issue by CayoM** [Zulko/moviepy#1225]
Im trying to augument a Clip adding some description to it. simply after adding some text to it and rewriting the clip, things get messy... i noticed this behaviour specially when dealing with clips where there is water. Everythime there is someone playing in water, or water splashes, the video output will be pretty much corrupt. When examining the video details, i noticed it had 1000 FPS and a huge file size. Im not sure how i can prevent this, since i have already tried many diferent settings (also fixing FPS) but nothing helped yet.

#### Expected Behavior
i expect that the output looks like any other clips with normal FPS.

#### Actual Behavior
after writing the clip its buggy. there is pretty much almos no Frames changing, then until the rest of the clip, there is just a frozen frame. The clip itself took extremely long to write... it has 1000 FPS and almost 10x the size.

#### Steps to Reproduce the Problem
Here is an example, which will always produce an corrupt outcome after modifying it with moviepy.

Clip: https://clips-media-assets2.twitch.tv/AT-cm%7C744460198.mp4

here is the Code Snipet with 30 fps (normally i use the default value... 30 fps is for testing, so the video can be written faster):
```
import requests
from moviepy.editor import *

remote_file = "https://clips-media-assets2.twitch.tv/AT-cm%7C744460198.mp4"
local_file = "./test_file.mp4"
augumented_local_file = "./augumented_test_file.mp4"

r = requests.get(remote_file, allow_redirects=True)

open(local_file, 'wb').write(r.content)


clip = VideoFileClip(local_file, target_resolution=(1080, 1920))

# Make the text. Many more options are available.
txt_clip = (TextClip("test text", fontsize=70, font="Arial", color="white", stroke_width=2, stroke_color="black")
            .set_position((295,870))
            .set_duration(5)
            .set_start(3))

result = CompositeVideoClip([clip, txt_clip.fx(transfx.crossfadein, duration=1).fx(transfx.crossfadeout, duration=1)])

result.write_videofile(augumented_local_file, codec='mpeg4', fps=30, bitrate="8000k", threads=8)
```

#### Specifications

  - Python Version: Python 3.6.9
  - Moviepy Version:  1.0.2 / 1.0.3
  - Platform Name: Linux
  - Platform Version: Ubuntu 18.04.4 LTS

**Comment by tburrows13** [comment]
Try doing `clip = VideoFileClip(local_file, target_resolution=(1080, 1920), fps_source="'fps")`.

According to ffmpeg, your clip has a `tbr` of '1k' and a `fps` of '29.88'. With the above fix it will use the 29.88 instead of the 1000.

**Comment by CayoM** [comment]
thank you so much! this pretty much solved the problem! im just curious if there is a way to accomplish the same thing regarding bitrate. Since i fixed the bitrate at 8000k, but maybe the video has a lower one and there is no benefit in increasing it that high?

**Comment by tburrows13** [comment]
Well your input video has a bitrate of 2403 kb/s, you can find this by accessing `clip.reader.bitrate`; it will be equal to `2403`. Which I believe is the equivalent of passing `bitrate="2403k"` to `write_videofile()`. So `8000k` might be a little higher than is necessary.

**Comment by CayoM** [comment]
thanks for the hint, however clip.reader.bitrate does not exist?
