### ISSUE TITLE
How we can use MoviePy for android project

### ISSUE THREAD

**Issue by d1hamid** [Zulko/moviepy#1226]
hi.
im learned a bit Python .
i have question: is it possible to use MoviePy for android purpose ?
i know that will be possible to use Kivy for developing an android with python language programming.
is it possible to use your framework into a Kivy project ?

Thank you for reading my question.

**Comment by tburrows13** [comment]
I'm not aware of anyone using MoviePy on Android before. I suppose that it is possible, but probably hard to setup. MoviePy primarily relies of FFmpeg, and it tries to automatically install it but I doubt that that would work on Android. You may find [mobile-ffmpeg](https://tanersener.github.io/mobile-ffmpeg/) useful.

**Comment by d1hamid** [comment]
Thank you bro.
