### ISSUE TITLE
Cutout removes from the audio twice

### ISSUE THREAD

**Issue by spollard** [Zulko/moviepy#1227]
#### Expected Behavior
 Calling ```newclip = clip.cutout(start_remove,end_remove)``` should result in a clip with a ```newclip.audio.duration``` equal to the ```newclip.duration``` and a ```newclip.audio.end``` equal to the ```newclip.audio.end```. 

#### Actual Behavior
Calling ```newclip = clip.cutout(start_remove,end_remove)``` correctly removes (end_remove-start_remove) seconds from the video, but it removes 2 * (end_remove-start_remove) from the audio. 

#### Steps to Reproduce the Problem

```
from moviepy.editor import VideoFileClip

clip = VideoFileClip(PATH_TO_VIDEO) # insert path to your video here
print(f"Clip duration {clip.duration} and end {clip.end}")
print(f"clip audio duration {clip.audio.duration} and end {clip.audio.end}")
newclip = clip.cutout(1,5)
print(f"Newclip duration {newclip.duration} and end {newclip.end}")
print(f"Newclip audio duration {newclip.audio.duration} and end {newclip.audio.end}")
```

#### Specifications

  - Python Version: 3.6.9
  - Moviepy Version: 1.0.0-1.0.3
  - Platform Name: Linux/Ubuntu
  - Platform Version: 18.04

#### Specific issue

Clip.cutout() in Clip.py is decorated by apply_to_audio from decorators.py, and so it is called later on clip.audio. Clip.cutout() calls newclip.set_duration while Clip.set_duration also is decorated by apply_to_audio, and so it is called on clip.audio later. 

The problem is that set_duration is called on newclip.audio *before* cutout() is called on newclip.audio. This results in the audio's duration being set to a shorter time (clip.duration - (end_remove-start_remove)) before the audio is cutout(), which calls set_duration again on the audio clip and reduces the audio duration to clip.duration - (end_remove-start_remove) - (end_remove-start_remove). 

#### Workarounds 

I am working around this issue this way:

```
newaudio = clip.audio.cutout(1,5)
newclip = clip.cutout(1,5)
newclip.audio = newaudio
```

**Comment by tburrows13** [comment]
Thanks for the report. I've just tested it and I can confirm that this is a bug.

**Comment by spollard** [comment]
A possible solution to this would be adjust the way that the apply_to_audio decorator works. At the moment, the newclip.audio is the passed in function (f) applied to newclip.audio. 
Inside apply_to_audio(): 
   ...
        newclip.audio = f(newclip.audio, *a, **k)

This could be changed to created the newclip.audio from the OLD clip.audio

        newclip.audio = f(clip.audio, *a, **k)

I'm not sure if this will break other functions or defy expectations, but it might solve this particular problem.

**Comment by tburrows13** [comment]
Thanks for that suggestion. If it doesn't affect anything else, it would definitely be the neatest solution.

**Comment by rishabhvarshney14** [comment]
Can I work on this?

**Comment by tburrows13** [comment]
Sure! It may be as simple as @spollard's suggestion, but it would be good to check a) whether it works and b) whether it breaks other things that use the `apply_to_audio` decorator.

In the PR that you make it would be good to include what you tested.

Thanks!
