### ISSUE TITLE
Is it possible to highlight a word within a string while using TextClip? 

### ISSUE THREAD

**Issue by xlwneal** [Zulko/moviepy#1228]
It looks like that TextClip can only support one color.
Is there a way to go around?

**Comment by tburrows13** [comment]
At the moment, this is not possible in MoviePy. TextClip is a simple wrapper around ImageMagick, which does not have this functionality. You can see it discussed here: https://www.imagemagick.org/discourse-server/viewtopic.php?t=13052 so you may be able to edit the code in `TextClip.py` to support this feature.

Note that we are likely to move away from the ImageMagick TextClip in v2.0. It may still be available, but the default will likely by pillow-based: #1145.

**Comment by xlwneal** [comment]
Thanks.  I'll look into the `TextClip.py`.

**Comment by keikoro** [comment]
Closing this as the original question was essentially answered.
