### ISSUE TITLE
Writing ImageSequenceClip with AudioFileClip results in video with no audio

### ISSUE THREAD

**Issue by brentshermana** [Zulko/moviepy#1229]
I'm executing the following code to create a video:

```
video = ImageSequenceClip(frames, fps)
audioclip = AudioFileClip(audio_filename)
audioclip.set_duration(10)
video.set_audio(audioclip)
video.write_videofile("test.mp4", audio=True, threads=4)
```

Where `frames` is a list of generated numpy ndarrays, and `fps` is 30

For reference, I'm also sharing this dropbox folder containing a wav and mp3 file that I've tried used as `audio_filename`. That folder also includes the resulting video files from each. If you try playing them you'll see they don't seem to have any sound.

https://www.dropbox.com/sh/g2tj2a98u0ywkta/AACvRbpoV54HENxyYavWNB1Xa?dl=0

### Expected Behavior

The video plays with sound, in either quicktime or vlc.

#### Actual Behavior

The video does not play with sound, in either quicktime or vlc.

#### Steps to Reproduce the Problem

Run my code above using either of the audio files provided. Instead of using an image sequence clip like I did, you can also instantiate `video` like this:
```
video = VideoFileClip(video_path)
```
and point `video_path` to either of the videos in the attached dropbox folder.

#### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.0.3
  - Platform Name: Osx
  - Platform Version: 10.14.6 (Mojave)

**Comment by tburrows13** [comment]
Thanks for the detailed problem description.

```
audioclip.set_duration(10)
video.set_audio(audioclip)
```
These lines are wrong. `set_...` methods always return a copy of the clip, they do not act inplace.

Use this instead:
```
audioclip = audioclip.set_duration(10)
video = video.set_audio(audioclip)
```

(This confusion is why we will likely rename these methods to `with_duration` and `with_audio` in v2.0.)
