### ISSUE TITLE
numpy error on trying to concatenate

### ISSUE THREAD

**Issue by icarito** [Zulko/moviepy#123]
I tried this with different versions of moviepy even git head. Tried python3.4 and python2.7.
I don't know what's wrong here: 

$ python gen_video1.py 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 1982, in cumsum
    cumsum = a.cumsum
AttributeError: 'list' object has no attribute 'cumsum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gen_video1.py", line 31, in <module>
    final = mpy.concatenate([mapa1, mapa2])
  File "/usr/lib/python3.4/site-packages/moviepy/tools.py", line 129, in fdepr
    return f(*a, **kw)
  File "/usr/lib/python3.4/site-packages/moviepy/video/compositing/concatenate.py", line 90, in concatenate_videoclips
    result.mask = concatenate_videoclips(masks, method="chain", ismask=True)
  File "/usr/lib/python3.4/site-packages/moviepy/video/compositing/concatenate.py", line 69, in concatenate_videoclips
    tt = np.cumsum([0] + [c.duration for c in clips])
  File "/usr/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 1984, in cumsum
    return _wrapit(a, 'cumsum', axis, dtype, out)
  File "/usr/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

The code in gen_video1.py is:

import moviepy.editor as mpy

mapa1 = mpy.ImageClip("mapa/laurelia-small.png")
mapa1 = mapa1.resize((400,300))
mapa1 = mapa1.fadein(5)
mapa1.set_duration(10)
mapa1.set_fps(15)

mapa2 = mpy.ImageClip("mapa/laurelia-small.png")
mapa2 = mapa2.resize((400,300))
mapa2.set_duration(5)
mapa2.set_fps(15)

final = mpy.concatenate([mapa1, mapa2])

**Comment by Zulko** [comment]
What is wrong is that your clips have no duration defined. Keep in mind that `mapa1.set_duration(10)` does not change the duration of mapa1, instead it creates a new clip with that duration.

So your code should look like this:

    mapa1 = (mpy.ImageClip("mapa/laurelia-small.png")
                .resize((400,300))
                .set_duration(10)
                .fadein(5))

I will change the error message so that it's more helpfull.

Note also that it's not necessary to use set_fps on every clip. Just leave them without fps, and define the fps when you write the final video:

    final.write_videofile("test.mp4", fps=15)

Tell me if this works so I can close the issue.

**Comment by icarito** [comment]
Thanks!

Admittedly I'm just a beginner moviepy-er. Thanks for your work and response.
It's a good idea to improve the error message.
I've changed my code to look what you posted, and now it works.

  mapa1 = (mpy.ImageClip("mapa/laurelia-small.png")
              .resize((400,300))
              .set_duration(10)
              .fadein(5))

  mapa2 = (mpy.ImageClip("mapa/laurelia-small.png")
              .resize((400,300))
              .set_duration(5))

  final = mpy.concatenate_videoclips([mapa1, mapa2])
  final.set_fps(15)

**Comment by Zulko** [comment]
Careful again: final.set_fps(15) does nothing, you must either write

    final = final.set_fps(15)

or simply not use set_fps and just provide a `fps` when you use `write_videofile`.

I'm closing this as solved.
