### ISSUE TITLE
WARNING:py.warnings:site-packages\moviepy\video\io\ffmpeg_reader.py:123: UserWarning: Using the last valid frame instead.

### ISSUE THREAD

**Issue by mike592** [Zulko/moviepy#1230]
Please help me out, I am using moviepy version 1.03, and I got a lot warning like this : 

WARNING:py.warnings:site-packages\moviepy\video\io\ffmpeg_reader.py:123: UserWarning: Warning: in file G:\AA\ADE8.mp4, 6220800 bytes wanted but 0 bytes read,at frame 450/451, at time 18.00/18.02 sec. Using the last valid frame instead.

really don't know how to resolve, please help me out.

**Comment by tburrows13** [comment]
If the program is not crashing and the output is what you expected, then you can safely ignore the warnings. The warnings might be fixed in #1220.

**Comment by mike592** [comment]
But really don't know what kind of input clip will cause this crash. I got this problem from the crash log of my program.  try ......(all my main program)  except Exception: e  logging.
