### ISSUE TITLE
Three Questions About TextClip

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1240]
```
from moviepy.editor import *
fps = 3
inf = r"text clip test"

txtclip = TextClip(inf ,font='Courier',fontsize=12,color='red',bg_color='white').set_duration(5).set_fps(1)

   # print("font", txtclip.list("font"))
   # print("color", txtclip.list("color"))
txtclip.write_videofile(r"F:\video\text.avi", codec='rawvideo', threads=threads)
txtclip.close()
```

#### Expected Behavior
Display information according to the set font content, size and color during movie playing，the font color is red,fontsize=12

#### Actual Behavior

1.The font color is blue;
2.The fontsize is larger than 12,and when set fontsize=8,it will be more  larger than fontsize=12
3. Letters upside down；
These three cases are shown in the capture.jpg,but I'm sorry  the upload failed,maybe upload later. 
4.txtclip.list("Font") report：

```
"C:\Program Files\Python37\python.exe" F:/study/python/project/moviepyTest/moviepyTest.py
Traceback (most recent call last):
  File "F:/study/python/project/moviepyTest/moviepyTest.py", line 17, in <module>
    print("font",txtclip.list("font"))
  File "C:\Program Files\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1177, in list
    return [l.decode('UTF-8')[8:] for l in lines if l.startswith(b"  Font:")]
  File "C:\Program Files\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1177, in <listcomp>
    return [l.decode('UTF-8')[8:] for l in lines if l.startswith(b"  Font:")]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8: invalid start byte
```

When I modified VideoClip.py at line 1177：
            return [l.decode('ANSI')[8:] for l in lines if l.startswith(b"  Font:")]
to:
       return [l.decode('ANSI')[8:] for l in lines if l.startswith(b"  Font:")]

There are other similar problems in codec, so it can be said that moviepy does not support Chinese environment or multi-national languages well

5.There's another question(A question about CompositeVideoClip #1223) that hasn't received a final answer. Are you still following up?

#### Steps to Reproduce the Problem

I can't confirm what environment will cause this problem. I think it may be related to the machine environment, especially the Chinese operating system environment.

#### Specifications

  - Python Version: 3.72
  - Moviepy Version:1.03
  - Platform Name:WINDOWS
  - Platform Version:win7 64bit

**Comment by tburrows13** [comment]
Hello.

1. This is because "red" is not a valid value, so it instead uses the default value of blue. Use `TextClip.list("Color")` or run `magick -list color` in the commandline  to see a list of valid values.

2. I'm not sure what is causing this.

3. I can't replicate this.

4. It could be because you have a non UTF-8 font name on your system. You can check that with `magick -list font` in your command line. I think that you will find that MoviePy v2.0.0.dev1 has fixed this problem. Update with `pip install moviepy --pre --upgrade`.

In v2.0 there will likely be a completely different backend for TextClip, using pillow (#1145), which will make all these issues that you have here invalid.

**Comment by LaoYuanPython** [comment]
The release of 2.0 is really something to celebrate，thanks very much！

**Comment by LaoYuanPython** [comment]
As for the new version 2.0, it is found that the problem of textclip has not been solved after installation. As for the problems mentioned in the earlier stage, here are some additional instructions:

1. The color does not take effect. It is confirmed that the color used in the script can be found in the list ('color '), and the PNG picture in the middle of the corresponding text has been generated. The color, font and arrangement in the picture file are very normal, but the color and font are not normal after the editing. This situation should be caused by the image with alpha layer. The image sequence clip is used to construct the middle picture file, and the display is normal, but the image clip is not. So the problem should be imageclip;

2. After textclip specifies the temptxt parameter, the problem that the content of TXT is replaced by the file name corresponding to temptxt has not been solved after verification, and the following code with related problems has not been modified.
The corresponding code is in lines 1190 to 1201 of videoclip, as follows:
'''
 if txt is not None:
            if temptxt is None:
                temptxt_fd, temptxt = tempfile.mkstemp(suffix=".txt")
                try:  # only in Python3 will this work
                    os.write(temptxt_fd, bytes(txt, "UTF8"))
                except TypeError:  # oops, fall back to Python2
                    os.write(temptxt_fd, txt)
                os.close(temptxt_fd)
            txt = "@" + temptxt
        else:
            # use a file instead of a text.
            txt = "@%" + filename
'''
As can be seen from the above code, when both txt and temptxt have values, txt is assigned "@" + temptxt， and the text content corresponding to txt is not written to the temporary file corresponding to the temptxt。

**Comment by LaoYuanPython** [comment]
As for the new version 2.0, it is found that the problem of textclip has not been solved after installation. As for the problems mentioned in the earlier stage, here are some additional instructions:

1. The color does not take effect. It is confirmed that the color used in the script can be found in the list ('color '), and the PNG picture in the middle of the corresponding text has been generated. The color, font and arrangement in the picture file are very normal, but the color and font are not normal after the editing. This situation should be caused by the image with alpha layer. The image sequence clip is used to construct the middle picture file, and the display is normal, but the image clip is not. So the problem should be imageclip;

2. After textclip specifies the temptxt parameter, the problem that the content of TXT is replaced by the file name corresponding to temptxt has not been solved after verification, and the following code with related problems has not been modified.
The corresponding code is in lines 1190 to 1201 of videoclip, as follows:
'''
 if txt is not None:
            if temptxt is None:
                temptxt_fd, temptxt = tempfile.mkstemp(suffix=".txt")
                try:  # only in Python3 will this work
                    os.write(temptxt_fd, bytes(txt, "UTF8"))
                except TypeError:  # oops, fall back to Python2
                    os.write(temptxt_fd, txt)
                os.close(temptxt_fd)
            txt = "@" + temptxt
        else:
            # use a file instead of a text.
            txt = "@%" + filename
'''
As can be seen from the above code, when both txt and temptxt have values, txt is assigned "@" + temptxt， and the text content corresponding to txt is not written to the temporary file corresponding to the temptxt。

**Comment by ODtian** [comment]
Hi @LaoYuanPython, I'm not sure what exactly issus you are facing, but I probably know something about that. If the text image are outlined with black lines on a transparent background, that comes from PIL, it doesn't consider transparency when pasting text on an RGBA image,  pr which fix this problem has been merged. 
For now, see the script in #1145 and create text from image manually.

**Comment by LaoYuanPython** [comment]
ok
