### ISSUE TITLE
TextClip

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1242]
```
from moviepy.editor import *
fps = 3
inf = r"text clip test"

txtclip=TextClip(inf,font='Courier',fontsize=12,color='red',bg_color='white',transparent=True,tempfilename=r'F:\temp\img\txtjpg.png',temptxt=r'F:\temp\img\txtjpg.txt',remove_temp=False).set_duration(15).set_fps(3)
```

#### Actual Behavior

When using the parameter temptxt of the construction method for TextClip to output the temporary file, it is found that the specified content of the txt parameter is replaced by the file name corresponding to temptxt. Therefore, after a careful look at the textclip related code, it is found that there should be a problem in the 1090 to 1098 lines of VideoCode.py. When enabling temptxt, replace the content of the txt parameter with '@' + temptxt。the 1090 to 1098 lines of VideoCode.py are：

```
        if txt is not None:
            if temptxt is None:
                temptxt_fd, temptxt = tempfile.mkstemp(suffix='.txt')
                try:  # only in Python3 will this work
                    os.write(temptxt_fd, bytes(txt, 'UTF8'))
                except TypeError:  # oops, fall back to Python2
                    os.write(temptxt_fd, txt)
                os.close(temptxt_fd)
            txt = '@' + temptxt
```

Further validation found that if the text to build TextClip comes from the file specified by the filename parameter, its content is also replaced by the file name.

#### Steps to Reproduce the Problem

```
1.
txtclip = TextClip(inf ,font='Courier',fontsize=12,color='red',bg_color='white',transparent=True,tempfilename=r'F:\temp\img\txtjpg.png',temptxt=r'F:\temp\img\txtjpg.txt',remove_temp=False).set_duration(15).set_fps(3)

2.
txtclip = TextClip(filename=r'F:\temp\img\test.txt', font='Courier', fontsize=12, color='red', bg_color='white', transparent=True,
                       tempfilename=r'F:\temp\img\txtjpg.png', temptxt=r'F:\temp\img\txtjpg.txt',
                       remove_temp=False).set_duration(15).set_fps(3)
```
#### Specifications

  - Python Version:3.7.2
  - Moviepy Version:1.03
  - Platform Name:windows
  - Platform Version:win7

**Comment by LaoYuanPython** [comment]
I found that the problem was focused on the image clip output, so turning off the problem raised another easy to explain situation.

**Comment by LaoYuanPython** [comment]
I found that the problem was focused on the image clip output, so turning off the problem raised another easy to explain situation.

**Comment by tburrows13** [comment]
This code will likely be removed with v2.0's upcoming pillow TextClips.
