### ISSUE TITLE
VideoClip.write_videofile's result is not expected

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1245]
```
    threads = 8
    fps = 3
    fname = r"F:\temp\alphaimg\txtjpg.PNG"

    imgclip = ImageClip(fname,  duration=3).set_fps(fps)
    imgclip.save_frame(r"F:\temp\alphaimg\txtjpg1.PNG", withmask=True)
    imgclip.write_videofile(r"F:\temp\alphaimg\red.avi", codec='rawvideo', threads=threads)
    imgclip.close()
```

[alphaimg.zip](https://github.com/Zulko/moviepy/files/4812240/alphaimg.zip)
The above codes create a clip from  the file "txtjpg.png"  and use ImageClip.save_frame output a frame to the file "txtjpg1.png",and finally output the clip content to "red.avi" .

#### Expected Behavior
1.txtjpg.png  is the same as txtjpg1.png
2.red.avi display contents like as  txtjpg.png

#### Actual Behavior
Execution results are:
1.txtjpg.png  is the same as txtjpg1.png
2.red.avi display contents  changes the color of the picture, and the text in the picture is  upside down.

txtjpg.png , txtjpg1.png and red.avi are compressed   together in the  alphaimg.zip attachmented

#### Steps to Reproduce the Problem

1. Download the attachment and unzip it;
2. Change the directory name in the above script according to the decompression directory;
3. Execute script

In addition to using ImageClip for implementation, the following methods also tested:

```
imsClip = ImageSequenceClip([r"F:\temp\alphaimg\txtjpg.png]",fps=1).set_duration(5)
```

There is the same problem。

#### Specifications

  - Python Version:3.7.2
  - Moviepy Version: 1.03  &  2.0.0.dev1
  - Platform Name: windows
  - Platform Version:win7 64bits

**Comment by LaoYuanPython** [comment]
[alphaimg.zip](https://github.com/Zulko/moviepy/files/4812369/alphaimg.zip)

**Comment by tburrows13** [comment]
Hello, thanks for this bug report. I have ran your code and looked at your linked files. Neither my code's output or any of your files appear upside down, so I think that this must be a problem with your video player. I am getting the blue text, but I don't know why. If you output to mp4 it does not occur. It may be to do with the `rawvideo` codec.

**Comment by LaoYuanPython** [comment]
Mp4 was generated during the first test, but Windows media player does not support this type or codec of this file. Therefore, an AVI file is generated. Windows Media Player encountered a problem while playing the file. As a result, another player from China's domestic manufacturer was used, and the problem of blue and character inversion was encountered. After reading your answer, modified the code,MP4 was generated and played normally with this player,but Windows Media Player can't play as before. Thank you very much!

**Comment by tburrows13** [comment]
Sorry, I have no idea how `f_accel_decel` works or what the formula would be called.

**Comment by LaoYuanPython** [comment]
Sorry to waste your time,thank you!
