### ISSUE TITLE
How to use manual_tracking and headblur?

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1246]
Hi，
The example maybe out of date in the https://zulko.github.io/moviepy/examples/headblur.html?highlight=manual_tracking , because the function to_ fxfy is not defined in the current version(1.03). How to use data obtained by manual_tracking  for headblur?And how to using autoTrack?

Thank you for reading my question.

**Comment by tburrows13** [comment]
Indeed the examples for some of these advanced tools are out of date or nonexistent (#850, #167). I'm expecting to update them soon.

In the meantime, have a look at #1061 or consider the documentation: https://zulko.github.io/moviepy/ref/videotools.html#module-moviepy.video.tools.tracking which looks like it is more up-to-date.

**Comment by LaoYuanPython** [comment]
Thanks for your reply,I found the examples in t #1061,but test found errors.The details is attached in https://github.com/Zulko/moviepy/pull/1061.

**Comment by LaoYuanPython** [comment]
I had resolved this question,the detail is listed in :https://blog.csdn.net/LaoYuanPython/article/details/107307239。

**Comment by KiLLAAA** [comment]
can you share the solution in english here, please? the page with detail throws 404, and its site is in chinese...

**Comment by LaoYuanPython** [comment]
I can't open the web becuase transfer speed is too slow in my environment,using to reply email:
Using following codes:
```
tracking = moviepy.video.tools.tracking.manual_tracking(clip,0,3, fps=2)[0] clip_blurred = clip.fx(vfx.headblur, tracking.xi, tracking.yi, 30) 
```
but must modify the headblur function to avoid the numpy error "ValueError: assignment destination is read-only",the modified code as following:
```
def headblur(clip, fx, fy, r_zone, r_blur=None): """ Returns a filter that will blurr a moving part (a head ?) of the frames. The position of the blur at time t is defined by (fx(t), fy(t)), the radius of the blurring by ``r_zone`` and the intensity of the blurring by ``r_blur``. Requires OpenCV for the circling and the blurring. Automatically deals with the case where part of the image goes offscreen. """ if r_blur is None: r_blur = 2 * r_zone / 3 r_blur = int(2 * r_zone / 3) # added by jwp,TypeError: integer argument expected, got float def fl(gf, t): im = gf(t) h, w, d = im.shape x, y = int(fx(t)), int(fy(t)) x1, x2 = max(0, x - r_zone), min(x + r_zone, w) y1, y2 = max(0, y - r_zone), min(y + r_zone, h) region_size = y2 - y1, x2 - x1 mask = np.zeros(region_size).astype('uint8') cv2.circle(mask, (r_zone, r_zone), r_zone, 255, -1, lineType=cv2.CV_AA) mask = np.dstack(3 * [(1.0 / 255) * mask]) orig = im[y1:y2, x1:x2] blurred = cv2.blur(orig, (r_blur, r_blur)) imblur = mask * blurred + (1 - mask) * orig imseg = np.hstack((im[y1:y2, 0:x1],imblur,im[y1:y2,x2:])) imnew = np.vstack((im[0:y1,0:],imseg,im[y2:,0:])) return imnew return clip.fl(fl)
```
And i think has another resolution but havn't test: using ```im = np.array(gf(t)) ``` to replace ```im = gf(t)```
From: Lukáš
Date: 2020-08-12 18:59
To: Zulko/moviepy
CC: LaoYuanPython; State change
Subject: Re: [Zulko/moviepy] How to use manual_tracking and headblur? (#1246)
can you share the solution in english here, please? the page with detail throws 404, and its site is in chinese...
