### ISSUE TITLE
TextClip's problem with Chinese support

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1248]
'''
 inf =  """
    Scrolls horizontally or vertically a clip, e.g. to make end credits

    Parameters
    -----------

    w, h
      The width and height of the final clip. Default to clip.w and clip.h

    x_speed, y_speed

    x_start, y_start

    apply_to
    中国欢迎你！
    Welcom to China!

    """
    clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4",audio=False).crop(0, 300, 540, 840).subclip(0,10)
    txtclip = TextClip(inf, font='Courier', fontsize=18, color='blue', bg_color='white', transparent=True).set_duration(8).set_fps(clip.fps).fx(vfx.scroll,x_speed=60).set_start(clip.end)
    newclip = CompositeVideoClip([clip,txtclip], bg_color=(255, 255, 255), ismask=False)
    newclip.write_videofile(r"F:\video\WinBasedWorkHard_scroll.mp4", threads=8)
'''

#### Expected Behavior
Text will show nomally in the final clip;

#### Actual Behavior
The chiness characters (the line before 'Welcom to China!') were disappered in clip,but other english characters were displayed normaly.

#### Specifications

  - Python Version:3.72
  - Moviepy Version:2.0.0.dev1
  - Platform Name:windows
  - Platform Version:win7 64bits

**Comment by ODtian** [comment]
That's probably because your font doesn't support Chinese char, actually there is a exists issue which come up with similar question, I think you could find it in the closed issues.

**Comment by LaoYuanPython** [comment]
Thanks,I had founded it at [NO chinese subtitle #1112](https://github.com/Zulko/moviepy/issues/1112)
