### ISSUE TITLE
TextClip can't preview

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1249]
```
from  moviepy.editor import *
inf =  """
    Scrolls horizontally or vertically a clip, e.g. to make end credits

    Parameters
    -----------

    w, h
      The width and height of the final clip. Default to clip.w and clip.h

    x_speed, y_speed

    x_start, y_start

    apply_to
    中国欢迎你！
    Welcom to China!

    """
txtclip = TextClip(inf, font='Courier', fontsize=18, color='blue', bg_color='white', transparent=True).set_duration(8).set_fps(30).fx(vfx.scroll,x_speed=60,y_speed=60)
preview(txtclip)
```

#### Expected Behavior
Text clip can be previewed.

#### Actual Behavior
preview failed because error:

```
>>> preview(txtclip)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    preview(txtclip)
  File "<decorator-gen-128>", line 2, in preview
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\io\preview.py", line 44, in preview
    pg.mixer.init(fps, -8 * nbytes, clip.nchannels, 1024)
AttributeError: 'VideoClip' object has no attribute 'nchannels'
>>> 
```

#### Steps to Reproduce the Problem

excute the scripts

#### Specifications

  - Python Version:3.72
  - Moviepy Version:2.0.0.dev1
  - Platform Name:windows
  - Platform Version:win7 64bits

**Comment by mondeja** [comment]
You are calling the function that previews the audio in a video file. The problem is that both video preview function and audio preview function have the same name `preview`. This could confuse and must be properly handled, I will open a pull for this. As a workaround, you can use `VideoClip.preview(txtclip)`.

**Comment by tburrows13** [comment]
> You are calling the function that previews the audio in a video file. The problem is that both video preview function and audio preview function have the same name `preview` in `moviepy.editor` module. I will open a pull for this. As a workaround, you can use `VideoClip.preview(txtclip)`.

This is correct, but you should use `txtclip.preview()` instead.
