### ISSUE TITLE
How can I release ffmpeg process after task finished

### ISSUE THREAD

**Issue by Boliang-Lu** [Zulko/moviepy#1258]
I use moviepy to loop through multiple video compositions, but after the synthesis, the ffmepg process cannot be released
![image](https://user-images.githubusercontent.com/32253349/86698987-5edae600-c042-11ea-9706-6400816299c9.png)

**Comment by tburrows13** [comment]
Are you calling `.close()` on your clips? You might find the advice here useful: https://zulko.github.io/moviepy/getting_started/efficient_moviepy.html#when-to-close-a-clip.

**Comment by Boliang-Lu** [comment]
thanks
