### ISSUE TITLE
Loading a 60fps VideoFileClip and saving it seems to make it 2x faster

### ISSUE THREAD

**Issue by jdjakub** [Zulko/moviepy#1263]
#### Steps to Reproduce the Problem
```
from moviepy.editor import *
clip = VideoFileClip('60fps-test.mp4')
clip.write_videofile('duplicate.mp4')
```

#### Expected Behavior
This should be an identity operation, right? Read in a file, output a copy unchanged. `duplicate.mp4` should at least have the same speed as the original.

#### Actual Behavior
`duplicate.mp4` is sped up by what appears to be a factor of 2, yet has the same duration. So the original video finishes halfway through, and the second half of the output is just the final frame of the original.

#### Other
Performing the above on a 24fps mp4 results in the expected behaviour. Just this 60fps one that gets sped up. And this speeding-up effect is unchanged by specifying the `fps` parameter in `write_videofile`, either as 60 or 24.

I noticed this when trying to compose a transparent overlay on top of a gameplay video, but managed to reduce it to this case.

#### Specifications
  - Python Version: 3.8.3
  - Moviepy Version: 1.0.3
  - Platform Name: MacOS
  - Platform Version: Catalina 10.15.1

**Comment by tburrows13** [comment]
Thanks for reporting this. It is a known issue, you can fix it by using `fps_source="fps"` in `VideoFileClip`. This will likely become the default in v2.0.
