### ISSUE TITLE
Video editing 

### ISSUE THREAD

**Issue by laxman432** [Zulko/moviepy#1266]
Hi we like to add images( logo) and text data on video template is it possible using movie py

**Comment by mgaitan** [comment]
For the logo consider [this example](https://github.com/Zulko/moviepy/issues/127#issuecomment-74221540)

For text, the very first example in the documentation show how to composite a "text clip" 
https://zulko.github.io/moviepy/getting_started/quick_presentation.html#example-code

PS (with the utmost respect): questions are very welcome, but try to make a minimum research by yourself before opening an issue.
