### ISSUE TITLE
[WinError 2] The system cannot find the file specified.

### ISSUE THREAD

**Issue by laxman432** [Zulko/moviepy#1267]
WinError 2] The system cannot find the file specified.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

the above error i am getting i am not able to get it i installed imagemagic but i am not able to give path in config defaults.py 
i am using anaconda spyder

**Comment by tburrows13** [comment]
See #1472 - ImageMagick is being replaced in v2.0 so this will no longer be an issue.
