### ISSUE TITLE
ValueError: Attribute 'duration' not set when compositing a TextClip on a ColorClip

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1268]
```
import moviepy.editor as mped
import numpy as np
colour_clip = mped.ColorClip(size=[500, 50], color=np.array([250, 90, 0]).astype(np.uint8), duration=3)
txtClip = mped.TextClip('Text', color="grey", fontsize=10)
stacked_clips = mped.CompositeVideoClip([colour_clip, txtClip])
stacked_clips.write_videofile('text_on_colour.mp4', fps=5)
```

#### Expected Behavior
I was expecting it to stack the text onto the coloured background.

#### Actual Behavior
Traceback (most recent call last):
  line 18, in <module>
    stacked_clips.write_videofile('text_on_colour.mp4', fps=5)
  site-packages\decorator.py:decorator-gen-51>", line 2, in write_videofile
  \moviepy\decorators.py", line 52, in requires_duration
    raise ValueError("Attribute 'duration' not set")
ValueError: Attribute 'duration' not set

#### Steps to Reproduce the Problem
Copy and paste code above and run

#### Specifications
  - Python Version:  3.7.6
  - Moviepy Version : 1.0.0
  - Platform Name : Windows
  - Platform Version : 10

**Comment by Zulko** [comment]
I think it's because your text clip is considered to have "inifinite" duration and by extension so does your stacked_clips. To fix this,  use set_duration as follows:

```python
txtClip = mped.TextClip('Text', color="grey", fontsize=10).set_duration(3)
# or
stacked_clips = mped.CompositeVideoClip([colour_clip, txtClip]).set_duration(3)
```

**Comment by OneWorld-github** [comment]
Thank you so much Zulko, this worked.
