### ISSUE TITLE
rotating TextClip on a coloured background creates a black box around the text, after adding a mask, and distorted edges without adding a mask

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1269]
```
# text rotation using moviepy
import moviepy.editor as mped
import numpy as np

colour_clip = mped.ColorClip(size=[300, 200], color=np.array([250, 90, 0]).astype(np.uint8), duration=1).set_position((0, 0))
txtClip = mped.TextClip('Text', color="#4a4a4a", size=[200,100]).set_position((0,0)).set_duration(1)
txtClip = txtClip.add_mask().rotate(45, unit='deg', expand=True)
stacked_clips = mped.CompositeVideoClip([colour_clip, txtClip]).set_duration(1)
stacked_clips.write_videofile('text_rotated_with_mask_applied_to_rotation.mp4', fps=5)
```

#### Expected Behavior
rotated text with nice edges, but without creating a black box around the text.

#### Actual Behavior
creates a black box around the text

ps. if you take add_mask() out, then what happens is that the text looks distorted around the edges.

#### Steps to Reproduce the Problem
copy and paste code above and run

If you try this line instead, ie without adding mask, you get distorted edges.
```
txtClip = txtClip.rotate(45, unit='deg', expand=True)
```

I think this might have something to do with an asset having a transparent background

#### Specifications
  - Python Version: 3.7.4
  - Moviepy Version: 1.0.0

**Comment by mondeja** [comment]
You only need to remove the `.add_mask()` call in `txtClip`.

**Comment by mondeja** [comment]
I've used your example to illustrate the poor quality of ImageMagick texts in #1472 and I will use that issue to track this. Thank you for open this :pray:
