### ISSUE TITLE
error when masking and rotating a png containing text, that has a transparent background -  ValueError: operands could not be broadcast together with shapes (830,830) (830,830,3) 

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1270]
Are there any patches or workarounds for this issue please ?

```
import moviepy.editor as mped
text_png = mped.ImageClip("a_png_of_text_with_transparent_background.png", duration=1).set_position((0,0))
masked_rotated_text_png = text_png.add_mask().rotate(45, unit='deg', expand=True)
stacked_clips = mped.CompositeVideoClip([masked_rotated_text_png]).set_duration(1)
stacked_clips.write_videofile('hello_masked_and_rotated_by_moviepy.mp4', fps=5)
```

#### Expected Behavior
to rotate the png and maintain the transparency.  The Pillow code below works alright.  But it doesn't work with the moviepy code above:-
```
from PIL import Image
png = Image.open("text_with_transparent_background.png")
im_masked_rotated = png.convert("RGBA").rotate(45, expand=True)
im_masked_rotated.save("hello_masked_and_rotated_using_pillow.png")
```

png_of_text_on_transparent_background_rotated_using_moviepy.py", line 28, in <module>
    stacked_clips.write_videofile('hello_masked_and_rotated_by_moviepy.mp4', fps=5)
  File "<decorator-gen-51>", line 2, in write_videofile
  moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  /moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  moviepy/video/VideoClip.py", line 326, in write_videofile
    logger=logger)
  moviepy/video/io/ffmpeg_writer.py", line 216, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  moviepy/Clip.py", line 475, in iter_frames
    frame = self.get_frame(t)
  File "<decorator-gen-10>", line 2, in get_frame
  moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  moviepy/video/compositing/CompositeVideoClip.py", line 118, in make_frame
    f = c.blit_on(f, t)
  moviepy/video/VideoClip.py", line 586, in blit_on
    return blit(img, picture, pos, mask=mask, ismask=self.ismask)
  moviepy/video/tools/drawing.py", line 45, in blit
    1.0 * mask * blitted + (1.0 - mask) * blit_region)

#### Steps to Reproduce the Problem
copy and paste the code above, find a file that has text in it, on a transparent background.
Change the filename in the function to match your downloaded png filename.
Run the code.

#### Specifications
  - Python Version: 3.7.4
  - Moviepy Version: 1.0.0
  - Platform Name: Windows or Mac

**Comment by Heedster** [comment]
related to #623

try the workaround in the thread. worked for me.

**Comment by keikoro** [comment]
Closing this due to lack of response after a potential solution was proposed.
