### ISSUE TITLE
How to get video and audio without set_audio

### ISSUE THREAD

**Issue by mr-winson** [Zulko/moviepy#1276]
Hello, I am I have a folder full of auto-generated videos and I want to combine concatenate them without listing them out obviously. There is never a certain number on clips in the folder, it is pretty random. I want to get all these clips and concatenate them.

here's what I have:
```py
videoFileList = []
for eachMP4File in os.listdir('./tmp/videos/'):
    videoFileList.append(moviepy.editor.VideoFileClip('./tmp/videos/' + eachMP4File))

print(videoFileList)
finalVideo = moviepy.editor.concatenate_videoclips(videoFileList, method="compose")
finalVideo.write_videofile(str(arguments.outputpath), audio_bitrate="1000k", bitrate="4000k")
```

Now obviously that will get rid of the audio because of `VideoFileClip` so what is a way I could get audio as well? I read a lot of the docs and can't seem to find an answer.

Thanks,
Jude Wilson

**Comment by tburrows13** [comment]
Sorry, I don't quite understand. VideoFileClip will also read the audio in as well, and will be accessible as a clip with `clip.audio`.

Your code should keep the audio intact and write it out at the end as well.

**Comment by mr-winson** [comment]
Hmm, ok. It doesn't seem this is happening with the final clip. I'll try a couple other things.

Thanks,
Jude Wilson

**Comment by mr-winson** [comment]
Actually, it seems this is an error with Preview, which is what I use to view files. After opening it in Chrome, it works

Thanks
