### ISSUE TITLE
TEXTCLIP

### ISSUE THREAD

**Issue by laxman432** [Zulko/moviepy#1282]
HI WE LIKE TO DISPLAY TWO OR THREE LINES OF TEXT ON VIDEO IS THERE ANY PROCESS TO DO WITHOUT WITHOUT USING REPEATED CODE   LIKE
 txt = ( TextClip("* We do AI PROJECTS",fontsize=70,color='red')
             .set_position('center')
             .set_duration(10) )
IF WE MAKE MULTIPLE TIMES ABOVE CODE WE CAN GET BUT WE NEED IN SINGLE

**Comment by tburrows13** [comment]
Try putting a newline (`\n`) in your text string.

**Comment by keikoro** [comment]
@laxman432 I assume the above helped fix your problem. Please feel free to reopen the issue with more info if that is not the case.
