### ISSUE TITLE
How do I properly do clip.close() ?

### ISSUE THREAD

**Issue by Va1a** [Zulko/moviepy#1283]
In my script, I import VideoFileClip() from moviepy's editor module:
```from moviepy.editor import VideoFileClip```

I then create a clip variable:
```
clip = VideoFileClip(video)
(work with video here)
clip.close() #this returns a "Clip has no attribute close()"
```
I saw that the documentation recommends using a with statement,
```
with VideoFileClip(video) as clip:
    (work with video here) [INDENTED]
```
And then moviepy should auto-close the clip, however this is not working either! It returns an attribute error, stating there is no `__enter__` attribute.

What do I do? Perhaps I am improperly importing VideoFileClip?

**Comment by tburrows13** [comment]
Are you running the latest version of MoviePy? (1.0.3)

**Comment by Va1a** [comment]
Ah, you are right, I was running an old version due to some old package requiring an older version. Thank you for your assistance.
