### ISSUE TITLE
Mirrored Arabic Letters using TextClip 

### ISSUE THREAD

**Issue by wellisrite** [Zulko/moviepy#1286]
I am trying to render the video which contains arabic letters. let's use مرحبا for the example. After video rendered the result is mirrored.

```
background = mp.ColorClip(mobile_size, (255, 255, 255), duration=0.5) #float(audiolength.info.length)
text1 = mp.TextClip(english, fontsize=45, color=fcolor, font=Font, size= (mobile_size[0], 185), method = 'caption', align="south").set_duration(0.5) #float(audiolength.info.length)
text2 = mp.TextClip(formatChineseSentences(translated).encode("utf-8"), fontsize=45, color=fcolor2, font=Font, size= (mobile_size[0], 185), method = 'caption', align="north").set_duration(0.5) #float(audiolength.info.length)

clip1 = mp.CompositeVideoClip([background, text1.set_position(('center', "top")), text2.set_position(('center', "bottom"))])
```
#### Expected Behavior
![Pasted File at August 3, 2020 9_30 PM-2](https://user-images.githubusercontent.com/33211155/89243919-697f9f80-d62f-11ea-8a62-1ebddd9fffb4.png)

#### Actual Behavior
![Pasted File at August 3, 2020 9_30 PM](https://user-images.githubusercontent.com/33211155/89243914-6684af00-d62f-11ea-9bd1-d22704c56b51.png)

#### Steps to Reproduce the Problem
Rendering TextClip with Arabic Characters. For this case we can use مرحبا.

#### Specifications

  - Python Version: Python 3.8.5
  - Moviepy Version: 1.0.3
  - Platform Name: Mac OS Catalina
  - Platform Version: 10.15.6

**Comment by ODtian** [comment]
It should be noted that Arabic is a right-aligned language, which may be derived from the wrong processing of the underlying text rendering, or it was not considered in the textclip implementation

**Comment by wellisrite** [comment]
Yeah This is not a bug. Case closed
