### ISSUE TITLE
bug introduced in 0.2.2.11?

### ISSUE THREAD

**Issue by amalgamatedclyde** [Zulko/moviepy#129]
i think i noticed some incorrect behavior in 0.2.2.11 that was not present in 0.2.2.10. i'm creating a clip with video.write_videofile  using one VideoFileClip. the final clip has the correct inpoint of the subclip but has an incorrect outpoint, and continues to the end of the VideoFileClip.

i tested it a bunch of times

clyde

**Comment by Zulko** [comment]
Thanks for the report. Can you give a minimal script to reproduce the error ?

**Comment by amaglamatedclyde** [comment]
give me a day or so. i had a bug in my own code that was causing the same behavior, so i need to check it out some more.

**Comment by earney** [comment]
@amalgamatedclyde  have you resolved this issue?  Can we close this issue?

**Comment by kerstin** [comment]
Closing this as there hasn't been a reaction in 10 days + it's a very old issue that never had a script added to it for testing purposes.

Please feel free to reopen with an example script if the error persists.
