### ISSUE TITLE
How is the start time of an audio file controlled?

### ISSUE THREAD

**Issue by jordansaethre** [Zulko/moviepy#1293]
Hello,

I am trying to create a video with an audio clip to be played 3 seconds into the video, but it always puts it at the beginning. 

Does set_start(n) mean that it will set the audio or video clip to start n seconds into the final video file?

Code below:

```
import numpy as np
from moviepy.editor import *

# grab a 5 second video clip without the audio
video = VideoFileClip("C:/.../examplevideo.mp4",audio = False).subclip(35,40)

# create a 'beep'
beep = lambda t: [ np.sin(640 * np.pi * t) ] 

# create an audio clip of the beep to last 0.7 seconds long
audioclip = AudioClip(beep, duration=.7)

# add audio clip to the video clip but have the beep start at 3 seconds in
video = video.set_audio(audioclip.set_start(3))

# write to video file
video.write_videofile("audiotest.mp4")
```

This code runs and creates a video just fine, except no matter what I do the beep is always at the beginning instead of at 3 seconds in. What am I missing here?

**Comment by tburrows13** [comment]
Instead of `video = video.set_audio(audioclip.set_start(3))`, try doing `video = CompositeVideoClip([video, audio clip.set_start(3)])`. `set_start()` has no effect unless it is included in a Composite Clip.

**Comment by keikoro** [comment]
@jordansaethre If the above didn't help/answer your question, please feel free to reopen the issue.

**Comment by EnragedViper** [comment]
@tburrows13 This doesn't seem to work for me. Using the OP's code and changing that line gives me this error (in moviepy 1.0.3):

```
Traceback (most recent call last):
  File "E:\EnragedViper\Documents\moviepytest.py", line 14, in <module>
    video = CompositeVideoClip([video, audioclip.set_start(3)])
  File "C:\Users\EnragedViper\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 91, in __init__
    audioclips = [v.audio for v in self.clips if v.audio is not None]
  File "C:\Users\EnragedViper\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 91, in <listcomp>
    audioclips = [v.audio for v in self.clips if v.audio is not None]
AttributeError: 'AudioClip' object has no attribute 'audio'
```

**Comment by skabbit** [comment]
Same error I have.

**Comment by skabbit** [comment]
Have the same error, but resolved it by using:
`clip.set_audio(CompositeAudioClip([audioclip.set_start(3)]))`
