### ISSUE TITLE
moviepy installed but 

### ISSUE THREAD

**Issue by XiaosongWen** [Zulko/moviepy#1294]
I have the moviepy installed using pip, and can see moviepy in pip list -v : 
moviepy                  1.0.3     c:\users\XXXXX\appdata\local\programs\python\python37-32\lib\site-packages

However, when I import into my jupyter notebook still get **No module named 'moviepy'**,

Any suggestions help.

Thanks a lot

**Comment by tburrows13** [comment]
This means that the installation of Python that jupyter is using isn't the same one that pip is using. This isn't really a MoviePy issue, just an issues with how you installed Python and MoviePy.
