### ISSUE TITLE
Setting AudioFileClip's Duration to longer than the original file causes OSError

### ISSUE THREAD

**Issue by robertjcolley** [Zulko/moviepy#1297]
Is there a way to set an AudioClip's duration to longer than the original duration?

```
from moviepy.editor import *
audio = AudioFileClip(tmpAudioFileName)
audio.set_duration(audio.duration + 1)
audio.write_audiofile(alternateAudioFileName)
```
This chunk of code gives me this error - I expected it to write empty audio for the last second.
OSError: Error in file audio-es.mp3, Accessing time t=21.36-21.40 seconds, with clip duration=21.320000 seconds, 

Is this an issue or have I misunderstood how to make an audio clip longer?

**Comment by keikoro** [comment]
This issue is missing information we request when creating new issues, like specs. I'd ask you to add them to make debugging easier (potentially), thanks.

**Comment by keikoro** [comment]
Also, please provide full error logs, thx.

**Comment by robertjcolley** [comment]
I've moved on from the project this was relevant too. I'll close for now!
