### ISSUE TITLE
Preview() fails, but write_videofile success

### ISSUE THREAD

**Issue by hpp0hpp** [Zulko/moviepy#1299]
When I do videoclip.Preview(), it fails as below. but write_videofile successful with right content.

I am not sure where this problem is. 

#### Expected Behavior
videoclip.Preview() successful

#### Actual Behavior

> File "C:\Users\hpp\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "<decorator-gen-218>", line 2, in preview
>   File "C:\Users\hpp\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
>     return f(clip, *a, **k)
> , line 49, in preview
>     sndarray = clip.to_soundarray(tt, nbytes=nbytes, quantize=True)
>   File "<decorator-gen-46>", line 2, in to_soundarray
>   File "C:\Users\hpp\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
>     return f(clip, *a, **k)
>   File "C:\Users\hpp\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\audio\AudioClip.py", line 110, in to_soundarray
>     max_duration = 1.0 * buffersize / fps
> TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
> 
#### Specifications

  - Python Version: 3.8
  - Moviepy Version: latest
  - Platform Name:windows
  - Platform Version: 10

**Comment by keikoro** [comment]
(fixed spelling of method)

**Comment by keikoro** [comment]
You didn't provide any code, which makes it impossible to debug this issue. -> Closing.
