### ISSUE TITLE
rotating image animation producing error

### ISSUE THREAD

**Issue by ebin123456** [Zulko/moviepy#130]
i have code like 

```
import numpy as np
import Image
from scipy import ndimage
import moviepy.editor as mpy

img = Image.open('leo_messi.jpg')
data = np.array(img.getdata(),np.uint8).reshape(img.size[1], img.size[0], 3)
def make_frame(t):
    return ndimage.rotate(data,int(t)*10)


clip = mpy.VideoClip(make_frame, duration=5)
clip.write_videofile("circle.mp4",fps=10)
```

I am trying to produce an animation that have rotation of input image. its not working

**Comment by Zulko** [comment]
what's the error ?

**Comment by ebin123456** [comment]
Full of noice in output video.

**Comment by ebin123456** [comment]
Hi 
i have fixed issue by passing reshape=False argument  
```
return ndimage.rotate(data,int(t)*10,reshape=False)
```

**Comment by Zulko** [comment]
Cool, I was going to suggest that. Just so you know it will soon be possible to rotate a clip like so in moviepy:

    newclip = clip.rotate(angle=lambda t: 10*t, *some_parameters)

I use the rotation offered by PIL (or rather pillow) I think it's slightly better than the one in ndimage.

**Comment by ebin123456** [comment]
Good work. 
Thanks.

**Comment by earney** [comment]
seems issue has been resolved.. closing
