### ISSUE TITLE
Previewing a video in a new thread

### ISSUE THREAD

**Issue by syedsajawalahmed** [Zulko/moviepy#1300]
I wanted to know if I can run/preview multiple videofileclips in separate threads?
I've been trying to do so using different multithreading libraries in python but unable to do so.
Facing errors. Any hint?

**Comment by keikoro** [comment]
I don't know about previewing specifically, but I'll refer you [to this comment](https://github.com/Zulko/moviepy/issues/1089#issuecomment-686136473) with regard to (potential future) multithreading support
