### ISSUE TITLE
Audio Frame Repeatition when combining videos clips

### ISSUE THREAD

**Issue by omerasif57** [Zulko/moviepy#1310]
Audio frames at very end of a clip get repeated when I concatenate two or more video clips.
I tinkered with
1. buffer size (writing with `audio_buffsize = 1000` works fine for now)
2. duration ( because I observed that for a clip with 43.15 sec of audio, final video get rounded to 44.0 which adds some glitch / last frame buffer repetition (I guess) = 44.0-43.15.)

writing with `audio_buffsize = 1000` works fine for now. But I am not sure whether it will work for every case. I need to write one long clips with many small clips hence need some advice/pointers on how to get cohesive result/clip.

```
com_vid.write_videofile(FINAL_OUT_VID,
                        fps=1,
                        audio_bitrate='192k',
                        audio_fps=44100,
                        audio_nbytes=2,
                        audio_codec="aac",
                        audio_bufsize=1000)  # fix issue for audio glitches.
```

**Comment by omerasif57** [comment]
updating the moviepy to latest version fixed the issue. pip was installing 1.0.3 version somehow.

**Comment by reddere** [comment]
Seems like it still happens, at least to me, even for merging few few-seconds-clips, and buffer size param is not there anymore, how can we fix this?

**Comment by omerasif57** [comment]
you can try this version
`moviepy==2.0.0.dev1`

**Comment by reddere** [comment]
Thanks! the audio frame repetition seems to have gone, but the audio is significantly delayed from the video, how can I fix it or delay it back? I've been looking for hours and cannot figure out the proper way

**Comment by omerasif57** [comment]
you can try this workaround: https://github.com/Zulko/moviepy/issues/1167#issuecomment-626302213

also you can try experimenting with audio params: such as audio fps or bitrate or buffersize or nbytes. (as mentioned above in my question)

Honestly, I am unable to provide any expert advice here as I used it for a tiny project and never used after since. I would suggest you to create a new issue here or any related forums with steps to reproduce and sample data if any. It would help to debug more effectively.

**Comment by reddere** [comment]
Thanks again Omer, actually I have just noticed that the audio is not delayed, but it is actually "anticipated".

With further investigation using a professional video editor program (Adobe Premiere Pro) I figured out that for every video used in the output, the audio gets automatically cut by 1 frame from its beginning (which is a LOT for 30fps videos), and since the video does not get cut in the beginning as for the audio, it results the video is delayed while only the audio is "anticipated". 

I tried finding a workaround, like cutting the video by 2 frames at its beginning, without success as VideoFileClip().set_start() seems not to work.

Also, I followed your suggestion and opened an issue at https://github.com/Zulko/moviepy/issues/1832, would be glad to get help to debug and finding a fix/workaround.

**Comment by dpkirchner** [comment]
I was able to work around the audio frame bug by preprocessing my video with ffmpeg to add a null audio source to the video. Roughly:

```bash
ffmpeg -i original.mp4 -f lavfi -i anullsrc=d=$duration -filter_complex '[0][1]amix=inputs=2:duration=first' -c:v copy -c:a aac -y output.mp4
```

What this does is it creates an audio-only input that has no audio and then mixes it with the audio from the original file.

This'll only work if you know the duration of the original video up front, unfortunately.

By the way, you can check to see if your video will be affected by the bug using ffprobe (on Linux, the Windows/PS command is probably 100x as long):

```bash
ffprobe -hide_banner -loglevel error -show_frames original.mp4 | egrep '^(media_type|pts_time)=' | awk -F= '{ if ($1 == "media_type") { type=$2 } else { foo[type] = $2 } } END { print "video", foo["video"], "audio", foo["audio"] }'
```

This will output the last timestamp of the video and audio streams in your mp4. (You'll need to adjust this if you have multiple video or audio streams, however.) If the timestamps are not identical or not very very close, you may end up with repeated audio at the end of your output video.
