### ISSUE TITLE
Quit preview of a clip

### ISSUE THREAD

**Issue by hugodomcon1** [Zulko/moviepy#1311]
I'd like to know how to quit de preview of a clip because Escape key doesn't work

Thank You

**Comment by ToxicOverload** [comment]
You should be able to quit with the escape key or simply close the window. Both are working fine for me.

**Comment by tburrows13** [comment]
The preview functionality is very rough and isn't really being actively maintained. It would be great to have something with more features (probably not using Pygame), but it isn't a high priority for me.

**Comment by keikoro** [comment]
Possible duplicate of #575

**Comment by mondeja** [comment]
This could have been fixed by #1537. If you still experiencing this problem with moviepy *master* version, please report it here and we'll investigate it. Without more knowing about the environment we can't reproduce nothing, so I'm closing this...
