### ISSUE TITLE
Bug by saving frame by frame

### ISSUE THREAD

**Issue by A2va** [Zulko/moviepy#1312]
```
import moviepy.editor as mpe_edit

clip=mpe_edit.VideoFileClip('input.mp4')

n_frames=clip.reader.nframes
fps=clip.fps

for i in range(0,n_frames):
    clip.save_frame('out/frame'+str(i)+'.jpg',t=i*fps)

clip.close()
```

#### Expected Behavior
Moviepy should save each frame of the video

#### Actual Behavior
Moviepy only saves the first frame, but 24 times (my video has 24 frames).

#### Steps to Reproduce the Problem
Run the above code

#### Specifications

  - Python Version:3.8.5
  - Moviepy Version:1.0.3
  - Platform Name: Windows 10

**Comment by jacobmischka** [comment]
Shouldn't the `t` value be just `i`, not `i*fps`?

Regardless, I believe [the iter_frames function](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.io.VideoFileClip.VideoFileClip.iter_frames) would be a more straightforward way to do what you're trying to do.

**Comment by tburrows13** [comment]
> I don't think the `i` value is correct, shouldn't it be `i/fps` instead of `i*fps`?
> 
> Regardless, I believe [the iter_frames function](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.io.VideoFileClip.VideoFileClip.iter_frames) would be a more straightforward way to do what you're trying to do.

Yes I agree
