### ISSUE TITLE
TextClip - TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by zilton7** [Zulko/moviepy#1313]
#### Expected Behavior
I want to add text to video

#### Actual Behavior
I am getting error - TypeError: 'NoneType' object is not callable

#### Steps to Reproduce the Problem
```
from moviepy.editor import *

clip = TextClip("text", font ="Arial-Bold", fontsize=50, color ="black").duration(3)

clip.write_videofile('final/yes.mp4', fps=30)
``` 

#### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.01
  - Platform Name: MacOS Mojave
  - Platform Version: 10.14.6

**Comment by zilton7** [comment]
`from moviepy.editor import *

clip = TextClip("text", font ="Arial-Bold", fontsize=50, color ="black").duration(3)


clip.write_videofile('final/yes.mp4', fps=30)`

**Comment by zilton7** [comment]
from moviepy.editor import *

clip = TextClip("text", font ="Arial-Bold", fontsize=50, color ="black").duration(3)


clip.write_videofile('final/yes.mp4', fps=30)

**Comment by eswar159** [comment]
sorry for posting here I'm facing an issue the video is being zoomed it at the output 
please, someone, help me
https://github.com/Zulko/moviepy/issues/1309
thank you

**Comment by keikoro** [comment]
@eswar159 Is your linked ticket in any way related to this one? Else I'd ask you to remove the comment (linking unrelated tickets will just continue to confuse everyone).

**Comment by ToxicOverload** [comment]
@zilton7 I think the function you're looking for is `set_duration()` instead of `duration()`.

[https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.TextClip.set_duration](url)

**Comment by tburrows13** [comment]
Agreed. Use `.set_duration()` (or in future v2.0 versions `.with_duration()`).

[The deleted comments were not relevant/off-topic]
