### ISSUE TITLE
videofile fps_source

### ISSUE THREAD

**Issue by leemengxing** [Zulko/moviepy#1315]
hi, when the tbr and fps of the video are inconsistent, set fps=fps_source, some video will cause the video to jam.
when fps=30, tbr=16k, set fps=fps_source ,it work great! but I find some video will be bad when fps=15, tbr=30. In the case ,video will jam a lot.

#### Specifications

  - Python Version: 2.7.12
  - Moviepy Version: 1.0
  - Platform Name: linux
  - Platform Version: centos7

**Comment by tburrows13** [comment]
In #1222 fps_source=fps is now the default. If you are running into issues then the fault is really with the input file. You can use fps_source=tbr or set the clip's fps manually if you need to.
