### ISSUE TITLE
TextClip Stroke is applied inside the characters 

### ISSUE THREAD

**Issue by robin-garnham** [Zulko/moviepy#1318]
Hey there,

Love the project, thanks all contributors.

The stroke property on TextClip seem to apply inside the characters, is there any way to change this to be on the outside? I have been trying to use the stroke as a mask (I select the stroke colour to the same as my background, so when it intersects with other elements they look nicer)

`mp.TextClip(string_one,
            color = font_color,
            font = font_family,
            stroke_color = stroke_color,
            stroke_width = stroke_width,
            kerning = kerning,
            align = 'center',
            size = text_size
        ).set_duration(duration).set_position(lambda t: ('center', top_position))`

Target:
<img width="609" alt="Screen Shot 2020-09-17 at 9 51 11 pm" src="https://user-images.githubusercontent.com/6599493/93469692-ff496280-f92f-11ea-81d7-a9136831f01e.png">

Without stroke:
<img width="625" alt="Screen Shot 2020-09-17 at 9 51 16 pm" src="https://user-images.githubusercontent.com/6599493/93469679-f9538180-f92f-11ea-9092-9b2e16b282c0.png">

With stroke of 10 (top line only):
<img width="538" alt="Screen Shot 2020-09-17 at 9 52 58 pm" src="https://user-images.githubusercontent.com/6599493/93469825-2a33b680-f930-11ea-9a01-30d324b4aef3.png">

**Comment by SDwarfs** [comment]
It seems the default color for the stroke is not set to the fill color. You need to set parameter 'stroke_color' to 'white' in your case (or whatever the color of your text is). This solved the issue for me.

**Comment by keikoro** [comment]
@robin-garnham Does the above comment solve your issue?

**Comment by litlol** [comment]
Hey, so is there a way to stroke on the outside of TextClip? default strokes inside

**Comment by rbailis99** [comment]
Hi, has anyone found a solution to this so that the outline can be applied to the outside of the text?

**Comment by keikoro** [comment]
Closing this issue as it hasn't seen any response from OP (to a solution suggested up-thread) in a couple of years.

**Comment by rbailis99** [comment]
Why was this marked as completed? We still need help getting the outline to be on the OUTSIDE of the text. It currently only shows on the inside.

**Comment by keikoro** [comment]
I don't understand what's not to understand about my previous comment.

**Comment by keikoro** [comment]
@rbailis99 I don't understand what's not to understand about my previous comment.

**Comment by rbailis99** [comment]
Thanks for responding. Who is OP? Does he/she know the answer to this issue? 

I’ve still not been able to figure it out unfortunately.

**Comment by keikoro** [comment]
OP = original poster, in this case: the person who opened the issue.

New comments on old issues aren't necessarily helpful, especially when solutions were suggested but the initial issuer does not respond anymore. Often it's impossible to know for sure if later reports are really about the _identical_ issue, also because parts of the code base change intermittently.  – In this case, we don't have any info on which version of moviepy the original poster used (and if it's the same that other commenters used).

**Comment by keikoro** [comment]
In a case like this, seeing as the issue was closed for the given reason, it would make more sense to create a new issue (following our issue template, in which we ask for e.g. platform, moviepy version,...) with own code samples + add a link to this older issue for reference.

**Comment by KateHutch** [comment]
Just putting this here for posterity (feel free to ignore). This is a fix to OP's original issue regarding MoviePy stroke being applied inside the characters.

- As we know, MoviePy uses ImageMagick to render text elements.
- According to the [ImageMagick docs ](https://legacy.imagemagick.org/Usage/draw/#stroke) the strokewidth property **_expands the stroke both inside and outward_**. 
- Therefore if you want to avoid the stroke line expanding _inside_ the text (as per OP's original issue) you must draw the same text twice - once with a stroke, and then without the stroke.
- Overlaying the two TextClips will then create the result you want.

**Comment by keikoro** [comment]
Thanks for sharing, @KateHutch!

**Comment by MASSKAgithub** [comment]
Code exampleeee pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by bastientaillandier** [comment]
> Code exampleeee pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

I think it is not really hard but here it is :) 
Can be upgrade of course

```
from moviepy.editor import (
    TextClip,
    CompositeVideoClip,
    concatenate_videoclips,
)

txt_titre_clip_stroke = TextClip(
    "Title",
    fontsize=96,
    font="Helvetica-Bold",
    color="#32DE23",
    stroke_color="#000000",
    stroke_width=20,
    method="caption",
)
txt_titre_clip_stroke = txt_titre_clip_stroke.set_duration(clip_duration)

txt_titre_clip = TextClip(
   "Title",
    fontsize=96,
    font="Helvetica-Bold",
    color="#32DE23",
    method="caption",
)
txt_titre_clip = txt_titre_clip.set_duration(clip_duration)

clip_base = CompositeVideoClip(
    [
        txt_titre_clip_stroke.set_position((157, 232)),
        txt_titre_clip.set_position((157, 232)),
    ],
)

final_clip.write_videofile("videoname.mp4", fps=24)

```
