### ISSUE TITLE
get_frame(index>0) has unexpected results(when using ffmpeg_reader)

### ISSUE THREAD

**Issue by ikanreed** [Zulko/moviepy#1320]
OS is Windows 10, with 

```
from moviepy.editor import *
video=VideoFileClip('filename.mp4')
```

#### Expected Behavior
video.get_frame(10) yields an array of pixel data from frame 10 of filename

#### Actual Behavior
OSError: MoviePy error: failed to read the first frame of video file filename.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

#### Notes

I've reviewed the code in ffmpeg_reader.py enough to verify that it is the source of the unexpected behavior, specifically that line 180:
`self.initialize(t)`
should probably be 
`self.initialize(pos),`
as t is in frames, and pos is in the -ss expected format of seconds

This seems to work, _possibly_, when I mangle my local files.

#### Specifications

  - Python Version: 3.8.3
  - Moviepy Version: 1.0.3
  - Platform Name: Windows 10
  - Other: ffmpeg version 4.3.1-2020-09-21-full_build-www.gyan.dev

**Comment by tburrows13** [comment]
Thanks for the report. I've changed that bit of code quite a bit in 2.0, so could you please try it in v2.0.0.dev1? (Use `--pre` to allow pip to find prerelease versions).

**Comment by ikanreed** [comment]
Still, there, but I think I've realized my own mistake.

get_frame(t) is not a frame index, but a time index, and I've been misusing your library.  You can close this ticket.
