### ISSUE TITLE
Error when writing video file out

### ISSUE THREAD

**Issue by LvInSaNevL** [Zulko/moviepy#1321]
#### Expected Behavior
Using `write_videofile("data/output.mp4", fps='30')` should produce a video file at `data/output.mp4`

#### Actual Behavior
Moviepy throws an error `TypeError: must be real number, not str` from the file `ffmpeg_writer.py` and exits the program. 

#### Steps to Reproduce the Problem
Below I have included the section of code that is responsible for actually generating and saving the video file to the disk
```py
clipData = []
for path in clipPaths:
     newClip = VideoFileClip(path)
    normalClip = audio_normalize(VideoFileClip(path))
    clipData.append(newClip)
finalVideo = concatenate_videoclips(clipData, method='compose')
finalVideo.write_videofile("data/output.mp4", fps='30')
```
* `clipPaths` is a list of paths to the clips that I am using to make the video.

I have also included the full stack trace that I get when I run the code
```
Moviepy - Building video data/output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
MoviePy - Done.                                                                                                                                                                               
Moviepy - Writing video data/output.mp4

Traceback (most recent call last):
  File "src/videoEditor.py", line 60, in <module>
    globals()[sys.argv[1]]()
  File "src/videoEditor.py", line 51, in GenerateVideo
    finalVideo.write_videofile("data/output.mp4", fps='30')
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
    with FFMPEG_VideoWriter(filename, clip.size, fps, codec = codec,
  File "/home/mwollam/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 88, in __init__
    '-r', '%.02f' % fps,
TypeError: must be real number, not str
```

#### Specifications

  - Python Version: Python 3.8.2
  - Moviepy Version: moviepy 1.0.3     
  - Platform Name: Ubuntu 20.04.1 LTS

**Comment by dleitee** [comment]
@LvInSaNevL have you tried using a real number instead of a string here?

`finalVideo.write_videofile("data/output.mp4", fps=30)`

**Comment by LvInSaNevL** [comment]
@dleitee oh my goodness that was definitely the answer! Thank you so much I was banging my head against the wall haha!

**Comment by tburrows13** [comment]
> write_videofile("data/output.mp4", fps='30')

Did you get that from documentation somewhere that needs changing?

**Comment by dleitee** [comment]
@tburrows13 I took a quick look into the whole code and didn't find any mention of fps as string.

**Comment by LvInSaNevL** [comment]
@tburrows13 I double checked with some googling and also could not find any reference to FPS as a string, I am not 100% sure where I got that from...

**Comment by tburrows13** [comment]
Ok thanks for the feedback. The only thing that I can think of is that I think the `bitrate` parameter is a string (that allows things like `'50k'`). That might be changed in the future though, it is fairly confusing.

**Comment by SattyAG** [comment]
Hi,
In my code, I am facing the same error but it's after the first two lines in output section:
```
Moviepy - Building video data/output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
```
I have set fps as `fps=clip.fps` where clip contains the original video file.

**Comment by SattyAG** [comment]
> Hi,
> In my code, I am facing the error `TypeError: must be real number, not NoneType` and it's after the first two lines in output section:
> 
> ```
> Moviepy - Building video data/output.mp4.
> MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp3
> ```
> 
> I have set fps as `fps=clip.fps` where clip contains the original video file.

It worked after upgrading moviepy.

Thank you.

**Comment by smidm** [comment]
This was a bug, that was fixed in https://github.com/Zulko/moviepy/pull/1565. You should not set fps as a string. You can upgrade to a prerelease https://github.com/Zulko/moviepy/releases/tag/v2.0.0.dev2 or add explicit argument for fps, e.g. `fps=clip.fps`.

**Comment by esdream** [comment]
> This happens when `moviepy` and `decorator` modules are not compatible (e.g. after the `decorator` module was upgraded to the last version).
> 
> This should solve the issue:
> 
> ```
> pip uninstall moviepy decorator
> pip install moviepy
> ```

That's right. You can also upgrade your moviepy module and uninstall decorator autometically:
```
pip install moviepy --upgrade
```

**Comment by kalyani-Dhavale** [comment]
I am facing exactly same problem. I tried all the ways mentioned above but nothing worked for me. I think the problem is that in the function [`FFMPEG_VideoWriter.__init__()`]  there is no else part as if `audiofile` is none. 
**actual code is:**
`if audiofile is not None:
          cmd.extend([
             '-i', audiofile,
             '-acodec', 'copy'
          ])`

**Comment by zhangwengyu999** [comment]
> 

In my case, I need to do ***both*** `pip uninstall moviepy decorator` and `pip install moviepy` to solve the problem. 
It did not work by using `pip install moviepy --upgrade` only.

**Comment by soumyadbanik** [comment]
> pip install moviepy

@smidm and @dleitee Thanks a lot
