### ISSUE TITLE
Hacktoberfest topic?

### ISSUE THREAD

**Issue by keikoro** [Zulko/moviepy#1324]
Should we temporarily put the Hacktoberfest topic on the repository? Digital Ocean/Hacktoberfest [changed their system](https://hacktoberfest.digitalocean.com/hacktoberfest-update) because people kept spamming OS repos with ridiculous PRs.

Now repositories have to opt in, which means the no. of projects people can contribute to dropped significantly. I guess no-one knows yet if this will discourage people trying to cheat the system (though well, they can go and create their own repos...) but it might also attract more people taking the idea seriously.

What do you think, @Zulko @tburrows13?

**Comment by keikoro** [comment]
Btw., I think only @Zulko can add/edit topics.

**Comment by Zulko** [comment]
I think that's a good idea, but as usual I have very little time to review PRs on MoviePy so I'd leave the decision to @tburrows13 . Happy to add `hacktoberfest` as a topic if you guys can't, just let me know.

**Comment by tburrows13** [comment]
Yes I'd support adding it. Thanks!

**Comment by Zulko** [comment]
Ok, topic added :+1:
