### ISSUE TITLE
How to automatically resize anamorphic widescreen compressed videos?

### ISSUE THREAD

**Issue by davidwdw** [Zulko/moviepy#1330]
This is a similar issue to [#48](https://github.com/Zulko/moviepy/issues/48), could you let me know how to read an anamorphic widescreen compressed video, where the SAR and DAR are different. Or is there an option to read the anamorphic widescreen flag in the metadata? Thanks!

Edit: 

I'm attaching the video metadata here:

`Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf52.103.0
  Duration: 00:06:44.17, start: 0.000000, bitrate: 2157 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 720x480 [SAR 32:27 DAR 16:9], 1986 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 164 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler`

**Comment by tburrows13** [comment]
I don't really know much about that, but if you're willing to dig into the code and create a PR for it, all the ffmpeg metadata parsing is done in `ffmpeg_parse_infos`. You could add an optional argument to that, `FFMPEG_VideoReader` and `VideoFileClip` to do what you want.

**Comment by davidwdw** [comment]
Thanks @tburrows13 for for the quick reply! I could do that but I don't think it will have much value for others because the data that I'm working with are dvd videos and it's rare to see such data nowadays. I managed to figure out how to convert them into proper widescreen videos using a third party software. Thanks!
