### ISSUE TITLE
OSError: MoviePy error: the file test.mp4 could not be found!

### ISSUE THREAD

**Issue by KeithLenders** [Zulko/moviepy#1336]
Hi

I am trying to convert an mp4 audio track into an mp3 file, i can download the mp4 file no problem and its visible in the folder, but when it comes to moviepy importing the mp4 i am geting this error.

"OSError: MoviePy error: the file test.mp4 could not be found!
Please check that you entered the correct path."

even tho i can see the mp4 in the current folder. here is the code i am using.

```
    name = yt.title
    videoclip = VideoFileClip(name+'.mp4')
    audioclip = videoclip.audio
    audioclip.write_audiofile(name+'.mp3')

    audioclip.close()
    videoclip.close()
```
the error also links to VideoFileClip.py and ffmpeg_reader.py files. i am stuck with this, any help would be appreciated. thank you

**Comment by Technerder** [comment]
Are you using youtube-dl to download the video file?

**Comment by keikoro** [comment]
@KeithLenders Could you please include the full stack trace of the error? Also, are you running the script from the same folder that contains the video file? (Not the same as your code _sitting_ in the same folder.)

**Comment by KeithLenders** [comment]
@Technerder i am using pytube to download the youtube video.  The strange thing is it will work most of the time, there are just a few videos that it will give this error for.

@keikoro Yes i have the python file in the same folder that the youtube video is downloaded to. As mentioned it will work for most videos, just some it will give this error.

```
Traceback (most recent call last):
  File "D:\Desktop\script.py", line 27, in <module>
    vid_dl()
  File "D:\Desktop\script.py", line 23, in vid_dl
    mp4_mp3(yt.title)
  File "D:\Desktop\script.py", line 6, in mp4_mp3
    videoclip = VideoFileClip(name+'.mp4')
  File "<decorator-gen-88>", line 2, in __init__
  File "D:\Users\0\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\Users\0\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 109, in __init__
    fps_source=fps_source,
  File "D:\Users\0\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 36, in __init__
    filename, decode_file, print_infos, check_duration, fps_source
  File "D:\Users\0\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 327, in ffmpeg_parse_infos
    % filename
OSError: MoviePy error: the file title.mp4 could not be found!
Please check that you entered the correct path.
```

**Comment by tburrows13** [comment]
I wonder if this is because Windows is hiding the actual file extension so whilst it appears to be called `title.mp4` it is actually called `title.mp4.mp4` or something similar. Or perhaps they are not actually `.mp4`s at all?

**Comment by keikoro** [comment]
Yeah, @KeithLenders have you had your script print out the name/full path of the file(s) prior to trying to handle them with moviepy, or could you otherwise do that to make sure they are correct?

I'm also always somewhat naturally suspicious of names that sound like they could be variables/attributes/key names/default values (`title`, `test` and even `script`, in your case).

**Comment by KeithLenders** [comment]
i can print out the file name ok and it displays it as normal.  Im wondering now if it may be somting to do with the title of the youtube video. notice it has a full stop after "feat."  maybe this is interfering with the naming structure / file extension.

Prodigy - Self Conscience (feat. Nas)
https://www.youtube.com/watch?v=A_JnNrMwxtI

**Comment by keikoro** [comment]
> i used title.mp4 in the first post just as an example by the way.

Ok, if you are giving us placeholder names, the advice we have given so far might not actually be applicable.

With the example you provided now, it's unclear to me what "title" even refers to. Is it the file name? The Youtube title of the video? Are you using them interchangeably? Does the name of the file you downloaded contain spaces?

**Comment by tburrows13** [comment]
I've checked, and yes the answer is that PyTube does not keep the full stop in the YouTube video name when saving as a local file. You can't use `yt.title + '.mp4'` and expect it to work.

I've not dug very deep into this, but it seems that doing `dl_file = YouTube('youtu.be/A_JnNrMwxtI').streams.first().download()` and then `VideoFileClip(dl_file.title())` does work.

**Comment by KeithLenders** [comment]
@keikoro sorry for the confusion, i only realised the youtube song name may be the problem after i posted the question. title would be what is taken from yt.title from above with .mp4 appended 

@tburrows13 ok, so the full stop will cause a problem with moviepy? pytube seems to be downloading the file without a problem, i think its when the mp4 file is passed to moviepy that it gives the error. it doesnt seem to be a major error and has only happend with this one song so far.

**Comment by tburrows13** [comment]
My understanding is that the full stop does not cause a problem with moviepy, it is Pytube that does not keep the full stop in the file name after download, so when you pass the file name with the full stop to moviepy it fails _because the file doesn't exist with that name_.

Feel free to reopen if this is not the case for you.

**Comment by stardustman** [comment]
if I pass the file path use a variabl，but the file path contains white space，it will report file doesn't exist. but when I copy the string path as parameter, there is no error,why?
