### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1338]
When running the test suite it reveals some deprecations:

      /home/runner/work/moviepy/moviepy/moviepy/audio/AudioClip.py:121: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

      /home/runner/work/moviepy/moviepy/moviepy/video/io/gif_writers.py:323: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.

Source: https://github.com/Zulko/moviepy/runs/1227641497 (under PyTest)
I think that the first one is NumPy and the second is Pillow (PIL).

It would be good to investigate and fix these 2 warnings.

**Comment by vincenzoml** [comment]
I do have an "arrays to stack must be passed as 'sequence' type" error which I did not have before, with moviepy 1.0.3, when muxing audio and video (saving the video); isn't this merged? Now it's no longer a warning and the code fails.

**Comment by hman009** [comment]
facing this issue while converting while running the to_soundarray() method 
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

**Comment by vinitnalhe** [comment]
I was also facing the same issue, when using python3.11. 

I tried using the earlier version of python ( python 3.8) and  to_soundarray() ran successfully.

**Comment by agamm** [comment]
> `pip install git+https://github.com/Zulko/moviepy.git@bc8d1a831d2d1f61abfdf1779e8df95d523947a5`

Why is this not added to a release yet?

**Comment by SohamTilekar** [comment]
> > `pip install git+https://github.com/Zulko/moviepy.git@bc8d1a831d2d1f61abfdf1779e8df95d523947a5`
> 
> Why is this not added to a release yet?

Because The Zulko is Not Active and #2085.

**Comment by keikoro** [comment]
The above discussion is not relevant, we are not actively using discussions. See issue #1874 instead.

**Comment by shllgtca** [comment]
by using this source of moviepy I get not only error on moviepy/video/io/ffmpeg_reader.py and have to add on l.259 infos = error.decode('utf8')

but also I get error when trying to set_fps to an moviepy.audio.io.AudioFileClip.AudioFileClip object , bith errors which works in the newest version.

I still don't know how to solve the set_fps error. If anyone can help, tks in advance.

:/

> For anyone stumbling on this like I did:
> 
> Installing moviepy from source ( `2.0.0.dev0` ) fixed this issue for me:
> 
> ```
> pip install git+https://github.com/Zulko/moviepy.git@bc8d1a831d2d1f61abfdf1779e8df95d523947a5
> ```
> 
> ### More info
> The PR attached to this issue solved the problem: #1443
> 
> Sample code that is working now, but didn't work with `moviepy==1.0.3`:
> 
> ```
> load_path = "path/to/my/video.mp4"
> video = VideoFileClip(load_path)
> audio_data = video.audio.to_soundarray(fps=16000)
> ```
