### ISSUE TITLE
different images created with imperceivable difference when comparing frame created in Gitlab-Runner(Linux) and frame created locally using Mac OS

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1343]
#### Expected Behavior
For moviepy to create identical video regardless of whether run locally on Mac or in Gitlab-Runner (Linux) or using Docker.

#### Actual Behavior
When I 
1. create a gif video with a slide in of a colorClip on a coloured background (the video only has two colours) inside Docker set up for Gitlab-Runner (linux),
and 
2. I create the gif video using exact same code locally on my mac
3. and extract the frame from each of these gif videos that has a hash difference
4. I extract them as PNGs because it is lossless, and then I compare the PNGs

I see that there are values that are not zero and in most cases up to 255, which should be zero when subtracted from each other if they were identical.

The difference is not visually perceivable, however it is different enough to create a completely new SHA256 hash.
Maybe there is a difference between the build in Linux and the build on Mac that creates a very slightly different video?
The difference artefacts can be seen in the top right and bottom right of the sliding color rectangle, like a little checkerboard pattern of

255, 0, 255,
0, 255, 0
255, 0, 255

In the two colours of the video.

Wondering if anyone had experienced this, and if they have a fix or workaround for it?  Or indeed any experiment suggestions, to determine what could be the cause of the problem?

I have been experimenting with difference and perceptual hashing, which seems to be a solution for this particular slide in unit-test.  However, Moviepy has lots of other effects.

#### Steps to Reproduce the Problem
create code that creates a background colour, and a colour clip rectangle in the video, apply slide in, extract gif video.  Push that code that creates the gif video to gitlab.  Locally, extract frames from video.

ssh in to gitlab-runner and run the same code to generate the gif video, copy the gif file to your local using sftp, then you can use the extract frames code.  Compare the local gif frames to the gitlab gif frames to see the differences.

Create some code to create the hash for the frame.  Compare the hashes, to see if they are the same.

#### Specifications
  - Python Version: 3.7.4
  - Moviepy Version: 1.0.0
  - Platform Name: Mac OS Mojave
  - Platform Version: 10.14.6

**Comment by keikoro** [comment]
Do you create the Docker image yourself based on the Dockerfile in the repo, or do you use the one we provide on Dockerhub? Because the latter might be a bit behind the repo.

**Comment by tburrows13** [comment]
Yes I'd say first check that the moviepy code is actually the same. The both the docker file in the repo and my one on docker hub (https://hub.docker.com/repository/docker/tburrows13/moviepy) will I think be pulling from `master`, which is unreleased content (this should be changed in the future, see #1341).

If the moviepy code is the same then the difference is probably in external libraries, particularly FFmpeg. If it isn't installed then moviepy will download a specific version (via https://github.com/imageio/imageio-ffmpeg), but perhaps you have a different version installed on each platform, or it creates different files on each platform.

Or in your case, you are writing gifs, which uses either Imageio, ImageMagick or ffmpeg. Experiment with different `program` values in `write_gif()`.

**Comment by OneWorld-github** [comment]
> Do you create the Docker image yourself based on the Dockerfile in the repo, or do you use the one we provide on Dockerhub? Because the latter might be a bit behind the repo.

I create the Dockerfile myself, but not based on the Dockerfile in the repo.  Hmm I don't think Dockerfile is the issue.  The gif created in Gitlab-Runner is different from the gif created locally.  I copied the gif from gitlab-runner directly to eliminate Docker being the source of the issue.

**Comment by OneWorld-github** [comment]
> Yes I'd say first check that the moviepy code is actually the same. The both the docker file in the repo and my one on docker hub (https://hub.docker.com/repository/docker/tburrows13/moviepy) will I think be pulling from `master`, which is unreleased content (this should be changed in the future, see #1341).
> 
> If the moviepy code is the same then the difference is probably in external libraries, particularly FFmpeg. If it isn't installed then moviepy will download a specific version (via https://github.com/imageio/imageio-ffmpeg), but perhaps you have a different version installed on each platform, or it creates different files on each platform.
> 
> Or in your case, you are writing gifs, which uses either Imageio, ImageMagick or ffmpeg. Experiment with different `program` values in `write_gif()`.

moviepy is version 1.0.0 locally and on gitlab.  I don't use the moviepy repo docker file.

How would you recommend testing if FFMPEG causes the creation of a very slightly different gif ?

**Comment by tburrows13** [comment]
First of all I'd check that they are using the same version of ffmpeg (for reading) and Imageio(which is the default library for writing gifs). Other then that I'm not so sure.

**Comment by OneWorld-github** [comment]
> First of all I'd check that they are using the same version of ffmpeg (for reading) and Imageio(which is the default library for writing gifs). Other than that I'm not so sure.

Tom, you are right !

Gitlab-Runner Build 4423447d
Moviepy            1.0.2
imageio             2.4.1

Locally
Moviepy            1.0.0
imageio             2.5.0
Imageio-fmpeg 0.3.0
