### ISSUE TITLE
new pip version

### ISSUE THREAD

**Issue by keikoro** [Zulko/moviepy#1344]
While experimenting with Docker setups, I just came across this `stdout` warning:

> After October 2020 you may experience errors when installing or updating packages.
This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

There's more info in this blog post [on the pip 20.2 release](https://discuss.python.org/t/announcement-pip-20-2-release/4863).

I haven't looked at this in detail yet, but thought I'd post this as a heads-up.

**Comment by keikoro** [comment]
Addendum: it looks like something in the `test` installs triggered the message.

**Comment by mondeja** [comment]
This is a warning from PIP, I've seeing a lot of times installing packages, nothing that we should do here.
