### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by raj6996** [Zulko/moviepy#1347]
#### Expected Behavior
```
Moviepy - Done !
Moviepy - video ready D:\0.Github\English\supercut.mp4
Exception ignored in: <function FFMPEG_VideoReader.__del__ at 0x000002318A9A6700>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 199, in __del__
    self.close()
  File "C:\Python38\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 190, in close
    self.proc.terminate()
  File "C:\Python38\lib\subprocess.py", line 1442, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x000002318A9A6CA0>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "C:\Python38\lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Python38\lib\subprocess.py", line 1442, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid

Administrator@WIN-R2BWEDEWS MINGW64 /c/Python38/Lib/site-packages/videogrep
$
```

#### Actual Behavior
This is not right place to discuss, but I checked code somehow related to moviepy,
I used videogrep in Windows with Github bash.
#### Specifications

  - Python Version: 3.8
  - Moviepy Version: Installed with Videogrep (not installed myself)
  - Platform Name: Windows 10 pro
  - Platform Version: [Version 10.0.19041.421]

**Comment by tburrows13** [comment]
This has been fixed in various versions of moviepy (I forget off the top of my head, but it should be gone by 1.0.3). Videogrep appears to be using 0.2.3.2 which is very outdated. You just need to update moviepy.

**Comment by raj6996** [comment]
`
C:\Users\Administrator>pip install moviepy
Requirement already satisfied: moviepy in c:\python38\lib\site-packages (1.0.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\python38\lib\site-packages (from moviepy) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in c:\python38\lib\site-packages (from moviepy) (4.50.0)
Requirement already satisfied: requests<3.0,>=2.8.1 in c:\python38\lib\site-packages (from moviepy) (2.24.0)
Requirement already satisfied: proglog<=1.0.0 in c:\python38\lib\site-packages (from moviepy) (0.1.9)
Requirement already satisfied: numpy>=1.17.3 in c:\python38\lib\site-packages (from moviepy) (1.19.2)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\python38\lib\site-packages (from moviepy) (2.9.0)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in c:\python38\lib\site-packages (from moviepy) (0.4.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (1.25.10)
Requirement already satisfied: pillow in c:\python38\lib\site-packages (from imageio<3.0,>=2.5->moviepy) (7.2.0)

C:\Users\Administrator>`

**Comment by BabyCY** [comment]
I updated to version 1.0.3, but this problem still exists

**Comment by BabyCY** [comment]
> This has been fixed in various versions of moviepy (I forget off the top of my head, but it should be gone by 1.0.3). Videogrep appears to be using 0.2.3.2 which is very outdated. You just need to update moviepy.

I updated to version 1.0.3, but this problem still exists
