### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1355]
The test coverage is currently at 67%. It would be good to be able to automatically test more things in the test suite. You can see which files are covered at https://coveralls.io/github/Zulko/moviepy (or PyCharm has a test coverage plugin that can be enabled).

In particular:

- some effects in moviepy/video/fx are not tested at all in their respective test function in test_fx.py.
- video/compositing/transitions.py
- audio/fx/audio_fadein and audio_fadeout

For the video tests it is better to use BitmapClip because it allows you to test pixel-perfect effects. But generally just testing that an action can be performed without crashing is better than nothing.

**Comment by mondeja** [comment]
# FX tests TODO

- [ ] `accel_decel`
- [x] `blackwhite`
- [ ] `blink`
- [x] `multiply_color`
- [x] `crop`
- [x] `even_size`
- [ ] `fadein` (more `duration` arguments)
- [ ] `fadeout` (rewrite using BitmapClip`)
- [x] `freeze`
- [ ] `freeze_region` (`mask` argument)
- [ ] `gamma_corr`
- [ ] `headblur`
- [x] `invert_colors`
- [ ] `loop` (use BitmapClip testing all behaviours)
- [ ] `lum_contrast` (rewrite using BitmapClip`)
- [ ] `make_loopable`
- [ ] `margin` (test `left`, `right`, `top`, `bottom` and `opacity` arguments)
- [ ] `mask_and`
- [ ] `mask_color`
- [ ] `mask_or`
- [x] `mirror_x`
- [x] `mirror_y`
- [ ] `painting`
- [ ] `resize` (rewrite using BitmapClip)
- [ ] `rotate` (other arguments beyond `angle`)
- [ ] `scroll`
- [x] `speedx`
- [ ] `supersample`
- [x] `time_mirror`
- [x] `time_symmetrize`
- [x] `audio_normalize`
- [ ] `multiply_volume`
- [x] `multiply_stereo_volume`

**Comment by tburrows13** [comment]
It would be quite hard to write BitmapClip tests for all of the effects, I think. Although you did manage with `blackwhite` in #1430 I wouldn't say it is worth it for some of the more 'color-gradienty' ones (such as `headblur` and `painting`).

**Comment by mondeja** [comment]
> It would be quite hard to write BitmapClip tests for all of the effects...

I have found it much easier to use ColorClip in tests for `mask_or` and` mask_and`.

**Comment by mondeja** [comment]
`audio_loop` must be removed in favour of `loop` @tburrows13?

**Comment by tburrows13** [comment]
Closing as these checklists are very out-of-date now that 2.0 is out. Test coverage is now at 86% 💪 (possibly due to obsolete code being removed as much as tests being added... but hey!)
