### ISSUE TITLE
Mistake in doc,  clips.html part.

### ISSUE THREAD

**Issue by dingyaguang117** [Zulko/moviepy#136]
It shoud be `TextClip.list('font')`, not `TextClip.list('fonts')`,and so is `TextClip.search('Amiri', 'font')` below.

**Comment by keikoro** [comment]
Does the problem persist and if so, would you send a PR to fix it (based on the most recent docs)?

**Comment by tburrows13** [comment]
Fixed in 6403c099e4f3a5c81dc188ccb5419ffcbfd0336e.
