### ISSUE TITLE
Loop effect needs fixing

### ISSUE THREAD

**Issue by tburrows13** [Zulko/moviepy#1368]
You can see in [`test_loop()`](https://github.com/Zulko/moviepy/blob/master/tests/test_fx.py#L189) that `loop` is not quite working as some tests are skipped or else they would cause the tests to fail. To close this issue you need to do the following

- [ ] Try running the tests that are currently broken
- [ ] Fix `loop` so that the tests can run (or convince me that the tests are wrong :) )
- [ ] Add some new tests using `BitmapClip` (in the vein of [`test_freeze()`](https://github.com/Zulko/moviepy/blob/master/tests/test_fx.py#L129) to test for frame-perfect looping

Feel free to comment here or on GitHub if you need some help.
This is a specific case of #1355.

**Comment by ParikhNand** [comment]
@tburrows13
Could you please assign this issue to me?

**Comment by somstrom** [comment]
@tburrows13 

Hey. I added some tests for loop using BitmapClip and they passed.

**Comment by RealA10N** [comment]
#1372 May be related & helpful :D

**Comment by julienbeisel** [comment]
Hi @tburrows13, 

I'm using Moviepy a lot and I'd like to contribute.

Maybe I'm wrong but I think the loop effect is still not working properly:

https://github.com/Zulko/moviepy/blob/6ab3efba36cf7fc5d3245f0ee0dc9244cb141c9e/moviepy/video/fx/loop.py#L7-L27

If n is set to a value but duration is set to None, the clip won't be updated. That might be one of the reasons the tests are broken.

Can I try to fix it or somebody else is already working on it ?

**Comment by tburrows13** [comment]
Hi @julienbeisel, I can't replicate that problem with the latest version in master (after #1373 is applied). Is it still an issue for you?
