### ISSUE TITLE
Crossfade effects seem deprecated

### ISSUE THREAD

**Issue by LuluDavid** [Zulko/moviepy#1369]
#### Expected Behavior
In the most recent version of moviepy (git clone + pip3 install .), the following code should produce a composition of two videos with a crossfadein/crossfadeout effect for both clips
```
from moviepy.editor import *
from moviepy.video.compositing.transitions import crossfadein, crossfadeout
clip1 = VideoFileClip(file1)
clip2 = VideoFileClip(file2).with_start(clip1.end - crossfade_duration)

clip1 = clip1.fx(crossfadein, crossfade_duration).fx(crossfadeout, crossfade_duration)
clip2 = clip2.fx(crossfadein, crossfade_duration).fx(crossfadeout, crossfade_duration)

final_clip = CompositeVideoClip([clip1, clip2])
final_clip.write_videofile(output_file,
                           threads=2,
                           fps=24,
                           codec='libx264',
                           audio_codec='aac',
                           temp_audiofile='temp-audio.m4a',
                           remove_temp=True)
```
#### Actual Behavior
It seems the code does not apply crossfade in the output. I do not know if it comes from a detail (the encoding for example), but I tried several formulations, and could not make it work.  

So I came back to the old version with pip3 install moviepy, and it eventually worked with the code above.
Maybe I am missing a point, or maybe the transition features became obsolete since last addings to pip3.
#### Specifications

  - Python Version: 3.8
  - Moviepy Version: pip3 latest version

**Comment by speaknowpotato** [comment]
pip3 install v1.0.3 works, but the source code in the master branch doesn't work.
