### ISSUE TITLE
[Feature Request] Write output using newlines

### ISSUE THREAD

**Issue by Netherdrake** [Zulko/moviepy#137]
I would be very happy for a feature like `--newline` in `youtube-dl`:
```
--newline                        output progress bar as new lines
```
https://github.com/rg3/youtube-dl/blob/master/README.md#readme

So instead of using using shell cursors to update the progress bar, just print it as newline.

It may sound as a silly thing to do, but I use moviepy to do some video encoding on server, and then I stream output of encoder service to end user's html5 client via websockets.
Doing newlines would make it very easy for me to parse output and show progress-bar in near-real-time.

If you have any ideas how to do this without changing moviepy, please let me know.

**Comment by mgaitan** [comment]
Hey @Netherdrake . to make the progress-bar more "hookable" is being discussed in #128 . please, check the ideas exposed there and give your opinion.

**Comment by Netherdrake** [comment]
I have solved the problem by parsing the output by `\r` rather than `\n`.
