### ISSUE TITLE
VideoFileClip constructor freezes with a video with a transparent layer

### ISSUE THREAD

**Issue by RealA10N** [Zulko/moviepy#1371]
#### Actual Behavior
While creating an instance of `VideoFileClip` for a file with a transparent layer (I've tried `.avi` and `.mov`),
the program freezes.

I tried working with the files in FFMPEG and there was no problem. After further investigation, I found that the program freezes exactly [here](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L148).

#### Steps to Reproduce the Problem
```python
from moviepy.editor import *

path = ""  # path to a video with a transparent layer
video = VideoFileClip(path, is_mask=True)  # Tested without the `is_mask` flag too, and it didn't work either.
```

#### Specifications

  - Python Version: 3.6
  - Moviepy Version: 1.0.3
  - Platform Name: Windows 10 Home
  - Platform Version: 10.0.19042

**Comment by tburrows13** [comment]
Thanks for the report. A few things to try: install v2.0.0.dev2 and see if it works there (using pip's `--pre` flag). Do `ffmpeg -I filename.avi` and post the output here.

**Comment by RealA10N** [comment]
Fixed using v2.0.0.dev2!
Thanks a lot for the quick response.
Do you still need the avi file information?

**Comment by tburrows13** [comment]
No, if that works, then it must have been fixed at some point :)

**Comment by RealA10N** [comment]
Thank you again! Stay safe and healthy!
