### ISSUE TITLE
Linebreak in Textclip

### ISSUE THREAD

**Issue by locphan57910** [Zulko/moviepy#1376]
Can anyone suggest a way to break line in textclip?

 "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor pharetra ipsum. Aenean facilisis, augue et feugiat consequat, neque lectus efficitur leo, in consectetur nisl elit at ex. Morbi sodales dictum mauris sollicitudin bibendum. Proin ac varius leo."

Right now its putting all of it in one line.
`contentClip =  TextClip(contentText, font='Amiri-regular', color='black', fontsize=18).fx(vfx.fadein, 2)`

**Comment by tburrows13** [comment]
Add `\n` into your string.
