### ISSUE TITLE
VideoFileClip open gif frames num error

### ISSUE THREAD

**Issue by python-yang** [Zulko/moviepy#1377]
example code:
```
    from moviepy.video.io.VideoFileClip import VideoFileClip
    from moviepy.video.fx.resize import resize
    clip = VideoFileClip("123.gif")
    print(clip.reader.nframes)
    clip = clip.fx(resize, width=1000)
    clip.write_gif("99999.gif", program='ffmpeg')
```

use mac open 123.gif only 4  frames but  open 99999.gif have 22 frames.
if not use `clip.fx(resize, width=1000)  ` file size form 4.7MB to 32.9MB,
I want to get the correct number of output frames and file size.

test gif file:
![123](https://user-images.githubusercontent.com/37257003/98499498-a2f62580-2284-11eb-83a7-3afd8894f63f.gif)

**Comment by keikoro** [comment]
Closing this issue as it's missing information we ask for when creating new issues.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
