### ISSUE TITLE
write_audiofile() - RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Wilann** [Zulko/moviepy#1381]
I'm trying to crop audio (.mp3) from a video (.mp4), based on a list of frames. 
Ex. `frame_list = [26, 51, ...]`, `fps=25` and I want to crop the audio from these frames, so I crop audio from frames 1-26, 26-51, etc. 

Stats about my files and variables: 
The video is ~857.7MB
`frame_list` has 993 integer elements 
I set `skip_frames_interval` to `fps`, to process the frame at each second 

A brief explanation behind my code: 
I'm using `subclip()` to crop the audio, and when I divide `frame_num` by `fps`, I get the video's timestamp where I need to crop. For each frame I'm only cropping a second, hence, `audio_clip = audio.subclip(audio_timestamp, audio_timestamp+1)`. 

```
import sys
import time
from moviepy.editor import *

def get_crop_audio(old_vid_path, new_audio_path, frame_list, fps, total_num_frames, skip_frames_interval):
    '''
    Crops audio from an video based on timestamps 
    
    Parameters:
        old_vid_path:            Path to original video 
        new_audio_path:          Path to new audio file  
        frame_list:              List of frames to crop audio from
        fps:                     Frames per second 
        total_num_frames:        Total number of frames 
        skip_frames_interval:    Process every ______ frames 
    '''
    
    video = VideoFileClip(old_vid_path)
    audio = video.audio
    new_audio = audio.subclip(0, 0)
    
    num_crop_clips = len(frame_list)
    audio_counter = 0
    start = time.time()
    
    for frame_num in range(1, total_num_frames, fps):
        
        # If the current frame should be cropped 
        if frame_num in crop_frames:
            
            # Clip a second of audio 
            # Frame 26 --> Sec 1 | 26 // 25 = 1
            # Frame 51 --> Sec 2 | 51 // 25 = 2
            # Frame 76 --> Sec 3 | 76 // 25 = 3
            # ...
            audio_timestamp = frame_num // skip_frames_interval                  
            audio_clip = audio.subclip(audio_timestamp, audio_timestamp+1)
            new_audio = concatenate_audioclips([new_audio, audio_clip])         
            
            audio_counter += 1
            end = time.time()
            time_min = int((end-start)/60)
            time_sec = round((end-start)%60)
            sys.stdout.write('\rWriting Frame: {:.2f}% {}/{}        Time Elapsed: {} min, {} s'
                             .format(audio_counter*100/num_crop_clips, audio_counter, num_crop_clips,
                                     time_min, time_sec))
            sys.stdout.flush()
    
    new_audio.write_audiofile(new_audio_path, logger='bar')
```

#### Expected Behavior
Writing Frame: 100.00% 993/993        Time Elapsed: 0 min, 1 s
...
MoviePy - Writing audio in new_audio_path.mp3
MoviePy - Done.

#### Actual Behavior
RecursionError: maximum recursion depth exceeded while calling a Python object

<img width="1321" alt="Screen Shot 2020-11-21 at 8 40 46 AM" src="https://user-images.githubusercontent.com/40744757/99878750-78d22b00-2bd5-11eb-99b1-e60f176cd9ca.png">

#### Steps to Reproduce the Problem
To reproduce the problem, I believe any .mp4 file would be sufficient. (I tried several files) 
If not, please let me know and I'll host the specific file on Google Drive. 

#### Specifications

  - Python Version: 3.7.0
  - Moviepy Version: 1.0.3
  - Platform Name: MacOS 
  - Platform Version: 11.0.1

#### Final Words
If there's anything you need to know to help solve this issue, please let me know. 
Thank you for checking this issue out.

**Comment by tburrows13** [comment]
Your basically calling `concatenate_audioclips` on the same clip 993 times, which presumably means that it is 'recursing' 993 times. You could try raising the Python recursion limit: https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it

Better would be to save the clips that you want to keep into a list and the concatenate them all at once at the end.

**Comment by Wilann** [comment]
Thanks! This simple solution solves the problem :)
