### ISSUE TITLE
Use  GPU

### ISSUE THREAD

**Issue by guduxingzou** [Zulko/moviepy#1382]
wish  use GPU，cpu is slow！ THANKS!!!
Chinese：
期待可以使用GPU进行渲染，CPU太慢了，谢谢开发者们的辛勤工作！

**Comment by wiebecommajonas** [comment]
I would also like the ability to work with my GPU rather than CPU.

**Comment by keikoro** [comment]
Closing this as duplicate of several comments and emoji upvotes in #1089.
