### ISSUE TITLE
CompositeAudioClip Error 'NoneType' object has no attribute 'end'

### ISSUE THREAD

**Issue by bluecrunch** [Zulko/moviepy#1384]
Hi, 
I am working on software to generate video and combine it with voiceovers and a music track. This worked fine so far, but today, when doing this for different content, I receive the following error:

```
Traceback (most recent call last):
  File "vigen_1_1_3_build-c.py", line 607, in <module>
    new_audioclip = CompositeAudioClip([fin_video.audio,voiceover,music])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 286, in __init__
    ends = [c.end for c in self.clips]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 286, in <listcomp>
    ends = [c.end for c in self.clips]
AttributeError: 'NoneType' object has no attribute 'end'
```

As far as I can say I've only changed the content to generate the file. Files seem to be normal, but the error seems to indicate that there is an empty object.

The code is:

```
fin_video = concatenate_videoclips(clips, method='compose')

segments = AudioSegment.empty()
for filename in sorted(os.listdir("unsp_audio")):
    if filename.endswith('_'+project_name+'.mp3'): 
        sound = AudioSegment.from_mp3("unsp_audio/"+filename)
        segments += sound
voiceover_file = project_name+"_final"
segments.export(project_name+"_final.mp3", format="mp3")
vo_file = AudioFileClip(voiceover_file+".mp3")
voiceover = vo_file.volumex(1.75)

audioclip = AudioFileClip("teaparty.mp3").subclip(0,vo_file.duration)
music = audioclip.volumex(0.15)
new_audioclip = CompositeAudioClip([fin_video.audio,voiceover,music])
fin_video.audio = new_audioclip
```
The second last line with the variable "new_audioclip" is line 607. My moviepy version is 1.0.x, so I assume it's up to date. 
Where could be the problem be and how do you know what's missing?
Thanks in advance for your help and suggestions.

**Comment by tburrows13** [comment]
1.0.3 is the latest 'stable' version of MoviePy but 2.0.0.dev2 is available through pip with the `--pre` flag. I'd recommend you try your code there as it has a lot of bug fixes.

**Comment by bluecrunch** [comment]
> 1.0.3 is the latest 'stable' version of MoviePy but 2.0.0.dev2 is available through pip with the `--pre` flag. I'd recommend you try your code there as it has a lot of bug fixes.

Thanks, done so. Used pip install moviepy --pre --upgrade, but the output is the same. 

`Traceback (most recent call last):
  File "vigen_1_1_3_build-c.py", line 601, in <module>
    new_audioclip = CompositeAudioClip([fin_video.audio,voiceover,music])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 310, in __init__
    ends = [c.end for c in self.clips]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 310, in <listcomp>
    ends = [c.end for c in self.clips]
AttributeError: 'NoneType' object has no attribute 'end'`

So could this be a bug or a mistake I make?

**Comment by tburrows13** [comment]
I'd recommend that if you run into a crash with moviepy that you have a look at the source to see if you can see what is going on. If you provide incorrect input at any point, it won't really tell you what was wrong, it will just crash with a seemingly strange error like this.

You can see that the definition of `CompositeAudioClip` init starts like this;

```python
    def __init__(self, clips):

        Clip.__init__(self)
        self.clips = clips

        ends = [clip.end for clip in self.clips]  # Your code crashes here
```

So your problem is that one of `fin_video.audio`, `voiceover`, and `music` is `None`. Probably `fin_video.audio` is `None` because `fin_video` presumably doesn't have audio. You need to work out why :)

**Comment by bluecrunch** [comment]
It works, thanks @tburrows13.
For those who want to know how I solved it:
```
if(fin_video.audio is not None):
new_audioclip = CompositeAudioClip([fin_video.audio,voiceover,music])
else:
new_audioclip = CompositeAudioClip([voiceover,music])

```
Maybe not elegant, but it works.
