### ISSUE TITLE
VideoFileClip with mask gives out warning if has_mask=True and video file is looped. 

### ISSUE THREAD

**Issue by Heedster** [Zulko/moviepy#1390]
The warning it gives out is along the lines of

> UserWarning: In file /var/folders/t4/dkz1hgzn75ld0zn3y5943wd40000gn/T/tmpyar_2sw6/fxTB6tpe28cew14XIp.gif, 238680 bytes wanted but 0 bytes read,at frame index 8 (out of a total 7 frames), at time 0.96/0.96 sec. Using the last valid frame instead.

#### Expected Behavior
No warning

#### Actual Behavior
So many warnings

#### Steps to Reproduce the Problem

Read a GIF file with some transparency layer with `VideoFileClip(file_name, has_mask=True)`
Loop it for more than its actual duration `loop(clip, duration=60)`
After the original duration of the clip, it will start emitting this warning. 

#### Specifications

  - Python Version: 3.8
  - Moviepy Version: 2.0.0dev2
  - Platform Name: Mac OSX
  - Platform Version:

**Comment by keikoro** [comment]
Hi, I'd ask you to provide actual code samples and the full error log to make it easier for others to debug or try to reproduce your problem. Please also fill out the rest of the issue template (platform version is missing).

Closing this until more information is available.
