### ISSUE TITLE
lost many frames when reading network files, and causes "xxx bytes wanted but 0 bytes read,at frame index xxx" and "Using the last valid frame instead"

### ISSUE THREAD

**Issue by jayn1985** [Zulko/moviepy#1391]
#### Expected Behavior
could read network file correctly

#### Actual Behavior
when reading some network files, it will lost many frames, and the final videos will have some issues, such as it likes freezing (may be "stopping" should be precise?) when watching it which cause the effect is not good.

t:  63%|██████▎   | 2274/3620 [03:36<04:02,  5.54it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 133 (out of a total 466 frames), at time 5.32/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2275/3620 [03:36<04:07,  5.44it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 134 (out of a total 466 frames), at time 5.36/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2276/3620 [03:36<04:01,  5.57it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 135 (out of a total 466 frames), at time 5.40/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2277/3620 [03:37<04:03,  5.51it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 136 (out of a total 466 frames), at time 5.44/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2278/3620 [03:37<03:57,  5.66it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 137 (out of a total 466 frames), at time 5.48/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2279/3620 [03:37<03:56,  5.67it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 138 (out of a total 466 frames), at time 5.52/18.64 sec. Using the last valid frame instead.
  UserWarning,
t:  63%|██████▎   | 2280/3620 [03:37<03:53,  5.73it/s, now=None]/Users/jayn/workspace/golang/ves/scripts/venv/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file https://xxx.mp4, 24883200 bytes wanted but 0 bytes read,at frame index 139 (out of a total 466 frames), at time 5.56/18.64 sec. Using the last valid frame instead.
  UserWarning,

(and more other warnings...)

#### Specifications

  - Python Version: 3.7.8
  - Moviepy Version: 2.0.0.dev2
  - Platform Name: MacBook Pro
  - Platform Version: macOs BigSur 11.0.1

**Comment by keikoro** [comment]
Closing this issue as it's missing information needed for debugging, like the code you used (also, full error logs).

Let us know when you've been able to update the issue so we can reopen it for you.
