### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by ooooooooopf** [Zulko/moviepy#1397]
I am not sure if this is where to put this issue but on this https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.colorx.html?highlight=brightness page is a typo, "reight" should be "right".. I am not a native English speaker (I am Dutch) so I verified it to be sure.

**Comment by tburrows13** [comment]
Thanks for the report. This was fixed in https://github.com/Zulko/moviepy/commit/90e42c108dcbefaf3e538d525800db9345fee714#diff-15d1c8ff82fd2f99b4d245e7dbf450baea440406b1f750ce227ff25502299549
