### ISSUE TITLE
utf8_decode() error on some mov files with quotes in metadatas

### ISSUE THREAD

**Issue by Fixazo** [Zulko/moviepy#140]
Hello,
I had a problem using moviepy with some .mov files which included bad metadatas, but I had to treat those files. It told me it couldn't decode 0x92 byte or something
I tracked down the error to ffmpeg_reader.py at line : 
infos = proc.stderr.read().decode('utf8')

I replaced it with that, and it solved my problem : 
infos = proc.stderr.read()

Maybe it can help !
Bye

**Comment by Zulko** [comment]
thanks, I think the "decode" is here because of python version compatibility. What's your OS and python version ?

**Comment by Fixazo** [comment]
Thanks for your answer,
I'm on windows 7 x64 and running on python 2.7.2 (I should update it maybe !)
By the way, it is a really useful module!!

**Comment by Fixazo** [comment]
I'm on 2.7.8 sorry!

**Comment by SandeR2012** [comment]
@Zulko 
Have same issue. Python 3.4.1, moviepy==0.2.2.11
Changed line 241 in moviepy\video\io\ffmpeg_reader.py to
`infos = proc.stderr.read().decode('utf8', errors='replace')`
Video for test: https://www.dropbox.com/s/hfuz7wlhx0ziu33/dark.m4v?dl=0

**Comment by TheShadow29** [comment]
I am facing the same issue on python3.7 moviepy==0.2.3.5

This is happening for some specific videos and the fix mentioned by @SandeR2012 worked for me. I can send in a pull request if needed. 

Here is a video for test: https://drive.google.com/open?id=1Ft0zEpG227j_wMiqueL_l5zEW42WRU41

**Comment by keikoro** [comment]
I'm wondering if this is even still an issue considering the linked PR got closed because it's no longer relevant (due to changes in the code).

**Comment by keikoro** [comment]
Closing this for now. Feel free to reopen or, ideally, open a new issue using the issue template (and link this one), in case the problem persists.
