### ISSUE TITLE
Expected numpy array format in AudioArrayClip

### ISSUE THREAD

**Issue by hbredin** [Zulko/moviepy#1400]
I am trying to instantiate an `AudioArrayClip` with a `numpy.ndarray` but keep getting weird sound out.
I suspect this is because the `dtype` and value range are not the ones expected by `MoviePy`.

```python
# this is just an example, in practice, `data` is generated programmatically
import scipy.io.wavfile
sample_rate, data = scipy.io.wavfile.read("audio.wav")

from moviepy.audio.AudioClip import AudioArrayClip
audio = AudioArrayClip(data, sample_rate)
```

What is the expected `dtype` and value range of `data`?

**Comment by tburrows13** [comment]
Hello, I think that the expected dtype is "uint8". Value range may be between -1 and 1. I'm not 100% sure about either of those answers though.

**Comment by hbredin** [comment]
Thanks for your reply.

However, `uint8` and [-1, 1] range do not really work well together since `uint8` stands for the integer range [0, 255].
Is there a particular part of the code base I could look at to try to understand this better?

**Comment by tburrows13** [comment]
Oh ok, I don't really know enough about it then.
You can see in https://github.com/Zulko/moviepy/blob/master/moviepy/audio/AudioClip.py#L278-L282 `AudioArrayClip`s return an index of the array as their frame.
This array item is converted to bytes and passed directly to stdout in https://github.com/Zulko/moviepy/blob/2ea5268f720cd3eac5b0a191d226eed39429ea3a/moviepy/audio/io/ffmpeg_audiowriter.py#L95.
FFmpeg reads from stdout using the parameters in https://github.com/Zulko/moviepy/blob/2ea5268f720cd3eac5b0a191d226eed39429ea3a/moviepy/audio/io/ffmpeg_audiowriter.py#L57-L84.

Hopefully that helps :)

**Comment by hbredin** [comment]
Thanks @tburrows13.

I did not manage to make `AudioArrayClip` work so went with the `AudioClip` + `make_frame` approach instead.
Here is the result if you are interested: https://github.com/pyannote/pyannote-audio/pull/585#issuecomment-763463807
