### ISSUE TITLE
Crop a Video with four different coodinate pairs

### ISSUE THREAD

**Issue by papar22** [Zulko/moviepy#142]
Hi all,

As most of you know, there is a module named "crop" in the video package of the Moviepy and it corresponds to crop a subpart of a video with all embedded frames and sounds. To this end, it needs two pair of cooridnates (the top-left and the bottom-rigth ones). Therefore, it crops a rectangle box. Now, I wanna do the perspective transformation on the video and crop it with four pair of coordinates (the top-left, the top-rigth, the bottom-rigth and the bottom-left). It would be appreciated if you give me any suggestions, as I looked for it on the net and didnot find anything.

P.s. if it is not a new issue, please simply delete the post.

bests,

**Comment by takosuke** [comment]
what you want to do would not be called crop, but 'corner pin' in a video effects suite, you will have to write your own I think. Search for matrix transformation algorithms, projective transformations, corner pin matrix...it seems to go by very different names. Here's some links I've found:
http://math.stackexchange.com/questions/296794/finding-the-transform-matrix-from-4-projected-points-with-javascript/339033#339033
http://compgroups.net/comp.graphics.algorithms/constructing-a-corner-pin-matrix/2050857

**Comment by kerstin** [comment]
Yeah, this is more of a (potential) feature request/special effects request. I'm closing this though due to a lack of response/activity on this rather old issue.
