### ISSUE TITLE
Migrate Windows CI to GH Actions

### ISSUE THREAD

**Issue by mondeja** [Zulko/moviepy#1428]
The "Run Test Suite" workflow has a [commented version of a Windows workflow](https://github.com/Zulko/moviepy/blob/20633adf256d8601141690d95ed0e986aa3a9289/.github/workflows/test_suite.yml#L66-L117) with a "TODO" comment. It seems to me that the execution on GH Actions could speed up the Windows CI set up time, and since Linux and MacOSX are tested using GH Actions, seems that should be migrated. I haven't been contributing for a long time, so I'd like to know if that's the case before start the migration. If so, please assign this issue to me and I'll give a try.

**Comment by tburrows13** [comment]
Yes, the idea was to do it all with GH Actions and drop Appveyor. I couldn't get ImageMagick to work on Github Windows, so I left it commented out, because I was (and still am) hoping to get rid of ImageMagick for 2.0, so I was going to revisit it then.
