### ISSUE TITLE
Convert gif to video has back background at the end of the video

### ISSUE THREAD

**Issue by noppanit** [Zulko/moviepy#143]
I'm using MoviePy to convert gif to mp4 and the result has black background at the end resulting in the video keeps blinking when play in loop. I was thinking of cut the last frame out but I might have missed something obvious here. 

Here's the code

```
        video = VideoFileClip(gif_path)
        video.save_frame(saving_snapshot_filename)

        result = CompositeVideoClip([video])
        result.write_videofile(saving_mp4_filename)
```

**Comment by Zulko** [comment]
I am not sure I understand the issue. Have you tried this ?

    video = VideoFileClip(gif_path)
    video.write_videofile(saving_mp4_filename)

Also, can you describe more precisely that "black background at the end" thing. You have a completely black frame ?

**Comment by noppanit** [comment]
I believe that solved the issue. 
And here's what I meant if you tried this in HTML

```
<!doctype>
<html>

<head>
    <title>
    </title>
</head>
<body>
    <video src="https://dl.dropboxusercontent.com/u/27106646/57203191c21df0cacf98f3fa9340f4.mp4" autoplay="" loop=""></video>
</body>
</html>

```

**Comment by Zulko** [comment]
Cool, I'm closing the issue. I didn't see any black frame in your linked example btw, I don't understand what was wrong.
