### ISSUE TITLE
Regarding maintenance of the project

### ISSUE THREAD

**Issue by mondeja** [Zulko/moviepy#1432]
First of all, thank you for the great work on this project, it's awesome! Moviepy has a lot of great features that I'm using, but sadly the code base is unstable and the maintenance of the project is very poor. Hopefully, the v2.0.0 release will solve a lot of these problems, but I do not see it very close with the speed of development that we have.

I would like to see this project mature, so I offer myself as a maintainer. I've been done some pull requests and code reviews, as well started trying to clarify some duplicate issues, getting familiar with the code. @tburrows13 suggested me that would open an issue like this, so here it is. What do you say about it @Zulko?

**Comment by Zulko** [comment]
Thanks so much for your contributions and offering your help, I'll give you maintainer rights.

**Comment by mondeja** [comment]
Thank you @Zulko, a pleasure!
