### ISSUE TITLE
Concatenation Glitchs

### ISSUE THREAD

**Issue by estebanhirzfeld** [Zulko/moviepy#1437]
I cant concatenate clips with differents resolutions, it glitches

neither use method "compose" or " video = CompositeVideoClip([clip1,clip2,clip3,clip 4]) "

```
from moviepy import *

import pygame
from pygame.locals import *

from moviepy.editor import VideoFileClip, concatenate_videoclips, clips_array, vfx


clip1 = VideoFileClip("./video.mp4")
clip2 = VideoFileClip("./video2.mp4")
clip3 = VideoFileClip("./video3.mp4")
clip4 = VideoFileClip("./video4.mp4")



clipf = concatenate_videoclips([clip1,clip2,clip3,clip4])


clipf.write_videofile("./concat.mp4", audio =False, method="compose" )
```

https://user-images.githubusercontent.com/55365571/104526893-4398f680-55e2-11eb-8c93-46f93b10a253.mp4

![imagen_2021-01-13_210015](https://user-images.githubusercontent.com/55365571/104526951-60352e80-55e2-11eb-8882-a35ad736914c.png)

**Comment by tburrows13** [comment]
`method = "compose"` goes in `concatenate_videoclips`, not `write_videofile`. Please check the docs next time :)
