### ISSUE TITLE
'coreader' methods of 'VideoFileClip' and 'AudioFileClip' are buggy

### ISSUE THREAD

**Issue by mondeja** [Zulko/moviepy#1441]
These methods were created at #1332 and https://github.com/Zulko/moviepy/commit/fdc51d29b7ce2f3b2c4d0d907c1c62b5da168128, but IMHO I think that are a misunderstanding of how `copy.copy` and `copy.deepcopy` works in Python.

- `coreader` methods currently does a shallow copy (like `copy.copy`) but only taking into account `filename` parameter.
- `Clip.copy` method is working like `copy.deepcopy`, but even for `AudioClip` the `mask` and `audio` attributes are checked in the instance.

### Actual Behavior

The `coreader` functionality is not working. It's implemented as `return AudioFileClip(self.filename, self.buffersize)`, but `AudioFileClip` accepts `buffersize` as a kwarg argument, so it's not taking the `buffersize`. The same applies to `VideoFileClip`.

The documentation of `coreader` methods are very poor, what are they supposed to do? I think that should be added an example, if they are really implemented and are not bad `copy.copy`-like code.

#### Steps to Reproduce the Problem

```python
>>> from moviepy.editor import *
>>> clip = AudioFileClip('media/crunching.mp3', buffersize=1000)
>>> clip_2 = clip.coreader()
>>> clip.buffersize
1000
>>> clip_2.buffersize
200000
```

### Expected behaviour

I'm not sure, are a failed copy, I'm thinking in two possible cases:

- New instance with only filename as the same argument
- New instance with filename and buffersize as same arguments 
  
I suspect that are just weird copy code, and `copy` method should be used instead (ovewriting it in `AudioClip` to because a `deepcopy` in those are not needed).

### Specifications

  - Python Version: 3.8.5
  - Moviepy Version: master
  - Platform Name: Ubuntu
  - Platform Version: 20.04

**Comment by tburrows13** [comment]
I have no opinion on the coreader methods. Feel free to scrap them, fix them, rename them, or implement proper copy methods if you like.

I've never used `.coreader()`, and I don't really know when I would.
