### ISSUE TITLE
Concatenation + Outro

### ISSUE THREAD

**Issue by estebanhirzfeld** [Zulko/moviepy#1445]
Sorry, im new in python and Moviepy, so i don't know how can i redact this this properly, this is my code it takes 100 clips and cut every 10 (that works)
 but i want to add an outro

something like this:

```
for i, j in enumerate(range(0, len(videos), CLIP_SIZE)):
       final_clip = concatenate_videoclips(videos[j:j+CLIP_SIZE])
```

to this
```

for i, j in enumerate(range(0, len(videos), CLIP_SIZE)):
       final_clip = concatenate_videoclips(videos[j:j+CLIP_SIZE], outro)  #<-------------------
```
but it returns an error

**Comment by mondeja** [comment]
> but it returns an error

Could you share the error?

**Comment by estebanhirzfeld** [comment]
> > but it returns an error
> 
> Could you share the error?

![image](https://user-images.githubusercontent.com/55365571/104775722-9647ef00-5757-11eb-99fa-789bee68de8f.png)

**Comment by mondeja** [comment]
You need to pass the clips as a list: `concatenate_videoclips([videos[j:j+CLIP_SIZE], outro])` :wink:

**Comment by estebanhirzfeld** [comment]
i also tried that
![image](https://user-images.githubusercontent.com/55365571/104783719-6bfd2e00-5765-11eb-9384-299a6c2222ee.png)

**Comment by estebanhirzfeld** [comment]
> You need to pass the clips as a list: `concatenate_videoclips([videos[j:j+CLIP_SIZE], outro])` 😉

i also tried that
![image](https://user-images.githubusercontent.com/55365571/104783812-9b139f80-5765-11eb-814a-5cc80b51769c.png)

**Comment by estebanhirzfeld** [comment]
> You need to pass the clips as a list: `concatenate_videoclips([videos[j:j+CLIP_SIZE], outro])` 😉

i also tried that
![image](https://user-images.githubusercontent.com/55365571/104783866-bd0d2200-5765-11eb-91d8-e648b8440a1b.png)

**Comment by tburrows13** [comment]
> You need to pass the clips as a list: `concatenate_videoclips([videos[j:j+CLIP_SIZE], outro])` 😉

This isn't quite right. `concatenate_videoclips(videos[j:j+CLIP_SIZE] + [outro])` is what you want.
