### ISSUE TITLE
'make_loopable' function repeated

### ISSUE THREAD

**Issue by mondeja** [Zulko/moviepy#1476]
`make_loopable` function is repeated in `video.compositing.transitions` and `video.fx.make_loopable`.
One of both must die :fire:

**Comment by tburrows13** [comment]
Added in https://github.com/Zulko/moviepy/commit/deb8a689a4283f98c9451f8895faf9c9652713bf and https://github.com/Zulko/moviepy/commit/b78f35ef325eb9c9b70eb4531bd9f0fa56df6eff
