### ISSUE TITLE
One of the examples doesnt work

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [Zulko/moviepy#149]
https://github.com/Zulko/moviepy/blob/master/examples/logo.py

you forgot to declare the mask added on line 15

**Comment by Zulko** [comment]
Ach. Thanks for the report. On a more general note, the examples from the examples session are reaaly outdated and mostly uninteresting, it would be time they are replaced.

**Comment by earney** [comment]
In my opinion, it is better to remove the outdated examples then leave them, since most of them do not work.  We can add new examples, here shortly.  What does others think?

**Comment by kerstin** [comment]
I agree. Examples that won't work with the current codebase just confuse people.

**Comment by Zulko** [comment]
Yes feel free to weed out anything broken.

**Comment by tburrows13** [comment]
This was fixed at some point
