### ISSUE TITLE
Stretching and blurring the background clip

### ISSUE THREAD

**Issue by markdrrr** [Zulko/moviepy#1494]
Tell me how to implement my idea with moviepy

 I have a video at the entrance.Vertical video:
![image](https://user-images.githubusercontent.com/56235826/105803029-95ac2580-5fad-11eb-9759-a7c52944077e.png)

At the exit, I want to get this result. Horizontal video with background
![image](https://user-images.githubusercontent.com/56235826/105802985-71e8df80-5fad-11eb-9314-39ceac67c64e.png)

**What methods should you use?**

**Comment by markdrrr** [comment]
i found two solutions
https://github.com/Zulko/moviepy/issues/884 
and 
https://stackoverflow.com/questions/30789367/ffmpeg-how-to-convert-vertical-video-with-black-sides-to-video-169-with-blur

Who can explain these meanings?
```
ffmpeg_params=['-lavfi', '[0:v]scale=ih*16/9:-1,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)/20:chroma_power=1[bg];[bg][0:v]overlay=(W-w)/2:(H-h)/2,crop=h=iw*9/16']
```

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
