### ISSUE TITLE
How to track and blur a part of movie (example a logo)

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [Zulko/moviepy#1497]
I have a movie with a logo/watermark. How can I track and blur it?

![image](https://user-images.githubusercontent.com/36155295/106708187-c9362200-6635-11eb-8ed1-3960e0f1324b.png)

**Comment by mondeja** [comment]
How to track and blur part of a movie is explained in detail in the [`headblur.py`](https://github.com/Zulko/moviepy/blob/8cc3eebb0950c07c123f8b1343fb50a706ab6f27/examples/headblur.py) example.
