### ISSUE TITLE
headblur.py not working

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [Zulko/moviepy#1498]
I run this head blur example https://github.com/Zulko/moviepy/blob/8cc3eebb0950c07c123f8b1343fb50a706ab6f27/examples/headblur.py

But I got this error:

Exception has occurred: TypeError
integer argument expected, got float
  File ".\blur_moviepy.py", line 29, in <module>
    clip_blurred = clip.fx(vfx.headblur, traj.xi, traj.yi, 25)

How do I solve it?

**Comment by mondeja** [comment]
Have you created the trayectory file in a previous execution as is described in [these lines](https://github.com/Zulko/moviepy/blob/8cc3eebb0950c07c123f8b1343fb50a706ab6f27/examples/headblur.py#L9-L16)?

**Comment by nguyenanhtuan1008** [comment]
> Have you created the trajectory file in a previous execution as is described in [these lines](https://github.com/Zulko/moviepy/blob/8cc3eebb0950c07c123f8b1343fb50a706ab6f27/examples/headblur.py#L9-L16)?

Yes. I did. I run it then it shows the video -> I click around the logo -> got the error above.

**Comment by mondeja** [comment]
> I click around the logo till the end clip

What logo? The example is using a clip of a Chaplin movie.

**Comment by nguyenanhtuan1008** [comment]
> > I click around the logo till the end clip
> 
> What logo? The example is using a clip of a Chaplin movie.

I'm using my custom clip with a logo I want to blur it. what is the difference between Chaplin movie and custom movies?

**Comment by mondeja** [comment]
I can't replicate your issue with the current example, so I need more information about this. If you are not running the example, could you provide your code and media files?

**Comment by nguyenanhtuan1008** [comment]
https://drive.google.com/file/d/1LlBQWrTFtWIW2NZYTZ_IeFWYAXCt6xG4/view?usp=sharing 
this is code and video. FOR example, I want to blur the TikTok logo in both the top left and bottom right? How do I do?

**Comment by mondeja** [comment]
1. Uncomment `manual_tracking(...` line.
2. Execute the code.
3. Click, for each frame, the object that you want to blur.
4. Comment the `manual_tracking(...` line.
5. Execute the code.

**Comment by nguyenanhtuan1008** [comment]
> 1. Uncomment `manual_tracking(...` line.
> 
> 2. Execute the code.
> 
> 3. Click, for each frame, the object that you want to blur.
> 
> 4. Comment the `manual_tracking(...` line.
> 
> 5. Execute the code. 

I know. I already did. After 5. Execute the code I got the error above. That why I open this issue.
P/s. Still not working! Can you run the code ?

**Comment by mondeja** [comment]
After a few success attempts, I've reproduced it

**Comment by mondeja** [comment]
What versions of moviepy and OpenCV are you using @nguyenanhtuan1008?

**Comment by nguyenanhtuan1008** [comment]
> What versions of moviepy and OpenCV are you using @nguyenanhtuan1008?

opencv4.0.1 and moviepy newest

**Comment by mondeja** [comment]
What is moviepy newest?

**Comment by nguyenanhtuan1008** [comment]
> What is moviepy newest? It seems that the example only works with the code in **master** branch. I can reproduce your issue using older versions of moviepy, but not with the master.

Sorry, what is version are you using? I using pip install moviepy and it's not working!

**Comment by mondeja** [comment]
> Sorry, what is version are you using?

The code in master branch, the example was adapted for that version. What is the version number that you are using?
