### ISSUE TITLE
Moviepy large memory usage upon import

### ISSUE THREAD

**Issue by shin-illua** [Zulko/moviepy#1503]
On console, I do a simple 
```
from moviepy.editor import * 
``` 
or even a 
```
from moviepy.video.io.VideoFileClip import VideoFileClip
```

#### Expected Behavior
Should use lesser memory? 

#### Actual Behavior
It uses 1+GB of memory. 

#### Specifications

  - Python Version: `Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32`
  - Moviepy Version: `moviepy==1.0.1`
  - Platform Name: `Windows`
  - Platform Version: `10`

**Comment by tburrows13** [comment]
Try uninstalling Pygame and see if that helps.

**Comment by shin-illua** [comment]
My bad. Seems like it's numpy's issue. Python instance uses upto 1.4GB of memory upon import of numpy. `numpy-1.19.3-cp38-cp38-win_amd64.whl`
