### ISSUE TITLE
TextClip make line in linux

### ISSUE THREAD

**Issue by meitnerium** [Zulko/moviepy#1504]
I add text to a video and it's work fine in windows. 

```
from moviepy import TextClip
txt_clip = TextClip("HR = " + str(hr[i]), fontsize=myfontsize, color='green')
txt_clip = txt_clip.set_position((posx,poxy)).set_duration(1)

```

![image](https://user-images.githubusercontent.com/149830/108451591-153bb600-7235-11eb-951b-dd23dd2f5de2.png)

However, in Linux, the same code create line instead of text :
![image](https://user-images.githubusercontent.com/149830/108451688-40260a00-7235-11eb-8d92-9f4c8e319757.png)

#### Expected Behavior
Same behavior in windows and linux, or an error ...

#### Steps to Reproduce the Problem

```
from moviepy.editor import VideoFileClip, concatenate_videoclips, TextClip, CompositeVideoClip, VideoClip, ImageClip
myfontsize = 150
posx=10
poxy = 10
txt_clip = TextClip("HR = 150", fontsize=myfontsize, color='green')
txt_clip = txt_clip.set_position((posx, poxy)).set_duration(1)
txt_clip.write_videofile("test.mp4",fps=24)
```
#### Specifications

  - Python Version: Linux 3.6, windows 3.8
  - Moviepy Version: 1.0.3
  - Platform Name: Windows 10 and CentOS 7
  - Platform Version:

**Comment by tburrows13** [comment]
This is why we are leaving ImageMagick behind in v2.0. Unfortunately I can't really help you on this one, unless you are willing to fiddle around with some moviepy git branches and undocumented/unfinished features.

**Comment by meitnerium** [comment]
Thank you. At this time, I will continue using windows version. Thank you for your help.

**Comment by RCambier** [comment]
I faced the same issue but really wanted to make it work on Linux. 

I solved it by switching to GraphicsMagick which approximately supports the same functionality. I had to modify the TextClip code to use that instead of ImageMagick.

**Comment by jakobhuss** [comment]
Looks like a bug in imagemagick
I upgraded to: `Version: ImageMagick 7.0.11-5 Q16 x86_64 2021-03-20`
Then it worked as expected again. Binary install found here: https://imagemagick.org/script/download.php

**Comment by keikoro** [comment]
Closing this as two potential solutions were provided by fellow users + a maintainer provided some general background info.
