### ISSUE TITLE
Is it possible to effect clone of yourself in video with moviepy

### ISSUE THREAD

**Issue by adjmxx** [Zulko/moviepy#1516]
I want to do a clone effect in a  video. The idea is that appear several clones of me in the same video

**Comment by mondeja** [comment]
You need to create a mask of your silhouette. There is no straightfoward way of doing some like this with moviepy, but you can take a look at [`moviepy.video.tools.tracking` module](https://github.com/Zulko/moviepy/blob/736abcc2fe771ecf84bd50fe3fd905b76e76566c/moviepy/video/tools/tracking.py), maybe with those tools you can achieve this without too much pain.
