### ISSUE TITLE
example of moviepy logo with a moving shadow doesn't work anymore, please, fix it

### ISSUE THREAD

**Issue by WilliamPythonDL** [Zulko/moviepy#1524]
My Moviepy version : Version: 2.0.0.dev2

example code in logo.py doesn't work,
first Error: no attribute "with_mask"
second Error: mask in "with_mask(mask)" is not defind
thirth Error: NameError: name 'biGradientScreen' is not defined

**Comment by tburrows13** [comment]
Thanks for reporting the issues. This has been discussed in #1507, so I'm closing this in favour of that issue.

PS We're all working on this voluntarily so please don't spam lots of people with @ .
