### ISSUE TITLE
Importing concatenate_videoclips

### ISSUE THREAD

**Issue by Fuchio** [Zulko/moviepy#1525]
I am using concatenate_videoclips which works fine when I use:
`from moviepy.editor import concatenate_videoclips`

But it doesn't seem to work when I use:
`from moviepy.video.compositing.concatenate import concatenate_videoclips`

Does anyone know how to fix this? The reason I want to import through moviepy.video.compositing is that PyInstaller gives an error when importing through editor.

Thanks in advance.

**Comment by tburrows13** [comment]
I'd recommend trying the current master branch instead of the pip-installable version, which allows you to do `from moviepy import concatenate_videoclips`.

**Comment by Fuchio** [comment]
Amazing, huge thanks for the quick response and it fixed my problem within five minutes. Everything works perfect now.
