### ISSUE TITLE
PyInstaller problem on Windows

### ISSUE THREAD

**Issue by mateus-werneck** [Zulko/moviepy#1527]
Hello, I've searched back and forth and couldn't find a solution for my problem. That's why i'm opening this issue.

When using moviepy VideoFileClip and also concatenate_videos my PyInstaller executable won't work. This is what cmd returns me:

![PyInstallerFFmpeg](https://user-images.githubusercontent.com/25112157/112709343-76d7eb80-8e97-11eb-87ae-5af46adb2821.png)

Strangely this is the same error message that appears for me if geckodriver.exe is not in the same directory as my Pyinstaller generated exe, when using selenium webdriver. When copying geckodriver.exe to the same folder this problem just disappears.

Things I've already tried:

1)Set FFMPEG binary path to PATH on Windows
2)--add-binary on pyinstaller
3) --add-data on pyinstaller
4) Copying my ffmpeg.exe to the same folder
5) Importing each specific module from moviepy:

"from moviepy.video.io.VideoFileClip import VideoFileClip"
"from moviepy.video.compositing.concatenate import concatenate_videoclips"

6) Changing binary path on config_defaullts.py

I also tried to import FFPMEG_Writer, but no-go.

On Ubuntu 20.04 after importing each specific module from moviepy i was able run the pyinstaller executable. When import moviepy.editor it would not work too.

Any ideas what the problem could be? Maybe permissions to open ffmpeg.exe on Windows with the .exe?

**Comment by keikoro** [comment]
Please provide the information we ask for when opening new issues (see issue template). Closing this for now, but feel free to reopen once the info is available.
