### ISSUE TITLE
Video duration and Audio Duration different when using cutout()

### ISSUE THREAD

**Issue by MiniMinnoww** [Zulko/moviepy#1529]
So I am using .cutout() on a file - my script looks something like this:

```
frame_ranges = [[10, 11], [15, 16]]
for lst in frame_ranges:
            vid = vid.cutout(lst[0], lst[1])
            if vid.audio.duration != vid.duration:
                print(f"BAD DURATION: {str(vid.duration)}, {str(vid.audio.duration)}")
```

So this prints 'BAD DURATION' if the audio and video times don't match - and they don't. I have checked and it is this part of the script that has the issue. It seems the audio is always a bit shorter than the video!

I am using the latest dev version (it also did the same on the latest version)

As well as this - for some one clip that I am cutting with the above comes up with an ```Index out of bounds``` error when exporting (with the write_audiofile() part)  - here is the full output for that: https://pastebin.com/DELBDZC7

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
