### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by Buster-2002** [Zulko/moviepy#1530]
#### Expected Behavior
Change gradient

#### Actual Behavior
This error being thrown:
```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    grad = color_gradient(moving_txt.size,p1=(0,2*h/3),
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\video\tools\drawing.py", line 147, in color_gradient
    if vector:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

#### Steps to Reproduce the Problem

Copying the code used [here](https://zulko.github.io/moviepy/examples/star_worms.html) (also set the height to an int, not float, to avoid a `TypeError`)

This error has been mentioned [here](https://github.com/Zulko/moviepy/issues/1205), and was said to be fixed, but that doesn't appear to be the case anymore.

#### Specifications

  - Python Version: 3.8.5
  - Moviepy Version: 1.0.3
  - Platform Name: Windows 10 Pro
  - Platform Version: Version 2004 OS Build 19041.867

**Comment by tburrows13** [comment]
Sorry, it is fixed, but not in v1.0.3. You'll have to install a v2.0 pre-release with the pip `--pre` flag.

**Comment by Buster-2002** [comment]
Changing the code myself to `if vector is None` then results in the following erorr: ```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\moviepy\video\tools\drawing.py", line 154, in color_gradient
    n_vec = vector/norm**2 # norm 1/norm(vector)
UnboundLocalError: local variable 'norm' referenced before assignment
```

**Comment by Manamama** [comment]
OK, probably that was to blame:

```
    # Attempt to load as a VideoFileClip, fallback to AudioFileClip
    try:
        clip = VideoFileClip(str(media_path)).with_memoize(True) # Sets whether the clip should keep the last frame read in memory, see https://zulko.github.io/moviepy/reference/reference/moviepy.Clip.Clip.html#moviepy.Clip.Clip.with_memoize
        is_video = True  # If it loads as a VideoFileClip, it's a video
        print(f"Loading as media type: Video")
    except:
        clip = AudioFileClip(str(media_path))
        is_video = False  # Fallback to audio-only clip
        print(f"Loading as media type: Audio")

```

- one should not memoize audio (it somehow did not throw any errors in the older version...)
