### ISSUE TITLE
which under lying machine will be faster?

### ISSUE THREAD

**Issue by esssajjad** [Zulko/moviepy#1532]
Considering a multi-process, multi-threaded rendering back end, where a lot of videos are being rendered. 
Is it GPU, CPU, or RAM that will render the videos faster?
What is the current status of moviepy for GPU acceleration support? 
I found this link on NVIDIA for ffmepg support [link](https://developer.nvidia.com/ffmpeg), but not sure if moviepy is fully supporting GPU acceleration. 

One should consider buying a VM of 
RAM 50G
vCPU 16

OR

RAM 25G
vCPU 16
NVIDIA 1X T4

Which one is better ?

**Comment by tburrows13** [comment]
MoviePy does not support GPU acceleration support. It may do in the future (see #1089 for some discussion), but certainly not for ~6 months and maybe never (you're very welcome to contribute it yourself!).

Given that, I guess your first machine would be better.

**Comment by keikoro** [comment]
Closing this as the original question was essentially answered. Any further discussion of GPU had better take place in the linked issue because GPU support has been commented on and "upvoted" there multiple times.
