### ISSUE TITLE
Large RAM usage in moviepy when concatenating and editing videos

### ISSUE THREAD

**Issue by VeckoTheGecko** [Zulko/moviepy#1535]
Hello! I'm having an issue with memory when editing with moviepy. I'm editting together 1000 gifs into one concatenated montage, including titles at the bottom of each gif and some other metadata (including a progress bar for each gif).

I've done the coding part, but once I try run the full script it uses all 8Gb of RAM by the 50th clip. The original 1000 clips are only 3.65Gb in total.

I was wondering whether it is normal for moviepy to use much more ram because it is editting the clips (whether resizing the clips to 1920x1080 and the editting would make the RAM usage skyrocket).

I was also wondering whether there would be any way that I could get around this issue. I saw posts on RAM usage with image sequences, but none for concatenating video. I assume that I can't `.close()` each video as I edit them as each video is used in the final concatenation.

I'd be happy to provide code if necessary, let me know if it would help 🙂

**Comment by tburrows13** [comment]
Your best bet is probably to do it in sections: take some of the files, edit them and write them out, then close all clips. Do successive lots until you've done all of them. Then take your intermediate files, read them back in, concatenation them, and write the final file out.

**Comment by VeckoTheGecko** [comment]
> Your best bet is probably to do it in sections: take some of the files, edit them and write them out, then close all clips. Do successive lots until you've done all of them. Then take your intermediate files, read them back in, concatenation them, and write the final file out.

Thanks for the response! I've started doing that and the RAM usage is much better.
