### ISSUE TITLE
AttributeError: 'TextClip' object has no attribute 'with_position'

### ISSUE THREAD

**Issue by TheNewThinkTank** [Zulko/moviepy#1538]
Here is what I am trying to do:

```
from moviepy import *
from moviepy.editor import *

video = VideoFileClip("video_orig.mp4")

txt_clip = (TextClip("Some dummy text",
                              fontsize=70,
                              color='white'
                              )
                  .with_position('center')
                  .with_duration(10)
                  )
```

I am getting this error:

`AttributeError: 'TextClip' object has no attribute 'with_position'`

#### Expected Behavior
I expected the TextClip to get created, so that I could create a composite of my original movie with this TextClip.

#### Actual Behavior
Attribute: 'with_position' is not recognized. I need this attribute in order to select area of video frame to insert my TextClip.

#### Steps to Reproduce the Problem
Simply run the script provided in the top.

#### Specifications

  - Python Version: 3.9.2
  - Moviepy Version: 1.0.1
  - Platform Name: Windows
  - Platform Version: 10

**Comment by Jafari-Amir** [comment]
Hey friends, I hope you are doing well.
I find out the term  .with_duration(10), seems do not function there or at least as far as I know it should be  .set_duration(10)
example:
from moviepy.editor import *

sub_clip = VideoFileClip("video.mp4").subclip(0, 20)
title = TextClip("Title", color="green").set_duration(1)
comp_clip = CompositeVideoClip([title, sub_clip])
comp_clip.write_videofile("output.mp4")

**Comment by daMS2005** [comment]
How did you solve this?

**Comment by TheNewThinkTank** [comment]
Hi @daMS2005 , I am adding here a small example demo, original video [here](https://www.youtube.com/watch?v=_GmDdPK2xWQ&ab_channel=GustavCollinRasmussen)

Result video after applying [this script](https://github.com/TheNewThinkTank/file-tools/blob/main/file_convertion_tools/movie.py) below:

https://github.com/user-attachments/assets/22384584-3f22-4eff-9950-7190f2359261

terminal output:

```BASH
(.venv) ➜  file_convertion_tools git:(main) ✗ python3 movie.py        
2024-12-17 18:01:11,612 - INFO - Cuts validated successfully.
2024-12-17 18:01:11,612 - INFO - Input file 'demo.mp4' found.
2024-12-17 18:01:11,612 - INFO - Processing video...
2024-12-17 18:01:11,822 - INFO - Adding text overlay to the video...
2024-12-17 18:01:13,061 - INFO - Exporting video to 'demo_edited.mp4'...
Moviepy - Building video demo_edited.mp4.
MoviePy - Writing audio in demo_editedTEMP_MPY_wvf_snd.mp3
MoviePy - Done.                                                                    
Moviepy - Writing video demo_edited.mp4

Moviepy - Done !                                                                   
Moviepy - video ready demo_edited.mp4
2024-12-17 18:01:16,312 - INFO - Video editing completed successfully.```

NB: If you're on Mac as I was, install ImageMagick with HomeBrew: `brew install imagemagick`

Hope you may find this useful 😃
