### ISSUE TITLE
Clip has an extra frame when using an fps of 43

### ISSUE THREAD

**Issue by richard-viney** [Zulko/moviepy#1539]
#### Expected Behavior

The following code should write a video file that has 100 frames, but it writes a video with 101 frames. This is triggered by having an fps of 43, which causes some rounding or other numerical inaccuracies to occur internally resulting in an extra frame being written.

If the FPS is 40 or 25 then no extra frame is written to the output file.

```
import moviepy.video.io.ImageSequenceClip
import numpy as np
frames = np.zeros((100, 640, 480, 3), 'float64')
clip = moviepy.video.io.ImageSequenceClip.ImageSequenceClip([f for f in frames], fps=43)
clip.write_videofile("output.mp4")
```

Use `ffprobe` to read the number of frames in the output file:

`ffprobe -v error -show_entries stream-nb_frames -of default=nokey=1:noprint_wrappers=1 output.mp4`

#### Actual Behavior

The output video should have 100 frames to match the input data.

#### Steps to Reproduce the Problem

See above for code and `ffprobe` command. Note that `clip.iter_frames` also iterates 101 frames instead of the expected 100, which I think is the underlying issue here.

#### Specifications

  - Python Version: 3.8.2
  - Moviepy Version: 1.0.3
  - Platform Name: macOS
  - Platform Version: 10.15.7

**Comment by richard-viney** [comment]
I ended up using `FFMPEG_VideoWriter` directly to work around this issue:

```
from moviepy.video.io.ffmpeg_writer import FFMPEG_VideoWriter

with FFMPEG_VideoWriter(
   "output.mp4",
    (640, 480),
    fps=43,
    codec="libx264",
    preset="slow",
    bitrate="5000k",
) as writer:
    for frame in frames:
        writer.write_frame(frame)
```

**Comment by mondeja** [comment]
I can't reproduce this with latest **master** branch:

<details>
  <summary><code>ffmpeg -i output.mp4</code></summary>

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'output.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:02.33, start: 0.000000, bitrate: 17 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x640, 10 kb/s, 43 fps, 43 tbr, 11008 tbn, 86 tbc (default)
    Metadata:
      handler_name    : VideoHandler  
```

</details>

<details>
  <summary><code>ffprobe -v error -select_streams v:0 -count_packets -show_entries stream=nb_read_packets -of csv=p=0 output.mp4</code></summary>

```
100
```

</details>
