### ISSUE TITLE
Add more details on missing ImageMagick error message regarding legacy tool installation

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [Zulko/moviepy#1551]
MoviePy needs ImageMagick to render text.
However, new versions of ImageMagick come without the `convert.exe` utitlity by default.
Thus, even if ImageMagick is in the path, MoviePy will not find it.

The error message in `VideoClip.py` should be enhanced:
```
            error = ("MoviePy Error: creation of %s failed because of the "
                     "following error:\n\n%s.\n\n." % (filename, str(err))
                     + ("Please check" +
                        "- that ImageMagick is installed on your computer,"
                        "- (for Windows users) that you specified the path to the ImageMagick binary in file conf.py,"
                        "- that the path you specified is correct,"
                        "- that you installed ImageMagick with the legacy tool support (convert.exe)"))
```

Also, I noticed that I don't have a file `conf.py` but `config.py`. Not sure whether I'm looking in the correct place.

**Comment by mondeja** [comment]
There is a plan to remove ImageMagick in #1472, but meanwhile pull requests enhancing that message are welcome.

**Comment by keikoro** [comment]
I'm closing this as the question or issue raised has, essentially been answered. As my co-maintainer said, we would, however, welcome PRs dealing with this, @thomasw-mitutoyo-ctl!
