### ISSUE TITLE
Very Slow Crossfade Operation: Is there a better way?

### ISSUE THREAD

**Issue by ekianjo** [Zulko/moviepy#1557]
Hi there, I have been experimenting with moviepy recently and I find it awesome, but I am facing some really slow rendering issues when it comes to crossfades. I am assuming I am probably doing things wrong, so hopefully someone can help. 

I made a function that takes a few arguments to concatenate 2 videos and one image (turned into a video clip) together with crossfade effects in between each of them.

the first video_title video is usually very short (7 seconds) and the video_trailer itself is the one that contains usually a few minutes of video. 
```
def make_one_title_chunk(jingle_path,video_title_path,video_trailer_path,image_path):
  jingle = AudioFileClip(jingle_path)
  video_title = VideoFileClip(video_title_path).fadein(2)
  video_trailer = VideoFileClip(video_trailer_path)
  final_clip = ImageClip(image_path).set_duration(10)
  cc = concatenate_videoclips([video_title,video_trailer.crossfadein(2)],padding=-2, method="compose")
  cc2 = concatenate_videoclips([cc,final_clip.crossfadein(2)], padding=-2, method="compose").fadeout(3)
  audioclip = CompositeAudioClip([jingle,cc2.audio])
  cc2.audio = audioclip
  cc2.to_videofile("test.mp4",
                       fps=60, bitrate="5000k",
                       audio_bitrate='500k',threads=4)
```
It works as expected, but it's very slow and I assume it's because it's doing compositing during concatenation. in the cc step I only need the crossfade for a few seconds but it slows down the whole operation.

I tried to change "compose" to "chain" but then it does not render the crossfade effect anymore. 

Is there anything obvious I should be doing to get more performance when rendering? Right now this whole operation takes about 30 mins for a video that's just 4 minutes long at the end. I would really like to get close to something like 10 mins rendering, not more. (note that I do not want to compromise on fps, it has to be 60 fps)

**Comment by AndreasWJ** [comment]
@ekianjo have you found any workarounds to decrease the render time?
I have the same issue crossfading between clips, my render time went from 10-15 minutes to 45-50 minutes.

**Comment by sruon** [comment]
I built a fork based on 1.0.3 with the performance patch applied (#1342)

30 it/s with upstream package and compose method
130 it/s with upstream package and chain method

70 it/s with my fork and compose method
130 it/s with my fork and chain method

`pipenv uninstall moviepy`
`pipenv install -e git+https://github.com/sruon/moviepy.git@main#egg=moviepy`

**Comment by ekianjo** [comment]
The only solution I found is to only do crossfade on subclips of the larger clip (i cut the first 2s of a larger clip to apply the crossfade only on the 2s piece, not the whole clip) and this is somewhat better, but not an ideal solution by any means.

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
