### ISSUE TITLE
crossfadein on TextClip doesn't work with the newest code

### ISSUE THREAD

**Issue by ningzichun** [Zulko/moviepy#1558]
Hello, I want the title text to fade in on the background, so I use crossfadein on TextClip.
Moviepy v2 brings performance improvements, and while migrating codes, I found that crossfadein doesn't work.

#### Expected Behavior
On moviepy v1.0.3, 
```
from moviepy.editor import *
color_clip = ColorClip(size=(1920,1080),color=(223, 234, 240)).set_duration(5)
title_clip = TextClip("TestTitle", color='green', kerning=5, fontsize=140).set_duration(8).set_start(0.5).crossfadein(2).set_position(('center',400))
openning = CompositeVideoClip([color_clip,title_clip], size=(1920,1080)).subclip(0, 3)
openning.write_videofile("op_v1.mp4",fps=5)
```
the output is

https://user-images.githubusercontent.com/30206254/117535918-ca0e9380-b02a-11eb-8750-cd51ecd38bfd.mp4

and it contains fade in animation.

#### Actual Behavior
On newest code(b5e5a30), the output is

https://user-images.githubusercontent.com/30206254/117535920-d0047480-b02a-11eb-9c85-6ab0b2c658b0.mp4

It doesn't have fade in animation.

#### Steps to Reproduce the Problem
```
from moviepy.editor import *
color_clip = ColorClip(size=(1920,1080),color=(223, 234, 240)).with_duration(5)
title_clip = TextClip("TestTitle", color='green', kerning=5, font_size=140).with_duration(8).with_start(0.5).crossfadein(2).with_position(('center',400))
openning = CompositeVideoClip([color_clip,title_clip], size=(1920,1080)).subclip(0, 3)
openning.write_videofile("op_v2.mp4",fps=5)
```

#### Specifications

  - Python Version: Python 3.9.1
  - Moviepy Version: 2.0.0.dev2(master)
  - Platform Name: Windows
  - Platform Version: Windows 10 x64

Or may there be other ways to achieve this function, thanks in advance for suggestions.

**Comment by ningzichun** [comment]
problem solved, https://github.com/Zulko/moviepy/pull/1552 works for me 👍

**Comment by LisaBBC** [comment]
@mondeja Can you let me know if you are still using crossfadein after the [#1552](https://github.com/Zulko/moviepy/pull/1552) bugfix or did you move to fadein? Using fadein I get the issue with there being a black mask showing up even though it should be using an alpha channel.
