### ISSUE TITLE
Export movie file dose not have sound.

### ISSUE THREAD

**Issue by sleepless-se** [Zulko/moviepy#1562]
I'm trying to set audio clip on image clip on Google Colab.

```
!pip install moviepy==1.0.3
from moviepy.editor import *
clip = ImageClip('sample.png')
audio_clip = AudioFileClip('sample.mp3')
clip = clip.set_duration(audio_clip.duration)
clip = clip.set_audio(audio_clip)
```

Audio and duration are returns value.

```
>>> clip.audio
<moviepy.audio.io.AudioFileClip.AudioFileClip object at 0x1241dbd30>
>>> clip.duration
4.18
```

However when I write as file.

```
clip.write_videofile('sample.mp4',fps=4)
```

I can't hear the sound. Are there any mistake on my code? I don't know how should I change my code... If you have any idea please help me!

My environment is

I had run same code on google colab, I got same problem. The video has 4.18 seconds, however it's no sound...

I downloaded audio file from [ondoku3](https://ondoku3.com/) and [youtube](https://yt1s.com/youtube-to-mp3/en2) as mp3

#### Specifications

 - Google Colab
 - Python 3.7.10
 - moviepy 1.0.3

Also I try on my Mac, the problem has happened.

 - MacOS 11.3.1
 - Python 3.9.5
 - moviepy 1.0.3

**Comment by sleepless-se** [comment]
I found QuickTime can't play sound. When I play VLC, I can hear the sound.

**Comment by SarvagyaVaish** [comment]
Same issue here. VLC has plays audio, but QuickTime doesn't. Any suggestions on how to fix?

> I found QuickTime can't play sound. When I play VLC, I can hear the sound.

**Comment by keikoro** [comment]
I'd assume it has to do with codecs used by the different apps?
