### ISSUE TITLE
ability to make a script that allow users to type path in terminal

### ISSUE THREAD

**Issue by Xellerate005** [Zulko/moviepy#1564]
after trying to make a script for MoviePy, im trying to figure out if theirs any way to give the user the ability before actually running the module and link it with the module, so it knows which path to choose, instead of going into the editor ever time

**Comment by mondeja** [comment]
Could you share an snippet of what are you exactly attempting to do?

**Comment by keikoro** [comment]
Closing due to a lack of response by OP.
