### ISSUE TITLE
Subtitle Color

### ISSUE THREAD

**Issue by MHumza3656** [Zulko/moviepy#1569]
Hello. We're allowed to pass a specific color for the subtitles but is it possible to change the color of a word after some time?
Example: "Hey what are you Doing?" -> "White color" -> Active for 5 seconds.... after 1-second change the color of "Hey" -> Black & rest remains white and so on. After 5 seconds all the text will be black this will be continued for all the subtitles.

I have gone to all the examples but they're mostly on TextClip & TextClip behaves differently than SubtitlesClip i.e. TextClip is defined initially & SubtitleClips are rendered during the creation of the clip & hence not accessible within code. Please let me know if there are certain libraries that I can look into, I think Gradient or Masking could help but again the issue is that SubtitleClip's Image frame cannot be altered within code as it is created after calling "write_videofile()"

**Comment by mondeja** [comment]
Subtitle support is being improved by #1512, but the removal of ImageMagick is blocking that (see discussion in #1472). I think that currently this is not possible.

**Comment by MHumza3656** [comment]
So, I was thinking that since the methods within moviepy `make_frame` & `make_mask_frame` are called everytime we create the frame. Simply fetch the objects in that frame by `findObjects` and now we have each letter's ImageClip object... but the issue here is that ImageClip is not allowing me to change the color it is its child TextClip that has the color attribute. If I can somehow change the color of the objects through FindObjects with my own timechecks I will be able to alter each frame right when its being fed.
What do you think? btw Amazing that you replied so quick. Thank you!

**Comment by MHumza3656** [comment]
an Update, I have used this feature of ffmpeg mentioned here: https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/subtitle/srt.html
To cater to my problem, thank you. Closing the issue
