### ISSUE TITLE
trying to resize a video and write it, but I got a TypeError.

### ISSUE THREAD

**Issue by yusukemiyazaki** [Zulko/moviepy#1570]
I'm going to resize a video clip with the following simple code.

`from moviepy.editor import *
from moviepy.video.fx.resize import resize

clip_orig = VideoFileClip("Movie.mp4")
clip = resize(clip_orig, (clip_orig.w/2, clip_orig.h/2))
clip.write_videofile("newMovie.mp4")`

I'm using macbook pro with macOS Mojave, anaconda and python3.8.

Unfortunately, the code doesn't work. 
I'm really happy if you can tell how I can fix the following TypeError:

**Error Message:**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-42-af5124acb6a9> in <module>
      4 clip_orig = VideoFileClip("Movie.mp4")
      5 clip = resize(clip_orig, (clip_orig.w/2, clip_orig.h/2))
----> 6 clip.write_videofile("newMovie.mp4")

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    229     """
    230     evaldict = dict(_call_=caller, _func_=func)
--> 231     es = ''
    232     for i, extra in enumerate(extras):
    233         ex = '_e%d_' % i

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/decorators.py in requires_duration(f, clip, *a, **k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, *a, **k)
     55 
     56 

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    229     """
    230     evaldict = dict(_call_=caller, _func_=func)
--> 231     es = ''
    232     for i, extra in enumerate(extras):
    233         ex = '_e%d_' % i

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/decorators.py in use_clip_fps_by_default(f, clip, *a, **k)
    135     return f(clip, *new_a, **new_kw)

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    229     """
    230     evaldict = dict(_call_=caller, _func_=func)
--> 231     es = ''
    232     for i, extra in enumerate(extras):
    233         ex = '_e%d_' % i

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/decorators.py in convert_masks_to_RGB(f, clip, *a, **k)
     20     if clip.ismask:
     21         clip = clip.to_RGB()
---> 22     return f(clip, *a, **k)
     23 
     24 @decorator.decorator

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/video/VideoClip.py in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)
    317     def write_images_sequence(self, nameformat, fps=None, verbose=True,
    318                               withmask=True, logger='bar'):
--> 319         """ Writes the videoclip to a sequence of image files.
    320 
    321         Parameters

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py in ffmpeg_write_video(clip, filename, fps, codec, bitrate, preset, withmask, write_logfile, audiofile, verbose, threads, ffmpeg_params, logger)
    206     logger = proglog.default_bar_logger(logger)
    207 
--> 208     if write_logfile:
    209         logfile = open(filename + ".log", 'w+')
    210     else:

~/opt/anaconda3/envs/control_jpv/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py in __init__(self, filename, size, fps, codec, audiofile, preset, bitrate, withmask, logfile, threads, ffmpeg_params)
     83             '-loglevel', 'error' if logfile == sp.PIPE else 'info',
     84             '-f', 'rawvideo',
---> 85             '-vcodec', 'rawvideo',
     86             '-s', '%dx%d' % (size[0], size[1]),
     87             '-pix_fmt', 'rgba' if withmask else 'rgb24',

TypeError: must be real number, not NoneType

**Comment by mondeja** [comment]
The example works with **master** branch, what version of moviepy are you using?

**Comment by yusukemiyazaki** [comment]
I appreciate your comment.

The version is 1.0.3. It's the latest, isn't it?
I installed it through "pip install moviepy".

**Comment by mondeja** [comment]
Could you try with v2.0.0.dev2? `python3 -m pip install moviepy==2.0.0.dev2`

**Comment by JorgeCeja** [comment]
@yusukemiyazaki the problem was solved for me by downgrading to `pip install moviepy==1.0.2`

**Comment by siu3334** [comment]
I am also receiving the same error, but downgrading fixed it. Not sure what was the breaking change in 1.0.3?!

**Comment by siu3334** [comment]
> I am also receiving the same error, but downgrading fixed it. Not sure what was the breaking change in 1.0.3?!

Turns out I had newer version of decorator pip package (>v5) than what is compatible for moviepy 1.0.3. Reinstalling moviepy installed correct version of decorator which fixed my issue.

**Comment by mondeja** [comment]
> Turns out I had newer version of decorator pip package (>v5) than what is compatible for moviepy 1.0.3 which was responsible for this typeerror. Reinstalling moviepy installed correct version of decorator which fixed my issue.

Decorator support for v5 has been added recently in #1565 but is not released yet.
