### ISSUE TITLE
AudioFileClip bombs on file read

### ISSUE THREAD

**Issue by ryanfox** [Zulko/moviepy#158]
Related: https://github.com/Zulko/moviepy/pull/157

I am trying to create an AudioFileClip from an mp3 file like so:

    clip = AudioFileClip('myaudio.mp3')

On line 275 of ffmpeg_reader.py, it looks like whether a file is video or not is determined by whether there is the string " Video: " anywhere in the result from ffmpeg.  At least in my case, this is throwing false positives.  This is the string that triggers it for me:

    u'    Stream #0:1: Video: png, 90k tbr, 90k tbn, 90k tbc'

I think the "video" is the album artwork.  Anyway, this causes ffmpeg_reader to think it's a video file instead of audio, and try to extract video dimensions.  Needless to say, those don't exist, and it throws an exception when it can't find them.

I am only interested in the audio data, not the png, whatever that is.  Is there a way to make ffmpeg_reader a little smarter about what kind of file it's looking at?

**Comment by Zulko** [comment]
This case is supposed to work. What's the error message exactly ?

**Comment by ryanfox** [comment]
MoviePy error: failed to read video dimensions in file 'myaudio.mp3'.
    Here are the file infos returned by ffmpeg:

And then a list of the information returned by ffmpeg.  I don't have the exact information available right now, I can get that later if it would be useful.

**Comment by Zulko** [comment]
Can you send a link to a file that doesn't work ?

**Comment by ryanfox** [comment]
Here it is: http://traffic.libsyn.com/geeknights/20150414.mp3  Warning: it's a 64mb file.

Also, I looked at the console printout a little more carefully.  It prints an error about "failed to read video dimensions" but doesn't crash there.  Later on, in line 305:

    float(line[match.start():match.end()].split(' ')[1])

`match` is None, so that line throws an error.
This is the value in `line`:

    u'    Stream #0:1: Video: png, 90k tbr, 90k tbn, 90k tbc'

**Comment by kerier** [comment]
I have encounter the same issue, AudioFileClip can't read mp3 file, but when i put a video file, it works fine! It's a very weird problem.

here is my code:
audio = AudioFileClip("test.mp3")

here is the except:
Traceback (most recent call last):
  File "testanimation.py", line 5, in <module>
    audio = AudioFileClip("test.mp3")
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/AudioFileClip.py", line 63, in __init__
    buffersize=buffersize))
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/readers.py", line 56, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/video/io/ffmpeg_reader.py", line 305, in ffmpeg_parse_infos
    result['video_fps'] = float(line[match.start():match.end()].split(' ')[1])
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by ryanfox** [comment]
I can take a crack at resolving this @Zulko, if you wouldn't mind.  If you're processing an audio file, there won't necessarily be video data, but there may be.  So in that case, it's not the end of the world (and worth crashing over) if there isn't a preview image or what have you.

**Comment by Zulko** [comment]
Thanks ! I'd be happy to review your PR.
