### ISSUE TITLE
Incorrect mp3 duration causing glitches when composing & concatenating videos

### ISSUE THREAD

**Issue by Troy76ch** [Zulko/moviepy#1621]
Hello! 
I have been trying to combine a series of audio and video inputs in a longer mp4 ouput. As a first step, I add the respective audio (aclip) to the video (vclip) to create what is referred to as avclip below.

...
avclip4=vclip4.set_audio(aclip4)
avclip5=vclip5.set_audio(aclip5)
...

as a prior step, to ensure that the video has the commensurate length, I use the .duration and .subclip commands to align audio and video:
aclip4dur=aclip4.duration
vclip4 = vclip4.subclip(0, aclip4dur)

Afterwards I use the concatenate method to join the segments: 
conc_AV= concatenate([avclip4, avclip5], method="chain")

The output sometimes has a glitch in that echos are heared at the end or the audio is cut off.

I suspect that the problem occurs because the duration of the mp3 calculated by movipy is sometimes inaccurate.  

For example, an mp3 file yields a moviepy duration of 27.99 seconds
The file explorer shows 25 seconds in the file properties.
Interestingly in an audio program like audacity the length appears to be 25.73 seconds.

As said, sometimes the duration measured is acutally too short, which makes it impossible to access the audio beyond that point. 

Has anyone had similar outcomes? Would love to hear of any possible workarounds. Appreciate any thoughts on this.

![moviepy](https://user-images.githubusercontent.com/64646946/123557719-d5f91500-d792-11eb-9734-e08ed9a7c370.JPG)
![fileProperties](https://user-images.githubusercontent.com/64646946/123557723-d8f40580-d792-11eb-9a53-2c18dd4b00bc.JPG)
![audacity](https://user-images.githubusercontent.com/64646946/123557725-db565f80-d792-11eb-85dd-f324e59f1d0e.JPG)

**Comment by asperduti** [comment]
try using wav files instead of mp3.

I have the same problem in kdenlive. They are different projects but both rely on FFmpeg.

**Comment by Troy76ch** [comment]
Thanks for the hint! Using wav instead of MP3 actually solved the problem.

**Comment by oliverdemus** [comment]
Hi, I have the same problem. Used WAV, but this didn't fix the problem. I have echoing at the end. 
My clips are 3.29 sec, 3.50 sec and 3.30 seconds. The final video after concatenating is 12 seconds and in the shorter videos I have longer echoing vs in the long one. 
The clips itself are without echoing. To combine them I used:
final_clip = concatenate_videoclips(clips, method='chain')
Any help or hints are appreciated.
