### ISSUE TITLE
.resize() causing cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-jhawztrk/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by Silreth** [Zulko/moviepy#1624]
Function runs fine on the majority of videos put through. 
However on one or two I get this error.

> Jul  3 02:00:43 ip-172-31-41-4 web: FileNotFoundError: [Errno 2] No such file or directory: '/var/app/current/1366F3C1C6_cropped_vertical_4_5.mp4'
Jul  3 02:04:59 ip-172-31-41-4 web: Internal Server Error: /sqs/
Jul  3 02:04:59 ip-172-31-41-4 web: Traceback (most recent call last):
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
Jul  3 02:04:59 ip-172-31-41-4 web: response = get_response(request)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
Jul  3 02:04:59 ip-172-31-41-4 web: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
Jul  3 02:04:59 ip-172-31-41-4 web: return self.dispatch(request, *args, **kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
Jul  3 02:04:59 ip-172-31-41-4 web: return bound_method(*args, **kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Jul  3 02:04:59 ip-172-31-41-4 web: return view_func(*args, **kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
Jul  3 02:04:59 ip-172-31-41-4 web: return handler(request, *args, **kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/eb_sqs_worker/views.py", line 65, in post
Jul  3 02:04:59 ip-172-31-41-4 web: result = task.run_task()
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/eb_sqs_worker/sqs.py", line 164, in run_task
Jul  3 02:04:59 ip-172-31-41-4 web: result = task_method(**self.task_kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/eb_sqs_worker/decorators.py", line 64, in <lambda>
Jul  3 02:04:59 ip-172-31-41-4 web: f.execute = lambda **kwargs: f(**kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Jul  3 02:04:59 ip-172-31-41-4 web: return view_func(*args, **kwargs)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/current/video/tasks.py", line 177, in video_intake
Jul  3 02:04:59 ip-172-31-41-4 web: render_style(active_style.title, clip, video)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/current/video/styles.py", line 49, in render_style
Jul  3 02:04:59 ip-172-31-41-4 web: cropped_horizontal_with_facecam_and_blurred_background_FULL(clip, video)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/current/video/styles.py", line 424, in cropped_horizontal_with_facecam_and_blurred_background_FULL
Jul  3 02:04:59 ip-172-31-41-4 web: headcam = final_clip.resize(width=width*0.8) 
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/fx/resize.py", line 152, in resize
Jul  3 02:04:59 ip-172-31-41-4 web: newclip = clip.fl_image(fl)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 490, in fl_image
Jul  3 02:04:59 ip-172-31-41-4 web: return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/Clip.py", line 136, in fl
Jul  3 02:04:59 ip-172-31-41-4 web: newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
Jul  3 02:04:59 ip-172-31-41-4 web: File "<decorator-gen-61>", line 2, in set_make_frame
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/decorators.py", line 14, in outplace
Jul  3 02:04:59 ip-172-31-41-4 web: f(newclip, *a, **k)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 644, in set_make_frame
Jul  3 02:04:59 ip-172-31-41-4 web: self.size = self.get_frame(0).shape[:2][::-1]
Jul  3 02:04:59 ip-172-31-41-4 web: File "<decorator-gen-11>", line 2, in get_frame
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/decorators.py", line 89, in wrapper
Jul  3 02:04:59 ip-172-31-41-4 web: return f(*new_a, **new_kw)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/Clip.py", line 93, in get_frame
Jul  3 02:04:59 ip-172-31-41-4 web: return self.make_frame(t)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/Clip.py", line 136, in <lambda>
Jul  3 02:04:59 ip-172-31-41-4 web: newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 490, in <lambda>
Jul  3 02:04:59 ip-172-31-41-4 web: return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/fx/resize.py", line 150, in <lambda>
Jul  3 02:04:59 ip-172-31-41-4 web: fl = lambda pic: resizer(pic.astype('uint8'), newsize)
Jul  3 02:04:59 ip-172-31-41-4 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/moviepy/video/fx/resize.py", line 16, in resizer
Jul  3 02:04:59 ip-172-31-41-4 web: return cv2.resize(+pic.astype('uint8'), (lx, ly),
Jul  3 02:04:59 ip-172-31-41-4 web: cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-jhawztrk/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Function looks like:

> clip = VideoFileClip(clip_dir)
    clip2 = clip.set_mask(mask) #assigns mask to highlight
    final_clip = clip2.crop(x_center=x, y_center=y, width=150, height=150)
    final__clip = final_clip.resize(width=width*0.8)

I suspect it has to do with the file having a dud frame in it, freaking out cv2 and causing the whole function to fail.
The cv2 error seems to be an incorrect directory on the image being resized but that shouldn't really be happening here.

Any ideas would be appreciated!

**Comment by HristoBuyukliev** [comment]
Can you try to resize with ints instead of floats? Or maybe resize wants both width AND height?

https://stackoverflow.com/questions/52162004/i-am-having-trouble-with-this-error-215assertion-failed-ssize-empty-in-fu 

Other stuff to try: are there special characters in the file name?  Is your webcam on?

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
