### ISSUE TITLE
Movie Studio Platinum can't open .mp4 generated by MoviePy

### ISSUE THREAD

**Issue by nicholaskross** [Zulko/moviepy#1627]
#### Expected Behavior
Successfully creates `.mp4` that VLC can play, with image and audio both present and working.
Can import the `.mp4` file into Movie Studio Platinum, it will load and play normally like other `.mp4` files.

#### Actual Behavior
Successfully creates `.mp4` that VLC can play, with image and audio both present and working.
However, when importing the `.mp4` file into Movie Studio Platinum, the file is missing video and has loud corrupted gibberish audio.

I've tried changing the mp4 codec and file formats used, with identical results.

(Encoding as mp4 _again_ using Handbrake, gives me a file that works in Movie Studio Platinum. Not sure how or why.)

#### Steps to Reproduce the Problem

```
from moviepy.editor import ColorClip, ImageClip, VideoFileClip, CompositeVideoClip, concatenate_videoclips

clip1bg = ColorClip((1920, 1080), (255, 255, 255), duration=3)
clip1 = ImageClip("myimage1.png", duration=3)

clip2bg = VideoFileClip("my_working_vid1.mp4").subclip(0, 3)
clip2 = ImageClip("myimage2.png", duration=3)

final_clip = concatenate_videoclips([CompositeVideoClip([clip1bg, clip1]), CompositeVideoClip([clip2bg, clip2])])

final_clip.write_videofile("output_clipbuilder_test_1.mp4")

final_clip.close()
clip1.close()
clip2.close()
clip2bg.close()
clip1bg.close()
```

#### Specifications

  - Python Version: 3.9.0
  - Moviepy Version: 1.0.3
  - Platform Name: Microsoft Windows
  - Platform Version:
  - Movie Studio Platinum Version: 15.0 (Build 157)

**Comment by Reen** [comment]
Have you tried adding `ffmpeg_params=['-vf', 'format=yuv420p']` to your call to `write_videofile`? For some resolutions or intpus FFmpeg decides to produce other pixel format. See https://trac.ffmpeg.org/wiki/Encode/H.264#FAQ

**Comment by nicholaskross** [comment]
I'm trying to do 1080 though... does this work for that?

**Comment by EbubekirUstalar** [comment]
I have a similar problem. In the Safari browser, I cannot open converted videos but other browsers don't have this problem. Should I open a new Issue?

**Comment by keikoro** [comment]
@EbubekirUstalar I think it'd be better to open a new issue and link this issue from there by mentioning it. The problem might be related, but it also might not be, and you're having the problem with a different piece of software than the OP.

**Comment by keikoro** [comment]
Closing due to lack of response by OP.
