### ISSUE TITLE
ffmpeg_extract_subclip is changing framerate eventually

### ISSUE THREAD

**Issue by dennymarcels** [Zulko/moviepy#1638]
I am processing lots of videos where I have to extract and view subclips with function `ffmpeg_extract_subclip`, where the only parameters I feed are starting time and ending time. All videos were recorded in the same conditions (same hardware and software, therefore some file extensions, codecs etc etc). Most clips are fine, nonetheless some clips have a higher frame rate from the original file, which is 30 fps. As a result, some clips are played accelerated and others don't even render (html). I could not find out what might be causing this. Is this a known issue?

#### Expected Behavior
All clips should have same fps as original video.

#### Actual Behavior
Some clips have a higher frame rate.

#### Specifications

  - Python Version: 3.7
  - Moviepy Version: 0.2.3.5
  - Platform Name: Google Colab
  - Platform Version: N/A

**Comment by keikoro** [comment]
Closing this issue as it's based on an old MoviePy version, so impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
