### ISSUE TITLE
Steps to get moviepy w/ImageMagick running on Heroku

### ISSUE THREAD

**Issue by CaseGuide** [Zulko/moviepy#1648]
I struggled a bit with getting moviepy to render a gif and textclip that uses ImageMagick and which works on Win 10 but not when deployed. I haven't verified it is working yet but figured I would document what I found here.

I first tried to add the `magick` binary in the root of my deployed repo but got an error that convert was prohibited from running the needed command.
I added [this buildpack](https://github.com/HiMamaInc/heroku-buildpack-imagemagick-heif) in my Heroku apps settings. 

I then got an error about using a named font,`convert: UnableToReadFont`, so I included the font file and ref'd it in `TextClip`. This seems to be working though I haven't fully verified yet. 

Environment Details:
 - heroku-20
 - python 3.6.17
 - moviepy 1.0.3

**Comment by IslamImtiaz** [comment]
bro i am using python 3.11
