### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by pingvinton** [Zulko/moviepy#1651]
After build docker container I try run tests with this command:
cd tests && python test_issues.py but get error that media files don't found
<img width="2061" alt="image" src="https://user-images.githubusercontent.com/68642472/131680481-e6c787ca-ec49-426a-b101-c919a4955740.png">

Catalog media with files are presented.

Thanks

**Comment by mondeja** [comment]
Please, see [CONTRIBUTING.md](https://github.com/Zulko/moviepy/blob/master/CONTRIBUTING.md). Tests must be executed from root using pytest.
