### ISSUE TITLE
[Feature Request] Zoom and Rotate

### ISSUE THREAD

**Issue by Netherdrake** [Zulko/moviepy#166]
I am wondering if the following features are planned for moviepy, or what would be the best way to implement them with the current version.

1.) Zoom
Kind of like resize, except that it would take a frame from the center (x/2, y/2) and scale it up to original resolution (zoom in)? http://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.resize.html#moviepy.video.fx.all.resize

2.) Rotate
The current rotate solution only flips the video by 90 degree increments. I am wondering of how would it be possible to rotate for any arbitrary amount (eg. 5 degrees).
http://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.rotation.html#moviepy.video.fx.all.rotation

Any tips are greatly appreaciated. Thank you for the awesome work done with the library.

**Comment by Zulko** [comment]
Rotating from any angle is already possible as long as you have PIL installed (see [the source](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/rotate.py)).

I'll add a zoom feature at some time, but for the moment what you are asking is basically crop+resize. So something like this (didn't check, I hope my math is correct):

    def zoom(clip, factor):
        c = (1-1.0/factor) / 2
        x_crop = int(c *clip.w)
        y_crop = int(factor * clip.h)
        return clip.crop(x_crop, y_crop, -x_crop, -y_crop).resize(clip.size)

    newclip = clip.fx(zoom, factor=2)

**Comment by Netherdrake** [comment]
Will the arbitrary angle rotate work with Pillow?


On Mon, May 4, 2015, at 10:15 AM, Zulko wrote:
> Rotating from any angle is already possible as long as you have PIL
> installed (see the source[1]).


> I'll add a zoom feature at some time, but for the moment what you are
> asking is basically crop+resize. So something like this (didn't check,
> I hope my math is correct):


> def zoom(clip, factor):
    c = (1-1.0/factor) / 2 x_crop = int(c *clip.w) y_crop = int(factor *
    clip.h) return clip.crop(x_crop, y_crop, -x_crop,
    -y_crop).resize(clip.size)

newclip = clip.fx(zoom, factor=2)
>
> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/rotate.py
  2. https://github.com/Zulko/moviepy/issues/166#issuecomment-98625621

**Comment by Zulko** [comment]
yes

**Comment by Netherdrake** [comment]
Upgrading to git version of moviepy fixed my PIL issue.

I implemented zoom as (hope its correct):
```
def zoom(clip, factor):
    return clip.crop(x_center=clip.w/2 , y_center=clip.h/2, width=int(clip.w*factor), height=int(clip.h*factor)).resize(clip.size)
```
Because I would get `ValueError: tile cannot extend outside image` otherwise, and I'm too lazy to try and figure out why or how to do it with 4 corner points.

Thank you :)
