### ISSUE TITLE
Audio and video out of sync

### ISSUE THREAD

**Issue by vishalchalana** [Zulko/moviepy#1660]
I am reading a video clip using VideoFileClip and write it back using write_videofile() and the audio and video go out of sync.

Here's how my code looks:
`clip = VideoFileClip('temp.mp4')`
`clip.write_videofile('temp1.mp4', fps=clip.fps, audio=True, audio_codec='aac', threads=4, logger='bar')`

Here's the link to the original video file:
https://drive.google.com/file/d/1GDcWRjtzxhuQXSqeW1yzaFyCeUMzTcdv/view?usp=sharing
and the output:
https://drive.google.com/file/d/1qnXpR6vz1S5VwQuVTff3Q-SUX8RJX3Z4/view?usp=sharing

BTW, also tried with default FPS and setting bitrate as the input bitrate. Same result.

The primary difference I see in the 2 files is that the original has variable frame rate and output has a constant frame rate. Could that be the reason for this issue? How can I correct this?

**Comment by xMasterPirated** [comment]
Hey, i have the same problem did you find a solution?

**Comment by vishalchalana** [comment]
My issue was indeed related to variable frame rate. I had to re-encode my input video to constant frame rate. I used ffmpeg using the following command.
`ffmpeg -i temp.mp4 -c:v libx264 -preset veryfast -crf 30 -c:a copy out.mp4`

You can also use handbrake cli
`handbrakecli --optimize -e x264 --encoder-preset veryfast -q 24 --cfr -r 30 --crop 0:0 -i temp.mp4 -o out.mp4`

Hope this helps.

**Comment by xMasterPirated** [comment]
¡It works! Thank you so much. i've been looking for a solution for weeks and you are the one who solved my problem. i really appreciate it.

**Comment by vishalchalana** [comment]
You are welcome! I am glad it worked out.
