### ISSUE TITLE
Facing issue while converting Video file to audio .

### ISSUE THREAD

**Issue by sandeshchand** [Zulko/moviepy#1669]
I am facing error while converting  video file to audio files. The video file has beed chunked into many small video files and then it is converted to audio files.But, while my program wants to read from the last audio file which is audioless, the program throw the below error:

OSError: MoviePy error: failed to read the first frame of video file video.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
How can i solve this error.

**Comment by keikoro** [comment]
@sandeshchand Have you tried updating (reinstalling) FFMPEG?

**Comment by keikoro** [comment]
Closing this issue due to a lack of response + lack of information needed to try to reproduce the problem.

Feel free to reopen it following our issue template if the issue persists after reinstalling FFmpeg.
