### ISSUE TITLE
headblur.py: ImportError to_fxfy

### ISSUE THREAD

**Issue by jjoe64** [Zulko/moviepy#167]
First, thanks for the great project!

I use the current codebase from github. when I want to start the headblur.py example, it throws an Input Error:

> $ python headblur.py
> 
> ```
> Traceback (most recent call last):
>   File "headblur.py", line 4, in <module>
>     from moviepy.video.tools.tracking import manual_tracking, to_fxfy
> ImportError: cannot import name to_fxfy
> ```

Please help

**Comment by bwagner** [comment]
Same here.

**Comment by plguhur** [comment]
The documentation from `manual_tracking` explains how the manual tracking should be done and reloaded:

```
    from moviepy.editor import VideoFileClip
    from moviepy.video.tools.tracking import manual_tracking
    clip = VideoFileClip("myvideo.mp4")
    # manually indicate 3 trajectories, save them to a file
    trajectories = manual_tracking(clip, t1=5, t2=7, fps=5,
                                       nobjects=3, savefile="track.txt")
    # ...
    # LATER, IN ANOTHER SCRIPT, RECOVER THESE TRAJECTORIES
    from moviepy.video.tools.tracking import Trajectory
    traj1, traj2, traj3 = Trajectory.load_list('track.txt')
    # If ever you only have one object being tracked, recover it with
    traj, =  Trajectory.load_list('track.txt')
```
