### ISSUE TITLE
outdated reference in docstring

### ISSUE THREAD

**Issue by keikoro** [Zulko/moviepy#1688]
https://github.com/Zulko/moviepy/blob/576fb1ab980ea53212675a775e059e1460488672/moviepy/audio/AudioClip.py#L19-L22

Just discovered this while looking at the file.

I'm assuming what's called `CompositeSoundClip` here should actually be `CompositeAudioClip`? I couldn't find any other references to `CompositeSoundClip`, incl. in (some of) the early history of this file.

(It's a bit confusing though because the other mention, `AudioFileClip`, sits in a different file.)

**Comment by mondeja** [comment]
Right, feel free to open a PR :+1:
