### ISSUE TITLE
Support for numpy 1.20+?

### ISSUE THREAD

**Issue by pmav99** [Zulko/moviepy#1692]
In the current master, numpy is required to be <=1.20
https://github.com/Zulko/moviepy/blob/552e94b710b648f88bfb4162974b59bc153b23c3/setup.py#L79

This was introduced with this commit: https://github.com/Zulko/moviepy/commit/646674c48017bca8bf1eaa576531a090d874a4ed

is there some problem with relaxing this constraint?

**Comment by keikoro** [comment]
This was solved for the current development version in #1732 -> closing.
