### ISSUE TITLE
Video having TextClip Formatting Error

### ISSUE THREAD

**Issue by thedevhack** [Zulko/moviepy#1696]
When i locally compile the video in my linux system using python it gives output as below

In this photo we can see the formatting of text is very good but in my next photo created by data from database is not formatted correctly
<img width="1388" alt="Screenshot 2021-11-24 at 11 37 06 AM" src="https://user-images.githubusercontent.com/47482315/143189398-a79e324a-d214-47d2-afee-460745a7ca57.png">

but when i get inputs from my website which is stored in a database and then the python code collects values from that database the ouput is like below WHY??????
<img width="1388" alt="Screenshot 2021-11-24 at 11 37 42 AM" src="https://user-images.githubusercontent.com/47482315/143189437-9c51243d-211c-4413-a5e6-3ef7a942924d.png">

**Comment by keikoro** [comment]
@thedevhack Please follow the template for new issues so other community members can better help you debug your problem.

**Comment by keikoro** [comment]
Closing this as we haven't heard back from you since I last commented. Feel free to reopen the issue following the issue template.
