### ISSUE TITLE
Weird output of TextClip saved as png

### ISSUE THREAD

**Issue by anikfal** [Zulko/moviepy#1698]
#### Code
```
from moviepy.editor import *
txt_clip = TextClip(txt="Hello There", fontsize=66, color="yellow", bg_color="blue")
txt_clip.save_frame("out_clip.png")
```

#### Output Image
Not a real image, but just a blue line with yellow segments. It looks as if the image has width, but not height!
![out_clip](https://user-images.githubusercontent.com/11738727/143921418-a205484d-3e94-41ed-ad2f-f9011c8f0911.png)

#### Specifications

  - Python Version: 3.9.7
  - Moviepy Version: 1.0.3
  - Platform Name: Fedora
  - Platform Version: 33

**Comment by selentium** [comment]
Doesn't reproduce for me. My specifications are:

- Python Version: 3.8.10
- Moviepy Version: 1.0.3
- Platform: Ubuntu 20.04

**Comment by anikfal** [comment]
I can reproduce it with your specifications. The only difference is the OS, which is Fedora.

**Comment by anikfal** [comment]
The code works without problem by the new specifications bellow:
- Python Version: 3.10.5
- Moviepy Version: 1.0.3
- OS: Fedora-36

**Output Image:**
![out_clip](https://user-images.githubusercontent.com/11738727/206903722-8105db2c-4d91-4bf4-bbeb-703240330adf.png)
