### ISSUE TITLE
module 'sys' has no attribute 'setcheckinterval'

### ISSUE THREAD

**Issue by hssnmnr** [Zulko/moviepy#1700]
I'm getting this error in function call VideoFileClip().audio.write_audiofile().
I'm not importing or using sys library anywhere in my code.

=> The error occur when i deploy my python function to azure. (Doesn't get error in local environment)

```
from moviepy.editor import VideoFileClip


def convert_video_to_audio_moviepy(video_file, output_ext="wav"):
    filename, ext = os.path.splitext(video_file)
    clip = VideoFileClip(video_file)
    clip.audio.write_audiofile(f"{filename}.{output_ext}")

    return f"{filename}.{output_ext}"
```

#### Expected Behavior
Convert video file to wav

#### Actual Behavior
Error at function call clip.audio.write_audiofile().

#### Steps to Reproduce the Problem

Deploy the function to azure functions.

#### Specifications

  - Python Version: 3.9.7
  - Moviepy Version: 1.0.3
  - Platform Name: Azure function
  - Platform Version: latest

**Comment by hssnmnr** [comment]
Guess what I didn't had the latest version of python in azure function app, I resolve the issue by upgrading azure function python version to 3.7,.

**Comment by elrondfeng** [comment]
@hssnmnr I have the same issue in my azure function and I'd like to follow your solution here. I am a little confused, you were using python 3.97 and you just downgraded it to 3.7 ? is that the solution?

**Comment by mondeja** [comment]
I suppose that the error is being raised from a really old version of **tqdm**, which is dependency of moviepy. I don't know because you didn't shared the complete traceback. This error was fixed in https://github.com/tqdm/tqdm/commit/2189a2b291c1b550fe35f54267d088083b737712 so the upgrade to a greater compatible version should fix the issue.

**Comment by elrondfeng** [comment]
thanks a lot! I updated the tqdm to a later version and the error is gone
