### ISSUE TITLE
formats supported

### ISSUE THREAD

**Issue by AbRamazani** [Zulko/moviepy#1706]
Hello!
Excuse me, which formats does Moviepy support?
Does Moviepy support all the formats in this [list](https://en.wikipedia.org/wiki/Video_file_format#List_of_video_file_formats)?
Thanks for answer!!

**Comment by AbRamazani** [comment]
@Zulko

**Comment by keikoro** [comment]
@AbRamazani Please don't tag maintainers into newly opened issues which can easily be solved by reading the docs. If you have a look at the repo – the README, the backlog of open issues and PRs – it should be clear that we're low on contributor resources, so CCing folks into low priority issues is both pointless and also a bit rude.

The [Download and Installation page](https://zulko.github.io/moviepy/install.html), literally the first page of the MoviePy docs, states:
> MoviePy depends on the software FFMPEG for video reading and writing.

Following from that, you'll have to check the FFMPEG docs to find out which formats are currently supported.
