### ISSUE TITLE
Video resized after converting from .mkv to .mp4 in python

### ISSUE THREAD

**Issue by ghost** [Zulko/moviepy#1711]
I was using moviepy to convert a video from .mkv to .mp4, however the resolution of each has been changed. Is there any way I can have another command that converts it back to the previous size (in the .mp4 file)?

Attached images show the changes (first is the original file, the second is the result file)
![2022-01-08 (1)](https://user-images.githubusercontent.com/95125858/148646155-f78d9638-1cb0-4233-8b61-50720974ae6b.png)
![2022-01-08 (3)](https://user-images.githubusercontent.com/95125858/148646156-29ef83eb-ffa6-40f9-9b51-00b7d11e2a1d.png)
:

**Comment by keikoro** [comment]
@JamesJoynsonEllis Please use the issue template when creating new issues + provide code snippets (and, ideally, example files) so others can try to reproduce the issue.

**Comment by keikoro** [comment]
Closing as the user never responded and now doesn't exist anymore.
