### ISSUE TITLE
SyntaxError: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by lalten** [Zulko/moviepy#1715]
The line
https://github.com/Zulko/moviepy/blob/db19920764b5cb1d8aa6863019544fd8ae0d3cce/moviepy/video/io/sliders.py#L61

causes a SyntaxError warning in my code:
```
File "/worker/build/xxx/root/bazel-out/k8-opt/bin/xxx/xxx/xxx/xxx/tests/xxx.runfiles/site-packages_pypi__xxx__moviepy_1_0_3/moviepy/video/io/sliders.py", line 61
    if event.key is 'enter':
       ^
SyntaxError: "is" with a literal. Did you mean "=="?
```

**Comment by keikoro** [comment]
@lalten Please use the issue template when opening new issues. I'd ask you to amend your issue with the missing information. Thanks.

**Comment by keikoro** [comment]
Closing this due to a lack of response. Feel free to reopen the issue when you can provide the info that was requested.

**Comment by NandhaxD** [comment]
[Bot] /app/.heroku/python/lib/python3.12/site-packages/moviepy/video/io/sliders.py:61: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if event.key is 'enter':


This the full info from heroku but I have no idea when check the repo it's actually `==` and saw this issues. I will. Try to install the repo rather installing package from pip
