### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Pronk99** [Zulko/moviepy#172]
Trying to install "videogrep", I get the following error...

Exception AttributeError: "FFMPEG_VideoReader instance has no attribute 'proc'" in > ignored

It occurs while script is trying to split video when matched word found.

Occurs in library "moviepy".

Thanks.

**Comment by Zulko** [comment]
C

**Comment by Pronk99** [comment]
PS C:\videogrep> python videogrep.py --input 123.mp4 --search 'Many'
123.srt
[+] Searching for video file corresponding to '123.srt'.
[+] Found '123.mp4'.
[+] Search term 'Many' was found in 1 places.
[+] Creating clips.
88.416 to 331.041:      Many.
Traceback (most recent call last):
  File "videogrep.py", line 261, in <module>
    videogrep(args.inputfile, args.outputfile, args.search, args.searchtype, arg
s.maxclips, args.padding, args.test, args.randomize, args.sync)
  File "videogrep.py", line 241, in videogrep
    create_supercut(composition, outputfile, padding)
  File "videogrep.py", line 86, in create_supercut
    videofileclips = dict([(f, VideoFileClip(f)) for f in all_filenames])
  File "c:\python27\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 5
8, in init
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "c:\python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 1
7, in init
    infos = ffmpeg_parse_infos(filename, print_infos)
  File "c:\python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 2
10, in ffmpeg_parse_infos
    if "No such file or directory" in lines[-1]:
IndexError: list index out of range
Exception AttributeError: "FFMPEG_VideoReader instance has no attribute 'proc'"
in <bound method FFMPEG_VideoReader.__del__ of <moviepy.video.io.ffmpeg_reader.F
FMPEG_VideoReader instance at 0x04D8B580>> ignored
PS C:\videogrep>

**Comment by Pronk99** [comment]
Currently running on Windows Hyper-V Server 2012 R2, without a GUI.

**Comment by tburrows13** [comment]
Likely no longer relevant
