### ISSUE TITLE
Documentation mispells argument name for write_videofile

### ISSUE THREAD

**Issue by Arkangus** [Zulko/moviepy#1721]
In the v: improve-docs version of the documentation, the write_videofile method has a mispelled argument. It is not ```pixel_format``` but ```pix_fmt```.

https://moviepy-tburrows13.readthedocs.io/en/improve-docs/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.VideoClip.write_videofile

#### Specifications

  - Python Version: 3.9
  - Moviepy Version: 2.0.0.dev2
  - Platform Name: Windows

**Comment by keikoro** [comment]
I'm not sure where the version of the docs you are referring to is even referenced/linked to from our side – not doubting that we set it up, I just don't remember where/when. Was going to ask you if you would send a PR to fix it, but I don't know where exactly to point you to (for this reason).

**Comment by Arkangus** [comment]
I'm glad it's not just me, I tried to find the reference but I've been unable to !
I am well aware of the fact that it is a development version, so it shouldn't matter so much I guess
Just letting you know that I found another issue with the documentation, as VideoClip.resize() does not exist in version 2.0.0.dev2 but is referenced here https://moviepy-tburrows13.readthedocs.io/en/improve-docs/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.VideoClip.resize

**Comment by keikoro** [comment]
I meant this version of the docs in general, where are we (currently) linking to it? Without a source, it's impossible to say if any of the issues with it – or corrections to them – are even relevant at this point.
