### ISSUE TITLE
How to match the speed of a gif after converting to a video

### ISSUE THREAD

**Issue by noppanit** [Zulko/moviepy#173]
I'm using moviepy to convert a gif to a video. The video is converted successfully. However, in some gif, the playback in some video is too fast resulting the video to be choppy when looping playback.

This is the example gif.

![sabradanielle-tumblr-com](https://cloud.githubusercontent.com/assets/638379/7821415/894ff0f8-03bc-11e5-9b19-0758d22f7984.gif)

This is the code I use to convert.

```
video = VideoFileClip(gif_path)
video.write_videofile(filename, fps=15)
```

**Comment by noppanit** [comment]
I tried with FPS 15 but it doesn't change anything.

**Comment by Zulko** [comment]
have you tried with fps=30, or better with fps=video.fps ? What version of moviepy are you using ?

**Comment by noppanit** [comment]
That solves the problem. I'm using version 0.2.2.8
