### ISSUE TITLE
VideoFileClip getting wrong fps

### ISSUE THREAD

**Issue by arceus-jia** [Zulko/moviepy#1731]
#### my code
    filepath = '/tmp/tmp.mp4'
    vc = VideoFileClip(filepath)
    print ('vc.fps', vc.fps)

#### Expected Behavior
ffmpeg -i /tmp/tmp.mp4 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p"
53.12

#### Actual Behavior
vc.fps 90000.0

#### Steps to Reproduce the Problem

the video url is 
https://superboostaa.s3.us-west-2.amazonaws.com/screen-20220309-180051-1646873790786_1646886001442.mp4

When I use vc.subclip to process the video, it processes up to 90,000 frames and throws a lot of warnings

#### Specifications

  - Python Version:  3.8.10
  - Moviepy Version: 1.0.3
  - Platform Name: ubuntu 18.04
  - Platform Version: 5.4.0-90-generic #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by arceus-jia** [comment]
In fact, this may actually be a problem with ffprobe, when I use ffprobe to get r_frame_rate, I also get 90000/1, but can moviepy get the correct fps some other way?

**Comment by mondeja** [comment]
This is fixed in master branch.
