### ISSUE TITLE
Converting mp4 to ogv error in bitrate

### ISSUE THREAD

**Issue by noppanit** [Zulko/moviepy#174]
I'm trying to convert mp4 to ogv and I got this error

```
16:56:55 web.1    | MoviePy error: FFMPEG encountered the following error while writing file /var/folders/c9/q6q270nn7pjbpv24w9rtdmr40000gn/T/a676055a8a13c907fe3bdedde85027.ogv:
16:56:55 web.1    |
16:56:55 web.1    |  Invalid encoder type 'libvorbis'
16:56:55 web.1    |
16:56:55 web.1    |
16:56:55 web.1    | The video export failed, possibly because the bitrate you specified was too high or too low for the video codec.
```

Is there anyway i could solve or debug this?

**Comment by Zulko** [comment]
can you paste your code ?

**Comment by noppanit** [comment]
Sorry. Here's my code

```
                video_from_mp4 = VideoFileClip(mp4_file)
                video_from_mp4.write_videofile(filename_to_convert, codec=codec[ext])
```

**Comment by noppanit** [comment]
The codec I choose is `libvorbis`

**Comment by noppanit** [comment]
Here's my mp4 file https://dl.dropboxusercontent.com/u/27106646/a676055a8a13c907fe3bdedde85027.mp4

**Comment by Zulko** [comment]
I think the problem is that libvorbis is for audio files. Try:
    
     video_from_mp4.write_videofile(filname_to_convert, codec='libtheora')

If you want the sound to be ogg:

    
     video_from_mp4.write_videofile(filname_to_convert, codec='libtheora', audio_codec='libvorbis')

**Comment by noppanit** [comment]
Thanks for all your fast reply. I really appreciate it. 

However, I have another problem if I encode the video with codec `mpeg4` it works on Safari but not on Chrome and `ogv` with codec `libtheora` doesn't work on FF. Do you have any suggestions that I can have all the videos to work for `<video>` tag in HTML5?

**Comment by kerstin** [comment]
@noppanit As this is quite old: did you manage to solve the problem? Did Zulko's tips help you solve the original problem?

**Comment by noppanit** [comment]
It did solve my original problem. Thanks! I'm closing the issue now.
