### ISSUE TITLE
About Chinese support in TextClip

### ISSUE THREAD

**Issue by Danee-wawawa** [Zulko/moviepy#1746]
Hi, thank you for your work.
When I use TextClip to process Chinese, I have encountered a problem that the Chinese display will appear garbled.
The code is as following:
# -*- coding: utf-8 -*-
#encoding=utf-8
from moviepy.editor import *

txt_clip1 = TextClip("happy~",font = 'SimHei.ttf',fontsize=100,color='white')
txt_clip2 = TextClip("我爱你中国！asd123!@#",font = 'SimHei.ttf',fontsize=100,color='red')

txt_clip1 = txt_clip1.set_pos('center').set_duration(10)
txt_clip2 = txt_clip2.set_pos('bottom').set_duration(10)
cvc = CompositeVideoClip( [txt_clip1.set_pos('center'),txt_clip2], size=(1280,720))
cvc.write_videofile("test.mp4",fps = 24)

The test.mp4 is like following:
![image](https://user-images.githubusercontent.com/24379250/161380837-0215e4d3-da76-4468-810c-4dd1da4da511.png)

Looking forward to your answer, thank you very much.

**Comment by Danee-wawawa** [comment]
My running environment is linux.

**Comment by Jaren1907** [comment]
How did you solve it, I also encountered the same problem. Thanks!

**Comment by zhongmiyu99** [comment]
How did you solve it, I also encountered the same problem. Thanks!
