### ISSUE TITLE
OSError: [Errno 8] Exec format error when ran in terminal

### ISSUE THREAD

**Issue by Python-dev-1** [Zulko/moviepy#1748]
i had a script on a raspberry pi that due to other dependencies needed to be ran using sudo but whenever i run it there i get this error but  when i run it in a code editor it works fine (without the other package working)

**Comment by keikoro** [comment]
We'll need a lot more info than that. Please use the template for submitting new issues and provide code samples. Closing this for now, but feel free to reopen the issue once you've edited it.
