### ISSUE TITLE
Read Subtitles file in Hebrew.

### ISSUE THREAD

**Issue by o-buly** [Zulko/moviepy#1752]
I'm using Moviepy in my python code and i have a problem with the subtitles tool, I searched on the internet and also try to read your documentation and there is a solution with encoding ='utf-8'.
When I try to write this line in my code, it's not recognized :
![not recognized](https://user-images.githubusercontent.com/44566428/162605126-a7761950-8c8f-4a03-9677-f015138df28c.jpg)
The error i get is an unicode error :
![error](https://user-images.githubusercontent.com/44566428/162605135-1794820e-4765-4306-a191-eb21592601b8.jpg)
My code :
![code](https://user-images.githubusercontent.com/44566428/162605149-e5e4c1ae-28bb-4c55-9d78-ffa07c28fbaa.jpg)

Does Moviepy not support encoding anymore?
Any other suggestions? Please, I need help, it's urgent !

**Comment by keikoro** [comment]
Hi, since other people have raised similar issues but I haven't seen anyone say anything like this:
> Does Moviepy not support encoding anymore?

Could you confirm this used to be supported? Do you know which version you last successfully encoded Hebrew subtitles with? Thanks.

**Comment by o-buly** [comment]
Hello and good morning,

i updated to  __version__ = "2.0.0.dev1", and it was fixed.
In the previous version (not dev), the encoding is not supported (the code
doesn't recognize the "encoding=''" parameter -> the function don't receive
3 parameters, only 2(the path and the generator)).


If you have further questions please feel free to contact me.

Thank you for paying attention to my request/question/mail.
Have a great day!


‫בתאריך יום ג׳, 26 באפר׳ 2022 ב-20:48 מאת ‪k‬‏ ***@***.***
‬‏>:‬

**Comment by keikoro** [comment]
I see, what you are referring to is an upcoming version, not a previous one. This new release has (intermittently) been worked on for a while now but is not production-ready yet.
