### ISSUE TITLE
CPU is loaded less than 20%

### ISSUE THREAD

**Issue by Daloshka** [Zulko/moviepy#1756]
You can add multi-threading

**Comment by Daloshka** [comment]
![image](https://user-images.githubusercontent.com/36123350/163677984-9de34cd7-8a55-4f7d-b47f-f622fc55a11a.png)

**Comment by Daloshka** [comment]
Sorry 
![image](https://user-images.githubusercontent.com/36123350/163678047-9af86dbe-08a7-474d-ab23-5bc63cf636e1.png)

**Comment by keikoro** [comment]
Please [see this comment](https://github.com/Zulko/moviepy/issues/1089#issuecomment-686136473) for (potential future) multithreading support.
