### ISSUE TITLE
About the realization of the text effect— the color of the text changes over time.

### ISSUE THREAD

**Issue by Danee-wawawa** [Zulko/moviepy#1758]
Hi, thank you for your work. 
I want to achieve the following text effects, for example, every 0.5 seconds, the color of the next text changes.
![image](https://user-images.githubusercontent.com/24379250/163787838-d0cd90fb-1ca8-47c1-998b-fac1be17d1e1.png)

Can someone help me？ Thanks you very much.

**Comment by keikoro** [comment]
MoviePy does not come with a built-in way to achieve this, please see existing issues #1123 and #1228 for more information on multi-coloured text.
