### ISSUE TITLE
hanging when using .mpg extension (but not .mp4 or others)

### ISSUE THREAD

**Issue by JohnLunzer** [Zulko/moviepy#176]
I'm running moviepy-0.2.2.11 with Python 2.7.8 with IPython 3.0.0 (in Spyder) on Windows 7 64-bit

Doesn't really matter what I do to the composite clip or how long the clip is. It's just this piece of code:

``` python
final.write_videofile('output.mpg', codec='libx264')
```

If my output filename has .mpg it hangs, if it has .mp4 it doesn't. Very strange. I've tried a couple other codec's as well ("h264", "mpeg4"). 

Is this expected behavior or is something weird going on with ffmpeg?

Anyway, it's not too big of a deal. I just do a shutil.move at the end of the script to change the filename over to ".mpg".

**Comment by kerstin** [comment]
@JohnLunzer Could you check if this is still a problem?
