### ISSUE TITLE
Moviepy error when I run the python app where the pyinstaller created -  AttributeError: module 'moviepy.audio.fx.all' has no attribute 'audio_fadein'.

### ISSUE THREAD

**Issue by lerry30** [Zulko/moviepy#1762]
![Capture](https://user-images.githubusercontent.com/96895997/166130925-8753878d-1edc-417b-bbd7-145ab0e3135a.JPG)

**Comment by keikoro** [comment]
Please edit the issue to include the info we ask for in the issue template, thanks.

**Comment by keikoro** [comment]
PS: Closing this until this is fixed.
