### ISSUE TITLE
Retirar barra de progresso do "write_audiofile"

### ISSUE THREAD

**Issue by Thomaz-Castro** [Zulko/moviepy#1772]
estou tendo um problema (https://github.com/marcelotduarte/cx_Freeze/issues/1497#issuecomment-1129039812), e acho que é por causa da barra de progresso do "write_audiofile", queria saber como remove-la ou fazer não aparecer no console

**Comment by keikoro** [comment]
Since the majority of users of this project use English/share English as common language, you are more likely to get responses if you provide an English version of your question (putting it through Google Translate might be sufficient).

**Comment by manuelthomsen** [comment]
add "logger=none" to write_videofile ( ). Like so:

`finalVideo.write_videofile(
        "Renders/" + globalConfig["render_name"] + ".mp4",
        fps=globalConfig["video_fps"],
        preset="ultrafast",
        codec="libx264",
        audio_codec="aac",
        logger=None,
    )`
