### ISSUE TITLE
Syntax error(s) in moviepy/decorators.py

### ISSUE THREAD

**Issue by abulgher** [Zulko/moviepy#1789]
While I was creating a videoclip from a list of static images, I received a syntax error in the decorators.py file. The argument function f was mispelled func. Here below the two code snippets with the bug commented out and with the proposed correction. 

```
def preprocess_args(fun,varnames):
    """ Applies fun to variables in varnames before launching the function """
    
    def wrapper(f, *a, **kw):
        #BUGFIX
        #names = inspect.getfullargspec(func).args
        names = inspect.getfullargspec(f).args
        new_a = [fun(arg) if (name in varnames) else arg
                 for (arg, name) in zip(a, names)]
        new_kw = {k: fun(v) if k in varnames else v
                 for (k,v) in kw.items()}
        return f(*new_a, **new_kw)
    return decorator.decorator(wrapper)

```
And here:

```
@decorator.decorator
def use_clip_fps_by_default(f, clip, *a, **k):
    """ Will use clip.fps if no fps=... is provided in **k """
    
    def fun(fps):
        if fps is not None:
            return fps
        elif getattr(clip, 'fps', None):
            return clip.fps
        raise AttributeError("No 'fps' (frames per second) attribute specified"
                " for function %s and the clip has no 'fps' attribute. Either"
                " provide e.g. fps=24 in the arguments of the function, or define"
                " the clip's fps with `clip.fps=24`" % f.__name__)

    #BUGFIX
    #names = inspect.getfullargspec(func).args[1:]
    names = inspect.getfullargspec(f).args[1:]
    
    new_a = [fun(arg) if (name=='fps') else arg
             for (arg, name) in zip(a, names)]
    new_kw = {k: fun(v) if k=='fps' else v
             for (k,v) in k.items()}

    return f(clip, *new_a, **new_kw)
```
#### Expected Behavior
Run without problems

#### Actual Behavior
Returned syntax errors

#### Steps to Reproduce the Problem
Build a video clip from a list of images

#### Specifications

  - Python Version: 3.9.7
  - Moviepy Version: 1.0.3
  - Platform Name: Win
  - Platform Version: 10 Home

**Comment by keikoro** [comment]
@abulgher Would you consider submitting a PR to fix the error?

**Comment by abulgher** [comment]
Funny enough, the package I have downloaded from conda is different compared to the one distributed here as v1.0.3.
In the github version the bug is already fixed. 
You can close this issue and maybe verify what is going wrong with the package generation.

**Comment by keikoro** [comment]
@abulgher Generally, our main branch here will be more recent than what's available pre-packaged, but interesting that the two versions with the same version no. should differ. Thanks for the update, in any case!
