### ISSUE TITLE
Mp4 file audio alignment issue between 'mpeg4 codec' and 'libx264' codec and 'aac' audio_codec

### ISSUE THREAD

**Issue by jltchiu** [Zulko/moviepy#1805]
#### Expected Behavior
I am clipping a video and then export the clip using write_videofile to write to a mp4 file.

When the codec='libx264' and audio_codec='aac'
The alignment between video and audio is perfect
I expect the proper alignment will also happen when codec='mpeg4 ' and audio_codec='aac'

#### Actual Behavior

When using codec='mpeg4 ' and audio_codec='aac', the exported mp4 file will have misalignment between video and audio. At the beginning of the exported video both seems aligned yet as the video goes the audio video become very apparently not aligned. The audio sounds the same, yet the video will be delayed comparing with audio.

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release). Please also make sure to update the issue with the code you used (with proper code formatting), any relevant outputs or error logs, and the specs we ask for in our issue templates.
