### ISSUE TITLE
CompositeVideoClip of CompositeVideoClips does not provide expected behavior.

### ISSUE THREAD

**Issue by davidbernat** [Zulko/moviepy#1808]
#### Expected Behavior

```video = CompositeVideoClip([background, overlays])```

When ```background``` and ```overlays``` are both ```CompositeVideoClip``` objects, the resulting new composite will often fail to contain the video elements of the latter. If, instead, the new composite is created using this code, the expected result occurs; however, under-the-hood functionality of true composites may be missed.

``` video = CompositeVideoClip(background.clips + overlays.clips)```

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
