### ISSUE TITLE
moviepy wrong frames at the end of the video

### ISSUE THREAD

**Issue by alcarazolabs** [Zulko/moviepy#1825]
Hi dear, I started to use this library with python, however after concatenate 3 videos, two of them with more than 100MB of weight I got a final video of more than of one 1GB and the worse of it was that I got a bad video, all was fine at the begining but at the end of the video showed wrong frames like the image of below:

![image](https://user-images.githubusercontent.com/7144988/188907751-cc29e6c0-b011-46db-a498-e43135bdea36.png)
https://www.youtube.com/shorts/aWeoii8kdXM
I have tested this four ways

```
result_clip.write_videofile(path_output, codec="libx264")
```

```
result_clip.write_videofile(path_output, codec="mpeg4")
```

```
result_clip.write_videofile(path_output, codec="libx264", fps=24)
```

```
result_clip.write_videofile(path_output, codec="mpeg4", fps=24)
```
However I'm getting the same result, I would like to know how fix this problem.
What should I do? I got this result after generating a .exe of my app.py with pyinstaller, is this the problem?
however should work fine.

I test two versiones:
pip install moviepy 1.0.3
pip install moviepy==2.0.0.dev2

thanks.

**Comment by keikoro** [comment]
I think we'll need to see more of your code.

**Comment by alcarazolabs** [comment]
> I think we'll need to see more of your code.
```
path_output = video_path_output + '/'+file_name+'.mp4'
result_clip = concatenate_videoclips(videos_array)
result_clip.write_videofile(path_output, codec=selected_codec, fps=24)
```
The problem was because a video had a different resolution, two videos where 1280x720 and last video 1152x720.
I fixed this problem doing:
`VideoFileClip(path, target_resolution=(1920,1080))`
of this way all the videos now has a fixed resolution.

I don't know if we could use another solution but this worked.
