### ISSUE TITLE
AttributeError: 'FramesMatches' object has no attribute 'write_videofile'

### ISSUE THREAD

**Issue by otheivan** [Zulko/moviepy#1827]
Hi,

I'm trying to make some looping clips with moviepy, I can get to work for gifs but not mp4. This is probably a simple issue and I'm overlooking something. I keep getting the error:
```
Traceback (most recent call last):
  File "S:\makegifs.py", line 35, in <module>
    selected_scenes.write_videofile(clip + ".mp4", name)
AttributeError: 'FramesMatches' object has no attribute 'write_videofile'
```
Full code for makegifs.py:

```
import os
import sys

import moviepy.editor as mp
from moviepy.video.tools.cuts import FramesMatches

if len(sys.argv) != 2:
    print("makegifs.py <video file>")
    sys.exit(1)

clip = mp.VideoFileClip(sys.argv[1])
name = os.path.splitext(os.path.basename(sys.argv[1]))[0]


scenes = FramesMatches.from_clip(clip.resize(height=144), 5, 2) 
scenes.save("matches-"+name)


scenes.load("matches-"+name)

selected_scenes = scenes.select_scenes(2, 0.5, 4, 0.5)
os.mkdir(name)
selected_scenes.write_videofile(clip + ".mp4", name) 

```
 
Any ideas? And please assume I'm an idiot, not to good with python.

**Comment by mondeja** [comment]
`FramesMatches.from_clip` does not returns a clip object, but an instance of `list`. See the [documentation of the function](https://github.com/Zulko/moviepy/blob/1393889d5bc29c8b7c4ed45bca4736d6dfdfad8d/moviepy/video/tools/cuts.py#L198-L241).
