### ISSUE TITLE
Loading video from url

### ISSUE THREAD

**Issue by nshung** [Zulko/moviepy#185]
Hi
thanks for such a great library.

I am wondering whether it is possible to load video from url(for example: https://example.com/video.mp4) instead of loading from file that is saved on the machine. 

What I want is..

url = "https://example.com/video.mp4"
clip = VideoFileClip(url)

and then edit it on the fly on server. Is this possible?

**Comment by Red5d** [comment]
A video could potentially be loaded from a remote source, but if you want to save the edits, the edited version would have to be saved locally. What's your use case?

**Comment by kerstin** [comment]
I'm closing this issue due to age + lack of further activity (the question asked was answered).
