### ISSUE TITLE
Team please share more communication about the project, v2 release, roadmap, focus, end of the support ...

### ISSUE THREAD

**Issue by Erim32** [Zulko/moviepy#1851]
Hello! Team could you please use this issue to communicate about the project, and your vision.
For us, v2.0.0 in beta since 2 years, no updates since 2 years, could you please communicate more about the project.

Great work, the project is awesome, and we hope a great future to moviepy.
Regards

**Comment by keikoro** [comment]
Hi, I'm closing your issue in favour of #1874, which also got pinned to the top of the issues tab.
