### ISSUE TITLE
Broken image on PyPI

### ISSUE THREAD

**Issue by techtonik** [Zulko/moviepy#187]
https://pypi.python.org/pypi/moviepy

points to https://raw.githubusercontent.com/Zulko/moviepy/master/docs/demo_preview_small.jpeg which was removed from repository

**Comment by Zulko** [comment]
I noticed :) That will be fixed next time I push a version on PyPI.

**Comment by techtonik** [comment]
PyPI also has a web interface for fixing that info. =)

**Comment by kerstin** [comment]
Thanks for the info, @techtonik.
This looks fine again in the current version –> closing.
