### ISSUE TITLE
Corrupted video(orjinal video file) bypass

### ISSUE THREAD

**Issue by FisherWooD** [Zulko/moviepy#1889]
Hi,

some video files Corrupted different duration. example: 20 min video corrupted min 5-8 min or 13-14. 

`video = VideoFileClip(inputfile)
duration = video.duration   
  
final= video.fx( effect) # special effect.
  
final.write_videofile(outputfile)`

My progress freeze when corrupted frames. and not give any error only freeze.

3 question
1- any config for bypass corrupted frames?
2- if not possible bypass corrupted frames. How can I check corrupted frame speedly without encoding?
3- if not possible How can I add timeout write_videofile?

**Comment by keikoro** [comment]
Please always include your specs like we ask for in our issue templates (MoviePy version, platform used etc.) as well as code samples for reproducability and complete logs for errors where applicable, thank you.
