### ISSUE TITLE
Video and Audio are out of sync after write

### ISSUE THREAD

**Issue by aloof-ruf** [Zulko/moviepy#192]
When trying to write two videos out one after the other, the second one seems to have audio and video out of sync. The audio sounds correct, but the video seems to be lagging behind. When I check the video properties it says the frame rate is a whopping 250 frames per second (I'm expecting around 15 fps).

**Comment by Red5d** [comment]
What settings are you using when writing the videos out?

**Comment by kerstin** [comment]
@aloof-ruf  I'm closing this issue due to age + lack of activity. Please feel free to update the thread with info on how you solved your original problem or any other comments that might be useful for folks running into similar issues in the future.
