### ISSUE TITLE
TextClip has no function with_audio()?

### ISSUE THREAD

**Issue by IfgiU** [Zulko/moviepy#1938]
Hi!
I'm trying to add an AudioClip to a TextClip using `my_text_clip.with_audio(my_audio_clip)`, however, I get an error stating `AttributeError: 'TextClip' object has no attribute 'with_audio'`. What am I missing? Do I need to import something else? I've tried importing everything from `moviepy.editor`, `moviepy.audio` and `moviepy.Clip`. Or is the documentation simply wrong?

**Comment by IfgiU** [comment]
Alright, seems that the function was renamed to `set_audio` and was never updated in the documentation.

**Comment by keikoro** [comment]
@IfgiU Sounds like this can be closed? Let me know if I'm mistaken.
