### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'disable'

### ISSUE THREAD

**Issue by RootRooster** [Zulko/moviepy#1961]
When I tried to write the final video file this error popped up.
However I managed to solve it by downgrading the tqdm version.
```
pip uninstall tqdm
pip install tqdm==4.49.0
```
Hope this helps someone out :).

#### Steps to Reproduce the Problem
```py
import os
os.environ["IMAGEIO_FFMPEG_EXE"] = "/usr/bin/ffmpeg"
from moviepy.editor import *
path = '...'
# Create a list of VideoFileClip objects for each file in the folder
clips = []
for filename in os.listdir(path):
    print(filename)
    if filename.endswith(".mp4"):
        clip = VideoFileClip(os.path.join(path, filename))
        clips.append(clip)

# Concatenate the clips together and save the result to a new file
output_path = os.path.join('...', "output.mp4")
final_clip = concatenate_videoclips(clips)
final_clip.write_videofile(output_path)
```

#### Specifications

  - Python Version: 3.11.0
  - MoviePy Version: 1.0.3

**Comment by mgaitan** [comment]
wich was the error that popped up?

**Comment by keikoro** [comment]
Closing this issue as it's missing information previously requested (error logs).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.
