### ISSUE TITLE
Invalid syntax error 

### ISSUE THREAD

**Issue by zephyr582** [Zulko/moviepy#1963]
The above code causes this error:
File "/Users/nicolasrulli/Desktop/MiscCode/python_projects/env/lib/python3.7/site-packages/moviepy/video/fx/all/__init__.py", line 16, in <module>
    exec("from %s import %s" % (name, name))
  File "<string>", line 1
    from __init__ 2 import __init__ 2
                  ^
SyntaxError: invalid syntax

#### Expected Behavior
This issue is preventing instagrapi from uploading a video. 

#### Specifications

  - Python Version: 3.7.3
  - MoviePy Version: 1.0.3

**Comment by keikoro** [comment]
Closing this issue as it's missing code to try to reproduce the problem.

I can reopen it once you provide a code sample + full log but please be aware you should try to work with the latest master of MoviePy where possible. The last PyPI release is quite old.
