### ISSUE TITLE
No module named 'moviepy', but i  already installed it 

### ISSUE THREAD

**Issue by ThinkCodeStudio** [Zulko/moviepy#1964]
```shell
❯ python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import moviepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'moviepy'
>>>
```
run:
```shell
❯ python -m pip install moviepy
Requirement already satisfied: moviepy in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (1.0.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (4.65.0)
Requirement already satisfied: requests<3.0,>=2.8.1 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (2.27.1)
Requirement already satisfied: proglog<=1.0.0 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (0.1.10)
Requirement already satisfied: numpy>=1.17.3 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (1.24.3)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (2.28.1)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from moviepy) (0.4.8)
Requirement already satisfied: pillow>=8.3.2 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from imageio<3.0,>=2.5->moviepy) (9.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0,>=2.8.1->moviepy) (3.3)
Requirement already satisfied: colorama in c:\users\think\appdata\local\programs\python\python310\lib\site-packages (from tqdm<5.0,>=4.11.2->moviepy) (0.4.4)
```
this is lib folder
![image](https://user-images.githubusercontent.com/40518405/236232982-90cb18e6-2811-408e-9aea-017a4ccf9dcf.png)
![image](https://user-images.githubusercontent.com/40518405/236233043-ea570698-d06f-4285-8424-266bfeb95991.png)

**Comment by galokchan** [comment]
same problem on 3.11.3 last week
for me switch to 3.10.9 and good to go!
hope it can help

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.

**Comment by ygorseiji** [comment]
Hello,
I had the same problem, I managed to solve it with the following commands.
pip uninstall moviepy
pip install moviepy==1.0.3

By default it always gets the latest version, which is currently 2.0.0, which is showing this error, so I tested it by installing an older version and I managed to solve it.
It might be interesting to use venv to test the moviepy versions

**Comment by MehdiAliRizvi** [comment]
Thanks, ygorseiji's comment worked like a charm

**Comment by sumitsartale4952** [comment]
> pip install moviepy==1.0.3

thank you

**Comment by dsong99** [comment]
I am having the same issue. I can import moviepy in PyCharm console, but cannot import from windows CMD command line. 
tried uninstall and reinstall:
conda install -c conda-forge moviePy==1.0.3

one problem I run moviePy from PyCharm to open a video is: permission denied. So I decided to try it on command line. 

Weird.
