### ISSUE TITLE
How to convert audio into mono channel 

### ISSUE THREAD

**Issue by rohitreddy21122000** [Zulko/moviepy#1972]
i have used the foloowing code 

from moviepy.editor import *

# Set the paths for input and output files
input_file = 'path/to/input.mp4'
output_file = 'path/to/output.wav'

# Load the video file
video = VideoFileClip(input_file)

# Extract the audio and convert to mono
audio = video.audio
audio = audio.set_channels(1)

# Write the audio to a WAV file
audio.write_audiofile(output_file, codec='pcm_s16le')

bu twhen itried to ecute the code i'm getting an error 

*** AttributeError: 'AudioFileClip' object has no attribute 'set_channels'   ****

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.
