### ISSUE TITLE
kombu.exceptions.EncodeError: Object of type VideoFileClip is not JSON serializable

### ISSUE THREAD

**Issue by nikhiltree** [Zulko/moviepy#1980]
```
from moviepy import *
clip = ColorClip((600, 400), color=(255, 100, 0), duration=2)

```

#### Steps to Reproduce the Problem
-  define the celery task 
-  pass this clip object to this celery arguments
```

@celery.task(autoretry_for=(Exception,), retry_kwargs={'max_retries': 3, 'countdown': 5},visibility_timeout=1800)
def video_edit(clip=clipe):
     pass
```

#### Specifications

  - Python Version: Python 3.8.10
  - MoviePy Version: moviepy==1.0.3
  - Platform Name: Ubuntu 
  - Platform Version: 20.04 LTS

**Comment by keikoro** [comment]
Please always include useful code samples for reproducability and complete logs for errors (code-formatted text only, no screenshots).

**Comment by nikhiltree** [comment]
please close this issue i solved this issue
