### ISSUE TITLE
Animate TextClip text value

### ISSUE THREAD

**Issue by maty974** [Zulko/moviepy#199]
Hi

I would like to animate the `TextClip` text parameter value at each frames, the text clip will be the 
current frame value or a `SMTPE` timecode for example.

Is it possible to do it with `MoviePy` ?

Thanks a lot for your help.

**Comment by Zulko** [comment]
Hey,

TextClip is really for texts that don't move. Look here for an example where I use PIL/Pillow to generate the texts dynamically (it makes a "chronometer" clip which prints the timecode):

https://gist.github.com/Zulko/06f49f075fd00e99b4e6#file-moviepy_time_accuracy-py-L33-L39

**Comment by maty974** [comment]
Cool I wil give it a try, but at the same time I've found this solution but I don't know if its safe to use TextClip like that

```
def make_frame(t):
    txt=TextClip("TEST %s" % t,color="#686868",fontsize=20,font="Arial")

    return txt.img

text_clip1=VideoClip(makeframe, duration=shot_clip.duration)
```

**Comment by Zulko** [comment]
I think it should be safe (no memory leak I think) but the solution I linked to is much faster.

**Comment by maty974** [comment]
Alright thanks for your help Zulko ;)

**Comment by saadtanveer427** [comment]
dklsdlsdklfklfkdf
