### ISSUE TITLE
Unable to cutout parts which  are more than 50% of the video length 

### ISSUE THREAD

**Issue by KishalayChakraborty** [Zulko/moviepy#1992]
#### Specifications

  - Python Version:
  - MoviePy Version:
  - Platform Name:
  - Platform Version:

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.
