### ISSUE TITLE
Why did the length of my video change?

### ISSUE THREAD

**Issue by Lucky-Jay** [Zulko/moviepy#1996]
#You can check the output, the length of my video changed after reading and writing directly

from moviepy.editor import *

video = VideoFileClip('temp.mp4')
video.write_videofile('result.mp4', )
video2 = VideoFileClip('result.mp4')
print(video.duration, video2.duration)

https://github.com/Zulko/moviepy/assets/81693303/2bfe36f1-e8ed-4c2c-bdbf-ff6e58f3b9fc

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it. Please be aware you should always try to work with the latest master of MoviePy where possible, not the last PyPI release, which is quite old.
