### ISSUE TITLE
module 'PIL.Image' has no attribute 'ANTIALIAS' - resize.py

### ISSUE THREAD

**Issue by yoichitgy** [Zulko/moviepy#2002]
#### Expected Behavior

`resize` function works without an error when Pillow version 10.0.0 is installed.

#### Actual Behavior

The following error is raised at `moviepy/video/fx/resize.py", line 37, in resizer`

```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

#### Steps to Reproduce the Problem

1. Re-install MoviePy. As its dependency, Pillow version 10.0.0 is installed.
2. Call `resize` function on a `ImageClip`.

This issue is caused by the deprecation of `ANTIALIAS` in Pillow version 10.0.0.

Reference:
https://stackoverflow.com/a/76616129/4522678

#### Specifications

  - Python Version: 3.11
  - MoviePy Version: 1.0.3
  - Platform Name: macOS
  - Platform Version: 10.15.7

**Comment by Mayank19j** [comment]
What should I do in my local to fetch the fix?

**Comment by motishaku** [comment]
> What should I do in my local to fetch the fix?

did you figure it out?

**Comment by delans** [comment]
I'm having the same error: 

Python Version: 3.11.5
MoviePy Version: 1.0.3
Pillow Version: 10.0.0
Platform Name: macOS
Platform Version: 12.6.7

**Comment by bwang514** [comment]
Had the same issues.  

After digging into the source code (https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py)

I found that moviepy will try to use opencv as resizer first, if opencv not installed it will use PIL which leads to the error we are seeing here. 

Instead of fixing the deprecated PIL package, simply installing opencv-python works for me.

**Comment by Kaszanas** [comment]
> Had the same issues.
> 
> After digging into the source code (https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py)
> 
> I found that moviepy will try to use opencv as resizer first, if opencv not installed it will use PIL which leads to the error we are seeing here.
> 
> Instead of fixing the deprecated PIL package, simply installing opencv-python works for me.

Then I suspect that this means that moviepy will add `opencv-python` as a dependency in future releases?

**Comment by COROYO** [comment]
> > Had the same issues.
> > After digging into the source code (https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py)
> > I found that moviepy will try to use opencv as resizer first, if opencv not installed it will use PIL which leads to the error we are seeing here.
> > Instead of fixing the deprecated PIL package, simply installing opencv-python works for me.
> 
> Then I suspect that this means that moviepy will add `opencv-python` as a dependency in future releases?

yeah i've added `openvc-python` and everything worked fine.

**Comment by paulocoutinhox** [comment]
I have the same error. When moviepy will be fixed to support pil 10? Thanks.

**Comment by COROYO** [comment]
> I have the same error. When moviepy will be fixed to support pil 10? Thanks.

Add opencast-python package to your pip

**Comment by djkewjrioesjfdwaoikdi** [comment]
I faced the same issue, so i downgraded to Pillow==9.4.0 and it worked for me!

**Comment by SohamTilekar** [comment]
The Pil attr ANTIALIAS is Been Deprecated. Therefor We Need to Downgrade the Pillow Version. or Re Download the Moviepy.

**Comment by g0T-h** [comment]
You can edit resize.py in line 37 with this line.
`resized_pil = pilim.resize(newsize[::-1], resample=Image.LANCZOS)`
ANTIALIAS is deprecated.

**Comment by SohamTilekar** [comment]
Yes, it can Work But it is Not Suggested.

**Comment by g0T-h** [comment]
Yeah, but this should work as an temporary solution.

**Comment by keikoro** [comment]
Thanks, @yoichitgy, also for the fix you submitted.

I'm closing this issue – like I've done with the other duplicates – in favour of #2072, which links to the library's official relase notes, to reduce noise.

**Comment by JoelOnyedika** [comment]
So does that mean that for production, i will be forced to make a copy of the entire moviepy repo on my vps, make configs on my dockerfile to edit the resize.py file or downgrade pillow?

**Comment by harsha7addanki** [comment]
you can as a previous comment said just install opencv
