### ISSUE TITLE
how to remove subtitles in a mp4 file?

### ISSUE THREAD

**Issue by chenzhiang669** [Zulko/moviepy#2019]
I have a requirement that to remove the subtitles in a mp4 file.
but I am a beginner in moviePy， anybody can give me a demo or example how to do it?

**Comment by SarthakJaindebugger** [comment]
@Zulko please assign this issue to me. I can resolve.

**Comment by keikoro** [comment]
It's not clear from your description what exactly you are asking and if your problem can even be solved with MoviePy. Closing until you update your issue with more information.
