### ISSUE TITLE
Problem creating VideoFileClip from URL on server

### ISSUE THREAD

**Issue by t-io** [Zulko/moviepy#204]
exception is raised when trying to get remote resource.
`clip = mp.VideoFileClip(url)`
This is what I get: `IOError: MoviePy error: failed to read the duration of file http://www.gifbin.com/bin/1236242020_JessicaBielTheTexasChainsaw.gif.`
```
ffmpeg version 2.4.2-   http://johnvansickle.com/ffmpeg/    Copyright (c) 2000-2014 the FFmpeg developers
  built on Oct  9 2014 07:24:56 with gcc 4.8 (Debian 4.8.3-11)
  configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --disable-ffserver --enable-libass --enable-gnutls --cc=gcc-4.8
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  1.100 / 56.  1.100
  libavformat    56.  4.101 / 56.  4.101
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  1.100 /  5.  1.100
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
[tcp @ 0x2fd7c40] Failed to resolve hostname www.gifbin.com: System error
http://www.gifbin.com/bin/1236242020_JessicaBielTheTexasChainsaw.gif: Input/output error
```

`ping google.com` works from inside the VM and also get this file with the requests library.
Has someone any ideas?

**Comment by t-io** [comment]
The problem is the ffmpeg binary for linux64 installed by imageio. 
When using the systems version of ffmpeg with setting the environment variable `IMAGEIO_FFMPEG_EXE` to `'ffmpeg'` it works. Maybe a good idea to document dependency settings somewhere.

**Comment by missionfission** [comment]
> The problem is the ffmpeg binary for linux64 installed by imageio. 
> When using the systems version of ffmpeg with setting the environment variable `IMAGEIO_FFMPEG_EXE` to `'ffmpeg'` it works. So I close this issue.
> 

Not working for us
