### ISSUE TITLE
how to write ImageClip?

### ISSUE THREAD

**Issue by PetroTruman** [Zulko/moviepy#2059]
I created an `ImageClip`, after transformation, how can I write it into **one** image file e.g.  "image.jpeg" ?
I didn't find the answer in the  moviepy documentation.
I tried `write_images_sequence` and `write_videofile`
it didn't work out.

**Comment by mgaitan** [comment]
Try `save_frame` 

```
from moviepy.editor import ImageClip

# Suppose you've created an ImageClip like this
img_clip = ImageClip('path_to_some_image.jpg')

# Apply your transformations here
# ...

# Save the frame (i.e., the image) to a file
img_clip.save_frame("image.jpeg")
```

**Comment by PetroTruman** [comment]
@mgaitan I tried it, it works! Thanks a lot!!!
