### ISSUE TITLE
Is it possible to write infinite looping videos?

### ISSUE THREAD

**Issue by t-io** [Zulko/moviepy#206]
I'm wondering if something like this is possible somehow. To have a video which loops infinite without specifying a duration or number of loops.
The `loop()` Function is decorated with `@requires_duration` but the duration and number of loops also can be empty. So I assume it's technically not possible to force something like an .mp4 to auto-loop.
I tried this:
```
url = 'http://www.gifbin.com/bin/1236242020_JessicaBielTheTexasChainsaw.gif'
clip = mp.VideoFileClip(url)
cc = clip.fx(vfx.loop)
cc.write_videofile("gif_video.mp4")
```

but always end up in a `ValueError("Attribute 'duration' not set")`
Do you know a clever way to loop a `.mp4` without bloating the filesize?
By the way thanks for the cool library :)

**Comment by Red5d** [comment]
I don't think the mp4 format allows for looping the video. The software playing the video would have to do that.

**Comment by t-io** [comment]
yes, I figured this out by myself. Thanks for your reply. I close this one.
