### ISSUE TITLE
audiofile double the actual length of video

### ISSUE THREAD

**Issue by Shashankabr** [Zulko/moviepy#2062]
#### Specifications

  - Python Version:3.11
  - MoviePy Version: 1.0.3
  - Platform Name: mac
  - Platform Version:14

**Comment by keikoro** [comment]
Closing this issue as it's missing code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it, but this sounds like it's a duplicate of what's been reported before.
