### ISSUE TITLE
Error when using ffmpeg_movie_from_frames "global name 'bitrate' is not defined"

### ISSUE THREAD

**Issue by chicocvenancio** [Zulko/moviepy#208]
I'm getting an error when trying to use ffmpeg_movie_from_frames on a ubuntu machine.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_tools.py", line 20, in ffmpeg_movie_from_frames
    "-b", "%dk"%bitrate,
NameError: global name 'bitrate' is not defined

**Comment by Zulko** [comment]
Either use directly an ffmpeg command (you can from Python with

    os.system("ffmpeg -i *.jpeg result.mp4")

Or use moviepy's `ImageSequenceClip`:
    
    import moviepy.editor as mpe
    clip = mpe.ImageSequenceClip(["list","of","filenames"], fps=15)
    clip.write_videofile("test.mp4", **some_options)

**Comment by chicocvenancio** [comment]
Great! Thanks, got an error when using unicode for the file paths but worked great with strings.
Should this be in the documentation somewhere? Is it already?
