### ISSUE TITLE
Gif to MP4 by VideoFileClip, always plays the first frame

### ISSUE THREAD

**Issue by chengxs1994** [Zulko/moviepy#2088]
#### Expected Behavior
Play dynamic content similar to gif

#### Actual Behavior
When I use VideoFileClip to convert gif to MP4, the generated MP4 always plays the first frame of content

#### Steps to Reproduce the Problem

```
from moviepy import editor
video = editor.VideoFileClip('pics.gif')
video.write_videofile(video_filepath)
```

#### Specifications

- Python Version: 3.11
- MoviePy Version: 1.0.3
- Platform Name: linux
- Platform Version:
‘’‘’‘’‘’‘’‘’‘’‘’

**Comment by SohamTilekar** [comment]
Is Your Gif Work Normally Because It Work on my pc.
Below is the Input Clip and Output Clip Chake Whether the Below Input Gif Work on Device.

Input Clip: -
![pigs_in_a_polka](https://github.com/Zulko/moviepy/assets/152298897/9b544821-5fb0-49f0-ad34-9f1db302f800)

Output Clip: -

https://github.com/Zulko/moviepy/assets/152298897/c34d6b06-62e1-4f23-95ed-b880c9ed409b

**Comment by SohamTilekar** [comment]
I was using the Windows 10, python 3.12, moviepy 1.03

Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.

**Comment by chengxs1994** [comment]
> 你的 Gif 工作正常吗？因为它在我的电脑上工作。 下面是输入剪辑和输出剪辑检查下面的输入 Gif 是否在设备上工作。
> 
> 输入剪辑：- ![波尔卡猪](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ![pigs_in_a_polka](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc)
> 
> 输出剪辑：-
> 
>  Pigs_in_a_polka.mp4



> Is Your Gif Work Normally Because It Work on my pc. Below is the Input Clip and Output Clip Chake Whether the Below Input Gif Work on Device.
> 
> Input Clip: - ![pigs_in_a_polka](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ![pigs_in_a_polka](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc)
> 
> Output Clip: -
> 
>  pigs_in_a_polka.mp4

Thank you very much. I used your GIF successfully, but the GIF I generated using ImageIO failed

**Comment by chengxs1994** [comment]
> Is Your Gif Work Normally Because It Work on my pc. Below is the Input Clip and Output Clip Chake Whether the Below Input Gif Work on Device.
> 
> Input Clip: - ![pigs_in_a_polka](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ![pigs_in_a_polka](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc) [ ](https://private-user-images.githubusercontent.com/152298897/293180007-9b544821-5fb0-49f0-ad34-9f1db302f800.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTkxNDEsIm5iZiI6MTcwMzc1ODg0MSwicGF0aCI6Ii8xNTIyOTg4OTcvMjkzMTgwMDA3LTliNTQ0ODIxLTVmYjAtNDlmMC1hZDM0LTlmMWRiMzAyZjgwMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxMDIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmY2YTA0OWQzMTY3ODhmYmU3OWVhZTk3YTJiOTU2YWRmNjY0Y2EwMDFiZTM4OTJiNDhhOWUxMjBiZDc2MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZt5AZqsWFaY0AXLGeWut4n-n2mAdIYhblGIERLDoEc)
> 
> Output Clip: -
> 
>  pigs_in_a_polka.mp4

Thank you very much. I used your GIF successfully, but the GIF I generated using ImageIO failed

**Comment by chengxs1994** [comment]
> I was using the Windows 10, python 3.12, moviepy 1.03
> 
> Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.



> I was using the Windows 10, python 3.12, moviepy 1.03
> 
> Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.

Okay, I'll try it locally

**Comment by SohamTilekar** [comment]
> > I was using the Windows 10, python 3.12, moviepy 1.03
> > Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.
> 
> > I was using the Windows 10, python 3.12, moviepy 1.03
> > Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.
> 
> Okay, I'll try it locally

I Am Currently Developing it Would You Like To Work With me on it. Reply me on the [Vidiopy](https://github.com/SohamTilekar/vidiopy) Discussions.

**Comment by chengxs1994** [comment]
> > > I was using the Windows 10, python 3.12, moviepy 1.03
> > > Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.
> > 
> > 
> > > I was using the Windows 10, python 3.12, moviepy 1.03
> > > Do you Like to Work on My Project [Vidiopy](https://github.com/SohamTilekar/vidiopy) Which is to Make an alternative to the Moviepy Because the Moviepy python Version is outdated, To Many Bugs, Zulko Unviability.
> > 
> > 
> > Okay, I'll try it locally
> 
> I Am Currently Developing it Would You Like To Work With me on it. Reply me on the [Vidiopy](https://github.com/SohamTilekar/vidiopy) Discussions.

Of course, I fork and star
