### ISSUE TITLE
Text is cropped at the top

### ISSUE THREAD

**Issue by takosuke** [Zulko/moviepy#209]
I installed ghostscript next to imagemagick because otherwise it wouldn't recognize OSX fonts, as described somewhere else. 

Perhaps because of that, fonts seem to often get cropped at the top like this:

![screen shot 2015-09-17 at 12 52 06](https://cloud.githubusercontent.com/assets/640028/9931392/8f46d674-5d3b-11e5-847b-a0c04be4313f.png)

**Comment by Zulko** [comment]
There is a way to provide a size (width, height) in TextClip, try providing a larger height so that the text will appear at the center of the TextClip.

**Comment by takosuke** [comment]
That works, but why does it crop it in the first place?

**Comment by Zulko** [comment]
Apparently ImageMagick doesn't like OSX fonts.

**Comment by jredd** [comment]
I'm having a similar issue but I'm on an ubuntu box...

**Comment by Zulko** [comment]
With any font ?

**Comment by jredd** [comment]
Seems to be that way. I'm using the imbedded fonts in moviepy

**Comment by Zulko** [comment]
Strange, can you post a minimal code + pictures ?

**Comment by jredd** [comment]
http://sistertech-banners.s3.amazonaws.com/Screen%20Shot%202015-09-25%20at%209.53.14%20AM.png

yearMakeModelText = TextClip(
                txt='Test Text',
                fontsize=30,
                color='white',
                font='AvantGarde-Book',
                # size=(300,34),
            ).set_start(3).set_duration(4)

I have fixed the issue by modifying it's size property. Just thought I'd at least report a similar issue.

**Comment by kerstin** [comment]
@jredd Could you specify how exactly you fixed the issue? Thanks!

**Comment by kerstin** [comment]
@jredd Oh, wait, was it just via the workaround suggested above? Hmm.

**Comment by tburrows13** [comment]
This is very old, and I've been using TextClips with Ghostclip on macOS for some time with no issues, so I will close this issue. If you are still having this problem, please comment here or open a new issue.

**Comment by darielgu** [comment]
Seeing this issue still ):
