### ISSUE TITLE
I tried to crop a video into circular frames and make the overlay transparent, which did'nt work. Any ideas on how to go about this? I want the video in a circle and the edges(cropped part) transparent.

### ISSUE THREAD

**Issue by Trinita21typeset** [Zulko/moviepy#2090]
#### Specifications

  - Python Version:
  - MoviePy Version:
  - Platform Name:
  - Platform Version:

**Comment by keikoro** [comment]
Closing this issue as it's missing information we request when creating new issues: specs like MoviePy version, platform used etc. and/or useful code samples for reproducability and/or complete logs for errors where applicable (code-formatted text only, no screenshots).

We can reopen the issue once you've updated it.
