### ISSUE TITLE
Any Unicode Font For TextClip

### ISSUE THREAD

**Issue by terry891** [Zulko/moviepy#2108]
Here's useful info when you try to use non-ASCII codes. 

MoviePY uses `convert` from `ImageMagick ` to generate the TextClip. So, if you'd like to write non-ASCII characters, simply choose the font that works for your text.

For example:
```
txt = TextClip("🤫", font = 'Segoe-UI-Emoji', fontsize = 44)    #Emoji Font
txt = TextClip("测试", font="Kaiti-TC-Regular", fontsize = 44)   #Chinese Font
```

You can use ` identify -list font` to see the list of available fonts you can use.
Related Issues:  #507,  #1520

**Comment by garvitomer** [comment]
Hi, I am loading text from the .txt file and it wasn't working. Is there anything else I need to keep in mind?
