### ISSUE TITLE
crop missing from moviepy.video.fx.all

### ISSUE THREAD

**Issue by NicoCaldo** [Zulko/moviepy#2113]
As stated [here](https://github.com/Zulko/moviepy/issues/914) I can't access `crop `

I've tried `from moviepy.video.fx import crop` but I'm having an error like `'crop' is not callable`

I'm using PyCharm 2023.3.3 and Python 3.11

Seeing the` __init__.py` of `moviepy.video.fx.all` I'm seeing it uses the `__all__`

[PyCharm seems to have some bugs with it](https://stackoverflow.com/questions/23248017/cannot-find-reference-xxx-in-init-py)

Could it be the case on why it doesn't work?

**Comment by NicoCaldo** [comment]
The fix is `from moviepy.video.fx import crop` and using `crop `as
`crop.crop()`

**Comment by Amar2502** [comment]
use it like this
crop_effect = Crop(x_center=w/2, y_center=h/2, width=crop_width, height=crop_height)
