### ISSUE TITLE
Detecting quicktime rotate flag (e.g. iphone portrait videos)

### ISSUE THREAD

**Issue by peircej** [Zulko/moviepy#212]
Thanks for creating moviepy (and saving me from the hell of importing movies using certain more complex libs!). Your code and API are super-neat and easy to use. We're going to use moviepy to add movies to a package for conducting experiments in neuroscience and psychology (www.psychopy.org).

One thing that's cropped up is that movies shot in portrait on an iphone are rotated by using a metadata flag to identify the correct final orientation. Moviepy doesn't seem to respect that rotation matrix. There's a pure-python lib to extract the info here:
     https://github.com/danielgtaylor/qtrotate

Any chance that could be corrected or simply provided as info from moviepy, or should we implement that ourselves in our package?

**Comment by kerstin** [comment]
@peircej Seeing as this issue is quite old: did you get this solved? I'll label it as enhancement for now in any case.

**Comment by peircej** [comment]
I'm not aware of this being fixed inside moviepy.
It would still be good to see moviepy do something to identify the correct orientation of movies shot on a rotated iphone.

**Comment by mxisaac** [comment]
+1 on that, I'd really like to see this resolved.  It's the one major issue I run into a lot and it's really difficult to solve for it.

**Comment by mondeja** [comment]
Closing in favour of #586 (has more context). Anyway, thank you for opening this :pray:
