### ISSUE TITLE
Invalid Gitter link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sohang3112** [Zulko/moviepy#2131]
In CONTRIBUTING.md, this Gitter link is mentioned for discussions: https://gitter.im/Movie-py . But opening the liink gives error *404 Not Found*.

**Comment by keikoro** [comment]
I'm not sure if the Gitter is even actively being used anymore, but if the link is wrong, it should get corrected. The README containes the correct link.

**Comment by sohang3112** [comment]
The Gitter link in README works: https://gitter.im/movie-py/Lobby - but it also doesn't seem to be actively used any more (as you said). Since the Reddit sub (https://www.reddit.com/r/moviepy/) is still active, it should also be added in CONTRIBUTING.md for discussions.

**Comment by sohang3112** [comment]
@keikoro Based on our discussion I opened the PR above to fix Gitter link & add Reddit link in CONTRIBUTING.md. Please review the PR & merge it.

**Comment by sohang3112** [comment]
@keikoro Please review & merge my linked PR to correct Gitter link.
