### ISSUE TITLE
Warning: skimage.filter is deprecated

### ISSUE THREAD

**Issue by petebachant** [Zulko/moviepy#214]
Getting this warning on import:

```
WARNING:py.warnings:C:\Users\Pete\Anaconda3\lib\site-packages\skimage\filter\__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
```

**Comment by kerstin** [comment]
@petebachant Did you try renaming the module and did that eliminate the warning? If so, would you like to send a PR fixing this?

**Comment by petebachant** [comment]
I'm not getting this warning the the latest PyPI version, and latest skimage in Anaconda, so I'm going to assume this is no longer an issue!
