### ISSUE TITLE
Defaults fail for ImageSequenceClip()

### ISSUE THREAD

**Issue by ryan-hill** [Zulko/moviepy#218]
I attempted the following code, where 'wd' contained a series of .jpegs.

```
wd = 'C:/Temp/animations/images/'
myclip = mpy.ImageSequenceClip(wd)
```

I got the error:
myclip = mpy.ImageSequenceClip(wd)
Traceback (most recent call last):

```
  File "<ipython-input-2-2adcd226a5d5>", line 1, in <module>
    myclip = mpy.ImageSequenceClip(wd)

  File "C:\Users\Ryan\Anaconda\Lib\site-packages\moviepy\video\io\ImageSequenceClip.py", line 81, in __init__
    self.duration = sum(durations)

TypeError: 'NoneType' object is not iterable
```

I was only able to get the code to work by providing a an 'fps' to the function (e.g., fps = 1) but I think the default is meant to provide an fps is none is provided.

**Comment by filipochnik** [comment]
@ryan-hill your code should raise ValueError https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ImageSequenceClip.py#L55

**Comment by kerstin** [comment]
@filipochnik Could you clarify what you meant with your comment? Thanks.

**Comment by filipochnik** [comment]
@kerstin You either have to pass fps or durations, as the linked line says.
