### ISSUE TITLE
No longer encoding subtitles

### ISSUE THREAD

**Issue by cslop3r** [Zulko/moviepy#2180]
I used to have the ability to encode subtitles but now it doesn't work anymore.

`subs = SubtitlesClip("subs.srt", gensubs, encoding='utf-8')`

`Traceback (most recent call last):
  File "/Users/nathan/Documents/RSL/index.py", line 210, in <module>
    subs = SubtitlesClip("subs.srt", gensubs, encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SubtitlesClip.__init__() got an unexpected keyword argument 'encoding'`

**Comment by antonpetrov145** [comment]
If you are on version 1.0.3 this parameter is not there, the feature is introduced in v2.0.0.dev1
see here https://github.com/Zulko/moviepy/releases/tag/v2.0.0.dev1

so try to update to pre-release version

**Comment by cslop3r** [comment]
> If you are on version 1.0.3 this parameter is not there, the feature is introduced in v2.0.0.dev1 see here https://github.com/Zulko/moviepy/releases/tag/v2.0.0.dev1
> 
> so try to update to pre-release version

Thanks!!
