### ISSUE TITLE
MoviePy error: FFMPEG permission error

### ISSUE THREAD

**Issue by hgillh** [Zulko/moviepy#220]
I am using Moviepy through a Django application on Ubuntu 14.04 system. It is giving me permissions error when it tries to write video file. Following are details of error :

MoviePy error: FFMPEG encountered the following error while writing file test1TEMP_MPY_wvf_snd.mp3:

test1TEMP_MPY_wvf_snd.mp3: Permission denied

It seems it has not correct permissions on directory where it is trying to write temporary files.

I have set the 777 on /tmp directory but no luck. 

@Zulko . Please help me. I shall be thankful to you. It's very urgent for me.

**Comment by Zulko** [comment]
I think you can provide the name of the tempfiles when you write a video with moviepy so you should pass a tempfile name with a path that can be written to.

**Comment by hgillh** [comment]
Thanks for quick reply.

I am going to try it.

**Comment by hgillh** [comment]
Hi,
Just want to say thanks for your help @Zulko.
You top help me to complete my task.
