### ISSUE TITLE
yielding write_videofile progress

### ISSUE THREAD

**Issue by henrymcl** [Zulko/moviepy#2200]
I'm building a video renderer with FastAPI and moviepy.
I wonder if the progress can be yielded, so that my Server Side Event (SSE) endpoint can serve the progress to the client.

This is a nice to have functionality - but I'll need to think of a way to keep the SSE connection open if it is too hard to achieve.

**Comment by bzczb** [comment]
There's a parameter `logger` to `write_videofile()`.

You can pass a custom logger which reports the progress bar like so:

```
class EngineProgressBarLogger(proglog.TqdmProgressBarLogger):
    def __init__(self):
        super().__init__(print_messages=False)

    def new_tqdm_bar(self, bar):
        from proglog.proglog import troncate_string

        """
        Need to override this so we can pipe the logger output to /dev/null
        if there's no terminal.
        Otherwise TQDM will throw a wrench in the works.
        """
        if (bar in self.tqdm_bars) and (self.tqdm_bars[bar] is not None):
            self.close_tqdm_bar(bar)
        infos = self.bars[bar]

        self.tqdm_bars[bar] = self.tqdm(
            total=infos['total'],
            desc=infos['title'],
            postfix=dict(now=troncate_string(str(infos['message']))),
            leave=self.leave_bars,
            file=sys.stderr or devnull,  # changed here
        )

    def bars_callback(self, bar, attr, value, old_value):
        super().bars_callback(bar, attr, value, old_value)
        value = value / self.bars[bar]['total']
        match bar:
            case 'chunk':
                eventqueue.enqueue(Event.GENERATE_PROGRESS, 'Rendering audio...', value)
            case 't' | 'frame_index':  # versions of moviepy have different name
                eventqueue.enqueue(Event.GENERATE_PROGRESS, 'Rendering video...', value)

    def callback(self, **kw):
        if 'message' in kw and kw['message']:
            moviepy_log.info(kw['message'])
        return super().callback(**kw)
```

The `eventqueue.enqueue` lines are where progress is reported.

Use the custom logger class like this:

```
clip.write_videofile(
                output_filepath,
                ...,
                logger=EngineProgressBarLogger(),
            )
```

**Comment by henrymcl** [comment]
> ```py
> eventqueue.enqueue(Event.GENERATE_PROGRESS, "Rendering audio...", value)
> ```

I'm a bit stumped there. Are you using Python's `queue` library for the `eventqueue` and `Event` ?

**Comment by henrymcl** [comment]
> > ```python
> > eventqueue.enqueue(Event.GENERATE_PROGRESS, "Rendering audio...", value)
> > ```
> 
> I'm a bit stumped there. Are you using Python's `queue` library for the `eventqueue` and `Event` ?

I'm having some luck with the `pip install eventpy`, but I can't async yield from callbacks:

```py
from eventpy.eventqueue import EventQueue

def callback(*args):
    now = datetime.datetime.now()
    with open("log/temp.txt", "a") as f:
        f.write(f"{now.time()}: {args}\n")
async def my_function():
    eventqueue = EventQueue()
    eventqueue.appendListener(1, callback)
```

Progress can be logged into temp.txt, but
```py
from eventpy.eventqueue import EventQueue

def callback(*args):
    now = datetime.datetime.now()
    yield (now, args)
async def my_function():
    eventqueue = EventQueue()
    eventqueue.appendListener(1, callback)
```

Nothing can be yielded.

**Comment by bzczb** [comment]
Since moviepy is not an async library, you need to run the render in a worker thread, and instead of eventpy use `run_coroutine_threadsafe()` or something like [janus queue](https://github.com/aio-libs/janus) to report from the moviepy thread.

**Comment by henrymcl** [comment]
Thank you for nudge - when I revisit my requirements I realized that I just wanted to sustain an SSE to prevent timeout and there's no need to bombard users with all progresses. So I just logged to a temporary location and read the progress from it every 5 seconds.
