### ISSUE TITLE
OSError: [WinError 193] %1 n’est pas une application Win32 valide

### ISSUE THREAD

**Issue by BowgartField** [Zulko/moviepy#221]
Hello,
When I want to to concateante two videos, I have a probleme:
My code:
from moviepy.editor import *
clip1 = VideoFileClip("clip1.mp4")
clip2 = VideoFileClip("clip2.mp4")
final = concatenate_videoclips([clip1,clip2])
final.write_videofile("final.mp4")

Error code:
Traceback (most recent call last):
  File "C:\wamp\www\LinkMyFriends\montage\test.py", line 3, in <module>
    clip1 = VideoFileClip("clip1.mp4")
  File "C:\Python34\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 55, in **init**
    reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "C:\Python34\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 32, in **init**
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration)
  File "C:\Python34\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 237, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Python34\lib\subprocess.py", line 859, in **init**
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 n’est pas une application Win32 valide

**Comment by Zulko** [comment]
Have a look in the previous issues I think I have already seen that error somewhere. Another thing you can do is intall ffmpeg and tell me if it makes things better. If no luck, please provide the moviepy version you are using as well as the windows version. For moviepy:

    from moviepy import __version__
    print (__version__)

**Comment by BowgartField** [comment]
Thanks you,
I already install ffmeg and add the variable to my windows path but it didn't make anything,
I use 0.2.2.11 of movie.At time i try to upgrade to the last version, It install numpy now.

**Comment by BowgartField** [comment]
?

**Comment by Zulko** [comment]
??

**Comment by BowgartField** [comment]
What can I do ?

**Comment by Zulko** [comment]
Switch to Linux ! 

Just kidding. I don't have enough infos to know what went wrong. Did you install ffmpeg the conventional way (and are you sure you're using the 32-bit version) ? Did you change the settings (path to binaries) of moviepy in any way ? Are you running on a server ? (not sure if it matters).

**Comment by BowgartField** [comment]
xD I think i going to switch on linux :)
I using windows 10 64bits and I install ffmpeg 64bits on the official web site.The path is the bin directory of ffmpeg, and i doesn't use moviepy on server now but when my code is finish i want to use it on server.

**Comment by Zulko** [comment]
Did you go to the config.py file of moviepy and change anything ?

**Comment by BowgartField** [comment]
No i don't touch config.py.
I thinks the probleme is on the file in C:/User/AppData/local/imageio/ffmpeg/ffmpeg.win32.exe.

**Comment by Zulko** [comment]
Ah ok. Then try this at the beginning of your script (this will force the use of your locally installed ffmpeg):

    from moviepy.config import change_settings
    change_settings({"FFMPEG_BINARY":"ffmpeg.exe"})

(I assumed that the ffmpeg binary you installed is actually named ffmpeg.exe)

**Comment by BowgartField** [comment]
At time it working !!! So I deduce the ffmpeg version of imageio are wrong !
I repost when it finish :)
Merci ;)

**Comment by Zulko** [comment]
Not clear what you mean by : Can I get the step of mounting in python to send this in AJAX ? I need a longer description.

**Comment by BowgartField** [comment]
2 hours later ... It finily working !! 
I want to use moviepy on server like youtube so I have to receive the video advancement mounting to create a progress bar on my web page.

**Comment by BowgartField** [comment]
?

**Comment by kerstin** [comment]
I'm closing this because the original question/problem was answered/resolved and the follow-up actually posted separately as well (#224).

**Comment by giritharant** [comment]
Hello,
     I want to run moviepy code in web browser, if its possible?
