### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Awesome-Guy1** [Zulko/moviepy#2226]
See [VideoClip Documentation](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html).
- the VideoClip class size attribute is has (width, heigth) 
![image](https://github.com/user-attachments/assets/a389c988-6bff-412f-83d0-e96fe34694ab)
- the CompositeVideoClip class parameters is (height x width) (wrong order)
![image](https://github.com/user-attachments/assets/8b2c95ec-659b-4edb-97b4-08f6b8908ca7)

**Comment by PranjalSurana** [comment]
Hi, I would like to work on this bug

**Comment by Awesome-Guy1** [comment]
i realised that it was fixed already, just that they have not updated documentation for a while.
