### ISSUE TITLE
Import of MoviePy and Mayavi causes a segfault

### ISSUE THREAD

**Issue by MichaelClerx** [Zulko/moviepy#223]
Hi!

I'm an enthusiastic user of MoviePy and have used it to create mp4 videos of simulations of electrical wave propagation on 2d and 3d cardiac tissue. Today, I've been trying to make movies using MoviePy of 3d scenes generated using the python package Mayavi. However, when I import the two modules on one of my systems everything runs flawlessly, on the other I get a segfault.

I'm running fedora 22 on both systems with very similar packages installed so I've been having trouble finding out where the difference is. I've gdb'd in but can't see anything that helps me.

Does anybody have an idea how I could start to debug this?

**Comment by Zulko** [comment]
Are you just importing the two modules, with no other code of any kind ?

**Comment by kerstin** [comment]
@MichaelClerx I'm closing this issue due to age + lack of activity. Please feel free to update the thread with info on how you solved your original problem or any other comments that might be useful for folks running into similar issues in the future.

**Comment by MichaelClerx** [comment]
Sorry, no new info!
