### ISSUE TITLE
Is moviepy still being maintained?

### ISSUE THREAD

**Issue by MitchMunn** [Zulko/moviepy#2237]
The latest version is from 2020.
The last commit was 6 months ago, and there appear to be many PRs just sitting around waiting for approval.

**Comment by Zulko** [comment]
This repository is very minimally maintained at the moment unfortunately, v2.0 was ready for a long time but I just didn't have the bandwidth to test and release (and fix the repo automation like CI and pypi release). I did some maintenance yesterday, and I can promise to do some maintenance if something has broken as a result of the release.
