### ISSUE TITLE
TextClip has no attribute list()

### ISSUE THREAD

**Issue by innovimia-cto** [Zulko/moviepy#2248]
Hi,

I've tried to use TextClip.list('font') as referenced in the documents and here  https://github.com/Zulko/moviepy/blob/6f2ae4e560cc1d2f74a68593f8f4d697f1d17bc0/moviepy/video/VideoClip.py#L1363

Unfortunately, there's no list() method for TextClip. Am I missing something?

**Comment by Zulko** [comment]
Thanks for flagging. This is a functionality that disappeared this week with v2.0 unfortunately and we'll need to update the docstring. In the past the list of fonts was provided by ImageMagick, now it's on us to help users accross OSes. cc @OsaAjani 

For instance on Ubuntu:

```
find /usr/share/fonts/ ~/.fonts/ -type f
```

We could just add docs steal a page from [matplotlib's findSystemFonts](https://github.com/matplotlib/matplotlib/blob/v3.9.2/lib/matplotlib/font_manager.py#L277)

**Comment by OsaAjani** [comment]
Yep, looks like I missed this docstring ^^.

Now the font must be given to the function as a filepath, so it's up to the user to find the file and provide path to it, like he would for his images and videos, as explained here https://zulko.github.io/moviepy/user_guide/loading.html#textclip.

While we definitely need to update the docstring, I'm not sure we need to add info to explain to users where to find the fonts on their OS as they should probably put their font file along the other ressources (images, videos, etc.) they use in their clip anyway. I think it should be considered good practice when someone write some code to produce a clip that all resources used in the clip ship with the code, so the result is not dependent on the machine running the code, but only the code and the associated resources directory.

**Comment by innovimia-cto** [comment]
I believe there are more missing functionalities, like fadein, fadeout and others that are documented but are not anywhere the package.Farzad KhandanOn Nov 22, 2024, at 2:20 PM, Pierre-Lin Bonnemaison ***@***.***> wrote:﻿
Yep, looks like I missed this docstring ^^.
Now the font must be given to the function as a filepath, so it's up to the user to find the file and provide path to it, like he would for his images and videos, as explained here https://zulko.github.io/moviepy/user_guide/loading.html#textclip.
While we definitely need to update the docstring, I'm not sure we need to add info to explain to users where to find the fonts on their OS as they should probably put their font file along the other ressources (images, videos, etc.) they use in their clip anyway. I think it should be considered good practice when someone write some code to produce a clip that all resources used in the clip ship with the code, so the result is not dependent on the machine running the code, but only the code and the associated resources directory.

**Comment by OsaAjani** [comment]
Hey, i'm fixing the original problem, can i ask you @innovimia-cto where did you see doc for fadein/fadeout etc. ?

**Comment by innovimia-cto** [comment]
Hi,Here: https://moviepy-tburrows13.readthedocs.io/en/improve-docs/ref/VideoClip/VideoClip.htmlRegards,Farzad KhandanCo-founder, CTOInnovimia Technologies Inc.www.innovimia.comOn Nov 23, 2024, at 4:18 AM, Pierre-Lin Bonnemaison ***@***.***> wrote:﻿
Hey, i'm fixing the original problem, can i ask you @innovimia-cto where did you see doc for fadein/fadeout etc. ?

**Comment by OsaAjani** [comment]
That's the documentation of v1, fadein/out don't appear in the new version doc. I think we can close.

**Comment by innovimia-cto** [comment]
Yes, you are right. So, are the fadein/fadeout effects removed from v2.0?Farzad KhandanCo-founder, CTOInnovimia Technologies Inc.www.innovimia.comOn Nov 24, 2024, at 11:20 AM, Pierre-Lin Bonnemaison ***@***.***> wrote:﻿
That's the documentation of v1, fadein/out don't appear in the new version doc. I think we can close.

**Comment by OsaAjani** [comment]
I think this is resolved by #2254, I'm closing.
