### ISSUE TITLE
MoviePy 2.0 throws exception on loading video previous version worked with

### ISSUE THREAD

**Issue by Breakthrough** [Zulko/moviepy#2256]
#### Expected Behavior

MoviePy should continue to work with the same videos it did previously, even if those videos aren't fully compliant (e.g. are missing some metadata).

#### Actual Behavior

The same video crashes on MoviePy 2.0 but works with MoviePy 1.x.

#### Steps to Reproduce the Problem

See the `corrupt_video.mp4` file from https://github.com/Breakthrough/PySceneDetect/tree/resources/tests/resources and the associated unit test in https://github.com/Breakthrough/PySceneDetect/blob/95d20ddca57bb8cba77354697cc092643bd04afb/tests/test_video_stream.py#L359

The issue seems to come from the ffmpeg info parser assuming the presence of certain metadata fields.  Instead of failing, MoviePy should probably try to set some reasonable default value for these fields if they are not critical, to improve compatibility with media files.

#### Specifications

Tested on a wide variety of OS and Python versions:
 -  os: [macos-13, macos-14, ubuntu-20.04, ubuntu-latest, windows-latest]
 - python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

**Comment by aperture147** [comment]
moviepy v2 has a lot of unexpected error, like transparent sometimes work incorrectly. Currently I have to switch to libopenshot for my project

**Comment by Breakthrough** [comment]
Thanks for getting a fix for this out so quickly @Zulko, much appreciated.
