### ISSUE TITLE
Lack of Documentation for Major Changes in Version 2.1.1

### ISSUE THREAD

**Issue by markolofsen** [Zulko/moviepy#2261]
Dear MoviePy Developers,

I’m writing this with frustration about the significant changes introduced in version 2.1.1. While I understand the need for updates and improvements, the lack of proper migration documentation is causing unnecessary confusion and wasting a tremendous amount of time for developers who rely on your library.

For example, the removal or alteration of fundamental functions like fadein, fadeout, and crossfadein is a major breaking change. There's no clear guidance on how to achieve these effects in the new version. Should we use masks, or is there an entirely different approach? The absence of a migration guide or any detailed release notes explaining how to adapt our code is simply unacceptable.

Many of us have production systems built around MoviePy, and it is not reasonable to expect us to reverse-engineer changes by trial and error. A professional library should include adequate documentation and migration paths for breaking changes.

Please address this issue by:

Publishing detailed release notes for version 2.1.1 that explain the changes and provide code examples for deprecated features.
Including a migration guide for users upgrading from earlier versions.
Ensuring that future updates are accompanied by proper documentation to help users transition smoothly.
MoviePy is a fantastic library, but the lack of developer consideration in this release undermines the trust of your community. I urge you to prioritize clear communication and proper support for your users moving forward.

Thank you for your attention to this matter.

**Comment by OsaAjani** [comment]
Let's dial it down a bit and consider also the effort put in standardizing things and actually update documentation shall we ?
First of all, we used v2 for a reason, that you can still use old version without breaking change if you used a properly versionned dependency.

Then, we was talking about this migration for literally more than a year, with a documentation already available in the merge request giving ample time to prepare.

We actually provided a recap for migration from v1 to v2 https://zulko.github.io/moviepy/getting_started/updating_to_v2.html, containing a specific section about the removing of effects as clip properties, with a link pointing to the new with_effects usage : https://zulko.github.io/moviepy/user_guide/modifying.html#modifying-effects.

So, you have ample documentation on how to use effects, what effects are available (https://zulko.github.io/moviepy/reference/reference/moviepy.video.fx.html#module-moviepy.video.fx) and even how to create your own effects https://zulko.github.io/moviepy/user_guide/create_effects.html...

And guess what, you even have a literal 10 minutes guide to help both old timers and new comers get a sense a how to use moviepy https://zulko.github.io/moviepy/getting_started/moviepy_10_minutes.html.

And again, you liked the old version and your code was working with it ? Keep at it, nothing changed. The previous version had barely seen any updates in years, it will just be the same now !

**Comment by Zulko** [comment]
@markolofsen please do not write out of frustration or use terms like "simply unacceptable". Reading through the new docs would have told you how to use the new fadein function (it's in the 10-mins introduction). @OsaAjani even put in the effort of writing an "updating to v2" page, which we can develop further, but it takes time en encouragement.

@OsaAjani I Googled "MoviePy fadein" and the results weren't great. It looks like when I reintroduced the docs for version  v1.0.3 (which lives here: https://zulko.github.io/moviepy/v1.0.3/) some files also made it to their former url address (without /v1.0.3/), and as a result Google started serving the old docs again. Googling for "fadein" could have brought @markolofsen to a fully-functional-looking old version of the doc, making it look as if there was no v2 docs at all. I fixed this, and now most Google links will be 404 (not great, but kinda expected, it will heal with time).

**Comment by Zulko** [comment]
@tburrows13 Hi and thanks again for your work on the library, I hope you're doing great! Would you mind taking down the MoviePy docs at this address?

https://moviepy-tburrows13.readthedocs.io/en/improve-docs/index.html

We're trying to consolidate the docs around v2 (with v1.0.3 docs now living there: https://zulko.github.io/moviepy/v1.0.3/) and would like the v2 docs to be the first to come out in searches.

**Comment by OsaAjani** [comment]
@Zulko and @tburrows13 I think those redirections should speed things up, and I guess Google should find out pretty quick about the new doc and his various subparts. It's already the first site coming up on my end when searching for moviepy after pipy.

I get the source of confusion, but honestly the link to the doc is like the first thing in the project readme. Anyway, hopefully this will help us limit the mess and speed up clarification on the state of the project.

I think we can close this one, but let you guys make the call :)

**Comment by markolofsen** [comment]
@OsaAjani  @Zulko 
Thank you for your quick response and for clarifying the situation.

I do appreciate the work that has gone into the new version and the updated documentation, and I understand that breaking changes are often necessary for long-term improvement. However, I must express that the transition from version 1.x to 2.x has been quite challenging due to the significant changes made to the API, particularly around the usage of transition effects such as fadein, fadeout, and crossfadein. While I understand the shift to using with_effects and the introduction of a more object-oriented approach, these changes were not as clearly documented or communicated in the migration guide, which made it more difficult to adapt the existing workflows.

I believe that providing more in-depth documentation specifically focused on the transition from version 1.x to 2.x would help developers avoid confusion. For instance, clearer examples of how to apply the new transition effects, especially in terms of the new syntax and the introduction of with_effects, would be extremely helpful for users like myself who rely on the stability and predictability of the library in production environments.

I understand the importance of updating and improving the library, and I respect the effort put into these changes. However, a more structured and comprehensive guide, especially regarding breaking changes, would ease the transition for many users and help maintain the trust and stability that MoviePy has built over the years.

Thank you again for your hard work and for taking the time to address these concerns. I look forward to continued improvements and clearer documentation in future releases.

**Comment by tburrows13** [comment]
I’m all for better docs but if you’re concerned about stability and predictability, I wouldn’t recommend updating libraries from 1.x to 2.x in production.

and what you call “ trust and stability” is probably more appropriately called “abandonment and neglect” :)

**Comment by Zulko** [comment]
> and what you call “ trust and stability” is probably more appropriately called “abandonment and neglect” :)

:point_up:  *Stable* abandonmnent and neglect. If this wasn't for a handful of maintainers, the library wouldn't even import today.

Closing this issue. We're doing our best!

**Comment by keikoro** [comment]
@tburrows13 Do the above comments re: docs mean that the [.readthedocs.yml](https://github.com/Zulko/moviepy/blob/49e3f2af039d977a0fe80d2a5ad3afa5334b9009/.readthedocs.yml) file is no longer needed?

**Comment by tburrows13** [comment]
> @tburrows13 Do the above comments re: docs mean that the [.readthedocs.yml](https://github.com/Zulko/moviepy/blob/49e3f2af039d977a0fe80d2a5ad3afa5334b9009/.readthedocs.yml) file is no longer needed?

Yes, I believe so.
