### ISSUE TITLE
Documentation doesn't match ffmpeg presets

### ISSUE THREAD

**Issue by Red5d** [Zulko/moviepy#232]
Using this search will show the sections of the two files that don't match when listing ffmpeg presets:
https://github.com/Zulko/moviepy/search?utf8=%E2%9C%93&q=superfast

Direct links:
https://github.com/Zulko/moviepy/blob/master/moviepy/video/VideoClip.py
https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_writer.py

The VideoClip.py file (which is where it looks like the documentation comes from) lists fewer and slightly different names for the available ffmpeg presets.

The ffmpeg_writer.py file has the correct preset list.

**Comment by mbeacom** [comment]
Updated in #282.
Thank you for reporting!
