### ISSUE TITLE
Add Environment Variable to overwrite FFMPEG_BINARY

### ISSUE THREAD

**Issue by dkarchmer** [Zulko/moviepy#237]
It would be great if I didn't have to manually install the package (rather than just use pip install) if I want to use my own version of ffmpeg.

One solution could be to check if there is an Environment Variable, and if so, use that instead of the defaults (`export FFMPEG_BINARY=ffmpeg`)

If this is an acceptable change, I may be willing to make it. Maybe something as simple as:

```
import os
FFMPEG_BINARY = os.getenv('FFMPEG_BINARY', 'ffmpeg-imageio')
IMAGEMAGICK_BINARY = os.getenv('FFMPEG_BINARY', 'auto-detect')
```

**Comment by Zulko** [comment]
Use this:

    from moviepy.conf import change_settings
    change_settings({"FFMPEG_BINARY": "ffmpeg"})

**Comment by dkarchmer** [comment]
Yes, but I don't want to require that on every one of my users.
I am creating a docker image with the latest ffmpeg and it is hard to use without been able to setup an environment variable.
Are you against using environment variables for any reason? I have a change ready to go. It should be transparent to everybody else.

**Comment by dkarchmer** [comment]
See https://hub.docker.com/r/dkarchmervue/moviepy/~/dockerfile/ for what I am trying to do.
I have a workaround (see end of file) by getting manually getting the source, changing the config_defaults.py and then running `python setup.py install` but I will like to avoid having to manually edit your code as part of the docker image.

I hope you agree it would not be best practices to hard code the binary location in all my scripts, as it is not really best practice to custom build any library.

**Comment by Zulko** [comment]
Can you elaborate on what

**Comment by dkarchmer** [comment]
Pull request tracked with #238 
Closing this one
