### ISSUE TITLE
MoviePy can generate clips of black and silence in front and behind the video?

### ISSUE THREAD

**Issue by salvaestudio** [Zulko/moviepy#239]
I've gotten from FFmpeg add some black frames before and behind a video and insert the timecode that interests me.

I wish I could do the same for a script to do that including a progress bar while video encoding. I would like to make a program in python to do this (I am a very beginner). MoviePy same with what I can get?

**Comment by tburrows13** [comment]
You can use a black ColorClip and concatenate it with the target clip.
