### ISSUE TITLE
Generating Gif from images

### ISSUE THREAD

**Issue by risonsimon** [Zulko/moviepy#240]
Hi,

I'm trying to generate gif from a panoramic image. But I'm having some trouble.

I'm using a modified code from [star worms](http://zulko.github.io/moviepy/examples/star_worms.html).

``` python
            scroll_speed = 200

            fl = lambda gf, t: gf(t)[:, int(scroll_speed * t):int(scroll_speed * t) + w]
            moving_image = image.fl(fl)
            fps = 24
            duration = 7 
            composition = (CompositeVideoClip(
                [moving_image],
                size=gifsize).crossfadein(duration / 2)
                .set_duration(duration).subclip(duration / 2,
                                                3 * duration / 2))
            composition.write_gif(
                'gifs/' + str(datetime.datetime.now()) + '.gif',
                fps=fps, fuzz=1, opt='OptimizePlus')
```

But it has following problems, how do I solve them:
1.  The gif starts at a different point than the beginning of the image. I noticed that when I remove scroll_speed from `fl` equation, it start at the beginning, but fail to move across the image.
2.  Another problem is that since the gif starts at a later point, it ends with blank black space as you can see in the gif.
3.  The size of the gif is **huge**. Sometimes around 10 mb, while the mp4 version is in kbs. I need the gif size to be below 3mb. How can I reduce the size and why is the size this high in the first place?

Here's the image I'm trying to convert.
![682987](https://cloud.githubusercontent.com/assets/871227/11914720/9b225c16-a665-11e5-9225-0d10f6a98bb3.jpg)

And here's the gif:

![2015-12-19 15 41 00 651677](https://cloud.githubusercontent.com/assets/871227/11914769/0762c5a4-a667-11e5-9060-c5830080fb24.gif)

**Comment by risonsimon** [comment]
Any help?

**Comment by dannguyen** [comment]
I can address the filesize part: GIFs are not optimized to efficiently compress video data, so getting a GIF that is significantly bigger than the movie clip is to be expected.

I didn't try out the code but if you're having timing issues, it may be because of the speed calculation vs frame rate. What happens when you tweak them? Are you able to get a result in which the panning cuts out early? Undesireable, obviously, but at least it's a place to start from (as opposed to what you have now, in which the panning extends past the image)

**Comment by risonsimon** [comment]
> What happens when you tweak them?

When I remove `scroll_speed`, the gif starts from the beginning. But if I specify any value for `scroll_speed`, it doesn't start from beginning. 

> Are you able to get a result in which the panning cuts out early?

No, the only other way I could make it kind of start from beginning is by adding a blank black image to the front of the image. 

> I can address the filesize part

How can I achieve this using moviepy?

**Comment by risonsimon** [comment]
I'm still looking for a solution. Any help would be great.

**Comment by risonsimon** [comment]
@Zulko can you help me out?

**Comment by Zulko** [comment]
That part: `set_duration(duration).subclip(duration / 2,  3 * duration / 2)` is strange, basically you are asking your clip to start at `duration/2` (so halfway through the image) and you set an end that is way too far.

I think you don't need to use a CompositeVideoClip, you could just do `moving_image = image.fl(fl).set_duration(7)`, maybe that would work ?

Actually the scrolling effect is already implemented in moviepy ([here](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/scroll.py)) so all you have to do is

```
import moviepy.editor as mpe
image = mpe.ImageClip("some_image.jpeg")
new_clip = clip.fx(mpe.vfx.scroll, w=some_width, x_speed=some_speed)
new_clip = new_clip.set_duration(float(image.w - some_width) / some_speed)
new_clip.write_gif("blabla.gif")
```

Please use stackoverflow or reddit/moviepy for this kind of questions, I prefer to keep Github for issue tracking.

**Comment by kerstin** [comment]
I'm closing this because answers were provided and there was no follow-up by OP (at least not here – it's not clear if the conversation moved to Reddit as suggested).
