### ISSUE TITLE
Credits1 is not working - gap missing, isTransparent flag not available

### ISSUE THREAD

**Issue by SumanthPuram** [Zulko/moviepy#247]
I installed moviePy from pop and trying the credits example and getting following errors : 
1.
  File "/Library/Python/2.7/site-packages/moviepy/video/tools/credits.py", line 97, in credits1
cc = CompositeVideoClip( [left, right.set_pos((left.w+gap,0))],
NameError: global name 'gap' is not defined
1. 
   File "/Library/Python/2.7/site-packages/moviepy/video/tools/credits.py", line 100, in credits1
     transparent=True)
   TypeError: **init**() got an unexpected keyword argument 'transparent'

I got a different error after fixing these two manually. I am just wondering if the credits example has the up to date code.

Thanks for the amazing library. I just wish I could test and use all of them :)

**Comment by kerstin** [comment]
Hi @SumanthPuram, some of the examples are outdated so it could indeed be that that was the problem. Hard to tell though without knowing what the (new) error was.

I'm closing this for now, but please feel free to update/reopen it with more information.
