### ISSUE TITLE
Zoom in/out effect on large image to create a video

### ISSUE THREAD

**Issue by diakonovm** [Zulko/moviepy#252]
Is it possible to use a large resolution image to create a video file that has a much smaller target resolution without incurring the overhead of the `crop` and `resize` methods? Using the current api, the following code illustrates what I mean by a zoom effect.

``` python
TARGET_IMG_RES_WIDTH = 1280
TARGET_IMG_RES_HEIGHT = 720

# Read large image
large_img = ImageClip("large_img.png")

# Create images
filenames = []
for i in range(1, 100):
    filename = "test%s.png" % (i)
    filenames.append(filename)
    # With each iteration the img is smaller - zoom in/out effect
    img = vfx.crop(large_img, x_center=center_x, y_center=center_y, width=width, height=height)
    # Resize to target resolution
    img = img.resize( (TARGET_IMG_RES_WIDTH, TARGET_IMG_RES_HEIGHT) )
    img = img.set_duration(FRAME_INTERVAL)
    img.save_frame(filename)

# Create clip
clip = ImageSequenceClip(filenames, fps=24)
```

**Comment by lolorama** [comment]
Have you found solution for this?

**Comment by tburrows13** [comment]
`VideoFileClip` has a `target_resolution` parameter, which seems to be roughly what you're looking for, except that you are using `ImageClip`.

**Comment by keikoro** [comment]
Closing due to lack of response by OP after a potential solution was proposed.
