### ISSUE TITLE
Avoid writing to disk with ImageSequenceClip

### ISSUE THREAD

**Issue by MDyahkonov** [Zulko/moviepy#261]
I am generating a significant number of images and writing them to disk. I then pass an array of the filenames to `ImageSequenceClip`. A major bottleneck is writing the images down to disk; is there a way to keep the images in memory then pass that to `ImageSequenceClip`, subsequently avoiding the time necessary to write/read to disk? 

```
filenames = []
for i in range(0, FRAMES):
	filename = "tmp/frame_%s.png" % (i)
	filenames.append(filename)
	center_x = IMG_WIDTH / 2
	center_y = IMG_HEIGHT - ((IMG_HEIGHT - i * HEIGHT_INC) / 2) 
	width = IMG_WIDTH - i * WIDTH_INC
	height = IMG_HEIGHT - i * HEIGHT_INC
	img = vfx.crop(img_w_usr_img, x_center=center_x, y_center=center_y, width=width, height=height)
	img = img.resize( (VID_WIDTH, VID_HEIGHT) )
	img.save_frame(filename)
	print "Proccessed: %s" % (filename)

seq = ImageSequenceClip(filenames, fps=FPS)
```

**Comment by MDyahkonov** [comment]
I ended up using `get_frame()` to get the numpy array  of the image and it works much faster now.

**Comment by Zulko** [comment]
The snippet you provide doesn't allow me to give the best answer. There are many ways to do this in MoviePy, e.g. using VideoClip or ImageSequenceClip:

```
def make_frame(t):
    return some_numpy_array #  corresponding to the frame to display at time t

clip = VideoClip(make_frame, duration).set_fps(20)
clip.write(videofilename)
```
or

```
frames = []
for i in range(50):
    frames.append(some_frame) # some_frame is a numpy array of an image

clip = ImageSequenceClip(frames, fps=20)
clip.write(videofilename)
```
