### ISSUE TITLE
IndexError when saving thumbnail for VideoClip made by concatenate_videoclips()

### ISSUE THREAD

**Issue by augustjd** [Zulko/moviepy#262]
As mentioned, when you try and call `save_frame()` with `t` > the duration of the video in an ordinary VideoClip, it saves without complaint.

However, VideoClips as generated by `concatenate_videoclip()` end up calling `make_frame()`, and due to a bad assumption made in **concatenate.py**:

``` python
def make_frame(t):
    i = max([i for i, e in enumerate(tt) if e <= t]) 
    return clips[i].get_frame(t - tt[i])
```

If provided with a value for `t` > the duration of the video, the last line triggers an IndexError.

Not 100% sure what would be best here - I realize that `save_frame()` is not marked as `requires_duration`, but perhaps, if a duration is present, the user can at least be informed of this issue  with a better error message?

Best of all would be to bring this behavior in line with the way an ordinary `VideoClip` works, i.e. it just takes the last frame of the video if the timestamp is specified beyond the duration of the video.

To reproduce this:

``` python
from moviepy.editor import concatenate_videoclips, VideoFileClip

clip = VideoFileClip("./10_seconds.mp4") # 10 seconds long
clip.save_frame("thumbnail.jpg", 100)

clip2 = concatenate_videoclips([clip, clip])
clip2.save_frame("thumbnail2.jpg", 100) # triggers IndexError
```

**Comment by keikoro** [comment]
Closing this as it's a very old issue without any new activity in several years and it's unclear if this is even still a problem. 

Feel free to open a new issue following our issue template and referencing this old issue if the problem persists with the latest recommended version of MoviePy. We also welcome PRs that improve the docs or error messages etc.!
