### ISSUE TITLE
Is there any documentation on how to use masking?

### ISSUE THREAD

**Issue by mhfowler** [Zulko/moviepy#271]
http://stackoverflow.com/questions/35857005/how-do-you-use-masks-from-pngs-with-moviepy

Thanks for any help -- Max

**Comment by keikoro** [comment]
@mhfowler Did you manage to solve the problem via the info provided on SO? Do you have a suggestion for info that should get added to the docs? (PRs welcome) Looking to close this issue as it's rather old.

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.
