### ISSUE TITLE
MoviePy error: the file "film.mp4" could not be found in Django project

### ISSUE THREAD

**Issue by millroad23** [Zulko/moviepy#273]
Hi,
Moviepy works great when running stand alone py scripts and the file is in the same path but when trying to work with files in Django and the files are in the MEDIA_URL path I get this error:
Exception Location: /Library/Python/2.7/site-packages/moviepy/video/io/ffmpeg_reader.py in ffmpeg_parse_infos, line 253

Would be great if anybody had some ideas, thanks!

**Comment by kerstin** [comment]
@millroad23 Did you figure out what the problem was? What exactly was Django complaining about? (Your message doesn't say what the error was, only where it occurred.)

**Comment by tburrows13** [comment]
I'm closing this because it is old, and likely not even an issue with Moviepy.
