### ISSUE TITLE
ffmpeg_resize refers to undefined globals

### ISSUE THREAD

**Issue by personalnadir** [Zulko/moviepy#276]
Line 65 in ffmpeg_tools refers to res, which I think should refer instead to the size parameters passed in. 

```
  File "main.py", line 24, in <module>
    io.ffmpeg_tools.ffmpeg_resize(video, "wash_"+str(pattern)+ "_circles.mp4", [100,100])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_tools.py", line 65, in ffmpeg_resize
    cmd= [get_setting("FFMPEG_BINARY"), "-i", video, "-vf", "scale=%d:%d"%(res[0], res[1]),
NameError: global name 'res' is not defined
```

**Comment by calebshafer** [comment]
I was having this problem too, and I did just change 'res' to 'size' and it seems to work.

**Comment by agalamatis** [comment]
Same problem, I changed the source code and it worked fine.

**Comment by kerstin** [comment]
All: could you let us know what needs to be fixed or submit a PR with a fix if this is about MoviePy's source code? Also, is this something that is not properly or incorrectly documented? Thanks.

**Comment by tburrows13** [comment]
This is currently fixed.
