### ISSUE TITLE
Allow tdqm progress bars to be disabled

### ISSUE THREAD

**Issue by personalnadir** [Zulko/moviepy#278]
The use of tdqm progress bars is fantastic when running from the terminal, but causes issues if you package your script using py2app. They cause Errno 32 Broken Pipe whenever the packaged app calls VideoClip.write_videofile. The code which calls tdqm is in Clip.iter_frames, which does support disabling the progress bars, but ffmpeg_writer.ffmpeg_write_video sets this to True.

From my limited experience, if tdqm can be disabled, moviepy can be used to created packaged Mac apps.

**Comment by Zulko** [comment]
Ok. If you make a PR I'll merge it.

**Comment by brianthelion** [comment]
Status?

**Comment by derblub** [comment]
+1

**Comment by Gloin1313** [comment]
This has been added in this PR. https://github.com/Zulko/moviepy/pull/300/files. I'll push to merge it soon

**Comment by codeAshu** [comment]
This is actually giving me error and I don't know why. When I run it on my OSX it works fine, but same code deployed on aws linux throws this error - 
`
clip.audio.to_audiofile(audio_file)\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/tools.py\", line 130, in fdepr\n    return f(*a, **kw)\n   File \"<decorator-gen-73>\", line 2, in write_audiofile\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/decorators.py\", line 54, in requires_duration\n    return f(clip, *a, **k)\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/audio/AudioClip.py\", line 208, in write_audiofile\n    progress_bar=progress_bar)\n   File \"<decorator-gen-70>\", line 2, in ffmpeg_audiowrite\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/decorators.py\", line 54, in requires_duration\n    return f(clip, *a, **k)\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py\", line 161, in ffmpeg_audiowrite\n    progress_bar=progress_bar):\n   File \"<decorator-gen-71>\", line 2, in iter_chunks\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/decorators.py\", line 54, in requires_duration\n    return f(clip, *a, **k)\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/moviepy/audio/AudioClip.py\", line 84, in iter_chunks\n    return tqdm(generator(), total=nchunks)\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/tqdm/_tqdm.py\", line 742, in __init__\n    self.postfix))\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/tqdm/_tqdm.py\", line 199, in print_status\n    fp_write('\\r' + s + (' ' * max(last_len[0] - len_s, 0)))\n   File \"/home/ubuntu/.env/spextenv/local/lib/python2.7/site-packages/tqdm/_tqdm.py\", line 192, in fp_write\n    fp.write(_unicode(s))\n"
`

**Comment by tburrows13** [comment]
This feature has long since been included. The most recent comment is not really related, and if you are experiencing the same problem, please open a new issue.
