### ISSUE TITLE
nine subwindows video played while requiring only one 

### ISSUE THREAD

**Issue by gregorybo** [Zulko/moviepy#280]
Hei,

I have a problem running a small script using moviepy.

Here is a description of what I am doing:
I have a list of numpy array (int32) called **imagearray**. Each numpyarray contains 40 - 200 two dimensionnal numpy array that are 1024 by 1024 in size. So the dimension of one element of the list is e.g. 40 times 1024 times 1024. I would like to make a videoclip of the elements of these list and make som video processing. I use the following script for the moment: 

```
from PIL import Image
import cv2
from moviepy.editor import ImageSequenceClip

# transform list as a numpy array
def numpyimage(name):
    return np.asarray(imagearray[name])

# get numpy array from one of the element of the list. 
testimage = numpyimage('ExampleImage.tif') #The dimension of testimage is (70L, 1024L, 1024L)

# I convert the (70L, 1024L, 1024L) numpy array to a list of 70 numpy array with 8 bits detph  
jpgsequence = [cv2.convertScaleAbs(testimage[i,:,:],alpha=(255.0/65535.0)) for i in np.arange(0,testimage.shape[0],1)] 

# create an ImageSequenceClip out of it
animation = ImageSequenceClip(jpgsequence, fps=1)
# and write it as a mp4
animation.write_videofile('test.mp4',fps=10,codec='mpeg4')
```

I do get a test.mp4 file, that run a video with the required 70 images. The problem is that instead of a large window running the video, I get 9 subwindows, each playing the same video. 

I do not manage to figure why this is happening. Could it be related to RGB issue? That one must specify that this is grey images one would like to run and not RGB?  Any ideas of why this is happening?

Thanks for any help.

Greg

**Comment by linuxjackto7** [comment]
Deadpool (2016) 720P Download ：https://movied.org/deadpool-2016_801438.html

**Comment by Zulko** [comment]
Any way you can share the file, I may be able to help on this.

**Comment by gregorybo** [comment]
Hei Zulko,
I can share the file on a dropbox repertory with you, because it is quite large, but I would need an email address. 
Grégory

**Comment by gregorybo** [comment]
Hei Zulko, 
I uploaded the video file, as well as the numpy array I used to generate it.
I tried a simplified code to generate the .mp4 but got the same result as in my first post: 

`def MakeFrameFromNumpy(t):
    return np.asarray(NumpyArray[t,:,:])
AnimationNumpyArray = VideoClip(MakeFrameFromNumpy,duration = 5)
AnimationNumpyArray.write_videofile('testNumpyArray.mp4',fps=10)
`

Grégory


[NumpyVideo.zip](https://github.com/Zulko/moviepy/files/295112/NumpyVideo.zip)

**Comment by keikoro** [comment]
Closing this as it's a very old issue without any new activity in several years.

Feel free to reopen it – or better yet, open a new issue following our issue template and referencing this issue – if the problem persists with the latest recommended version of MoviePy.
