### ISSUE TITLE
Adding subtitles doesn't work

### ISSUE THREAD

**Issue by pelednoam** [Zulko/moviepy#283]
Hey all,
I've tried to add subtitles (following [this example](https://zulko.github.io/moviepy/ref/videotools.html#module-moviepy.video.tools.subtitles)) and not sure why, it didn't work. What am I doing wrong?

```
from moviepy.video.tools.subtitles import SubtitlesClip
from moviepy.video.io.VideoFileClip import VideoFileClip
subs = [((0, 3), 'sub1'),
        ((3, 7), 'sub2'),
        ((9, 11), 'sub3'),
        ((11, 16), 'sub4')]
subtitles = SubtitlesClip(subs)
clip = VideoFileClip(video_fname)
video = movedit.CompositeVideoClip([clip, subtitles])
video.to_videofile(output_video_name)
```

btw, the subtitles.py doesn't work with python 3, this line of code
`subtitles = [(map(cvsecs, tt),txt) for tt, txt in subtitles]
`Is needed to be changed to
`subtitles = [(list(map(cvsecs, tt),txt)) for tt, txt in subtitles]`

**Comment by kerstin** [comment]
Just tried this unsucessfully as well. @pelednoam did you ever manage to get it to work?

**Comment by pelednoam** [comment]
Yes, I've used the following workaround:

```
def add_text_to_movie(movie_fol, movie_name, out_movie_name, subs, fontsize=50, txt_color='red', font='Xolonium-Bold'):
    from moviepy import editor

    def annotate(clip, txt, txt_color=txt_color, fontsize=fontsize, font=font):
        """ Writes a text at the bottom of the clip. """
        txtclip = editor.TextClip(txt, fontsize=fontsize, font=font, color=txt_color)
        cvc = editor.CompositeVideoClip([clip, txtclip.set_pos(('center', 'bottom'))])
        return cvc.set_duration(clip.duration)

    video = editor.VideoFileClip(op.join(movie_fol, movie_name))
    annotated_clips = [annotate(video.subclip(from_t, to_t), txt) for (from_t, to_t), txt in subs]
    final_clip = editor.concatenate_videoclips(annotated_clips)
    final_clip.write_videofile(op.join(movie_fol, out_movie_name))

```

**Comment by kerstin** [comment]
Thank you! I only realised too late that what I tried was different from what you did (I tried with an existing `.srt` file) but I think I'll switch to creating manual subs now anyway, so your workaround code is appreciated!

**Comment by YoWhatever** [comment]
@kerstin Have you managed to add a .srt file to a video? Can you show me how? Thanks!!

**Comment by earney** [comment]
@YoWhatever   see [https://github.com/Zulko/moviepy/blob/master/tests/test_misc.py](https://github.com/Zulko/moviepy/blob/master/tests/test_misc.py)  for an example of adding an srt to a video.

**Comment by llazzaro** [comment]
Hi,
I tried this with the `ColorClip` and it works fine. When using another video clip, I can see the subtitles but no video.

**Comment by llazzaro** [comment]
Found the solution, I leave it here just someone cames here by using google. CompositeVideoClip has the use_bgclip with default value `False`, change it to `True` and the video will be shown with subtitles.

**Comment by dzapologize** [comment]
> op.join

Hi, is the “op.join”  here, os.path.join? or is it some other package?

**Comment by pelednoam** [comment]
Yes, it's os.path.join (import os.path as op)

**Comment by pelednoam** [comment]
Yes, it's op.join (import os.path as op)

**Comment by amirdolev** [comment]
Hi. I have a code that is working well for all but one MP4 file. All MP4 files came from the same source. Any idea what may be the issue? I do not see any errors, but the output file doesn't include subtitles.
