### ISSUE TITLE
audio in clip.write_videofile

### ISSUE THREAD

**Issue by rschmaelzle** [Zulko/moviepy#288]
Hi, I am trying to add audio to a videoclip created from individual frames. For convenience, I am trying to pass on an AudioFileClip rather than a path to an audiofile. I had assumed this should work, but it doesn't. Here is the code that produces the empty audio file as well as the more cumbersome code that has audio in it:

```
clip = mp.ImageSequenceClip(files, fps=30)

clipaudio = mp.VideoFileClip(video_filename).subclip(0,34)

#this does not work
clip.write_videofile("full_movies_sound_clipaudio.mp4",fps=30, codec='libx264', audio=clipaudio.audio) 

#this works
clipaudio.audio.write_audiofile("theaudio2.mp3", fps = 22050)
clip.write_videofile("full_movies_sound.mp4",fps=30, codec='libx264', audio="theaudio2.mp3") 

```

thought that write_videofile would accept the AudioFileClip from clipaudio.audio? Thanks, R

**Comment by tburrows13** [comment]
I'm leaving the open as the docs or the API could be improved here. Currently, the `audio` parameter only accepts a boolean or a string (filename), but if it is neither, then it is ignored which is not great. The preferred way to do it currently would be to do `clip = clip.set_audio(audioclip)` first.

**Comment by tburrows13** [comment]
Closing - continue discussion in #1339.
