### ISSUE TITLE
How to apply "bold effect" to the text when using a TextClip

### ISSUE THREAD

**Issue by hellovenkat** [Zulko/moviepy#307]
basically I just want to create a textclip object with the bold effect applying to the text. Is there any parameter for that? I searched for that and I cant find any in this link. It would be very helpful to know.
https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html?highlight=textclip#moviepy.video.VideoClip.TextClip

**Comment by flothesof** [comment]
Hi, 
while reading the documentation for moviepy, I stumbled across an example that might answer your question: for bold fonts try to add "bold" to the font name.
The line is:

```
the_end = TextClip("The End", font="Amiri-bold", color="white",
                   fontsize=70).set_duration(clip.duration)
```

It's taken from [this example](https://zulko.github.io/moviepy/examples/the_end.html).

Best,
Florian

**Comment by kerstin** [comment]
@hellovenkat Did @flothesof suggestion help you fix your problem?

**Comment by Cyberghost999** [comment]
No, you can check the available fonts in your operating system. Only some of them have the "Bold" version.
