### ISSUE TITLE
movie duration changes after write_Videoclip

### ISSUE THREAD

**Issue by jwe080** [Zulko/moviepy#308]
Hi,

I'm making movie subclips and saving as a new mp4 with moviepy.  However, the duration of the clip is changed when you reopen the file, it's 0.04 s longer in this case.  This causes an issue with converting the audioclip to a soundarray because it is missing a few data points at the end. FWIW, if you take a subclip of this subclip and remove a few end points  (e.g 0.01s) you can convert the audio to a soundarray without problems.  Just don't try saving it because it will falsely increase the duration of the clip and you'll get the same error with the soundarray length.

Any help fixing this would be appreciated.  Thanks.

Jen

In [119]: sub = video.subclip('00:00:29', '00:00:45')

In [120]: sub.write_videofile('test.mp4')
[MoviePy] >>>> Building video test.mp4
[MoviePy] Writing audio in testTEMP_MPY_wvf_snd.mp3
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 353/353 [00:01<00:00, 336.59it/s]
[MoviePy] Done.
[MoviePy] Writing video test.mp4
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 480/481 [00:04<00:00, 101.12it/s]
[MoviePy] Done.
[MoviePy] >>>> Video ready: test.mp4 

In [121]: sub.duration
Out[121]: 16.0

In [122]: mov = meditor.VideoFileClip('test.mp4')

In [123]: mov.duration
Out[123]: 16.04
## In [126]: mov.audio.to_soundarray()

IOError                                   Traceback (most recent call last)
<ipython-input-126-d0a283e29d16> in <module>()
----> 1 mov.audio.to_soundarray()

<decorator-gen-179> in to_soundarray(self, tt, fps, quantize, nbytes, buffersize)

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.pyc in requires_duration(f, clip, _a, *_k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, _a, *_k)
     55 
     56 

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.pyc in to_soundarray(self, tt, fps, quantize, nbytes, buffersize)
    112             if self.duration>max_duration:
    113                 return stacker(self.iter_chunks(fps=fps, quantize=quantize, nbytes=2,
--> 114                                                  chunksize=buffersize))
    115             else:
    116                 tt = np.arange(0, self.duration, 1.0/fps)

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/numpy/core/shape_base.pyc in vstack(tup)
    226 
    227     """
--> 228     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    229 
    230 def hstack(tup):

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.pyc in generator()
     79                 tt = (1.0/fps)*np.arange(pospos[i],pospos[i+1])
     80                 yield self.to_soundarray(tt, nbytes= nbytes, quantize=quantize, fps=fps,
---> 81                                          buffersize=chunksize)
     82 
     83         if progress_bar:

<decorator-gen-179> in to_soundarray(self, tt, fps, quantize, nbytes, buffersize)

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.pyc in requires_duration(f, clip, _a, *_k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, _a, *_k)
     55 
     56 

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.pyc in to_soundarray(self, tt, fps, quantize, nbytes, buffersize)
    125         #print tt.max() - tt.min(), tt.min(), tt.max()
    126 
--> 127         snd_array = self.get_frame(tt)
    128 
    129         if quantize:

<decorator-gen-121> in get_frame(self, t)

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.pyc in wrapper(f, _a, *_kw)
     87         new_kw = {k: fun(v) if k in varnames else v
     88                  for (k,v) in kw.items()}
---> 89         return f(_new_a, *_new_kw)
     90     return decorator.decorator(wrapper)
     91 

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.pyc in get_frame(self, t)
     93                 return frame
     94         else:
---> 95             return self.make_frame(t)
     96 
     97     def fl(self, fun, apply_to=[] , keep_duration=True):

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/AudioFileClip.pyc in <lambda>(t)
     69 
     70 
---> 71         self.make_frame =  lambda t: reader.get_frame(t)
     72         self.nchannels = reader.nchannels
     73 

/Users/evansjw/Library/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/readers.pyc in get_frame(self, tt)
    191                        "At time t=%.02f-%.02f seconds, "%(tt[0], tt[-1])+
    192                        "indices wanted: %d-%d, "%(indices.min(), indices.max())+
--> 193                        "but len(buffer)=%d\n"%(len(self.buffer))+ str(error))
    194 
    195         else:

IOError: Error in file test.mp4, At time t=15.87-16.04 seconds, indices wanted: 100000-107363, but len(buffer)=107334
index 107334 is out of bounds for axis 0 with size 107334

**Comment by earney** [comment]
@jwe080   are you still having this issue?   if so, is there a way you can provide us a sample that does the same thing?

**Comment by jwe080** [comment]
Yeah, the workaround I've been using is re-cutting it and rounding.  Let me
know if you still need a clip.

------

import moviepy.editor as meditor

fn='film_clips/'

video = meditor.VideoFileClip(fn+'ForrestGumpclip.mp4')


# the audioclip seems to have a rounding error, which is 'fixed' by lopping
off 0.01 seconds.

print video.duration

sub2 = video.subclip(0,video.duration-0.01)

print sub2.duration


sub2.write_videofile('Gump_jwe.mp4')

-----

**Comment by gyglim** [comment]
related to this PR and the issues linked: https://github.com/Zulko/moviepy/pull/377/

**Comment by timtan** [comment]
I meet the same problem. 

may I know why  #377 is related?

**Comment by keikoro** [comment]
Closing this as it's a very old issue without any new activity in several years and it's unclear if this is even still a problem. 

Feel free to open a new issue following our issue template and referencing this old issue if the problem persists with the latest recommended version of MoviePy.
