### ISSUE TITLE
librelist does not work

### ISSUE THREAD

**Issue by videobrain** [Zulko/moviepy#309]
I sent two emails to moviepy@librelist.com and got no answer, seems to be broken.

It would be really very nice to have some discussion group for this wonderful piece of software, it feels a little bit abandoned without a public discussion group. The Reddit group for me looks more like kind of a 'show what you did with moviepy', slightly different from malinglists, also not in your inbox.

I would like to suggest to create a Google Group for moviepy - I still hope there will be some day a provider big enough to do a reliable version of librelist, however as long as it is not for private communications I believe Google is ok for this kind of thing. 

What do you think?

**Comment by kerstin** [comment]
Hi @videobrain, according to @Zulko, the list should still work, but there is a brand new [Gitter community](https://gitter.im/movie-py) for the project also, which I guess is the kind of thing you were looking for. (:
