### ISSUE TITLE
ImageClip's with default settings can not be concatenated

### ISSUE THREAD

**Issue by AlexanderNickolsky** [Zulko/moviepy#314]
How to reproduce:
Create two ImageClips from images. Pass them as arguments to concatenate_videoclips.
The result is an error.

The reason is somewhat complicated. The ImageClip, created with default settings, has a mask. A mask is itself a clip and has no duration attribute. These masks  are concatenated using the same concatenate_videoclips functions which requires duration attribute.

Possible fix. There are many possible ways of fixing this, but the simplest is to set duration attribute of the mask clip in VideoClip.py

```
            elif transparent:
                self.mask = ImageClip(
                    1.0 * img[:, :, 3] / 255, ismask=True, **duration=duration** )
```

**Comment by earney** [comment]
@AlexanderNickolsky ..  I believe this is fixed now..   Can you reopen if, if it persists?
