### ISSUE TITLE
is there a way to composite a video with a alpha channel?

### ISSUE THREAD

**Issue by WaterThin** [Zulko/moviepy#317]
I have two videos
video1 : have a alpha channel, RGBA
video2  :dont have a alpha channel, RGB

I try to put video1 top on the video2,
I am using CompositeVideoClips([video1, video2]), but not work
and I try to use the video mask
but i read wiki the mask is only have 1and0 for is value?

is there any way to use the video's alpha channel?
if CompositeVideoClips can support this ,will be the best.

**Comment by Zulko** [comment]
Try loading video1 with:

    video1 = VideoFileClip("myvideo1.mp4", has_mask=True)

**Comment by WaterThin** [comment]
thank you , my problem has solved^_^
