### ISSUE TITLE
Documentation for resize parameter is wrong

### ISSUE THREAD

**Issue by hbradlow** [Zulko/moviepy#319]
The documentation [here](https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.resize.html) says that the `newsize` tuple is in format `(height,width)` but the [function](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/resize.py#L92) decodes the parameter as `w, h = clip.size`.

**Comment by earney** [comment]
Pull request #346 was merged into the repo.  I believe this issue has been resolved.
