### ISSUE TITLE
Does Moviepy work with a Raspberry Pi?

### ISSUE THREAD

**Issue by Gloin1313** [Zulko/moviepy#322]
I am trying to use moviepy with my raspberry pi (for python 3.2) but I get an error message as soon as I try to load a videofileclip. It is a unhelpful error message but I think it is OSerror. Are raspberry pis supported? It may be a completely unrelated problem, but I am copying some of the code directly off the tutorials...

**Comment by flothesof** [comment]
Hi @Gloin1313,

Can you post your precise error message? That would help.
I'm no expert, but I believe moviepy could work with a raspberry pi.

Best,
Florian

**Comment by Gloin1313** [comment]
I input the following code:
`from moviepy import *
clip = VideoFileClip("vid.mov")`
And it outputs a long error ending with "raise child_exception_type" via some FFMPEG modules.
The error is :
'OSError: [Errno 8] Exec format error'

If I input:

**Comment by flothesof** [comment]
Hi @Gloin1313,
I'm no expert, but there could be a lot of reasons. For instance I'm thinking of these:

- ffmpeg is not installed
- the files you are referring to are in a location different from your working directory
- moviepy is not compatible with Python 3.2 

Each of these issues can be investigated. 
My suggestion would be as follows.
- create a virtual environment with Python 2.7 using the conda utility
- activate this environment
- install moviepy using pip
- try loading the clips above again

The logic behind this is: (disclaimer: I'm a Python 3.5 user) moviepy sometimes does strange things with Python 3 so falling back to 2 for testing seems a good idea. 

Let me know if you need more details about the procedure.
Best,
Florian

**Comment by Gloin1313** [comment]
@flothesof 
Thanks,
I have run the same program using the python2 idle on the raspberry pi. The videofileclip method gave an identical error message, and the imageclip method gives a different error message.
Regarding the possible problems you listed;
I thought FFMPEG was supposed to automatically download with moviepy, if it didn't how to I go about doing it again?
The program is running in the same folder as the pictures/videos.
I am trying to update the python idle to 3.5, but am struggling...

**Comment by Gloin1313** [comment]
Turns out, no, moviepy does not work entirely normally on the RPi. After discussion in [this](http://stackoverflow.com/questions/40004639/moviepy-oserror-exec-format-error-missing-shebangl) post, it transpires that the ffmpeg that is downloaded does not work with the RPi.  To get the right version, follow [these](http://hannes.enjoys.it/blog/2016/03/ffmpeg-on-raspbian-raspberry-pi/) instructions, then it should work fine.

**Comment by flothesof** [comment]
Nice @Gloin1313, you fixed it! Congrats! It would be worthwhile to document this in the FAQ or somewhere. What do you think @Zulko?
Best,
Florian

**Comment by Gloin1313** [comment]
Yes, I agree
