### ISSUE TITLE
TextClip generates an error when written to disk

### ISSUE THREAD

**Issue by flothesof** [Zulko/moviepy#323]
Hi,
I'm having the following use case:
- I have a movie from which I want to make subclips
- each subclip starts with an introduction texts (a few seconds)

I'm having the hardest time doing this with moviepy.

Basically, I tried to start with your example from the crash-course but instead concatenate with my other existing subclip.

```
from moviepy.editor import TextClip, concatenate
txt_clip = TextClip("My Holidays 2013",fontsize=70,color='white')
# Say that you want it to appear 2s at the center of the screen
txt_clip = txt_clip.set_pos('center').set_duration(2)
# Concatenate the text clip with the subclip
video = concatenate([txt_clip, clip])
# Write the result to a file
video.write_videofile("subclip.mp4",fps=24, codec='mpeg4')
```

The problem with this is that this doesn't work: the written file is not readable with VLC. 

Running ffmpeg -i on it yields:

```
ffmpeg version 2.8 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.0 (clang-700.0.72)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff895000000] moov atom not found
subclip.mp4: Invalid data found when processing input
```

Any idea on how to help?

Thanks in advance,
Florian

**Comment by earney** [comment]
I can verify that this is still an issue.

Here is some code that can be used with the media files we have in the test/media directory.
```
clip=VideoFileClip("media/knights.mp4").subclip(50,60)

txt_clip = TextClip("My Holidays 2013",fontsize=70,color='white')
# Say that you want it to appear 2s at the center of the screen
txt_clip = txt_clip.set_pos('center').set_duration(2)
# Concatenate the text clip with the subclip
video = concatenate([txt_clip, clip])
# Write the result to a file
video.write_videofile("subclip.mp4",fps=24, codec='mpeg4')
```

**Comment by zakisaad** [comment]
FWIW, seems to be an underlying issue with ffmpeg... I am having this issue when using ImageClips (using ffmpeg 3.3 on Arch Linux, official repos)

**Comment by flyte** [comment]
Does anybody have a workaround for this?

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any updates in years, so it's impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
