### ISSUE TITLE
Pythonanywhere Moviepy

### ISSUE THREAD

**Issue by pirali** [Zulko/moviepy#324]
What is problem?
I'm running on Pythonanywhere.com.

```
[MoviePy] This command returned an error !Traceback (most recent call last):
  File "deneme.py", line 6, in <module>
    txt_clip = TextClip("My Holidays 2013",fontsize=70,color='white')
  File "/home/pirali/.local/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 1145, in __init__
    raise IOError(error)
IOError: MoviePy Error: creation of None failed because of the following error:
Youtube Foto Galeri: not authorized `@/tmp/tmpxjn5vu.txt' @ error/property.c/InterpretImageProperties/2959.
Youtube Foto Galeri: no images defined `PNG32:/tmp/tmp3lNxp8.png' @ error/convert.c/ConvertImageCommand/3044.
.
.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to th
e ImageMagick binary in file conf.py, or.that the path you specified is incorrect
```

**Comment by flothesof** [comment]
Hi @pirali,
Do you have access to the command line from pythonanywhere? If so, you could test whether ImageMagick is installed by typing:
`convert`
If it outputs something, ImageMagick is installed, else it's not.
It would make sense that this is the problem, as ImageMagick is used behind the scenes to generate the text backgrounds.
Best,
Florian

**Comment by pirali** [comment]
convert
Version: ImageMagick 6.7.7-10 2016-06-01 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC

**Comment by flothesof** [comment]
Okay, another thought: your command line message says moviepy is (temporarily) writing a file to /tmp, which doesn't seem to be authorized (you don't have rights to write there).

That's a tough one. Maybe contact pythonanywhere to find out if there is a way to write to /tmp?

Best,
Florian

**Comment by kerstin** [comment]
Closing this for now due to lack of follow-up comments regarding the issue. Please consider updating with solutions you found.
