### ISSUE TITLE
CI Testing

### ISSUE THREAD

**Issue by birm** [Zulko/moviepy#325]
The tests aren't run on commit. We could set up travis to run the tests to assure that new commits don't break the project.
We should also probably expand regression testing where possible.

**Comment by flothesof** [comment]
Hi @birm!
I'm not officially involved in moviepy, but strongly in favor of adding some tests. 
Would @Zulko be willing to accept pull requests regarding tests?
Best,
Florian

**Comment by kerstin** [comment]
Introducing tests would be cool! Not sure if Zulko currently accept PRs though.

**Comment by earney** [comment]
closing this issue, because we have travis-ci and coveralls running..  Please reopen the issue if you need to.
