### ISSUE TITLE
ImageSequenceClip: Error when fps not provided but durations provided

### ISSUE THREAD

**Issue by jeromegrosse** [Zulko/moviepy#326]
[This line](https://github.com/Zulko/moviepy/blob/d4c9c37bc88261d8ed8b5d9b7c317d13b2cdf62e/moviepy/video/io/ImageSequenceClip.py#L54) throws an error when both `fps` and `duration` are not provided. Isn't it a typo? Shouldn't it be `durations` as it is impossible to pass `duration` to ImageSequenceClip?

**Comment by earney** [comment]
A pull request has been merged that corrects your issue. . Thanks!
