### ISSUE TITLE
Help with contributing to the documentation?

### ISSUE THREAD

**Issue by keikoro** [Zulko/moviepy#327]
Heya @Zulko, could you possibly add some basic info on how to contribute to the documentation to the project's `README` (the main one in the master branch)? I was going to make some edits and actually already started but now realised I should probably not edit the html files because... they get generated?

Which files would I need to edit and how would I test they look alright? Thanks!

**Comment by kerstin** [comment]
(Right now, I'm specifically looking for how to contribute to the [Videotools](https://zulko.github.io/moviepy/ref/videotools.html)/Subtitles section.)

**Comment by kerstin** [comment]
Ping! Could it be that parts of the reference manual are missing from the repo? Like, entire folders?

I tried to compare the online documentation with the contents in `gh-pages` and would have expected files for the [Reference Manual](https://zulko.github.io/moviepy/ref/ref.html) to be in here: [gh-pages/_sources/ref](https://github.com/Zulko/moviepy/tree/gh-pages/_sources/ref). (Based on the other files in that branch, I'm guessing most of the documentation is saved in `.txt` files which are then turned into HTML.)

I wanna help improve the docs, and ideally while Hacktober is still going on. ^^

**Comment by kerstin** [comment]
@mbeacom I saw you merged stuff and added labels to new issues, are you helping maintain the project now? I've been checking back every couple of months and was sad to never see it getting updated or issues receiving replies etc.

I'd still love to help make moviepy better because I myself want to use an improved version. (:

**Comment by Gloin1313** [comment]
I also wouldn't mind contributing to the documentation [here](http://zulko.github.io/moviepy/). I'm not good enough at python to contribute to the actual codebase, but I understand most of it.

**Comment by Zulko** [comment]
@kerstin @Gloin1313 , thanks for proposing some help, are you interested in becoming maintainers (= being able to merge to the git repo, which includes the online documentation) ? CC @mbeacom

**Comment by kerstin** [comment]
@Zulko Ohhh, I'd love to!! Though I guess it also depends on how much of a responsibility it is (: or what the workload would be (I'm not always "around" myself).

Then again, I imagine there's no master plan for the project ^^ and any help is better than none, so yeah, I'm up for it!!

**Comment by Gloin1313** [comment]
@Zulko As I said, I'm not good enough currently to contribute to the actual code, but it would be something for me to aim towards (I have a few ideas for things to create). I've also never used GitHub before either. I can certainly work on updating the docs though; there is much to be desired there.

I can't guarantee any commitment, but if you are happy with that, so am I.

**Comment by kerstin** [comment]
@Gloin1313 Have you used git before? If not, I think it can be a little overwhelming at first, but there are lots of resources out there and a little practice can go a long way. Documentation is also really important, so I would not worry about not being able to contribute much or any code at this point!

**Comment by Gloin1313** [comment]
@kerstin Only a tiny bit, but it is such a useful thing to learn anyway I don't mind!

**Comment by Gloin1313** [comment]
@Zulko @mbeacom Yes, I would definitely love to be a collaborator on this project

**Comment by Zulko** [comment]
@kerstin @Gloin1313 @earney @mbeacom Thanks for caring about the library, I have granted all of you push access to the repo, that'll be more fun that way. Please use it wisely ! All docs improvements are welcome, but avoid drastic code/api changes without previous discussion. 

Also, please keep Github conversations concise, and use [r/moviepy](https://www.reddit.com/r/moviepy/) for broader discussions.

Thanks again !

**Comment by Gloin1313** [comment]
@Zulko Thank you. If I want to edit the documentation, do I have to do it by editing the html files in the gh-pages branch, or is there an easier way? Thanks

**Comment by Zulko** [comment]
The HTML is autogenerated from the files that are in the `doc` repository. The language is some sort of RST (very near to markdown) so you should be able to write new stuff easily. You will need to read about sphinx ([here](http://www.sphinx-doc.org/en/stable/)) to compile it to html, but I could do that for you. If you need more support, r/moviepy would be the place for discussion.

**Comment by kerstin** [comment]
@Zulko Thanks so much!!

I don't really use Reddit – would it perhaps make sense to discuss something like workflow via e-mail? (I'm really only talking about "meta" stuff that is not so relevant to other people interested in contributing to the project/perusing the repo.)

**Comment by kerstin** [comment]
Regarding your reply to @Gloin1313 about the `docs` directory: if all the documentation is in `docs` on master... what is the `gh-pages` branch?

I originally assumed it to host the documentation because GitHub's .io pages usually mirror that. Is it just an old, outdated branch now which we should ignore?

**Comment by Zulko** [comment]
The docs directory contains the "code" that will generate the docs. These docs need to be compiled into HTML and the HTML is then pushed to the gh-pages branch. It's well explained online. This is the standard way of documenting a python package with Sphinx, see here for instance:

https://daler.github.io/sphinxdoc-test/includeme.html

**Comment by kerstin** [comment]
Okay, thank you, I knew GitLab could do that but have never used Sphinx with GitHub (and only the tiniest bit on GL so far). I only ever manually pushed to `gh-pages` and I guess I was thrown off by the `docs` directory having a commit that was not reflected in the `gh-pages` branch as far as I could see (`install.rst`, commit from December 2015).

**Comment by kerstin** [comment]
@Reuben-Thorpe Hey there, please join the new MoviePy Gitter (linked from the README, badge at the top) – it's open to everyone and was created specifically for chatting about the project/"meta" discussions so as to keep the GitHub issues free of them.
