### ISSUE TITLE
VideoClip.write_images_sequence() is slow

### ISSUE THREAD

**Issue by datamut** [Zulko/moviepy#340]
It is slow to use VideoClip.write_images_sequence(video_file, fps=4) to generate frames from a video. But when I try

``` shell
ffmpeg -i video.avi -vf fps=4/1 out_%03d.png
```

It is much faster. VideoClip.write_images_sequence will call VideoClip.save_frame iteratively for every 1.0 / fps seconds. Is it possible to directly use ffmpeg's command above?

**Comment by keikoro** [comment]
Not sure if this is still an issue, but AFAIA there's no way to run FFMPEG commands directly from within MoviePy -> closing.
