### ISSUE TITLE
Unexpected Behavior With negative t_start in Subclip

### ISSUE THREAD

**Issue by kcy1019** [Zulko/moviepy#341]
Whenever I call `subclip` with small negative number something like `clip.subclip(-0.05, clip.end).write_videofile(new_name, audio = False)`, It spits out the original video with additional _random_ padding(no video data - just white frames). The problem is, It does not give the error and the padding is way _too long_(my case: 5min video, 5 hour padding).

**Comment by earney** [comment]
@kcy1019   are you still having issues with this?  The current repo should fix this issue.

**Comment by kerstin** [comment]
Ping @kcy1019.
