### ISSUE TITLE
AAC support for mp4

### ISSUE THREAD

**Issue by jeromegrosse** [Zulko/moviepy#344]
In this [pull request](https://github.com/Zulko/moviepy/pull/26), the AAC compatibility was added to MoviePy by passing `-strict -2` to ffmpeg.

Between then and now, some changes have been done. The `-struct -2` is still being passed to ffmpeg but it is not possible to pass the kwarg `audio_codec="aac"` while writing an mp4 to VideoClip without getting the error `The audio_codec you chose is unknown by MoviePy.`

**Comment by mbeacom** [comment]
Resolved in #345.
