### ISSUE TITLE
Moviepy can't find imagemagick in OSx sierra

### ISSUE THREAD

**Issue by tomasdms** [Zulko/moviepy#347]
I have been trying to get it to work for days.
ImageMagick it's installed, i can run convert from the terminal. it also works when i run python scripts using wand. but when i try to create text
txt = TextClip("hello word", fontsize=70, color='black').set_duration(5)

I get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'unset'

During handling of the above exception, another exception occurred:

OSError: MoviePy Error: creation of None failed because of the following error:

[Errno 2] No such file or directory: 'unset'.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or.that the path you specified is incorrect

it use to work but now it doesn't maybe it's the OS update.

can somebody help me?

**Comment by tomasdms** [comment]
I got it to work on my local machine with this:
```
from moviepy.config import change_settings
change_settings({"IMAGEMAGICK_BINARY": "/usr/local/Cellar/imagemagick/6.9.6-2/bin/convert"})
```

but i bet it will give me problems when i deploy

**Comment by Chan-saravanan** [comment]
I got this error!
When i enterd,
from moviepy.config import change_setting


Error:
Traceback (most recent call last):
  File "D:/python programs/moviepy_config.py", line 1, in <module>
    from moviepy.config import change_setting
ImportError: cannot import name 'change_setting'

**Comment by Chan-saravanan** [comment]
I got this error!
When i run this,,
from moviepy.config import change_setting

Error:
Traceback (most recent call last):
  File "D:/python programs/moviepy_config.py", line 1, in <module>
    from moviepy.config import change_setting
ImportError: cannot import name 'change_setting'

please help me!

**Comment by alexantonica** [comment]
Getting the same error on a macbook pro with Sequoia 15.5 (24F74)

Tried the solution above and i get 
```
Traceback (most recent call last):
  File "/Users/<username>/Documents/projects/<project>/python/generator.py", line 8, in <module>
    from moviepy.config import change_settings
ImportError: cannot import name 'change_settings' from 'moviepy.config' (/Users/<username>/.pyenv/versions/3.10.10/lib/python3.10/site-packages/moviepy/config.py)
```
