### ISSUE TITLE
ImportError: No module named tracking (OS: 10.11.6 "El Capitan", Python 2.7.12)

### ISSUE THREAD

**Issue by bwagner** [Zulko/moviepy#348]
I did `pip install -U scikit-image`
resulting in
`Successfully installed dask-0.11.1 decorator-4.0.10 networkx-1.11 pillow-3.4.2 scikit-image-0.12.3 toolz-0.8.0`

However, when running this code:

```
from moviepy.editor import VideoFileClip
from moviepy.tools.tracking import manual_tracking
```

I get this error:

```
Traceback (most recent call last):
  File "tracking.py", line 2, in <module>
    from moviepy.tools.tracking import manual_tracking
ImportError: No module named tracking

```

**Comment by earney** [comment]
This error seems to be from an error in how moviepy was installed
  Can you try to reinstall moviepy?

**Comment by earney** [comment]
try the following:

from moviepy.editor import VideoFileClip
from moviepy.video.tools.tracking import manual_tracking

note that the second from .. import contains video

**Comment by kerstin** [comment]
@earney Slightly off-topic, but as I've noticed this more than once now: code is better readable if it's formatted as such. Helps differentiate between e.g. instructions on how to do things and actual commands.

In case the Markdown formatting is unknown: this can be achieved with backticks (french accents) – single ones for individual words `like so`, triple backticks for code blocks. Though there's also a button for code in the formatting bar of these comment fields. [More info by GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by earney** [comment]
@bwagner   closing this issue.  please reopen if you need additional help.

**Comment by bwagner** [comment]
FYI, this somehow worked:

```
from moviepy.editor import *
from moviepy.video.tools.tracking import manual_tracking
from moviepy.video.tools.tracking import Trajectory

clip = VideoFileClip("SonarOrig.mp4").subclip(50,60)

trajectories = manual_tracking(clip, t1=5, t2=7, fps=5,
                                       nobjects=1, savefile="track.txt")

```
This generated a file track.txt (as an intermediate result to check):

```
# t(ms)	x	y
5000	438	338
5200	495	685
5400	714	303
5600	351	72
5800	44	674
6000	658	666
6200	713	378
6400	901	468
6600	901	468
6800	901	468

```

```
traj, = Trajectory.load_list("track.txt")

clip_blurred = clip.fx( vfx.headblur, traj.xi, traj.yi, 50)

clip_blurred.write_videofile('blurred.mp4', bitrate="3000k")
```

It might make sense to update the documentation:
https://zulko.github.io/moviepy/examples/headblur.html

**Comment by bwagner** [comment]
I'm still struggling with something when capturing the trajectory: The video that is being played for capturing seems to finish before I got a chance to do all my tracking, even when setting `fps=None`.

**Comment by Old-Asus** [comment]
Help me please

I have the next moviepy code:

import pickle

from moviepy.editor import *
from moviepy.video.tools.tracking import manual_tracking
from moviepy.video.tools.tracking import Trajectory

clip = VideoFileClip('elon3.mp4')

trajectories = manual_tracking(clip, t1 = 5, t2 = 7, fps = 5, nobjects = 1, savefile='track.txt')

This generated a file track.txt

# t(ms)	x	y
5000	625	202
5200	625	202
5400	625	202
5600	625	202
5800	616	201
6000	616	201
6200	616	201
6400	616	201
6600	616	201
6800	616	201


traj, = Trajectory.load_list("track.txt")
clip_blurred = clip.fx( vfx.headblur, traj.xi, traj.yi, 50)
clip_blurred.write_videofile('blurred.mp4', bitrate="3000k")

After run have got the next error:

Traceback (most recent call last):
  File "E:\Мои видео\часть 11\blurr.py", line 12, in <module>
    clip_blurred = clip.fx( vfx.headblur, traj.xi, traj.yi, 50)
  File "C:\Python3\lib\site-packages\moviepy\Clip.py", line 214, in fx
    return func(self, *args, **kwargs)
  File "C:\Python3\lib\site-packages\moviepy\video\fx\headblur.py", line 48, in headblur
    return clip.fl(fl)
  File "C:\Python3\lib\site-packages\moviepy\Clip.py", line 137, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "C:\Python3\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Python3\lib\site-packages\moviepy\video\VideoClip.py", line 661, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Python3\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Python3\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Python3\lib\site-packages\moviepy\Clip.py", line 137, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Python3\lib\site-packages\moviepy\video\fx\headblur.py", line 44, in fl
    blurred = cv2.blur(orig,(r_blur, r_blur))
TypeError: integer argument expected, got float
