### ISSUE TITLE
flv codec

### ISSUE THREAD

**Issue by ZedYeung** [Zulko/moviepy#351]
what codec should be set while write_videofile(*.flv)
I had tried mpeg4 and rawvideo, but it can't work.
But after I turned the same file(flv) into mp4, it worked.
I don't know what this Broken pipe about.
What codec should I choose to tackle flash video?

BrokenPipeErrorTraceback (most recent call last)
E:\Anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in write_frame(self, img_array)
    136         try:
--> 137             self.proc.stdin.write(img_array.tostring())
    138         except IOError as err:

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

TypeErrorTraceback (most recent call last)
<ipython-input-7-4dfd16cf4604> in <module>()
      1 flvclip = VideoFileClip(r'F:\Video\natu3.flv').subclip(212, 347)
----> 2 flvclip.write_videofile('natu.flv', fps=25, codec='rawvideo')

<decorator-gen-175> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params)

E:\Anaconda3\lib\site-packages\moviepy\decorators.py in requires_duration(f, clip, *a, **k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, *a, **k)
     55 
     56 

<decorator-gen-174> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params)

E:\Anaconda3\lib\site-packages\moviepy\decorators.py in use_clip_fps_by_default(f, clip, *a, **k)
    135              for (k,v) in k.items()}
    136 
--> 137     return f(clip, *new_a, **new_kw)

<decorator-gen-173> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params)

E:\Anaconda3\lib\site-packages\moviepy\decorators.py in convert_masks_to_RGB(f, clip, *a, **k)
     20     if clip.ismask:
     21         clip = clip.to_RGB()
---> 22     return f(clip, *a, **k)
     23 
     24 @decorator.decorator

E:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params)
    337                            audiofile = audiofile,
    338                            verbose=verbose, threads=threads,
--> 339                            ffmpeg_params=ffmpeg_params)
    340 
    341         if remove_temp and make_audio:

E:\Anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in ffmpeg_write_video(clip, filename, fps, codec, bitrate, preset, withmask, write_logfile, audiofile, verbose, threads, ffmpeg_params)
    209             frame = np.dstack([frame,mask])
    210 
--> 211         writer.write_frame(frame)
    212 
    213     writer.close()

E:\Anaconda3\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in write_frame(self, img_array)
    142                                  "\n\n %s" % (self.filename, ffmpeg_error)))
    143 
--> 144             if "Unknown encoder" in ffmpeg_error:
    145 
    146                 error = error+("\n\nThe video export "

TypeError: a bytes-like object is required, not 'str'

**Comment by tburrows13** [comment]
I'm closing this issue because the error was fixed a long time ago. Any of the codecs listed [here](https://trac.ffmpeg.org/wiki/SupportedMediaTypesInFormats) eg `mpeg4` or `libx264` should work for `.flv` files.
