### ISSUE TITLE
Are you running moviepy on Mac? Please help!

### ISSUE THREAD

**Issue by Gloin1313** [Zulko/moviepy#362]
I am trying to run moviepy on macOS Sierra, but I can't get even simple tasks to work. Whenever I write a video, I get strange error messages!

If you are using moviepy, please can you tell me your:
OS version
Python version
How you are running python (Which IDE?)
Where you installed your python (python.org, homebrew, anaconda etc)

If you can post a sample code that reads a couple of vids, concatenates them, then writes it to a file, along with the videos that work on your system, that would be amazing!
Thanks

**Comment by timtan** [comment]
what is your message?

**Comment by liketemple** [comment]
You should use Homebrew to install ImageMagick first, maybe ffmpeg either, then maybe python binding library of ImageMagic, wand.

**Comment by Gloin1313** [comment]
I deleted the ffmpeg binary in /Application Support/imageio/ and ran moviepy again to redownload it. It all works now.
