### ISSUE TITLE
Different size videos

### ISSUE THREAD

**Issue by BillyJohn3** [Zulko/moviepy#365]
Great library, thanks. I just started using it and am having trouble when using the concatenate function.

If I specify multiple clips the first will always be fine but the following ones will play weird. The code I'm using is:

from moviepy.editor import *

clip = VideoFileClip("C:/Users/Me/Desktop/forMovs/Portrait.mp4")  # Change paths and filenames
clip2 = VideoFileClip("C:/Users/Me/Desktop/forMovs/Car.mp4")

clip3 = concatenate_videoclips([clip,clip2])

clip3.write_videofile("C:/Users/Me/Desktop/forMovs/Portrait&Car.mp4") 
print ("done")

I believe it's because the files aren't the same size but I may be wrong.
I attach the two source clips and the final. You'll see that the car clip is displaying weirdly.
[Clips.zip](https://github.com/Zulko/moviepy/files/649395/Clips.zip)

Thank you!

**Comment by liketemple** [comment]
concatenate_videoclips(clips, method="compose")
This "compose" argument will put the clips with smaller size in the center of biggest clip size.
