### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so

### ISSUE THREAD

**Issue by chinmaydas96** [Zulko/moviepy#379]
Hi. I installed moviepy in conda environment in python 3.5  .
While importing  " from moviepy.editor import * "
it shows the following error "Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so".
I don't know what goes wrong ? please help .

**Comment by Gloin1313** [comment]
When you say you installed moviepy in conda, do you mean you used anaconda pip to install it? I am by no means an expert, but even in conda, I use pip to install such packages. If you did use pip, I guess you should try to uninstall then reinstall moviepy(/pip/python/conda!).

**Comment by chinmaydas96** [comment]
I did some google then somewhere say  update scipy . So I did .And my problem is solved . And thanks for the advice .
