### ISSUE TITLE
read_chunk() breaks in numpy 1.12.0

### ISSUE THREAD

**Issue by tyarkoni** [Zulko/moviepy#383]
In `audio.io.readers.FFMPEG_AudioReader`, the `read_chunk()` method breaks as of numpy 1.12.0 (released a few days ago). Numpy no longer accepts floats as index values, so the `result.reshape((len(result)/self.nchannels, self.nchannels))` call raises an exception. In practice, this means working with audio files is basically impossible with the latest numpy. Patch is trivial; PR coming in a moment.

**Comment by Goddard** [comment]
This solved it for me.
