### ISSUE TITLE
DirectoryClip??? Where is it?

### ISSUE THREAD

**Issue by chibill** [Zulko/moviepy#385]
I can't find DirectoryClip any where. While it is mentioned in the docs.

**Comment by chibill** [comment]
Okay I found ImageSequenceClip which sounds like it is what that other clip actually is. The docs should be changed to reflect this.

**Comment by Gloin1313** [comment]
Where in the docs does it say that?

**Comment by chibill** [comment]
http://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#moviepy.video.VideoClip.VideoClip.write_images_sequence

Also in the comments of the .py file it says so.

**Comment by earney** [comment]
PR #434  should fix this issue.

**Comment by chibill** [comment]
It should reference  ImageSequenceClip but as it does what DirectoryClip theoretically should have. Right?

**Comment by earney** [comment]
@chibill   you are correct,   I'll modify the PR.

**Comment by earney** [comment]
pull request has been merged into the master repo.   closing this issue.
