### ISSUE TITLE
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by mattdornfeld** [Zulko/moviepy#391]
So I have a bit of an unusual use case. I have a 40 core computer, and on each core I'm creating a moviepy object, having that object connect to an mp4 file, then having each object decompress random images from the mp4 file. I'm doing this so I can use the images to train a neural network. It actually works really except I'm getting this warning

`ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
`

I can't figure out its source. Here is a basic code example

```
from moviepy.editor import VideoFileClip
from queue import Queue, deque
import threading, multiprocessing
import numpy as np

def decompress_worker(training_data:Queue, frame_idxs:Queue, video_file_path:str):
	"""
	Eache of these workers will pop off one integer from frame_idxs.
	It will then decompress that frame number from vs. Finally
	it will store the decompressed image in training_data.
	"""
	vs = VideoFileClip(video_file_path)
	fps = vs.fps

	while frame_idxs.qsize() > 0:
		frame_number = frame_idxs.get()
		frame = vs.get_frame( frame_number / fps )
		training_data.put(frame)


num_cores = multiprocessing.cpu_count()
frame_idxs = Queue()
training_data = Queue()
frame_idxs.queue = deque(np.random.randint(0, 10000, size = 1000))

decompress_threads = []
for n in range(num_cores):
	decompress_thread = threading.Thread(target=decompress_worker, 
		args=(training_data, frame_idxs, video_file_path))
	decompress_threads.append(decompress_thread)
	decompress_thread.start()

[thread.join() for thread in decompress_threads]
```

I'm guessing it's coming from me reading data from the mp4 file to fast? It would be nice if I could just suppress the warning. Is there a way to do that?

**Comment by Titorat** [comment]
hello there,
have you been able to solve the issue?
I am getting a similar one when trying to use celery and run multiple renderings at the same time.

**Comment by tburrows13** [comment]
If it is just a standard Python warning that you are trying to suppress, you can do

```
import warnings
    warnings.simplefilter("ignore")
```

**Comment by keikoro** [comment]
Closing this due to lack of response after a potential solution was proposed.

**Comment by blooop** [comment]
Calling pygame.mixer.quit() may fix your issue. (if you have pygame installed)
