### ISSUE TITLE
Aliasing when resizing text

### ISSUE THREAD

**Issue by peterbispham** [Zulko/moviepy#402]
Hi there, having some issues when attempting to create a slow swell or shrinking of text using the resize method. I have opencv installed which is being used to do the resize, though this also happens when PIL does the resize.

Static text looks fine, but as soon as I shrink the text we get aliasing around the edges. I've enclosed an example below which shows non-shrinking text for comparison, slow shrinking of the same text and the same but starting from a font 10x larger and resizing down 10x as much.

Is this a known issue? Or is there a better way of creating a zooming in/out effect that I should be using instead?

Great library BTW :)

PS using version 0.2.2.11

    from moviepy.editor import *

    f = 'Times Bold'
    w, h = 1920, 1080

    # Static text for comparison, no resizing
    txt1 = TextClip('Static text', font=f, color='white', fontsize=100).set_duration(5)

    # Dynamic resize of same text
    txt2 = TextClip('Resizing text', font=f, color='white', fontsize=100).set_duration(5)
    txt2 = txt2.resize(lambda t: 1-0.02*t)

    # Same but using 10x larger font
    txt3 = TextClip('Larger text', font=f, color='white', fontsize=1000).set_duration(5)
    txt3 = txt3.resize(lambda t: 0.1 * (1-0.02*t))

    clip = CompositeVideoClip([txt1.set_position(('center', 'top')),
                               txt2.set_position('center'),
                               txt3.set_position(('center', 'bottom'))], size=(w, h))

    clip.set_duration(5).write_videofile('/tmp/resizing.mp4', fps=25)

**Comment by Zulko** [comment]
Unfortunately the only antialiasing way I know is to create big text and then scale it down. For info I have recently been using my other library Gizeh to generate the texts. It relies on Cairo SVG and produces beautiful results at 20x the speed of ImageMagick. One reason I didnt replace ImageMagick by Gizeh/Cairo is that these are not easy to install on all OS.

**Comment by peterbispham** [comment]
Thanks for replying :) Sounds cool. Any code snippet you could share to get us started? Thanks

**Comment by Zulko** [comment]
[Here](https://gist.github.com/Zulko/e072d78dd5dbd2458f34d2166265e081#file-text_clip_with_gizeh-py) is the code of what could be a longer-term replacement for Moviepy's textclip, based on Gizeh/Cairo. Let me know if it worked for you.

**Comment by peterbispham** [comment]
Thanks for this. I'm about to take a look at it now :) Will let you know!

**Comment by keikoro** [comment]
Closing this due to lack of updates/activity for several years after feedback and potential solutions were provided.
