### ISSUE TITLE
How can moviepy write a video with any fps?

### ISSUE THREAD

**Issue by Gloin1313** [Zulko/moviepy#408]
When you run `clip.write_videofile()` you can specify any fps (e.g. `(fps=30)`). This overwrites the clip's existing fps (if it has one) and writes the video at the new fps.  The written video, however, plays at the same speed, just if you specify a low fps it will be a bit jumpy.  How does moviepy write any video with any fps?  Does is insert duplicate frames in places to keep the play speed the same?

Example:
I have a video taken at 29 fps. If I tell moviepy to write it to a file at 30 fps, does it duplicate the 29th frame to keep the overall speed the same?

**Comment by Zulko** [comment]
Think of clips as "frame servers": you ask a clip "what frame do you display at t=1.16s" and it answers "this frame".

Say you give a fps of 25. Moviepy will start at t=0 and ask the clip (or the clip**s** if it is a composite clip): "give me your frame at time 0". then moviepy advances at time 0.04, and asks the clip(s): what frame are you playing at t=0.04. Then t=0.08, etc.

This is what allows moviepy to re-sample clips, but also play different clips with different fps at the same time, and even play clips with no fps (images) and clips with infinite fps (continuous animations defined by a function f(t)).
