### ISSUE TITLE
error 'unicode' object has no attribute 'shape'

### ISSUE THREAD

**Issue by leonardoo** [Zulko/moviepy#417]
i found this error with the python 2

**Comment by Zulko** [comment]
Thanks for the report, can you provide the moviepy version you are using (or if you installed it recently), and a sample of your code that produces the problem ?

**Comment by leonardoo** [comment]
@Zulko in using the last version

**Comment by Gloin1313** [comment]
@Leonardoo can we see the code that causes this error please?

**Comment by leonardoo** [comment]
@Gloin1313 this is a sample code https://gist.github.com/leonardoo/55eb16ac81fb9239a1d8633f2d79f682

**Comment by earney** [comment]
I have just added a pull request for this.  hopefully it will get accepted and pushed into the repo, ASAP.

**Comment by earney** [comment]
A fix has been merged to the repo
