### ISSUE TITLE
Can't import gifs into moviepy

### ISSUE THREAD

**Issue by DanielHHowell** [Zulko/moviepy#452]
The below code is working marvelously as-is for other file types such as .webm (when changed in the glob.glob call) but when I try to use it for .gifs nothing happens at all - no errors or exceptions raised. Any ideas? Thanks you in advance for any help!

    from moviepy.editor import *
    import glob

    def movie_maker(location_path):
        raw_clips = [VideoFileClip(path) for path in glob.glob(location_path+'*.gif')]
        sized_clips = [clip.resize((600,600)) for path in raw_clips]
        final_clip = concatenate_videoclips(sized_clips)
        final_clip.write_videofile(path + 'Video.avi', fps=24, codec='png')

**Comment by Zulko** [comment]
just checking: did you print 'raw_clips' to make sure it's not empty ?

**Comment by Gloin1313** [comment]
"Nothing happens"? Does `final_clip.write_videofile` not do _anything_? Have you tried just running a simple `clip = VideoFileClip(file.gif)` and `clip.write_videofile(path etc)`?

**Comment by DanielHHowell** [comment]
Thanks for the very fast responses. Printing raw_clips as is ins't possible, the script is just getting stuck on the first line.

Gloin1313: 
I tried that and it worked - so it seems this is an issue of looping through multiple .gifs?

**Comment by Gloin1313** [comment]
@DanielHHowell You could try expanding your loop, e.g.:
    list = glob.glob(path+'*.gif')
    for clip in glob.glob(path+'*.gif'):
        raw_clips.append(VideoFileClip(clip))

And then print certain variables at different points to try and troubleshoot better.

**Comment by DanielHHowell** [comment]
raw_clips = []
    for clip in glob.glob(path + '*.GIF'):
        print(clip)
        raw_clips.append(VideoFileClip(clip))
    print(raw_clips)

So the loop is being iterated through - it prints each path instance of 'clip' here, however nothing else will happen past that. I'm very confused how the append clip is passed over with seemingly no error raised

**Comment by Gloin1313** [comment]
Just a side note; don't name a variable containing a string a `clip`. I'd recommend just calling it `path`. Reserve variable names with `clip` in them for actual instances of a moviepy `clip`. I've edited you posts in this thread for clarity.

**Comment by DanielHHowell** [comment]
Everything is working properly now - even the code I originally introduced. Deleting some .gif path's from the directory revealed that the ffmpeg process was keeping them open, even though no processes were running on the PyCharm IDE. Very strange

**Comment by Gloin1313** [comment]
So nothing wrong on moviepy's side then? If so, we can close this.

**Comment by DanielHHowell** [comment]
My guess is that this was related to ffmpeg - go ahead and close the issue. Thanks for the rapid responses - will keep in mind that debugging process!
