### ISSUE TITLE
ImageSequenceClip issue

### ISSUE THREAD

**Issue by earney** [Zulko/moviepy#454]
I'm taking two images, and adding them to a list about a half a dozen times, and incrementing the duration 1 second for each set I'm adding.  In python 3, this produces a 5.3 MB file, but it does not play in VLC.  In python 2 the file size is 5.4 MB, it does play in VLC, but the images don't look right, and the duration is way off.    Here is the code..

```
import os
from moviepy.editor import *

def download_url(url, filename):
    if not os.path.exists(filename):
       print("\nDownloading %s\n" % filename)
       download_webfile(url, filename)
       print("Downloading complete...\n")

download_url("https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_$
             "media/python_logo.png")

download_url("http://matplotlib.org/_images/barh_demo.png",
             "media/matplotlib_demo1.png")


images=[]
durations=[]

for i in range(5):
    durations.append(i)
    images.append("media/python_logo.png")
    durations.append(i)
    images.append("media/matplotlib_demo1.png")

clip=ImageSequenceClip(images, durations=durations)
clip.write_videofile("/tmp/ImageSequenceClip1.mp4", fps=30)
```

Does anyone know what is going on?   I was trying to produce a set of tests for ImageSequenceClip, and ran into this issue.

**Comment by earney** [comment]
sorry, the url for the first download got chopped off.  here is that url:
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_logo_and_wordmark.svg/260px-Python_logo_and_wordmark.svg.png

**Comment by earney** [comment]
I'm still stuck on this issue.  Someone else want to give it a try?

**Comment by Zulko** [comment]
Maybe your pictures don't have the same size ? At which case ImagesSequenceClip is not supposed to work.

**Comment by earney** [comment]
Thanks..  I'll take a look at that.

**Comment by earney** [comment]
Yes, the image sizes were the issue.  I have added some code to check that the image sizes are all the same.  If not an exception is thrown.  I've added this code to the repo.
