### ISSUE TITLE
Bytes-like object is required, not 'str' in version 0.2.2.13

### ISSUE THREAD

**Issue by arnieadm35** [Zulko/moviepy#455]
Updated to the latest version of moviepy 0.2.2.13. When attempting to get a list of available colors using the instructions in the documentation:
Color of the background. See TextClip.list('color') for a list of acceptable names.
I get:
>>> TextClip.list('color')
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    TextClip.list('color')
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 1207, in list
    return [l.split(" ")[1] for l in lines[2:]]
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 1207, in <listcomp>
    return [l.split(" ")[1] for l in lines[2:]]
TypeError: a bytes-like object is required, not 'str'
>>>

**Comment by earney** [comment]
this has been fixed in the current repo.  Can you try pulling from there?

**Comment by Gloin1313** [comment]
Shall we push a new update to PyPI? Or are we holding back for some reason?

**Comment by earney** [comment]
The only reason I could see us holding back is to produce more tests.   Some may feel the current repo is a bit unstable, since we don't have a lot of tests, and the PR activity has been high.  On the other hand, if we push this out, and there are issues, we can fix those issues, create tests, and make a more stable repo over time.  That might sacrifice present stability for more long term stability.

**Comment by earney** [comment]
just to make myself clear, I think we should push a new update to PyPI.  Maybe I'm biased, but I want to be optimistic about the Pull requests we have submitted.

**Comment by arnieadm35** [comment]
I was just about to pull from the repo, but would rather pull a released
version. If you're about to push new update, please tell me and I'll
immediately grab it to play with.

**Comment by earney** [comment]
@Gloin1313   I've pushed a few PR's, mainly doing with testing..  I've never pushed an update to PyPI, so for now, I'll leave that to someone whom has more experience.

**Comment by Gloin1313** [comment]
@earney I'm all for pushing to PyPI, but I also have no idea how to do it!

**Comment by arnieadm35** [comment]
Please let me know if you do!

**Comment by arnieadm35** [comment]
I grabbed moviepy-master from Github and installed per documentation. I tried again and got different errors:
>>> TextClip.list('color')
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    TextClip.list('color')
NameError: name 'TextClip' is not defined
>>> TextClip.list('font')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    TextClip.list('font')
NameError: name 'TextClip' is not defined

**Comment by Gloin1313** [comment]
I assume you ran `from moviepy.editor import *` at the top?

**Comment by earney** [comment]
also.. did you do..
````
python setup.py install
```

**Comment by arnieadm35** [comment]
I did setup.py install. What I did not remember to do was import * . It works now. Thanks. Now I can start trying to solve the problem I set out to solve!

**Comment by earney** [comment]
Awesome!  Let us know if you run into some issues, and we'll try to help.

**Comment by arnieadm35** [comment]
Where do I go for help instead of bugs? I'm new to a lot of the terminology
here, and I have a specific problem I'm trying to solve, but I don't want
to clog up the bug list with my pitiful help questions.

**Comment by earney** [comment]
@arnieadm35   I'm probably not a good person to go for help.  I'm pretty good at python, but consider myself a moviepy beginner as well.

**Comment by kerstin** [comment]
@arnieadm35 From the README: "You can also discuss the project on Reddit (preferred over GitHub issues for usage/examples), Gitter or the mailing list moviepy@librelist.com." (links there)

I.e. Reddit is preferred if you want to know how to solve specific problems with MoviePy.

**Comment by arnieadm35** [comment]
Ok. Ty.

**Comment by earney** [comment]
can we close this issue?

**Comment by arnieadm35** [comment]
If I have a vote, yes. I have demonstrated that it works in the repo
version.

**Comment by Gloin1313** [comment]
Feel free to post on the [gitter](https://gitter.im/movie-py/Lobby?source=orgpage) chat for a quick bit of help!
