### ISSUE TITLE
Change speed of clip based on a curve?

### ISSUE THREAD

**Issue by cnelsonsic** [Zulko/moviepy#46]
Does anyone have any ideas as to how to change the speed of a clip gradually over a bezier curve?

Is there any demand for this feature?
Am I the only one who wants this?

**Comment by SreeniASU** [comment]
Hi Zulko,
 I tried this and it seems that the speed of the video clip changes, whereas the accompanying audio doesn't speed up.  The file format is mp4. Can you please help?

**Comment by Zulko** [comment]
Try this, with apply_to=['audio'] in fl_time:

    clip = VideoFileClip("my_video.mp4")
    clip2 = clip.fl_time( lambda t: t+ sin(t), apply_to=['audio'] )
    # maybe indicate a new duration for the clip:
    clip2 = clip2.set_duration(some_new_duration)
    clip2.write_videofile("my_time_warped_video.mp4")

**Comment by SreeniASU** [comment]
Thanks Zulko for your quick response. It worked like a charm. But, I have one more concern. On changing the playback rate of the video the voice of the person in it also changes. That is, if I double or halve the speed of video, the dialogues are clear, but the voice becomes annoyingly unpleasant. This doesn't happen if I play the original video in a video player with 2x or 0.5x speed. Is there any way to avoid that?

**Comment by isdito** [comment]
hello,
I'm looking for a way to slow down a point in the video but then x time later it returns to normal speed.

Imagine recording it at 50 fps or 100 fps per second while its playback is constant at 1/25, when the car is close then use those frames. Typical of after effects programs is a retime curve.

Slow down a point of the video and then continue normal

any help please

**Comment by keikoro** [comment]
Please note that you are commenting on old, closed issues meaning only very few people will see your comments.
