### ISSUE TITLE
New install... VideoFileClip("x.mp4").subclip(0,13) gives "reader not defined error"

### ISSUE THREAD

**Issue by hallcp2** [Zulko/moviepy#461]
I have installed Python & MoviePy successfully on one Win7 machine, but on the other I get this error:

clip = VideoFileClip("x.mp4").subclip(0,13)
... (lengthy traceback) ...
NameError global name 'reader' is not defined.

Both ffmpeg and ImageMagick are in the command path. I'm brand new to Python and I'm clueless as to what it's trying to tell me.

Sorry if this is the wrong forum for newbie questions, but I couldn't find any other place to turn to for help.

C. Hall

**Comment by earney** [comment]
Did you install moviepy from the repo or from pip, etc?  If you installed from pip try installing from the repo.

**Comment by hallcp2** [comment]
Wow, you're a genius! Getting a fresh copy from the Repo and re-installing did the trick.  I don't recall how I installed it originally, but maybe wherever it was pulling from was broken.

Thanks so much. I was out of ideas.

**Comment by earney** [comment]
I'm gonna close this issue.  Feel free to reopen it, if you need to!
