### ISSUE TITLE
FFMPEG_VideoReader read from pipe

### ISSUE THREAD

**Issue by truskovskiyk** [Zulko/moviepy#473]
add ability read from pipe FFMPEG VideoReader
like: cat <video_file> | ffmpeg -i pipe:0
I think some little changes https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L28 
rename filename var and check it it path of raw bytes 

@Zulko  what do you think about it? 

thanks!

**Comment by keikoro** [comment]
Closing this issue as it's old and missing information we now request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
