### ISSUE TITLE
problem after setup with imageio package

### ISSUE THREAD

**Issue by gpantelis** [Zulko/moviepy#479]
When i tried to run the tutorial 
![moviepy](https://cloud.githubusercontent.com/assets/15388689/23798565/e4b86534-05ad-11e7-9fbc-02d3f7d81d4c.PNG)
an NeedDownLoadError occur.
Then i have to run the following command on python : 
"imageio.plugins.ffmpeg.download()"
to download the ffmpeg.win32.exe.

**Comment by gpantelis** [comment]
*so the user doesnt need to enter to that process(downloading "ffmpeg.win32.exe")
 thanks

**Comment by earney** [comment]
I'm not sure I understand..   Did you enter ```imageio.plugins.ffmpeg.download()``` into python?

**Comment by Zulko** [comment]
From what I understand Moviepy used to work "out of the box" but now we should check for ffmpeg and run ``imageio.plugins.ffmpeg.download()`` if ffmpeg is not on the machine (that would be done once per machine).

**Comment by gpantelis** [comment]
So i can try to add tis command " imageio.plugins.ffmpeg.download() " in the setup file, so 
the user doesnt need to run it after the installation ?
By the way im a student in a university of athens, and my project is to contibute in an open source project nad i choose moviepy.
thank you

**Comment by earney** [comment]
see #493 for a possible solution....

**Comment by earney** [comment]
has this been resolved?

**Comment by tburrows13** [comment]
Resolved a while ago.
