### ISSUE TITLE
TextClip in Videos  (Before the main film.)

### ISSUE THREAD

**Issue by bobozar** [Zulko/moviepy#480]
Kudos to Zulko and other dev behind this app! 

How do I add TextClip properties `txt_clip = TextClip("My Holidays 2013",fontsize=70,color='white')` to the beginning of the video? It should show the watermark or text first before the main film. Nothing like this in the doc.  

I need an idea. :)

**Comment by Gloin1313** [comment]
Do you mean as a separate 'slide'? So a blank screen with text, then your video? If so, put the `TextClip` on top of a `ColorClip` (with `color` parameter to (0,0,0) for black), then concatenate that with your main `VideoClip`. Let us know if you need more help!

**Comment by bobozar** [comment]
Been on the road yet to give it a try.. but will let you know. Thanks man!

P:S How can I get the video duration in this format- 03:05 or 01:23:05 instead of the default format 60.15 for I hr 15 secs video.?

**Comment by earney** [comment]
@bobozar ,  here is some modified code I wrote this morning, that should give you the results you want..

```
_txt=TextClip("my title text goes here..", fontsize=70, color='white')
_txt=_txt.set_position('center').set_duration(5)

#why do we need to do this?  I don't know, but it works..
txt = CompositeVideoClip( [_txt], size=video.size)

#video is a VideoFileClip I've already read in..  # video=VideoFileClip("myvideo.mp4")
final = concatenate_videoclips([txt, video])
final.write_videofile("video.mp4", fps=30)
```

**Comment by earney** [comment]
see issue #502 for your question about formatting the duration.

**Comment by earney** [comment]
@bobozar   do these responses answer your questions?

**Comment by earney** [comment]
closing issue, since no response in 2 months..

**Comment by bobozar** [comment]
@earney Thanks for the input. I'm back now! Been away for some time. :( 

I have series of questions to ask, but please permit me to start one by one.

#Q1 

I tried it, but the text was displayed when the video started and it disappeared after 5secs. What I really wanted is the text to show first before showing the film. Kindly [check this Link](http://www.worldstarhiphop.com/featured/110001) on Worldstar to see what I mean. When you hit play on the video, the first thing you will see is WORLDSTAR HIP-HOP.COM watermark before other things. That's exactly what I want to achieve. I hope you get my point?
