### ISSUE TITLE
Should we push another version?

### ISSUE THREAD

**Issue by Gloin1313** [Zulko/moviepy#481]
Is it time to push another version (0.2.2.14?) to PyPI?  Are the certain things we are waiting for before we have another release?

**Comment by kerstin** [comment]
I think merging the most recent "trivial" PRs that are still open would be a good idea before releasing a new version.

**Comment by earney** [comment]
I think it would be good to add some additional tests too.   Currently our code coverage is 47% (which is up from 22% the beginning of the month)..

**Comment by earney** [comment]
I'm thinking we should push another version out to PyPI.   Anyone know (or has access) to do with with moviepy?   We have 13 remaining PR's, and we have 50% code coverage at this point.

**Comment by Gloin1313** [comment]
Yes please! We have issues solved a month (or so) ago that haven't been fixed in the PyPI version yet. @Zulko...?

**Comment by mbeacom** [comment]
@earney I'm not sure who all was added to pypi, but I can push updates whenever is agreed.

**Comment by Gloin1313** [comment]
I'd say ASAP

**Comment by earney** [comment]
I agree.  as soon as possible.

**Comment by mbeacom** [comment]
Please see:  [Release v0.2.3.1](https://github.com/Zulko/moviepy/releases/tag/v0.2.3.1)
Wheel and source pushed to pypi.

**Comment by Gloin1313** [comment]
Great! Thanks
