### ISSUE TITLE
Duration Format With Moviepy

### ISSUE THREAD

**Issue by bobozar** [Zulko/moviepy#502]
How can I get the video duration in this format- 03:05 or 01:23:05 instead of the default format 60.15 for I hr 15 secs video. 

Can seems to even get a template tag for this. Any idea on how to go about this in Python or in Django by saving the default format and change it in template.?

**Comment by Zulko** [comment]
Not sure what you mean. A video clip duration is expressed in seconds in Moviepy. 60.15 means 60 seconds and 15/100. To get the time format you want, you'd write

```
hours = clip.duration / 3600
mins = (clip.duration % 3600) / 60
secs = (clip.duration % 60)
duration = "%02d:%02d:0.2f" % (hours, mins, seconds)
```

**Comment by bobozar** [comment]
Yeah something like this! Let me try it and get back to you. Thanks!

**Comment by bobozar** [comment]
Done it. For anyone who might need this!

        >>> mx=clip.duration
         >>> seconds=mx
         >>> m, s=divmod(seconds, 60)
         >>> h, m=divmod(m, 60)
         >>> print "%d:%02d:%02d" % (h, m, s)
         0:01:00

**Comment by Gloin1313** [comment]
@bobozar has a solution. Closing this now.

**Comment by earney** [comment]
should we add a function that will accept seconds and return a string in hh:mm:ss format ?
