### ISSUE TITLE
How do I add borders around a video?

### ISSUE THREAD

**Issue by justswim** [Zulko/moviepy#505]
Hi, I've tried playing around with the examples from the documentation and I can't for the life of my figure this out. 

I'm trying to take a video and add a black frame around it. I made a quick photoshop of what i'm talking about: 

![borders](https://cloud.githubusercontent.com/assets/1372528/24184820/1adfe3ca-0e8d-11e7-9acc-4fcec72dab17.png)

What is the right way to do this? Can I expand the height of a video clip somehow to add the top and bottom borders?

Thanks for your help.

**Comment by Zulko** [comment]
There are several ways to do this, but the simplest/fastest would be with [``margin``](https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.margin.html):

```
# 110 black pixels above and below the clip
clip_with_borders = clip.margin(top=110, bottom=110)
```

You can also set another color for the margin with ``color=(110, 5, 27)``.

**Comment by justswim** [comment]
Thanks for your help. I did try that, and it didn't work at first. The reason is that I realized that the height of the video must be an even number. Adding an odd numbered margin will not work. 

Just wanted to note that in case anyone else ran into the same problem. Thank you for your help!

**Comment by Zulko** [comment]
Can you give more details on what "did not work" ?
From what I remember, the "even number" constraint is only a problem for some mp4 codecs, and with some video players.

**Comment by justswim** [comment]
If I run `clip_with_borders = clip.margin(top=111, bottom=111)` the script executes successfully, the video gets created, but I the .mp4 file that gets generated is not compatible to be played with Quicktime. Maybe I'm doing something wrong?

**Comment by Zulko** [comment]
No, that's what I am saying above. Try reading the video with, say, VLC, it should work. But that's really due to the format you are exporting to, maybe if you changed the output format to .ogv or if you changed the codec, you wouldn't have this problem.

**Comment by justswim** [comment]
Gotcha. Thanks for the context.

**Comment by New-dev0** [comment]
How can i set radius too, of that margin 😅
