### ISSUE TITLE
FFMPEG_VideoReader and subprocess error

### ISSUE THREAD

**Issue by skylin008** [Zulko/moviepy#506]
The error information as flow:
Traceback (most recent call last):
  File "/home/pi/Desktop/CarND-LaneLines-P2-master (1)/detect_lane_lines.py", line 109, in <module>
    clip1 = VideoFileClip("project_video.mp4")
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/VideoFileClip.py", line 57, in __init__
    reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 32, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 238, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

How to solve this issue.Thanks !

**Comment by gyglim** [comment]
I'd guess it is an issue with ffmpeg. Can you run?
```ffmpeg -i project_video.mp4```

**Comment by gyglim** [comment]
there you have your reason. Moviepy relies on ffmpeg, see:
http://zulko.github.io/moviepy/install.html

You need to install it first

**Comment by Zulko** [comment]
Note that in near future moviepy will also have its own ffmpeg version via imageio, as it used to, so you wont have ffmpeg in your binaries path but you'll still be able to use ffmpeg with moviepy.

**Comment by skylin008** [comment]
@Zulko  Thanks,Yes.I had installed ffmpeg via imageio latest version.But any issue as up show.

**Comment by earney** [comment]
can we close this issue?  Has it been resolved?

**Comment by mincaeuro** [comment]
Hi, got same issue, but I'm getting result on ffmpeg -i:
ffmpeg -i test.mp4
ffmpeg version N-91240-g3769aaf Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=./build/ --enable-cross-compile --cross-prefix=/usr/bin/arm-linux-gnueabihf- --arch=armhf --target-os=linux --enable-gpl --enable-libx264 --enable-static --enable-pic --extra-cflags=-I./x264/ --extra-ldflags=-L./x264/ --extra-libs=-ldl
...

I've installed ffmpeg from source

**Comment by keikoro** [comment]
I'm closing this issue as it's rather old and it's unclear if this is even still an issue now.
