### ISSUE TITLE
Adding emoji with moviepy

### ISSUE THREAD

**Issue by justswim** [Zulko/moviepy#507]
Hi,

I was wondering if it was possible to add emoji characters with TextClip. For example, rendering something like this: 😅😂😂😂 on top of a video.

I tried adding a text clip with the proper unicode characters, but they show up as question marks.

Thanks in advance for your help

**Comment by Zulko** [comment]
Not unless you use a specific emoji font. You can also load your emojis as images using ImageClip.

**Comment by Yash17Agrawal** [comment]
@Zulko @justswim  can you list the font type for emoji because all the available solutions suggest converting to bytes and then using it. I don't want to use ImageClip for now. So can you please suggest the font type.

**Comment by justswim** [comment]
I was never actually able to get this to work. I think there is an underlying issue with ffmpeg which prevents emojis from being supported.

**Comment by notanotherbrick** [comment]
Wondering if this worked for anyone now?

**Comment by makiisthenes** [comment]
Anyone found a solution to this? or is it a problem forever to be forgotten and lost :(((

**Comment by mrhosein** [comment]
MS Word displays emojis with font 'Segoe-UI-Emoji'. When I set the font of my clip to this, it was able to display the emoji's but not with colours. 

For example: 
`txt = TextClip(temp_comment[i], font = 'Segoe-UI-Emoji', fontsize = 44)`

**Comment by makiisthenes** [comment]
> MS Word displays emojis with font 'Segoe-UI-Emoji'. When I set the font of my clip to this, it was able to display the emoji's but not with colours. 
> 
> 
> 
> For example: 
> 
> `txt = TextClip(temp_comment, font = 'Segoe-UI-Emoji', fontsize = 44)`

Thanks for this!

**Comment by kaka1909** [comment]
For those who are finding solutions to add colorful emoji to video, you can use the below snippet.

The prequistes:
1. install Pilmoji: pip install -U pilmoji
2. download a colorful emoji font, like [Noto Color Emoji ](https://fonts.google.com/noto/specimen/Noto+Color+Emoji)

The solution:
1. Draw an image based on emoji and emoji font.
2. Make an image clip

The code to mix-in an emoji to a video:

```python
    def make_emoji_image(emoji, font_path, font_size):
        emoji_font = ImageFont.truetype(font_path, font_size)
        text_size = emoji_font.getsize(emoji.strip())
        image = Image.new("RGBA", text_size, (0, 0, 0, 0))
        with Pilmoji(image) as pilmoji:
            pilmoji.text((0, 0), emoji.strip(), (0, 0, 0), emoji_font, emoji_scale_factor=0.9)
        return np.array(image)
    
    video_clip = VideoFileClip("/path/to/your/video")
    emoji_clip = ImageClip(make_emoji_image("😜", "/path/to/your/emoji/font", 48), duration=10).set_start(0)
    result = CompositeVideoClip([video_clip, emoji_clip])
    result.write_videofile("/path/to/output")
```

**Comment by tyler239** [comment]
The solution of @kaka1909 works fine, but not for apple emojis :( . I tried to just use the apple emoji font from https://github.com/samuelngs/apple-emoji-linux but it did not work. It raises an "OSError: invalid pixel size". Anyone trying to work with apple emojis ?

**Comment by benjamenharper** [comment]
> For those who are still finding solutions to add colorful emoji to video, here is a demo.
> 
> The prequistes:
> 
> 1. install Pilmoji: pip install -U pilmoji
> 2. download a colorful emoji font, like [Noto Color Emoji ](https://fonts.google.com/noto/specimen/Noto+Color+Emoji)
> 
> The solution:
> 
> 1. Draw an image based on emoji and emoji font.
> 2. Make an image clip
> 
> The code to mix-in an emoji to a video:
> 
> ```python
>     def make_emoji_image(emoji, font_path, font_size):
>         emoji_font = ImageFont.truetype(font_path, font_size)
>         text_size = emoji_font.getsize(emoji.strip())
>         image = Image.new("RGBA", text_size, (0, 0, 0, 0))
>         with Pilmoji(image) as pilmoji:
>             pilmoji.text((0, 0), emoji.strip(), (0, 0, 0), emoji_font)
>         return np.array(image)
>     
>     video_clip = VideoFileClip("/path/to/your/video")
>     emoji_clip = ImageClip(make_emoji_image("😜", "/path/to/your/emoji/font", 48), duration=10).set_start(0)
>     result = CompositeVideoClip([video_clip, emoji_clip])
>     result.write_videofile("/path/to/output")
> ```

this worked.. was ready to jump
