### ISSUE TITLE
AttributeError: AudioFileClip instance has no attribute 'afx'

### ISSUE THREAD

**Issue by batmanrising** [Zulko/moviepy#513]
I was trying to experiment with audio but I am getting this error, where am I doing wrong ? 

```
`from moviepy.editor import VideoFileClip, AudioFileClip, concatenate_videoclips
import moviepy.editor as mpe
import moviepy.audio.fx.all as afx

videoClip = VideoFileClip("testVideo.mp4")
audioClip = mpe.AudioFileClip("testAudio.mp3")

newAudio = (audioClip.afx( vfx.volumex, 0.5)
                     .afx( vfx.audio_fadein, 1.0)
                     .afx( vfx.audio_fadeout, 1.0))
new_clip = videoClip.set_audio(newAudio)

new_clip.write_videofile("newVidWithAudioFX.mp4")`
```

**Comment by Zulko** [comment]
please provide the error

**Comment by Zulko** [comment]
change ``audioClip.afx().afx()...`` to ``audioClip.fx().fx()``

**Comment by batmanrising** [comment]
Before changing the code, the error was

> 
> Traceback (most recent call last):
>   File "tempVidAud1.py", line 10, in <module>
>     newAudio = (audioClip.afx( vfx.volumex, 0.5)
> AttributeError: AudioFileClip instance has no attribute 'afx'

And after changing it from `audioClip.afx().afx()... `to `audioClip.fx().fx()` the error is 

> Traceback (most recent call last):
>   File "tempVidAud1.py", line 10, in <module>
>     newAudio = (audioClip.fx( vfx.volumex, 0.5)
> NameError: name 'vfx' is not defined
>

**Comment by Zulko** [comment]
Add this:
```
from moviepy.editor import vfx
```

For such questions (which are more related to python than moviepy, refer to stackoverflow, or reddit/learnpython)

**Comment by Gloin1313** [comment]
Should this be closed?

**Comment by earney** [comment]
closing since no response.

**Comment by haishibei** [comment]
@Zulko 
when i run the script as below :
`newAudio = (audioClip.volumex(0.5)
                     .fadein(1.0)
                     .fadeout(1.0))`
it report error below:
`AttributeError: 'AudioFileClip' object has no attribute 'fadein`

**Comment by Taitava** [comment]
@haishibei I was able to solve the same problem. Try to change `newAudio = (audioClip.volumex(0.5) .fadein(1.0) .fadeout(1.0))` to `newAudio = (audioClip.volumex(0.5) .audio_fadein(1.0) .audio_fadeout(1.0))`. I have not used `.volumex()` so I don't know if that needs the `audio_` prefix too or not.
