### ISSUE TITLE
FFMPEG crashes if the script is a .pyw

### ISSUE THREAD

**Issue by whelly** [Zulko/moviepy#517]
I'm trying to integrate my script into a background service, which means I need the command window to be invisible for compatibility issues. Everything works great as a normal .py file, but trying to hide the console as a .pyw causes some issues when the render starts. I see a spike in my CPU usage for a few seconds, then it exits. I also tried setting the FFMPEG parameter "loglevel" to silent but that didn't help either. Any idea what's causing this problem? I'm using Windows, Python 2.7, and the MoviePy package from pip.

**Comment by whelly** [comment]
Figured it out! There is a nifty parameter for `write_videofile` called `progress_bar`, so setting that to False fixed the issue! It's missing from the documentation which is why I didn't think of it, so perhaps adding that might help others looking for windowless renders. BTW, thanks for an awesome library Zulko!

**Comment by earney** [comment]
Awesome!

**Comment by Gloin1313** [comment]
The reason its not in the docs is because it was only recently added (#380 and #458), and is not in the PyPI version of moviepy. When we release another version, I assume we'll redo the docs to include all the added docstrings. Until then, we can't have the docs documenting unimplemented stuff!
