### ISSUE TITLE
I'm converting a .gif to .mp4, and it can play in QuickTime, but not in Chrome

### ISSUE THREAD

**Issue by linzhi** [Zulko/moviepy#519]
## do it like this,program execution without any errors
import moviepy.editor as mp
clip = mp.VideoFileClip("mygif.gif")
clip.write_videofile("myvideo.mp4", codec='mpeg4')

**Comment by earney** [comment]
Is the gif an animated gif?  If not you have to set a duration such as clip.set_duration (5)

**Comment by linzhi** [comment]
I set clip.set_duration (5),But still can not play in Chrome, Is not chrome does not support mpeg format video @earney

**Comment by earney** [comment]
Is chrome the only place where this is an issue?  Does it work in vlc?

**Comment by linzhi** [comment]
@earney  It can work in QuickTime...I do't install vlc

**Comment by earney** [comment]
have you tried another browser such as firefox?

**Comment by linzhi** [comment]
It could not play in firefox too..

**Comment by earney** [comment]
you could be right..  Could you remove the codec='mpeg4' and see if it works in chrome?

**Comment by linzhi** [comment]
If i remove codec=mpeg4 It will cause error...Maybe beacuse my ffmpeg don not support x264 @earney

**Comment by earney** [comment]
@linzhi   try opening the image file (gif) with ImageClip, instead of VideoFileClip.  Something like this:

```
import moviepy.editor as mp
clip = mp.ImageClip("mygif.gif")
clip.write_videofile("myvideo.mp4", codec='mpeg4')
```

**Comment by keikoro** [comment]
Closing this due to a lack of response after a potential solution was provided.
