### ISSUE TITLE
How to add a .srt file to a video as subtitle?

### ISSUE THREAD

**Issue by YoWhatever** [Zulko/moviepy#543]
I have a video without subtitle and an existing .srt file... What function can i use?

**Comment by earney** [comment]
@YoWhatever   see [https://github.com/Zulko/moviepy/blob/master/tests/test_misc.py](https://github.com/Zulko/moviepy/blob/master/tests/test_misc.py)  for an example of how to add a srt file to a video.

**Comment by Gloin1313** [comment]
@YoWhatever Did the link that Earney posted answer your question?

**Comment by YoWhatever** [comment]
@earney Thanks！

**Comment by earney** [comment]
@YoWhatever  can we close this issue?

**Comment by earney** [comment]
closing issue...  Please reopen if necessary..
