### ISSUE TITLE
Is there one potential bug in FFMPEG_READER?

### ISSUE THREAD

**Issue by duguyue100** [Zulko/moviepy#546]
Hi,

I'm using moviepy to read my video, using `FFMPEG_VideoReader`. As I'm reading a large volume of videos, I start to get this warning message:

```
Warning: in file /to/path/dataset/UCF-101-split/train/UnevenBars/v_UnevenBars_g20_c03.avi, 230400 bytes wanted but 0 bytes read,at frame 91/101, at time 3.64/4.00 sec. Using the last valid frame instead.
```

And then I tested my load frame function, it appears fine if I load the same video. I'm reading UCF-101 where there are about 13,000 videos for training a neural network. This really bug me because I don't see the reason why this is happening.

Here I attached my entire video loading function:

```python
def load_video(path, grayscale=False, target_size=None,
               n_frames=None, data_format=None):
    """Load Video."""
    if data_format is None:
        data_format = K.image_data_format()
    if data_format not in {'channels_first', 'channels_last'}:
        raise ValueError('Unknown data_format: ', data_format)

    vid_container = FFMPEG_VideoReader(path)
    # calculate how many frames skipped
    skip_frames = vid_container.nframes // n_frames
    frames = []
    for i in xrange(n_frames):
        frame_t = vid_container.read_frame()
        frame_t = util.img_as_float(frame_t)

        # gray scale
        if grayscale:
            if frame_t.ndim == 3:
                frame_t = color.rgb2gray(frame_t)

        # resize
        if target_size:
            frame_t = transform.resize(frame_t, target_size)
        # skip frames
        vid_container.skip_frames(skip_frames)
        frames.append(frame_t)

    vid_container.close()

    # make sure it's n_frames
    assert len(frames) == n_frames

    frames = np.asarray(frames, dtype=np.float32)
    # match data format
    if len(frames.shape) == 4:
        if data_format == 'channels_first':
            frames = frames.transpose(0, 3, 1, 2)
    elif len(frames.shape) == 3:
        if data_format == 'channels_first':
            frames = frames.reshape(
                (frames.shape[0], 1, frames.shape[1], frames.shape[2]))
        else:
            frames = frames.reshape(
                (frames.shape[0], frames.shape[1], frames.shape[2], 1))
    else:
        raise ValueError('Unsupported image shape: ', frames.shape)

    return frames
```

Regards,
Yuhuang.

**Comment by Gloin1313** [comment]
Is this with the latest version? Run `pip3 install moviepy --upgrade` to get the latest (or just `pip install...` for python 2).

**Comment by duguyue100** [comment]
Thanks for the fast reply, I'm using python 2, as the latest release is just one day ago.. my current version is `0.2.3.1`

**Comment by Gloin1313** [comment]
Can you try with 0.2.3.2? I doubt it'll have changed, but you might as well?

**Comment by duguyue100** [comment]
@Gloin1313 False alarm, I think the reason is simply because I overshot.

But there is one thing that is missing from the ffmpeg_reader, in `read_frame()` function, `self.pos` is not updated:
https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L118

Shouldn't it be updated after reading a frame successfully?

**Comment by Gloin1313** [comment]
@duguyue100 Do you want to open a new issue for that?

**Comment by duguyue100** [comment]
@Gloin1313 Emm... I'm handling it externally by manually adding 1 after calling `read_frame()`.
So I'm good for now.
But you or I can reopen this one if you feel this missing pos update is actually a bug.
