### ISSUE TITLE
Write_videofile results in 1930x1080 even when I force clip.resize(width=1920,height=1080) before write_videofile

### ISSUE THREAD

**Issue by evanthemann** [Zulko/moviepy#547]
I have a script that transforms Vertical video into horizontal video. Right now these source files are all from mobile devices, and sometimes from Snapchat. I think there is something weird about the pixel aspect ratio because some of my clips come out as 1930x1080 or other resolutions that are *almost* 16x9. Any idea what the problem could be?

```
    clip = VideoFileClip(path)
    clip2 = clip.crop(x_center=202, y_center=360, width=404, height=227)
    clip3 = clip2.resize(width=1920,height=1080)
    clip3.write_videofile(output, codec='libx264', audio_codec='aac', temp_audiofile='temp-audio.m4a', remove_temp=True)
```

**Comment by Gloin1313** [comment]
You're not supposed to use both `height=` and `width=`. You use one of them, and it automatically works out the other keeping the same aspect ratio. You don't want this to happen, so use `newsize=(1920,1080)`.
See [resize docs](https://zulko.github.io/moviepy/ref/videofx/moviepy.video.fx.all.resize.html).

**Comment by evanthemann** [comment]
Thank you! That was exactly what I needed.

**Comment by kallimadhavareddy** [comment]
newsize=(1920,1920)
clip_resized = clip.resize(newsize)
clip_resized.write_videofile("C:\\TEST\\NEW_4.mp4")

**Comment by keikoro** [comment]
@kallimadhavareddy It's not clear to me why you added your comment to this closed issue. I'd ask you to open a new issue if you are experiencing problems and fill in the issue template as best as you can.

**Comment by vaccarieli** [comment]
hi, I am trying to resize a video and force the aspect ratio, I got a video 1280*720 and want to resize to 1280*1596, so the video keeps the same aspect ration but in the process the spaces for the height are filled out with black frames instead. So my final result is the original video in the center on that dimention.
