### ISSUE TITLE
make Mixing clips work on rtmp stream?

### ISSUE THREAD

**Issue by notedit** [Zulko/moviepy#554]
moviepy is great. 

i want to do video composing with rtmp stream.   i know moviepy does not  support rtmp stream now.

i want to do this base moviepy, can you give me some keyword  or direction ?

what i want to do is  picture in picture mixing and side by side mixing.

**Comment by realwol** [comment]
rtsp is needed too!

**Comment by keikoro** [comment]
I'm closing this since the issue hasn't had any new comments since 2017. Video editing (incl. supported formats) is dependent on FFMPEG.
