### ISSUE TITLE
Time-symetrization not running for .gif conversion

### ISSUE THREAD

**Issue by joelven** [Zulko/moviepy#556]
Hello I am running Moviepy with virtual environment and python3 I tried a few examples for "Making GIFs From Video Files" and are running good however I am having problems with the one for Time-symetrization" I am getting different errors.  I end up getting " ... "

This is the code I am running. Perhaps I am missing something! Do I need 

`from moviepy.editor import *`

or the order of commands are incorrect or incomplete?
```
from moviepy.editor import *
from moviepy.decorators import (apply_to_mask, apply_to_audio,requires_duration)
from moviepy.video.compositing.concatenate import concatenate_videoclips
from .time_mirror import time_mirror
def time_symetrize(clip):
    return concatenate([clip, clip.fx( vfx.time_mirror )])
clip = (VideoFileClip("frozen_trailer.mp4", audio=False)
        .subclip(36.5,36.9)
        .resize(0.5)
        .crop(x1=189, x2=433)
        .fx( time_symetrize ))
clip.write_gif('sven.gif', fps=15, fuzz=2)
```
I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '__main__.time_mirror'; '__main__' is not a package
```
Thanks in advance

**Comment by tburrows13** [comment]
Simply remove the line `from .time_mirror import time_mirror` and it should work.
