### ISSUE TITLE
Reading / writing videofile clip with alpha layer

### ISSUE THREAD

**Issue by harshvak** [Zulko/moviepy#559]
Hi,

I am not able to write a video file with the transparency mask (alpha layer) using the write_videofile function. The videofile clip is created using ImageClip function on a png image file having alpha layer.

The code is below

    img = numpy.zeros([1200,1800,4],dtype=numpy.uint8)
    img[:,:] = [255,255,255,0] #<-- created a blank transparent frame of dimension 1800x1200
    scipy.misc.imsave('outfile.png', img)

    initial_clip = editor.ImageClip("outfile.png")
    initial_clip = initial_clip.set_duration(audioclip.duration+1)

    initial_clip.write_videofile("initial.avi", codec = 'png', fps = 24)

On using the write_videofile in the last statement above, with the png / mpeg4 codecs, the alpha layer is getting lost and a video with a white background is created, with no transparency.

When I read the video back using VideoFileClip, and iterate through the frames, I get the numpy array shapes as (1800,1200,3) with the 3 standing for rgb (alpha layer missing).

    initial_clip_test = editor.VideoFileClip('initial.avi',has_mask=True)
    for frame in initial_clip_test.iter_frames():
        print(frame.shape)

frame.shape gives me (1800,1200,3) instead of (1800,1200,4)

I need to write the video clips created while maintaining the transparency layer at multiple stages of my code. How do I go about this?

**Comment by harshvak** [comment]
The crux of the matter is, I am not able to save a VideoClip with a mask to a video file with a mask.

The documentation for VideoFileClip says otherwise, but not able to figure out how to do it -

has_mask:

Set this to ‘True’ if there is a mask included in the videofile. Video files rarely contain masks, but some video codecs enable that. For istance if you have a MoviePy VideoClip with a mask you can save it to a videofile with a mask. (see also VideoClip.write_videofile for more details).

**Comment by MilesGordon** [comment]
I am also having this problem, and can't find much information about it. Everything that I find that's related is, like this post, unanswered.

**Comment by TejasBob** [comment]
I also faced same issue, didn't find any relevant source of information, please help.

**Comment by jonata** [comment]
I have made various tests with codecs, and I did not find a way to export with alpha channel (for example, using ProRes 4444, or png inside avi/mov, or using ffv1).

**Comment by harshvak** [comment]
I have found a way to do this, just recently. It has to do with a minor change in the moviepy source code. Will publish the same by tomorrow

**Comment by harshvak** [comment]
This looks good. Closing the thead.

**Comment by mondeja** [comment]
Since this is not added yet, I'm reopening this.

**Comment by robinechuca** [comment]
To find the all the available codecs supporting alpha layer, you can use [cutcutcodec](https://cutcutcodec.readthedocs.io/latest/build/examples/advanced/write_alpha.html):
```python
from cutcutcodec.core.compilation.export.compatibility import Compatibilities
print(Compatibilities().codecs_video(pix_fmt="rgba"))  # for lossless
print(Compatibilities().codecs_video(pix_fmt="yuva420p"))  # for lossely
```
CutCutCodec and MoviePy are both using ffmpeg in background, so theses results are available for moviepy as well.
