### ISSUE TITLE
Investigate test_matplotlib and test_issue_368 failures

### ISSUE THREAD

**Issue by mbeacom** [Zulko/moviepy#563]
The `test_issue_368` method in `test_issues.py` and `test_matplotlib` in `test_examples.py` fails during travis builds for Python 3.4 and 3.6 (which includes all matrices now as the others are already disabled for these tests).

**Comment by mondeja** [comment]
This is superseded by #1412 and #1417. Could you close this @tburrows13?

**Comment by mbeacom** [comment]
Whoa! 😂  Thanks!
