### ISSUE TITLE
tqdm progress bar write_videofile send to iterator

### ISSUE THREAD

**Issue by djevo1** [Zulko/moviepy#568]
It would be useful if moviepy was able to output the progress bar as an interator for use with tools such as slack progress bar to create integrated encoding solutions.

**Comment by Gloin1313** [comment]
Yes, this is a good request, see #412 (and others linked from there) for discussion. This has been implemented in #154 and #150, so you can have a look at those PRs, and see if they do what you want. Please report back if they solve your problem!

**Comment by djevo1** [comment]
Yes it does appear to solve the issue, but I can't find any reference to 
this in the manual.

**Comment by Gloin1313** [comment]
That's because they are not in the main repo ... yet.

**Comment by djevo1** [comment]
Any plans on when it will make it to the main repo?

**Comment by Gloin1313** [comment]
Hmm... we'd need some documentation on how to use it, and a confirmation that it works. Would you like to try #154 on your machine, and check it works?

**Comment by djevo1** [comment]
Sure, but I am not sure how to access the progress bar

**Comment by tburrows13** [comment]
Implemented in v1.0. See #1020.
