### ISSUE TITLE
Geting framesize from moviepy

### ISSUE THREAD

**Issue by djevo1** [Zulko/moviepy#571]
Is there a simple method for getting video dimensions in moviepy?

**Comment by Gloin1313** [comment]
I guess you've found the answer, but for future googlers, you use `clip.w` to get its width, and `clip.h` to get the h.eight

**Comment by djevo1** [comment]
Yes. I did. I used clip.size however.

---Sent from Boxer | http://getboxer.com

On May 27, 2017 at 4:21:50 AM EDT, Gloin1313 <notifications@github.com> wrote:I guess you've found the answer, but for future googlers, you use clip.w  to get its width, and clip.h  to get the h.eight  —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Zulko/moviepy","title":"Zulko/moviepy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Zulko/moviepy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Gloin1313 in #571: I guess you've found the answer, but for future googlers, you use `clip.w` to get its width, and `clip.h` to get the h.eight"}],"action":{"name":"View Issue","url":"https://github.com/Zulko/moviepy/issues/571#issuecomment-304437490"}}}

**Comment by mbeacom** [comment]
[VideoClip Attr Docs](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#videoclip) for more details regarding VideoClip `attributes`.
