### ISSUE TITLE
ImageSequenceClip video changes the object's color in the created video clip

### ISSUE THREAD

**Issue by eduardocl** [Zulko/moviepy#573]
Hello,

I'm gathering some images from a IP cam through OpenCV and the frames are hold on array called "frames". I wish to create a video with these frames, and first, I tried with ffpmeg and it is ok, but if I try to generate the video with lines bellow, the video shows different colors, such as, a red car is shonw purple. 

Can anyone help on this?  

motionvideoclip = ImageSequenceClip(self.frames, fps=20)
motionvideoclip.write_videofile("output.mp4", fps=20)

Best regards,
Eduardo.

**Comment by ybloch** [comment]
Okay, I found, for me, this solves the problem:
`import cv2` 
`my_clip = ImageSequenceClip([cv2.cvtColor(frame, cv2.COLOR_RGB2BGR) for frame in frames], fps=20)`

**Comment by keikoro** [comment]
Closing this due to a lack of response after a potential solution was shared.
