### ISSUE TITLE
Bug: ffmpeg_reader opens stderr to a socket, but never reads it - ffmpeg hangs after 4096 bytes of stderr messages

### ISSUE THREAD

**Issue by shlomimatichin** [Zulko/moviepy#576]
Hi,

moviepy/video/io/ffmpeg_reader.py line 81: stderr is opened in subprocess.PIPE mode, which underlying implementation actually opens a socket for, which the linux kernel buffers for 4096 bytes. Some of the files we've been working with produce stderr messages, and since noone ever reads the stderr pipe, the ffmpeg reader process just hangs, hanging the complete video pipeline. For our internal use we have commented out this line (and line 171), but this can also be solved by opening a thread which sole purpose is to read stderr, and prevent this hang.

Thanks for all your work, big fan here,
Shlomi

**Comment by earney** [comment]
for ffmpeg_audio, we have the option to output stderr to a logfile (or to None).  Do you think something like that might be sufficient for your needs?

**Comment by keikoro** [comment]
Closing this due to a lack of response by OP since 2017.

**Comment by shlomimatichin** [comment]
Apologies, only saw this now.... of course, go ahead and close it. Thanks
again for maintaining moviepy. Cheers!
