### ISSUE TITLE
read_frame stops returning frames of data

### ISSUE THREAD

**Issue by pkarp0** [Zulko/moviepy#583]
If a short HD mp4 VideoFileClip (~12MB) is concatenated after a long HD VideoFileClip (~650MB) (where both are being read from a url on amazon s3) the short clip will freeze a few seconds in since the reader no longer is returning frames.

```
from moviepy.editor import *
long_vid = VideoFileClip("https://example.s3.amazonaws.com/long.mp4")
short_vid = VideoFileClip("https://example.s3.amazonaws.com/short.mp4")
out = concatenate_videoclip([long_vid, short_vid])
out.write_videofile('output.mp4', preset='ultrafast', verbose=True)

```
Logs may show the ffmpeg_reader warning that xxx bytes wanted but 0 bytes read while writing frames from short_vid. This occurs after a few seconds into short_vid but the video image will be frozen from that point forward since the reader is no longer returning any data.

My workaround is to first read the short video to the local filesystem. This will not work going forward since this application must run on lightly provisioned systems.

**Comment by keikoro** [comment]
Closing this issue as it's old and missing information needed to try to reproduce the problem.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
