### ISSUE TITLE
Black background on transparent watermark after first loop

### ISSUE THREAD

**Issue by ramazk** [Zulko/moviepy#594]
I'm putting watermark on video with blinking element. The problem is that on first loop the element disappear as expected, but on all next loops after disappearing there is a black background beneath it. Here is my code:
`videoClip = VideoFileClip("video.mp4")`
`logoClip = ImageSequenceClip([#lots of 32bit png files here that construct watermark#], with_mask=True, fps=24).loop(duration=videoClip.duration)`
`videoClip = CompositeVideoClip([videoClip, logoClip.set_pos(#setting position here#)])
videoClip.write_videofile("result.mp4", fps=24, progress_bar=False)`

**Comment by Zulko** [comment]
Sounds like a bug of the ``loop`` feature which forgets to loop the mask. If that is it, it should be fixed at some point. In the meantime can you try this workaround ?

```
logo_clip = ImageSequenceClip(...)
looped_mask = logo_clip.mask.loop(duration=video_clip.duration)
logo_clip = logo_clip.loop(duration=video_clip.duration).set_mask(logo_clip.mask.loop(looped_mask))
```

**Comment by ramazk** [comment]
Had to add loop duration to logo_clip ImageSequenceClip:
`logo_clip = ImageSequenceClip(...).loop(duration=video_clip.duration)` otherwise got `ValueError: Attribute 'duration' not set` exception.
But result is the same - only first loop looking normal.

**Comment by Zulko** [comment]
I dont understand that. What is the exact code you tried ?

**Comment by ramazk** [comment]
If this:
```
video_clip = VideoFileClip("video.mp4")
logo_clip = ImageSequenceClip(logoFiles, fps=24)
looped_mask = logo_clip.mask.loop(duration=video_clip.duration)
logo_clip = logo_clip.loop(duration=video_clip.duration).set_mask(looped_mask)
videoClip = CompositeVideoClip([video_clip, logo_clip])
```
I receive `ValueError: Attribute 'duration' not set`
If I add this duration - `logo_clip = ImageSequenceClip(logoFiles, fps=24).loop(duration=videoClip.duration)`, I get mask problems as mentioned in first message.

**Comment by ksfire** [comment]
I had the issue when creating a `CompositeVideoClip` from a gif and looping the clip using `.loop` , the repetitions were all black. The gif was only displayed for the first time. I found a workaround of temporarily writing the file using `write_videofile` and creating a new `VideoFileClip` from that file.

**Comment by keikoro** [comment]
I'm closing this as it's an old issue and the above comment contains a workaround.

Feel free to open a new issue following our issue template and referencing this older one if the problem persists with the latest recommended version of MoviePy.

**Comment by Kampfkarren** [comment]
You can fix the duration attribute error by calling `set_duration` on the mask:

```py
def loop(video, duration):
	looped_mask = video.mask.set_duration(video.duration).loop(duration = duration)
	looped_video = video.loop(duration = duration)
	return looped_video.set_mask(looped_mask)
```
