### ISSUE TITLE
ffmpeg not installed on Mac

### ISSUE THREAD

**Issue by fmarzocca** [Zulko/moviepy#595]
Hi,

I installed moviepy on Mac with `pip3 install moviepy`, but no ffmpeg got in. Should I have to manually install ffmpeg with Homebrew?

**Comment by Gloin1313** [comment]
Just run any program with `from moviepy.editor install *`, and it will download it for you.
If it doesn't (I think this might have actually changed recently), it will give you a command to run, `imageio.plugins.ffmpeg.download()`, which you can run in the shell after running `import imageio`.
Let us know if this helped!

**Comment by Zulko** [comment]
Wow, I didn't know you could have syntax like ``from moviepy.editor install *``. Is it a new thing ?

**Comment by Gloin1313** [comment]
@Zulko Sorry, my bad! Should  be `import`!

**Comment by Zulko** [comment]
I actually believed it know I am disappointed. It's cool to see that moviepy is auto-installing ffmpeg again.

**Comment by Gloin1313** [comment]
Sorry, I really haven't made myself very clear! I don't think it is auto-installing ffmpeg again, when I said it had changed recently, I meant it had _stopped_ auto-installing ffmpeg. And, yeah, I guess it wasn't that recent.

**Comment by Zulko** [comment]
ok got it

**Comment by fmarzocca** [comment]
Thanks. I will go through this

**Comment by fmarzocca** [comment]
it downloaded a "ffmpeg.osx" file. What is it?

**Comment by fmarzocca** [comment]
Got. it. I had to make it executable in order to test it. But this is an old version of ffmpeg (2.6.3). Current verison is 3.3.2

**Comment by jakirkham** [comment]
FWIW am adding a package to [conda-forge]( https://conda-forge.org/ ), which would install `moviepy` with `ffmpeg` out of the box. Feedback and other maintainers on the package welcome. 😄

xref: https://github.com/conda-forge/staged-recipes/pull/3331

**Comment by tburrows13** [comment]
Now that moviepy uses `imageio_ffmpeg`, this shouldn't be an issue.
