### ISSUE TITLE
test_duration() fails in test_TextClip()

### ISSUE THREAD

**Issue by Julian-O** [Zulko/moviepy#598]
I am trying to get the tests to run on my Windows machine. One of the tests that fails is `test_TextClip::test_duration()`.

However, I don't think it is a problem with my set-up. The test *should* fail. 

At first glance, the test seems reasonable: 
```
    clip = TextClip('hello world', size=(1280,720), color='white')
    clip.set_duration(5)
    assert clip.duration == 5
```

However, `set_duration()` has an `@outplace` decorator, which means it doesn't act on the clip you pass in, but instead makes a copy and acts on that. So, the original clip's duration is not affected, and the test fails.

Either it should not have the `@outplace` decorator, or the second line should read:

```
    clip = clip.set_duration()
```

(I am afraid I can't tell which is more appropriate; I am still new to the code.)

The test is skipped by Travis (because of what sounds like an ImageMagick configuration error).

Does it work for Linux users?

**Comment by earney** [comment]
PR #585 fixes this.  It just has not been merged into the repo yet.   Since I authored the PR, it is probably best for someone to merge (and someone elses eyes get a chance to look at it before it is merged).

**Comment by Julian-O** [comment]
Great. Thanks. Will close and wait. (This merge won't be fun.)
