### ISSUE TITLE
test_tools.test_6() doesn't test anything.

### ISSUE THREAD

**Issue by Julian-O** [Zulko/moviepy#599]
`test_6()` in `test_tools.py` looks like this:

~~~ """Test subprocess_call for operation.
    The process sleep should run for a given time in seconds.
    This checks that the process has deallocated from the stack on
        completion of the called process.
    """
    process = tools.subprocess_call(["sleep" , '1'])
    time.sleep(1)
    assert process is None
~~~

It has a number of problems, but mainly that it doesn't test anything.

* Calling `sleep` as a subprocess doesn't work on Windows, where `sleep` is not a defined command/executable. (The equivalent batch command on Windows (`timeout`) requires careful dealing wit `stdin`. Consider using `["ping", '127.0.0.1', '-n1' '-w', '1000']` instead. I believe that is cross-platform.

* Sleeping afterwards is unnecessary. The command will already have completed before it returns. It is not concurrent.

* (If it *was* concurrent, sleeping for 1 second would be insufficient. Sleeping for more than a couple of seconds would be required.)

* The value of process does not/could not be changed by the subprocess_call, even if it were concurrent.

* The subprocess_call does not return a value, so process will always be None, which is the only reason this test passes.

All it tests is that subprocess_call doesn't raise an exception. I'm inclined to remove the test entirely.

**Comment by tburrows13** [comment]
`test_6()` no longer exists.
