### ISSUE TITLE
where can i find the material(png, mov) files used in the example code?

### ISSUE THREAD

**Issue by bubble501** [Zulko/moviepy#602]
I am trying to run the example code, but I had no clue as for where to find the files used in the example,

**Comment by kencochrane** [comment]
@bubble501 not sure which example you are talking about, but you can find the ones that are available here: https://github.com/Zulko/moviepy/tree/master/examples

**Comment by kerstin** [comment]
@bubble501 Did @kencochrane comment help you solve your problem?

**Comment by tburrows13** [comment]
Linking #1133

**Comment by keikoro** [comment]
Closing in favour of the linked issue, which has more information on the topic of examples.
