### ISSUE TITLE
Very tight requirements

### ISSUE THREAD

**Issue by jakirkham** [Zulko/moviepy#615]
It seems like the [requirements]( https://github.com/Zulko/moviepy/blob/v0.2.3.2/setup.py#L63-L65 ) for this package are very tightly pinned (down to the patch number). Having this tight of pinning makes it hard to install `moviepy` into environments or use with larger software stacks that have other requirements that may conflict with these specific versions. Would it be possible to loosen them a bit?

**Comment by Zulko** [comment]
That's a very valid issue. @mbeacom would it still work if the ``==`` were replace by ``>=`` ?

**Comment by Gloin1313** [comment]
@Zulko not necessarily. I seem to remember that we had a problem where a _newer_ version of numpy broke something. However, maybe we should just fix the code to cope.

**Comment by Julian-O** [comment]
There have been significant improvements to this as part of PR #626. It was necessary to loosen the requirements to make it easier to install across multiple platforms.

Please inspect the setup.py file there, and determine if you are happy to close this when that is merged.

**Comment by tburrows13** [comment]
This is currently fulfilled. All current versions and many previous versions of main dependencies are marked as acceptable in setup.py.
