### ISSUE TITLE
Adding conda-forge package

### ISSUE THREAD

**Issue by jakirkham** [Zulko/moviepy#616]
Just dropping a note here to indicate that I'm adding a package to [conda-forge]( http://conda-forge.org/ ). This will allow people to easily install `moviepy` with [conda]( https://conda.io/docs/ ). Here is the PR ( https://github.com/conda-forge/staged-recipes/pull/3331 ). Welcome feedback and other maintainers.

**Comment by tburrows13** [comment]
This is being stored at https://github.com/conda-forge/moviepy-feedstock. Currently rather out of date though.
