### ISSUE TITLE
Installation of tests

### ISSUE THREAD

**Issue by jakirkham** [Zulko/moviepy#617]
Currently if one installs `moviepy`, one gets a `test` package in `site-packages` next to `moviepy`. This is a bit confusing if one installs many packages as one doesn't know what brought in `tests`. If the goal is to ensure the `tests` are to be installed with `moviepy`, would recommend a common pattern, which is to place `tests` under `moviepy`. This way everything is self-contained in one package clearly associated with `moviepy`. Alternatively if the `tests` are not to be installed, it would be good if `setup.py` were updated to avoid this behavior.

**Comment by Zulko** [comment]
Great point. @earney @mbeacom any reason why moviepy installs a "test" package

**Comment by earney** [comment]
No reason..   I believe this was done by mistake.

**Comment by jakirkham** [comment]
Do you have a preference w.r.t. the 2 options presented above or some other yet unconsidered alternative?

**Comment by Zulko** [comment]
From what @earney said it would be option 2: update ``setup.py`` to avoid this behavior.

**Comment by berndf** [comment]
Any news here?
moviepy cannot be updated in gentoo because the standard installation routine fails with:

`Package installs 'tests' package which is forbidden and likely a bug in the build system.`

Which is true. I did not see what leads to this problem in setup.py, seems that the 'tests' directory is not masked from installation.

**Comment by berndf** [comment]
BTW, seems that the line
`recursive-include docs *`
in MANIFEST.in is the culprit as it marks 'tests' for installation (and 'docs' twice, formally).

**Comment by tburrows13** [comment]
Fixed in #880.
