### ISSUE TITLE
concatenate_videoclips() can't handle TextClips

### ISSUE THREAD

**Issue by ixbidie** [Zulko/moviepy#622]
## Description
When composing a clip with an ImageClip and a TextClip, the composition will render, but the clip resulting from calling ``concatenate_videoclips()`` won't.

## HowTo reproduce
1. save example to .py file
2. Have moviepy version 0.2.3.2 installed
3. run the example with python 3 (tested with 3.5.2)

```python
#!/usr/bin/python3

import requests
import os
from moviepy.editor import ImageClip, TextClip, CompositeVideoClip, concatenate_videoclips

IMAGE_URL = 'http://www.planwallpaper.com/static/images/4-Nature-Wallpapers-2014-1_cDEviqY.jpg'
IMAGE_PATH = '/tmp/test.jpg'
RESULT_PATH = '/tmp/result.png'

# get test image if necessary 
if not os.path.exists(IMAGE_PATH):
    resp = requests.get(IMAGE_URL)
    with open(IMAGE_PATH, 'wb') as f:
        for chunk in resp.iter_content(chunk_size=128):
            f.write(chunk)

image_clip = ImageClip(IMAGE_PATH, duration=1)
text_clip = TextClip('Hello World', fontsize=70, color='white')
comp_clip = CompositeVideoClip([image_clip, text_clip])
comp_clip.save_frame(RESULT_PATH) # works

concat = concatenate_videoclips([comp_clip], method="compose")
concat.save_frame(RESULT_PATH) # fails
```

## Behaviour
The code will render the image to the specified path but will crash afterwars when trying the same with 
the ``concatenate_videoclips()`` function.
The error looks like this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2112, in cumsum
    cumsum = a.cumsum
AttributeError: 'list' object has no attribute 'cumsum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "moviepy_bug.py", line 21, in <module>
    concat = concatenate_videoclips([comp_clip], method="compose")
  File "/usr/local/lib/python3.5/dist-packages/moviepy-0.2.3.2-py3.5.egg/moviepy/video/compositing/concatenate.py", line 71, in concatenate_videoclips
    tt = np.cumsum([0] + [c.duration for c in clips])
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2114, in cumsum
    return _wrapit(a, 'cumsum', axis, dtype, out)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

## Thoughts
I saw #123, but TextClip does not have a duration afaik. CompositionClips neither. Please tell me if I'm wrong here.

**Comment by ixbidie** [comment]
raw pastebin: https://pastebin.com/raw/DB5UsJmL

**Comment by Zulko** [comment]
This is not a rendering bug, it's just that ``concatenate_videoclip`` is not meant to accept clips with no duration. Your CompositeClip has no duration because the TextClip is considered infinite, but my guess is that if you give a duration to the CompositeClip it should work:
```
comp_clip = CompositeVideoClip([image_clip, text_clip]).set_duration(1)
```

**Comment by ixbidie** [comment]
That's right. Thanks. I feel dumb now.

**Comment by earney** [comment]
We really need to implement a more user friendly error message.  May we use your example as a base case for testing?

**Comment by ixbidie** [comment]
I'd love if I can help :)

**Comment by ixbidie** [comment]
Accept my humble contribution

**Comment by earney** [comment]
Thanks..

**Comment by lorenaceballos** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-15-4b8ff0f21337> in <module>
----> 1 img = concatenate_videoclips(clips)

~/.local/lib/python3.6/site-packages/moviepy/video/compositing/concatenate.py in concatenate_videoclips(clips, method, transition, bg_color, ismask, padding)
     73     sizes = [v.size for v in clips]
     74 
---> 75     w = max([r[0] for r in sizes])
     76     h = max([r[1] for r in sizes])
     77 

ValueError: max() arg is an empty sequence

**Comment by TheNewThinkTank** [comment]
I think my current issue might be related to this. Here is what I am trying to do:

`from moviepy import *
from moviepy.editor import *

video = VideoFileClip("video_orig.mp4")

txt_clip = (TextClip("Some dummy text",
                              fontsize=70,
                              color='white'
                              )
                  .with_position('center')
                  .with_duration(10)
                  )`

I am getting this error:

`AttributeError: 'TextClip' object has no attribute 'with_position'`

Is this also due to something with duration, or another issue ?

**Comment by tburrows13** [comment]
Use `set_position` and `set_duration` because you are still on v1.x. They are being renamed in v2.0.

**Comment by donnijobb-cloud** [comment]
# pip install moviepy

from moviepy.editor import (
    ImageClip, AudioFileClip, CompositeVideoClip,
    concatenate_videoclips, vfx, ColorClip
)
import glob, os, sys

# ====== Grundsetup ======
W, H = 1080, 1920          # 9:16 canvas
IMG_DUR   = 1.5             # sek per bild
LOGO_DUR  = 2.0             # sek för logga
ZOOM_STRENGTH = 0.06        # 6% total zoom över klippets längd
LOGO_ZOOM = 0.02            # svagare zoom på loggan
AUDIO_VOL = 0.85
FADE_AUDIO = 1.0
FPS = 30
BITRATE = "5000k"
TRANSITION = 0.35           # crossfade mellan bilder (sek)
USE_CONTAIN = False         # True = letterbox, False = täck & beskära

# ====== Källfiler ======
images = [
    "bild1.jpeg", "bild2.jpeg", "bild3.jpeg", "bild4.jpeg", "logga.jpeg"
]
music_file = "hype.mp3"

# Auto-upptäck bilder om listan saknas/inte finns
if not all(os.path.isfile(p) for p in images):
    found = sorted(
        glob.glob("*.jpg") + glob.glob("*.jpeg") + glob.glob("*.png")
    )
    if len(found) >= 2:
        # sista antas vara logga om filnamn innehåller 'log'/'logo' annars sista i listan
        logo_candidates = [f for f in found if "log" in f.lower()]
        logo_path = logo_candidates[-1] if logo_candidates else found[-1]
        images = [f for f in found if f != logo_path] + [logo_path]
    else:
        print("Hittade inte tillräckligt med bilder. Avbryter.")
        sys.exit(1)

# ====== Hjälpfunktioner ======
def ken_burns_zoom(clip, strength: float):
    # Linjär skala 1.0 -> 1.0 + strength
    return clip.fx(vfx.resize, lambda t: 1.0 + (strength / max(clip.duration, 0.001)) * t)

def fit_cover_to_canvas(path, duration, zoom_strength):
    c = ImageClip(path).set_duration(duration)
    # Skala efter höjd, beskär center till exakt W x H
    c = c.resize(height=H)
    if c.w < W:  # om för smal, skala efter bredd istället
        c = ImageClip(path).set_duration(duration).resize(width=W)
    c = c.crop(x_center=c.w/2, y_center=c.h/2, width=W, height=H)
    return ken_burns_zoom(c, zoom_strength)

def fit_contain_to_canvas(path, duration, zoom_strength):
    c = ImageClip(path).set_duration(duration)
    # Skala så hela bilden syns
    aspect_img = c.w / c.h
    aspect_can = W / H
    c = c.resize(height=H) if aspect_img > aspect_can else c.resize(width=W)
    bg = ColorClip(size=(W, H), color=(0,0,0), duration=duration)
    c = CompositeVideoClip([bg, c.set_position(("center", "center"))], size=(W, H))
    return ken_burns_zoom(c, zoom_strength)

def make_clip(path, dur=IMG_DUR, zoom=ZOOM_STRENGTH):
    return fit_contain_to_canvas(path, dur, zoom) if USE_CONTAIN else fit_cover_to_canvas(path, dur, zoom)

# ====== Bygg bildklipp (alla utom loggan) ======
body_paths = images[:-1]
logo_path  = images[-1]

clips = []
for p in body_paths:
    if not os.path.isfile(p):
        print(f"Varning: {p} saknas. Hoppar över.")
        continue
    try:
        clips.append(make_clip(p, IMG_DUR, ZOOM_STRENGTH))
    except Exception as e:
        print(f"Fel vid inläsning av {p}: {e}. Hoppar över.")

if not clips:
    print("Inga giltiga bildklipp att rendera. Avbryter.")
    sys.exit(1)

# ====== Crossfade-setup ======
# Lägg crossfade på alla klipp utom första och använd padding=-TRANSITION i concat.
clips_fx = [clips[0]]
for c in clips[1:]:
    clips_fx.append(c.crossfadein(TRANSITION))

# ====== Logga-outro ======
if os.path.isfile(logo_path):
    try:
        logo_img = ImageClip(logo_path).set_duration(LOGO_DUR)
        target_logo_w = min(600, int(W * 0.7))
        logo_img = logo_img.resize(width=target_logo_w)

        logo_bg  = ColorClip(size=(W, H), color=(0,0,0), duration=LOGO_DUR)
        logo_cmp = CompositeVideoClip(
            [logo_bg, logo_img.set_position(("center", "center"))],
            size=(W, H)
        )
        logo_cmp = ken_burns_zoom(logo_cmp, LOGO_ZOOM)
        # mjuk ingång i loggan
        logo_cmp = logo_cmp.crossfadein(TRANSITION)
        clips_fx.append(logo_cmp)
    except Exception as e:
        print(f"Varning: kunde inte bygga logga-outro ({e}). Fortsätter utan logga.")
else:
    print(f"Varning: logga hittades inte på {logo_path}. Fortsätter utan logga.")

# ====== Sätt ihop med crossfade ======
final = concatenate_videoclips(clips_fx, method="compose", padding=-TRANSITION)

# ====== Musik (med fade in/out & trim) ======
if os.path.isfile(music_file):
    try:
        audio = AudioFileClip(music_file).volumex(AUDIO_VOL)
        audio = audio.audio_fadein(FADE_AUDIO).audio_fadeout(FADE_AUDIO)
        audio = audio.subclip(0, final.duration)
        final = final.set_audio(audio)
    except Exception as e:
        print(f"Varning: kunde inte lägga ljud ({e}). Exporterar utan ljud.")
else:
    print(f"Varning: Hittar inte {music_file}. Exporterar utan ljud.")

# ====== Export ======
final.write_videofile(
    "nof_reel.mp4",
    fps=FPS,
    codec="libx264",
    audio_codec="aac",
    preset="medium",
    bitrate=BITRATE
)
