### ISSUE TITLE
make an ImageClip from an image file failed

### ISSUE THREAD

**Issue by tismagic** [Zulko/moviepy#624]
I wanna make a ImageClip from an image use
clip = ImageClip(image_name, duration=3)
here is the image link "https://p3.pstatp.com/origin/26e10004661cb573c9a5"
but the program failed with an error "SyntaxError: not a TIFF file (header b'' not valid)"
Any suggestions? Thank you
需要帮助，谢谢

**Comment by keikoro** [comment]
The linked file is not available anymore and it's unclear what was tried at that point.
Feel free to reopen the issue using the issue template + code samples + example files.
