### ISSUE TITLE
Adopt Semantic Versioning

### ISSUE THREAD

**Issue by Julian-O** [Zulko/moviepy#627]
The current versioning of MoviePy includes a total of four parts. This is incompatible with the bdist feature of setuptools. Further, because it doesn't follow industry practices, it makes it hard for other people to determine the versions they are happy to install.

I recommend adopting [Semantic Versioning](http://semver.org/).

This requires changing the version number (up to 0.3.0) and declaring in the Readme that we use it and clients can depend on that.

**Comment by tburrows13** [comment]
Done from version 2.0 onwards.
