### ISSUE TITLE
render supersampled time_mirrored clip

### ISSUE THREAD

**Issue by timpauli** [Zulko/moviepy#635]
When you call `write_videofile()` on a clip on which you called `supersample()` and `time_mirror()` before you always run into:

> OSError: MoviePy error: failed to read the first frame of video file material_hd/jeita/wtf1.avi. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

Example Code:

```
from moviepy.video.fx.all import time_mirror, supersample

def supersample_time_mirror(clip):
        result = supersample(clip.fx(time_mirror), 1, 1)
        result.write_videofile("supersample_time_mirror.mp4")
```

**Comment by tburrows13** [comment]
I think that this has been fixed in #1124. Feel free to reopen if the issue persists.
