### ISSUE TITLE
video.to_ImageClip(t=timestamp) not throwing error on corrupted video

### ISSUE THREAD

**Issue by angyangie** [Zulko/moviepy#639]
When I test a video that is corrupted and should not work with the code below, the program stops running at `clip = video.to_ImageClip(t=timestamp)`, locking up a certain percentage of memory (the amount it was using before the code stopped running). There is no error thrown, no error caught - the code simply stops running and does not exit. If I send enough corrupted videos to be processed, as a worst case test scenario, my service fails due to a lack of available memory, since all previous corrupted videos that were sent, are still technically being processed.

The freeze seems to be coming from Clip.py, line 95, `get_frame()`: https://github.com/Zulko/moviepy/blob/master/moviepy/Clip.py#L95. I try stepping through the code, and this is where I get to.

Do you have suggestions on how I can get around this? I am using the following url to test: https://img.buzzfeed.com/video-api-stage/assets/2f2626a63c384f738a3e2b70c8fa4426/BFV8815_5JobsInDangerOfExtinction-FB_1080.mp4. You'll notice that this video stops running after minute 0:49 and should throw an error.

**Code:**

```python 
try:
    video = editor.VideoFileClip(file_url)
    image_timestamps = [int(video.duration * percentage / 100) for percentage in [10, 30, 50, 70, 90]]

    clips = []
    for timestamp in image_timestamps:
                clip = video.to_ImageClip(t=timestamp)
                duration_clip = clip.set_duration(0.9)
                clips.append(duration_clip)
except Exception as e:
    print e
```

**Comment by keikoro** [comment]
Closing this issue as it's rather old and it's unclear if this is still a problem today.

Feel free to reopen it following our issue template (which asks for info relevant for debugging) in case the problem persists with the latest recommended version of MoviePy.
