### ISSUE TITLE
How to change the duration dynamic

### ISSUE THREAD

**Issue by luckystar1992** [Zulko/moviepy#641]
I am using the moviepy to capture a gif for Machine Learning Training Process. Each time, I can not determine the duration in advance, if there is any function or tools that can add frames or VideoClip dynamic.

**Comment by tburrows13** [comment]
`clip = clip.set_duration(your_duration)`

**Comment by tburrows13** [comment]
Sorry, you've not given enough information for us to help. Feel free to reopen if you still need help.
