### ISSUE TITLE
Trying to use moviepy on lambda, but has problem with ffmpeg

### ISSUE THREAD

**Issue by TibbersDriveMustang** [Zulko/moviepy#642]
I am trying to run moviepy on lambda funciton, since lambda has different infrustructure, there are tons of .so dependencies problem, anybody has idea how to setup the environment correctly?

**Comment by TibbersDriveMustang** [comment]
Here are the errors I got:


File "videoRenderController.py", line 386, in start
music = (AudioFileClip(self.downloadPath + musicFile['s3Path'][6:]).
File "/var/task/moviepy/audio/io/AudioFileClip.py", line 63, in __init__
buffersize=buffersize)
File "/var/task/moviepy/audio/io/readers.py", line 56, in __init__
infos = ffmpeg_parse_infos(filename)
File "/var/task/moviepy/video/io/ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
filename, infos))
IOError: MoviePy error: failed to read the duration of file /tmp/dbbd8ec6-e1cd-45fd-8c50-d3a548e225bb/901172e2-49b8-4d53-bc96-8fbd12c944ab.mp3.
Here are the file infos returned by ffmpeg:

/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libjack.so.0)
/var/task/ffmpeg: /lib64/libdbus-1.so.3: no version information available (required by /var/task/lib/libpulse.so.0)
/var/task/ffmpeg: /lib64/libncursesw.so.5: no version information available (required by /var/task/lib/libcaca.so.0)
/var/task/ffmpeg: /lib64/libncursesw.so.5: no version information available (required by /var/task/lib/libcaca.so.0)
/var/task/ffmpeg: /lib64/libtinfo.so.5: no version information available (required by /var/task/lib/libcaca.so.0)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/task/lib/libzmq.so.5)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libzmq.so.5)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/task/lib/libopencv_core.so.2.4)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libopencv_core.so.2.4)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libopencv_imgproc.so.2.4)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libsnappy.so.1)
/var/task/ffmpeg: /lib64/libdbus-1.so.3: no version information available (required by /var/task/lib/libpulsecommon-8.0.so)
/var/task/ffmpeg: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libtbb.so.2)
/var/task/ffmpeg: /lib64/libgpg-error.so.0: no version information available (required by /var/task/lib/libgcrypt.so.20)

**Comment by sirgogo** [comment]
Any luck here? I am getting a similar issue (not doing the same task), and am tracking it back to libzmq and GLIBCXX_3.4.20.

**Comment by TibbersDriveMustang** [comment]
Use a static build FFmpeg will solve this dependency issue
