### ISSUE TITLE
moviepy runs from python interpreter but not from Idle_script run - Windows 7

### ISSUE THREAD

**Issue by gpnaveen** [Zulko/moviepy#643]
i have this issue : I am trying to run sample code given as examples.

**The code works fine if i run it from python interpreter** - that is typing python and copy pasting code.
Video is created automatically with text ('cool effect'example)

**The same code does not work with IDLE**, with code saved as .py script.
i am getting below error : 
 _from moviepy.editor import *
ModuleNotFoundError: No module named 'moviepy.editor'; 'moviepy' is not a package_

Both the methods use the same interpreter (ENV path also pointing to same interpreter) still facing the issue.

**Comment by Zulko** [comment]
This sometimes happens if you have a folder called moviepy in your current directory. Is that the case ?

**Comment by xaisng** [comment]
My Interpreter path : 
>>> print(sys.executable)
C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\python.exe
>>> import moviepy
>>> print(moviepy)
<module 'moviepy' from 'C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python36-32\\moviepy-master\\moviepy\\__init__.py'>


Contents of folder : 
 Directory of C:\Users\xxx\AppData\Local\Programs\Python\Python36-32
09/11/2017  09:55 PM    <DIR>          .
09/11/2017  09:55 PM    <DIR>          ..
09/11/2017  06:24 PM    <DIR>          DLLs
09/11/2017  06:24 PM    <DIR>          Doc
09/11/2017  06:23 PM    <DIR>          include
09/11/2017  06:24 PM    <DIR>          Lib
09/11/2017  06:24 PM    <DIR>          libs
07/08/2017  04:20 AM            30,351 LICENSE.txt
09/11/2017  07:18 PM    <DIR>          moviepy-master
07/08/2017  03:58 AM           349,530 NEWS.txt
07/08/2017  04:17 AM            97,944 python.exe
07/08/2017  04:15 AM            58,008 python3.dll
07/08/2017  04:15 AM         3,267,224 python36.dll
07/08/2017  04:17 AM            96,408 pythonw.exe
09/11/2017  09:06 PM    <DIR>          Scripts
09/11/2017  06:24 PM    <DIR>          tcl
09/11/2017  06:24 PM    <DIR>          Tools

moviepy-master folder does have moviepy folder
