### ISSUE TITLE
'missing handle' error

### ISSUE THREAD

**Issue by YitzhakSp** [Zulko/moviepy#644]
Hi, I get the 'missing handle' error in the following scenario. 
When I open a video with VideoFileClip() inside a myfunc and then open it once again after the function was executed

```
some code 
myfunc(video_path) 
myclip=VideoFileClip(video_path)
```
I already tried to apply 
```subproccess._cleanup()```
and
 ```del myclip ```
inside  myfunc, but it didn't work

**Comment by tburrows13** [comment]
Can you post both the exact error message, and a short succinct piece of code that demonstrates the point please?

**Comment by YitzhakSp** [comment]
actually I ran it on win 10 (previously win 7) and now its working well. Maybe the reason is different: another python version (3.6, previously 3.5). I am not sure.

**Comment by tburrows13** [comment]
Ok, great! For any future readers, we currently have an issue with `del myclip` not really doing what it should. Use `myclip.__del__` instead.
