### ISSUE TITLE
Output video is garbled, single frames output are fine

### ISSUE THREAD

**Issue by hexagonist** [Zulko/moviepy#651]
I'm having issues when exporting the video. It does render but it does not render correctly. 
I'm trying to make a compilation of videos. The first video is always fine but the rest are all garbled.

OS : OS X EL Capitan v.10.11.6

This is how I concatenate all the clips and add the audio to it. 
I used the write_videofile parameters from issue #356 [(direct link to comment)](https://github.com/Zulko/moviepy/issues/356#issuecomment-321519848) but I'm still getting the issue...

    final_audio = mp.AudioFileClip(music_fp)

    # clip_list is a list of CompositeVideoClip
    final_clip = mp.concatenate_videoclips(clip_list).fadein(2).fadeout(2)

    final_clip = final_clip.set_audio(final_audio.set_duration(int(final_clip.duration)))

    final_clip.write_videofile(
            output_fp,
            verbose=True,
            codec="libx264",
            audio_codec='aac',
            temp_audiofile='temp-audio.m4a',
            remove_temp=True,
            preset="medium",
            ffmpeg_params=["-profile:v","baseline", "-level","3.0","-pix_fmt", "yuv420p"])

### Garbled output example
![screen shot 2017-10-05 at 11 18 10 am](https://user-images.githubusercontent.com/7473283/31205783-50c1d322-a9bf-11e7-8d55-eeb3d1aa4a4f.png)

*I know this shouldn't be posted here but more on Stackoverflow or the moviepy subreddit but it seems to take forever to get even a single response on either of those. Thanks in advance for your help*

**Comment by hexagonist** [comment]
I managed to fix this, I needed to add a `method="compose"` parameter to `concatenate_videoclips()` most likely because my clips might have been of different sizes.

**Comment by kerstin** [comment]
Hi @hexagonist, will close this issue as you managed to resolve your problem.
