### ISSUE TITLE
How do I close a VideoFileClip

### ISSUE THREAD

**Issue by Droppers** [Zulko/moviepy#653]
I am really lost on this one. I am trying to close a VideoFileClip, but it does not kill the ffmpeg.exe process.

```
import os
from moviepy.editor import *

path = 'video.webm'

clip = VideoFileClip(path)

clip.reader.close()
del clip.reader
del clip

os.rename(path, path)
```

This does not seem to work, is there a way to do this? As far as I can see there is no built-in way to do this.

moviepy version: `0.2.3.2`

**Comment by tburrows13** [comment]
Hmmm, I do seem to remember us having an issue with properly deleting clips... does calling `clip.__del__()` do anything?

**Comment by kerstin** [comment]
Is this related to #596?

**Comment by tburrows13** [comment]
`clip.close()` should now work.
