### ISSUE TITLE
Time returned from clip.iter_frames does not exactly correspond to original time frame.

### ISSUE THREAD

**Issue by vignesh1905** [Zulko/moviepy#654]
Hi, I am trying to use moviepy to get frames as well as the frame time from a video file. My code is as follows. My video fps is 29.97 as given by the info. The duration of my video is 60.93 seconds. 

```
import moviepy.video.io.ffmpeg_reader as reader
import moviepy.editor as mpy
import numpy as np
import matplotlib.pyplot as plt

#Getting info about the video file
infos = reader.ffmpeg_parse_infos('one_minute.mp4')

#Reading the video and getting the frames and time pointer
clip = mpy.VideoFileClip('one_minute.mp4')

frame_list_moviepy = []
time_list = []
for t,frame in clip.iter_frames(with_times= True):
     frame_list_moviepy.append(frame)
     time_list.append(t)
         
#Getting a single frame at a specified time     
frame_at_time = mpy.VideoFileClip('one_minute.mp4').get_frame(60.927533333333336)
```

The problem I am facing here is get_frame here does not give me the frame at this specified time, which is the time which iter_frames gives me as the time of the last frame, instead it gives me the first frame of the video. 

I also used pure ffmpeg with python subprocess to compare the frames, the frames seems to match but the time seems to be inaccurate. In fact pure ffmpeg decodes frames only upto 60.86s whereas the time given here is greater than that.  Anything wrong with the way I am getting the time pointer for the frames ? Is there a better way to get the time for each video frame so that I can again go back to the eact frame ?

**Comment by amraneabdeslam** [comment]
I have the same problem

**Comment by Boliang-Lu** [comment]
I also have this problem

**Comment by keikoro** [comment]
Hi, seeing as this is a rather old issue, does this problem persist with the latest recommended version of MoviePy?

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.
