### ISSUE TITLE
.png images display static instead

### ISSUE THREAD

**Issue by bahasa1** [Zulko/moviepy#658]
the following code works with jpegs, but not with pngs

```
from moviepy.editor import *

video3 = VideoFileClip("mymovie5.mp4").subclip(4,10)
clipta = ImageClip("oranger.png")
taresult = concatenate_videoclips([video3, clipta.set_duration(3)]) 
taresult.write_videofile("test17.mp4")
```

**Comment by keikoro** [comment]
It's unclear what the expected result was.
Closing this since it's a very old issue, feel free to reopen using the issue template if the problem persists.
