### ISSUE TITLE
how to load GIF with its transparency

### ISSUE THREAD

**Issue by mkandulavm** [Zulko/moviepy#661]
Hi

I am loading a gif and compositing into a final video. However the gif transparency is not showing up in the final video. How to do this ?

Here is sample code

vidArr = [somevideo]
clickVid = VideoFileClip("click.gif")
vidArr.extend( [clickVid.set_pos("center") ] )
outvideo2 = CompositeVideoClip(vidArr)

**Comment by rakshitajain5** [comment]
I am facing the same issue. Can someone help?

**Comment by keikoro** [comment]
Closing this issue as it's old and missing information we request when creating new issues (like specs).

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
