### ISSUE TITLE
Issue combining videos

### ISSUE THREAD

**Issue by imcquerrey** [Zulko/moviepy#663]
Im using moviepy to combine videos I downloaded from Instagram using this line of code:
final_clip = concatenate_videoclips(clips, method='compose')
It works but some of the original clips that are fullscreen are now cropped and centered but the ones that are portrait size are fine. How can I make moveiepy not resize any clips and play them together?

**Comment by alexzach** [comment]
The `compose` method takes the first clip's size as the right one and crops / adds black edge to to other resolutions.
You should first resize all the clips to one resolution if you want the to fill the frame.

**Comment by skinnyp3t3** [comment]
When I was making the program and was looking for ways to compile the clips
the only reasonable way on python was to use moviepy. Moviepy does what you
said below and I have tried different things like putting the biggest clip
first or messing with the black bars but the best I could get moviepy to do
is change the color of the black bars. If you do decide to investigate this
more please let me know if you are able to fix it.

**Comment by alexzach** [comment]
Only resizing will solve your problem:
```
for i, clip in enumerate(clips):
  if clip.w != some_clip.w:
    clips[i] = clip.resize(width=some_clip.w)
```

**Comment by keikoro** [comment]
@skinnyp3t3 Did you manage to solve your problem with @alexzach's help? Can we close this issue?
