### ISSUE TITLE
audio in mp4 dont changes

### ISSUE THREAD

**Issue by Dnomin** [Zulko/moviepy#672]
```
import imageio
imageio.plugins.ffmpeg.download()

from moviepy.editor import *

audio = AudioFileClip("IBScene1.mp3").subclip(0,41)
video = VideoFileClip("321.mp4")
```

[from here](https://zulko.github.io/moviepy/getting_started/audioclips.html)

in video nothing changes, 0 errors.

**Comment by tburrows13** [comment]
What are you expecting to happen?  You are creating an audio clip, and a separate video clip, then doing nothing with them.
You can use `video = video.set_audio(audio)` to add the audio you have to the video.
Then use `write_videofile` to save it to a .mp4 file.
