### ISSUE TITLE
How can I pass a binaray file in 'VideofileClip'  function?

### ISSUE THREAD

**Issue by rickyfunfun** [Zulko/moviepy#673]
I have two url for Audio.
And then, I want user 'CompositeAudioClip' function between them.
How can I do?

ps.In my case, I cannot save them to disk. Only in memery.

**Comment by keikoro** [comment]
@rickyfunfun I saw you never received an answer to your question (Stackoverflow is the better place to ask in general) – did you manage to solve your problem, is this issue still relevant?
