### ISSUE TITLE
TextClip color displays differently from CompositeVideoClip bg_color

### ISSUE THREAD

**Issue by pkarp0** [Zulko/moviepy#680]
```
from moviepy.editor import *
clip = TextClip("WHEN YOUR TEXT\nIS COLORFUL", font='Proxima-Nova-Bold', color='#68AF14', fontsize=78).set_duration(5)
out = CompositeVideoClip([clip], size=[700, 200], bg_color=[0x68, 0xAF, 0x14])
out.write_videofile('output.mp4',  fps=24)
```
Sample code shows a TextClip with hex color #68AF14 and a bg_color in the CompositeVideoClip using the int array [0x68, 0xAF, 0x14]

This should have resulted in painting text the same as the background. Instead the color the text is different than the background as seen in the attached screenshot from quicktime. 

I believe this is related to gamma correction in imageio handling of PNG files.

![screen shot 2017-11-30 at 4 06 33 pm](https://user-images.githubusercontent.com/3496475/33455073-f2092d84-d5e8-11e7-84bc-307c385e0b8d.png)

**Comment by pkarp0** [comment]
This is the intermediate PNG created by IM for the TextClip. Using a color eyedropper shows the text color rendered correctly as input: [0x68, 0xAF, 0x14]. 
![img](https://user-images.githubusercontent.com/3496475/33466347-49f014ea-d61b-11e7-9282-a489119dfca3.png)

**Comment by pkarp0** [comment]
I tracked the problem to imageio.imread in the ImageClip constructor and replaced it with the PIL Image.open command. I don't know what imageio is doing with color in this situation.

```
class ImageClip(VideoClip):
    def __init__(self, img, ismask=False, transparent=True, fromalpha=False, duration=None):

        VideoClip.__init__(self, ismask=ismask, duration=duration)

        if PY3:
            if isinstance(img, str):
                img = Image.open(img)
                img = np.array(img)
        else:
            if isinstance(img, (str, unicode)):
                img = imread(img)

        if len(img.shape) == 3:  # img is (now) a RGB(a) numpy array

            if img.shape[2] == 4:
                if fromalpha:
                    img = 1.0 * img[:, :, 3] / 255
                elif ismask:
                    img = 1.0 * img[:, :, 0] / 255
                elif transparent:
                    self.mask = ImageClip(
                        1.0 * img[:, :, 3] / 255, ismask=True)
                    img = img[:, :, :3]
            elif ismask:
                img = 1.0 * img[:, :, 0] / 255

        # if the image was just a 2D mask, it should arrive here
        # unchanged
        self.make_frame = lambda t: img
        self.size = img.shape[:2][::-1]
        self.img = img
```

**Comment by pkarp0** [comment]
I found a fix that continues to use `imread` and sets the arg `ignoregamma=True` 

```
    def __init__(self, img, ismask=False, transparent=True,
                 fromalpha=False, duration=None):

        VideoClip.__init__(self, ismask=ismask, duration=duration)

        if PY3:
           if isinstance(img, str):
              img = imread(img, ignoregamma=True)
        else:
           if isinstance(img, (str, unicode)):
              img = imread(img, ignoregamma=True)

        if len(img.shape) == 3:  # img is (now) a RGB(a) numpy array

            if img.shape[2] == 4:
                if fromalpha:
                    img = 1.0 * img[:, :, 3] / 255
                elif ismask:
                    img = 1.0 * img[:, :, 0] / 255
                elif transparent:
                    self.mask = ImageClip(
                        1.0 * img[:, :, 3] / 255, ismask=True)
                    img = img[:, :, :3]
            elif ismask:
                img = 1.0 * img[:, :, 0] / 255

        # if the image was just a 2D mask, it should arrive here
        # unchanged
        self.make_frame = lambda t: img
        self.size = img.shape[:2][::-1]
        self.img = img
```

**Comment by cvn** [comment]
Hey @pkarp0 ,

Your code above applies ignoregamma to all instances of ImageClip. Is this intentional, or just for the sake of demonstration?

If it would be better to apply the fix only to TextClips, PR #683 would help. If merged, I believe you'd be able to fix this issue with a one line change to the TextClip class in [VideoClip.py](https://github.com/Zulko/moviepy/blob/v0.2.3.2/moviepy/video/VideoClip.py#L1231):
```diff
- ImageClip.__init__(self, tempfilename, transparent=transparent)
+ ImageClip.__init__(self, tempfilename, transparent=transparent, imageio_params={'ignoregamma': True})
```

**Comment by pkarp0** [comment]
Hi @cvn,
The code was just for demonstration to correct the TextClip without including additional code from TextClip. I was excited to see the addition of imageio_params in PR #683. As your example above shows it allows an easy fix to this text color issue.

**Comment by keikoro** [comment]
If I'm reading the above messages correctly, it sounds like solutions to this problem were found long ago. -> Closing.
