### ISSUE TITLE
ffmpeg leftover processes

### ISSUE THREAD

**Issue by mmuric** [Zulko/moviepy#681]
Hello, I've started using moviepy to generate some simple videos. My code is running inside supervisord process. Everything runs smoothly, and I'm very satisfied with moviepy, so thanks for the package :)

Recently I've started noticing leftovers of processes like this:

```
# ps aux | grep ffmpeg | grep -v grep

prod      3334  0.0  0.0      0     0 ?        Z    11:52   0:00 [ffmpeg] <defunct>
prod      3361  0.0  0.0 275724  1600 ?        Sl   11:52   0:00 /usr/bin/ffmpeg -i /path_to_file/00006.mp4 -vn -loglevel error -f s16le -acodec pcm_s16le -ar 44100 -ac 2 -
prod      3384  0.1  0.2 666408  9056 ?        Sl   11:52   0:05 /usr/bin/ffmpeg -i /path_to_file/00007.mp4 -loglevel error -f image2pipe -vf scale=1920:1080 -sws_flags bicubic -pix_fmt rgb24 -vcodec rawvideo -
prod      3396  0.0  0.0 275760   900 ?        Sl   11:52   0:00 /usr/bin/ffmpeg -i /path_to_file/00007.mp4 -vn -loglevel error -f s16le -acodec pcm_s16le -ar 44100 -ac 2 -
prod      5618  0.0  0.1 666824  4176 ?        Sl   11:57   0:01 /usr/bin/ffmpeg -ss 3.000000 -i /path_to_file/00006.mp4 -ss 1.000000 -loglevel error -f image2pipe -vf scale=1920:1080 -sws_flags bicubic -pix_fmt rgb24 -vcodec rawvideo -
```

where 00006.mp4 and 00007.mp4 are files used for background videos. In code this videos is used like this:

```
background_clip = VideoFileClip("/path_to_file/00007.mp4")
cc = CompositeVideoClip([background_clip, text_clip, logo, etc.])
cc.crop(x_center=960 , y_center=540, width=1080, height=1080).\
                    set_audio(audio).\
                    write_videofile(resfile, fps=25, codec="libx264", audio_codec="libmp3lame")

```
This is just a snippet, sorry if I misspelled something.

My problem here is that this process are hanging forever, which flood my RAM eventually. Is there a way to prevent this, or to tell process to ignore, kill or whatever this error ffmpeg processes?

Thanks in advance.

**Comment by mgaitan** [comment]
Related to #596

**Comment by m-decoster** [comment]
I have a similar issue when processing many video files in a loop, like so:

```
for begin, end, path in entries:
    clip = VideoFileClip(path)
    relevant_portion = clip.subclip(begin, end)
    out_filename = path + '_short.mp4'
    relevant_portion.write_videofile(out_filename, codec='libx264', audio=False, verbose=False, progress_bar=False)
    clip.reader.close()
    del clip.reader
    del clip
```

Eventually I run out of memory.

This still happens in the latest release (0.2.3.5).

**Comment by tburrows13** [comment]
There's been a lot of improvements on process exiting since this issue. Make sure to call `clip.close()` when you are done with a clip (and any clip derived from it) and you should be fine.
