### ISSUE TITLE
Remove Python 3.3 testing ?

### ISSUE THREAD

**Issue by Zulko** [Zulko/moviepy#688]
Hi all,

It appears that the Python3.3 tests always fail for some reason, even when tests for all other python versions succeed. This makes PR harder to evaluate as Travis always chimes in to say the tests didnt go through. What about we remove python 3.3 testing ?

**Comment by kerstin** [comment]
Imo it's ok to officially drop support for a Python version that is not the one EVERYONE uses (should such a version exist) if it continually causes problems.

**Comment by earney** [comment]
it seems to be a problem with pytest, which doesn't seem to support python 3.3    I am fine with removing the tests for python 3.3
