### ISSUE TITLE
Refer to magick on https://zulko.github.io/moviepy/install.html

### ISSUE THREAD

**Issue by mgrazebrook** [Zulko/moviepy#689]
A cousin of #378 

This documentation is out of date and should refer to magick not convert:

https://zulko.github.io/moviepy/install.html

The current text
> Once you have installed it, ImageMagick will be automatically detected by MoviePy, except on Windows !. Windows user, before installing MoviePy by hand, go into the moviepy/config_defaults.py file and provide the path to the ImageMagick binary called convert. It should look like this
> 
> IMAGEMAGICK_BINARY = "C:\\Program Files\\ImageMagick_VERSION\\convert.exe"
> 

The github version of the docs has the same bug:

> Windows users, before installing MoviePy by hand, need to edit moviepy/config_defaults.py to provide the path to the ImageMagick binary, which is called convert. It should look like this

**Comment by tburrows13** [comment]
Fixed in #980.
