### ISSUE TITLE
Several examples refer to non-existent files

### ISSUE THREAD

**Issue by keithstellyes** [Zulko/moviepy#690]
Many of the examples in `examples/` refer to video and image files (for example `examples/starworms.py` refers to `../../videos/stars.jpg`) that don't seem to have ever existed in 4 years in this repo.

Where are these files?

**Comment by keithstellyes** [comment]
Does nobody know?

**Comment by Zulko** [comment]
The examples are seriously outdated indeed. They are from very early versions of Moviepy. At the time I was afraid of copyright claims repo size so I did not include media files. Not sure about all examples, but I am not 100% sure but I assume that replacing the image with most other space images would work.

**Comment by MythicManiac** [comment]
How about using tests as examples? Or at least make the test runner run the examples in a similar way as tests?

This way the examples would never end up in an unusable state, and you'd get additional code coverage as a side benefit

**Comment by tburrows13** [comment]
Linking #807

**Comment by mondeja** [comment]
Closing as duplicate of #338.
