### ISSUE TITLE
Typo in variable name in transitions.py(t_s instead of ts)

### ISSUE THREAD

**Issue by ankita-2798** [Zulko/moviepy#692]
While using transitions, I got an error in /moviepy/video/compositing/transitions.py - 

**NameError : global name  'ts' is not defined in line 110**

Traversing to the file, I realised that it had a typo during the declaration of variable name 'ts'. It was defined as 't_s' instead of 'ts' and so the error. On correcting it, the code worked perfectly fine.

Don't know if anybody else has faced the same issue during recent installs, I thought it's worth looking into :)

Thanks!

**Comment by keikoro** [comment]
Does this still need fixing?

**Comment by tburrows13** [comment]
Fixed in #612
