### ISSUE TITLE
write_videofile can erroneously confirm that a file has been made

### ISSUE THREAD

**Issue by chelsell** [Zulko/moviepy#699]
So this was a user error where I was unwittingly cropping a video down to zero pixels. Attempting to write this video did not trigger any error message. What happens is that moviepy confirms that the file was created and prints the path, but the file simply isn't there. I infer that ffmpeg's behavior is to silently refuse to write a zero-pixel video (which is a bad behavior in my opinion, but no fault of yours).

I'd suggest that moviepy actually check for the existence of the video file itself, it looks to me that it only checks that the log exists.

**Comment by keikoro** [comment]
It's not clear at all what you are referring here. Seeing as this is also a rather old issue, I'm closing this. Feel free to reopen using the issue template we use for new issues.
