### ISSUE TITLE
How to install MoviePy on OS High Sierra

### ISSUE THREAD

**Issue by EaGlFr** [Zulko/moviepy#706]
Hi, 
I need to install MoviePy for my studies, and i run python with Pyzo on a Macbook. But actually i didn't succeed in installing it, some help would be really welcome !
Thanks !

**Comment by kerstin** [comment]
Hi @EaGlFr, please let us know what you tried (the exact steps of your installation procedure) so we can more easily try to pinpoint what the problem could be.

**Comment by EaGlFr** [comment]
I went on GyThub, clicked on 'clone or download', opened 'setup.py' and 'ez-setup.py' with Pyzo, but the shell returned 'something went wrong during the installation'

**Comment by notedit** [comment]
pip install  moviepy

**Comment by EaGlFr** [comment]
It answers 'invalid syntax', and shows install with an arrow...

**Comment by albertogaona** [comment]
sudo pip install moviepy

**Comment by Zulko** [comment]
@EaGlFr It seems that you are trying to install the library from inside python, while you should install it from the terminal. I will close this issue as it is not related to MoviePy directly, but you can ask for support on many other forums. You should look around for tutorials on installing new modules, it will be very useful in your Python journey.

https://stackoverflow.com/questions/17271319/how-do-i-install-pip-on-macos-or-os-x

**Comment by EaGlFr** [comment]
Indeed, as you may have seen, my computer knowledges are quite...well i don't have some !
Thanks a lot for your help !

**Comment by hkgrild** [comment]
sudo pip install moviepy failed for me on macos Sierra 10.12.6

`:> sudo pip install moviepy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: The directory '/Users/groot/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/groot/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting moviepy
  Downloading https://files.pythonhosted.org/packages/fb/32/a93f4af8b88985304a748ca0a66a64eb9fac53d0a9355ec33e713c4a3bf5/moviepy-1.0.0.tar.gz (398kB)
     |████████████████████████████████| 399kB 1.3MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: error in moviepy setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in imageio>=2.5,<3.0; python_version>='3.4' at ; python_version>='3.4'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-1JyrfN/moviepy/

`

**Comment by keikoro** [comment]
@hkgrild Please open a new issue and don't reply to closed & resolved issues when reporting problems. Also, to make reading error messages easier, please format them as a block of code instead of one long line (use 3 backticks instead of 1 at the beginning and end of the block).
