### ISSUE TITLE
Did CompositeVideoClip support composited clips?

### ISSUE THREAD

**Issue by jamesneo3000** [Zulko/moviepy#720]
When I use CompositeVideoClip to compose several composed clips, the result did not work as expected.

I wrote a simple demo to show my issue. There are two methods to compose clips.

Method 1 compose [imgclip, sub_img_clip_1, sub_img_clip_2], and the result looks good.

Method2 compose sub_img_clip_1 and sub_img_clip_2 first into animation_clips, and then compose imgclip and animation_clips together as the final clips. The result video shows a still image without any animation.

```
# -*- coding: utf-8 -*-
import numpy as np
from PIL import Image
from moviepy.editor import *


def narrow(clip, duration, left, top, ratio):
    return clip.set_duration(duration).resize(lambda t : 1 - ratio*t/duration).set_pos((left, top))

def enlarge(clip, duration, left, top, ratio):  
    return clip.set_duration(duration).resize(lambda t : 1 + ratio*t/duration).set_pos((left, top))

img = Image.open('./1.jpg')
imgclip = ImageClip(data).resize(height=720).set_pos('center').set_start(0)

sub_img_clip_1 = imgclip.set_duration(0.3)\
                                         .resize(height=720)\
                                         .set_pos('center')\
                                         .set_start(1.0)
            
sub_img_clip_2 = imgclip.set_duration(0.3)\
                                          .resize(height=864)\
                                          .set_pos('center')\
                                          .set_start(1.3)
            
sub_img_clip_1 = enlarge(sub_img_clip_1, 0.3, 'center', 'center', 0.2)
sub_img_clip_2 = narrow(sub_img_clip_2, 0.3, 'center', 'center', 0.2)
         
#method 1, work out fine
final_clips = CompositeVideoClip([imgclip, sub_img_clip_1, sub_img_clip_2], size=((1280,720)))
final_clips.set_duration(2.5).write_videofile('./temp1.mp4',fps=24)

#method 2, didn't enlarge nor narrow the image clip
animation_clips = CompositeVideoClip([sub_img_clip_1, sub_img_clip_2], size=((1280,720))) 
final_clips = CompositeVideoClip([imgclip, animation_clips], size=((1280,720)))
final_clips.set_duration(2.5).write_videofile('./temp2.mp4',fps=24)
```

**Comment by anandkpandey1** [comment]
I have a similar requirement to compose two different CompositeVideoClips, and it is not working.
It would be great to get if we can have this implemented, since it would help us to make more complex videos with ease

**Comment by liudaozhenjun** [comment]
I also want to know

**Comment by jayn1985** [comment]
who solved this issue? i met this also in recent project...

**Comment by keikoro** [comment]
Closing this issue as it's old and did not include any specs, so it's unclear if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
