### ISSUE TITLE
Storing Processed Video clip takes a long time

### ISSUE THREAD

**Issue by waterruns** [Zulko/moviepy#726]
I have used moviepy to load and process a video. during processing the fps and total number of frames dont change, but each frame is rotated with 10 degrees, the outer area of frame are set as black.
when I want to store the videos, it takes a very long time (4 times the video time) using the the following command,
clip.write_videofile(outpath, fps=clip.fps, codec = 'mpeg4', audio=True, threads=8)

**Comment by tburrows13** [comment]
How long is the video? What is the difference in writing times between before you’ve edited it, and after?

Also, you shouldn’t need to pass `fps=clip.fps` into `write_videofile()`.

**Comment by waterruns** [comment]
the video is 30 seconds with 900 frames, it takes almost 1.5 minutes to write, before processing it takes around 40 seconds to write

**Comment by Zulko** [comment]
What is the image resolution ? For HD video, rotating 1 frame can take some time, so if you have 30 frames per second it will be slow. What do you use to rotate the video ? Maybe there exist faster options.

**Comment by waterruns** [comment]
the whole processing is done separately, and takes 3 seconds per video, the above numbers are for just saving the result of the video with or without rotation process (3 seconds)

**Comment by Zulko** [comment]
Can you paste the exact code you are using ?

**Comment by waterruns** [comment]
```
totaltime=time.time()
clip, ID = video_capture_api(dirpath)
```
```
fps  = clip.fps

t = time.time()
clip_realiz = generate_realization(clip.copy(), varins=(somearguments))
print('Realiz Gen Time: {}'.format(time.time() - t)); # this one takes 3 seconds
t = time.time();     
outpath = output_dir + '/' + ID + '_' + str(n_real) + '.mp4'      
clip_realiz.write_videofile(outpath, codec = 'mpeg4', audio=True, threads=100) 
print('Storage Time: {}'.format(time.time() - t));
print('Total Time: {}'.format(time.time()-totaltime)) # this one is about 2 minutes

```

```
def generate_realization(video, varins):
    video = video.fl_image(lambda frame: frame_manipulate(frame, varins),apply_to='mask')
return video
```

**Comment by waterruns** [comment]
if I save clip.write_video , it is super fast, but clip_realiz.write_video is slow

**Comment by tburrows13** [comment]
I think the results you are getting are pretty typical.  I may be wrong, but I don’t think moviepy does much processing in your `generate_realization` line.  It ‘saves’ it all until you actually write it to a file, hence why it takes so much longer.

**Comment by Zulko** [comment]
It's clearer now, and I think your problem is wrong assumptions on what is going on in the script. When you apply ``generate_realization``, it does NOT process all the frames of your clip, only the first frame (hence the 3 seconds that you observe). The other frames of your clip are only processed, one by one, when you call ``write_video_file``.

**Comment by waterruns** [comment]
oh, i see, thank you for that, 
is there a way to make sure the processing is done inside generate_realization ? 
also is an in herit function inside moviepy for shifting and rotating frames?

**Comment by tburrows13** [comment]
Not sure about your first question, but you should be able to use `clip = clip.rotate(10)`.

**Comment by waterruns** [comment]
is there a way to replace all the frames inside a clip with a numpy array? 
I can make my processing really fast on the whole numpy array of frames, if the replacement can be done, it will be helpful.

**Comment by Zulko** [comment]
I am closing this thread as it is not a moviepy bug/feature request anymore.

To answer your first question, yes you could with [the unfortunately undocumented ImagesSequenceClip](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ImageSequenceClip.py)

But beware that all these numpy arrays in memory are going to take a lot of RAM !

Another option is to convert your clip to a sequence of images on your disk using "clip.write_images_sequence", then load these images using ImageSequenceClip (which in this case will only load the images as they are needed).

**Comment by waterruns** [comment]
Thank you for the replies and solution provided. I really appreciate you guys efforts in building such a nice package.
