### ISSUE TITLE
Tracking progress on the front end in a web application

### ISSUE THREAD

**Issue by JMIdeaMaker** [Zulko/moviepy#736]
I'm making a web application that uses moviepy functions but am only able to track progress at a basic level (video uploading, video processes happening, etc, not percentages). How might I be able to track progress information to give to the client?

**Comment by keikoro** [comment]
@JMIdeaMaker I'm closing this issue since there hasn't been any new activity on it since 2018.

Feel free to reopen it with info on what you found in the MoviePy docs or code comments that points in the direction of what you're looking for.
