### ISSUE TITLE
MemoryError when generating clip from numerous images with sound

### ISSUE THREAD

**Issue by flothesof** [Zulko/moviepy#74]
I'm trying to build a video from a sequence of images with audio.

What I want to do is:
- generate images and write them to disk
- generate sounds that go with the images and write them to disk
- do a loop over my 120 items and build a CompositeVideoClip for each item that I store in a list
- assemble the composite video clips at the end with concatenate to write the movie to disk

When I loop over 10 items, it works fine. When I loop over the 120 items, it stops at number 106 with a memory error. Indeed, checking for the memory footprint yields the following:
![memory_error](https://cloud.githubusercontent.com/assets/2360669/4457308/32efbcb2-4895-11e4-94c1-e8901292d446.PNG)

Could you please explain what I'm doing wrong?
The code can be found [here](http://nbviewer.ipython.org/github/flothesof/TheRingtoneVariations/blob/master/make_yt_video.ipynb).
In case you want to try it out, just clone [this repository](https://github.com/flothesof/TheRingtoneVariations) and follow instructions found in the readme file.

**Comment by kerstin** [comment]
@flothesof, I'll interpret your last comment as a description of a possible bug/unexpected behaviour, or something that could be improved.

**Comment by mattvenn** [comment]
@zulko wrote "Here you have 120 frames of size 480_800_3,"
but this is only 1.1Mb. So with 120 videos should be about 130Mb. But his process is using 1.7Gb (if I read the windows thing correctly).

I'm having a similar issue. Trying to take a bunch of mostly stills, with a couple of videos and concatenate them into a longer file. After 10 files memory usage is 3GB and the process is killed.

**Comment by rakshitajain5** [comment]
Hi, I am getting a similar error. Did anyone get a solution?

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any updates from OP in years, so it's impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
