### ISSUE TITLE
Progress bar newline error in Jupyter

### ISSUE THREAD

**Issue by jarmitage** [Zulko/moviepy#740]
## Problem
1. Progress bar works fine initially:
<img width="717" alt="2018-03-13 at 13 45 12" src="https://user-images.githubusercontent.com/2885827/37345455-e7c19280-26c4-11e8-8459-4f52468126e1.png">
2. Stop the process (using toolbar) and get a huge KeyboardInterrupt dump:
<img width="741" alt="2018-03-13 at 13 45 21" src="https://user-images.githubusercontent.com/2885827/37345461-ee0d9238-26c4-11e8-8a5c-c558f67fceda.png">
3. Run again and the progress bar prints to a new line:
<img width="767" alt="2018-03-13 at 13 45 43" src="https://user-images.githubusercontent.com/2885827/37345485-fdc4108a-26c4-11e8-99cf-ab944c252903.png">

## Code
```python
import moviepy.editor as mpy
import os

clip1 = mpy.VideoFileClip("a.mp4").subclip(10,15).set_pos((0,0)).set_start(0)
clip2 = mpy.VideoFileClip("a.mp4").subclip(20,25).set_pos((0,1080)).set_start(5)
clip3 = mpy.VideoFileClip("a.mp4").subclip(30,35).set_pos((0,2160)).set_start(10)

comp = mpy.CompositeVideoClip([clip1, clip2, clip3], size=(3000,3240))
```

## Versions
- Jupyter 4.4.0, Notebook 5.4.0, Lab 0.31.12 (same problem in Notebook as Lab)

## Comments
- Is this somehow related to this issue? https://github.com/jupyterlab/jupyterlab/issues/1104
- Perhaps with `tqdm`, this is needed `from tqdm import tqdm_notebook as tqdm`? ([stackoverflow](https://stackoverflow.com/questions/42212810/tqdm-in-jupyter-notebook))
- Perhaps this flag could be used with `clip.ipython_display`? https://github.com/Zulko/moviepy/issues/128

Thanks for any support in advance!

**Comment by jarmitage** [comment]
I was able to solve this problem by switching to `tqdm_notebook` at these locations:

https://github.com/Zulko/moviepy/blob/db9e5f8681e682d3f26cef6702153aabfa4e54c7/moviepy/Clip.py#L486

https://github.com/Zulko/moviepy/blob/cd80d62065039d301ac872d6afa6cf86444b926f/moviepy/audio/AudioClip.py#L83

**Comment by tburrows13** [comment]
@Zulko, no the commit I just pushed was to solve merging conflicts in #701 so that it could be used as a workaround before we implement a proper solution.  I still haven’t done anything with Proglog yet, but I think I will.

**Comment by keikoro** [comment]
Any progress on this? (Not sure how to tag this...)

**Comment by danmash** [comment]
https://github.com/Zulko/moviepy/issues/740#issuecomment-372687029
is there a way to do this with no modification of the source?

**Comment by tburrows13** [comment]
Proglog support has been added as of v1.0. See #1020.
