### ISSUE TITLE
VideoClip from bytes

### ISSUE THREAD

**Issue by GiovanniCardamone** [Zulko/moviepy#741]
Hi, i have a situation where i don't want to store a video on disk, a video is stored as bytes, and i have the format and the mime_type, how i can create `VideoClip` or `VideoFileClip` from those?

**Comment by mgaitan** [comment]
if you know how to read those "bytes" to return a numpy array per each frame, then you are done, passing that "frame factory" function as the argument. 

check this 
https://zulko.github.io/moviepy/getting_started/videoclips.html?highlight=make_frame#videoclip

**Comment by keikoro** [comment]
@GiovanniCardamone Did the above comment help you solve your problem, can we close this issue?

**Comment by AmitMY** [comment]
Not solved because it does not address audio.
I would like to be able to just open the MP4 file I have as a bytes array not only as file.

**Comment by praneethnooli** [comment]
Hi @GiovanniCardamone, May I know how did you solve the issue of creating VideoClip from bytes?

**Comment by WillLiGitHub** [comment]
did you sove the issue?

**Comment by WillLiGitHub** [comment]
did you solve the issue?

**Comment by tburrows13** [comment]
For both video and audio, create a function `make_frame` for each that returns the value at time `t`, as demonstrated: https://zulko.github.io/moviepy/getting_started/videoclips.html.

**Comment by sekpona1-crypto** [comment]
Hello, my problem is how can i convert moviepy output to Bytes IO using for example clip..iter_frames? Please healp me.

**Comment by david-macintosh-prospect** [comment]
Has this been resolved? I see @tburrows13 has closed but the solution given is rather convoluted, is there no way to change the byte stream that is being sent in from a file in storage to just simply accepting a byte stream? It would open a lot of doors for running video processing in parallel where you can't persist to memory.

**Comment by stevenQinwen** [comment]
use ffmpeg

**Comment by elrondfeng** [comment]
I am not clear how to code the make_frame function with the input byte stream, can anyone put some sample code here? thanks!

**Comment by yallavaibhav** [comment]
I am facing with the same issue, I have extracted video file which is in the form of bytes from S3 bucket. Now how should I use that file in VideoFileClip(). 

Should we convert the bytes in any format to run in the function??

**Comment by HenryXiaoYang** [comment]
I am still having trouble on this issue. Is there any code sample?
