### ISSUE TITLE
How to prepend hexadecimal data to a binary file?

### ISSUE THREAD

**Issue by Swiffers** [Zulko/moviepy#757]
hi,

I need to prepend some pre-defined hex datas: `\x00\x01\x00\x00\x65... `
At the begining of my video.mp4, I wonder how to do it using moviepy or pure python?

Thanks

**Comment by mgaitan** [comment]
Please, check this https://stackoverflow.com/a/16387689

btw, this os clearly a general python question. consider asking this kind of question at stackoverflow (or in a general python-related forum/list/chat).
