### ISSUE TITLE
install moviepy

### ISSUE THREAD

**Issue by Dominux** [Zulko/moviepy#758]
Hello! 
I want to install moviepy, but I have got that error.
Please, write me back, what I should do?
![image](https://user-images.githubusercontent.com/38255311/38565667-90702474-3cea-11e8-8a59-d9afe60e286b.png)

**Comment by Zulko** [comment]
This looks like an imageio utf-8 related error (possibly because you have russian characters in your system ?). Try posting the issue on the imageio project, maybe @almarklein ca help.

**Comment by almarklein** [comment]
Does pip work for installing other packages? I don't see imageio in the traceback (only pip itself).

**Comment by Zulko** [comment]
Indeed, sorry. I saw the error at imageio installation, but maybe it's just because imageio gets installed first. @Dominux, maybe investigate it as a pip error (and post the issue in the [pip project](https://github.com/pypa/pip))

**Comment by GadgetSteve** [comment]
Which version of pip are you using @Dominux? The latest is Version 10.0 (if you are using an earlier version use `python -mpip install --upgrade pip` to update.

**Comment by Dominux** [comment]
Thank u, good pybenders
After pip3 upgrade moviepy has been installed!

**Comment by tburrows13** [comment]
Great, thanks for getting back to us with your solution!
