### ISSUE TITLE
[BUG] VideoFileClip doesn't close file process properly (Ubuntu 14.04)

### ISSUE THREAD

**Issue by spohngellert-o** [Zulko/moviepy#759]
Trying to use `VideoFileClip` for many video files does not close the process properly. Code to reproduce the issue:

```
from moviepy.editor import VideoFileClip

for i in range(1000):
	print(i)
	video = VideoFileClip("YOUR_FILE").subclip(0,1)
```

I believe the issue is on the following line, but not sure how to prove this: https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L259

Instead of using `terminate` maybe `kill` should be used?

Thanks 😄

**Comment by spohngellert-o** [comment]
After doing some digging I have found a workable fix:

```
from moviepy.editor import VideoFileClip

for i in range(1000):
	print(i)
	video = VideoFileClip("FILE").subclip(0,1)
	video.reader.close()
	if video.audio and video.audio.reader:
		video.audio.reader.close_proc()
```
This was inspired by the following thread:

https://github.com/Zulko/moviepy/issues/164

I'll consider making a pull request for a general close method.

**Comment by tburrows13** [comment]
The ability to properly close clips has been discussed quite a bit: #596 for some more. It is on the todo list to sort out.

**Comment by spohngellert-o** [comment]
Yes for sure. Definitely would be good to have a general close function. It would also be awesome if it supports `with` syntax, i.e.:

```
with VideoFileClip("FILE") as clip:
    # do something
```
Thanks! I may try looking into this.

**Comment by spohngellert-o** [comment]
Hey, not sure if this is the right place to ask but I am trying to get development set up and am having some issues (Windows 10). If you could point me in the right direction for where to get help @tburrows13 that would be awesome. 😄

**Comment by tburrows13** [comment]
You can post issues here, or on the Gitter chat room: https://gitter.im/movie-py/Lobby
Feel free to privately message me on Gitter instead if you’d like.

**Comment by keikoro** [comment]
@spohngellert-o Did you manage to fix your issues, any progress on the issue?

**Comment by tburrows13** [comment]
`VideoFileClip.close()` has now been part of MoviePy for some time. It automatically closes it's audio, audio.reader and video.reader.

**Comment by whmzsu** [comment]
> `VideoFileClip.close()` has now been part of MoviePy for some time. It automatically closes it's audio, audio.reader and video.reader.

It seemed that the close function still have problem randomly. After the close the VideoFileClip.close(), I try to rename the video file and got the PermissionError: [WinError 32]  , it said that the file is opened by another process.

python version 
Python 3.8.5    windows 10  amd64
moviepy version
1.0.3

**Comment by Naaach** [comment]
In my case I can solve thiso problem, clossing first the clips inside the "VideoFileClip"

```python
for clip in importedClips:
  if hasattr(clip, 'clips'):
      for subclip in clip.clips:
          subclip.close()
  if hasattr(clip, 'close'):
      clip.close()
```
