### ISSUE TITLE
Unable to use unicode strings with Python 2

### ISSUE THREAD

**Issue by flothesof** [Zulko/moviepy#76]
I'm trying to use French labels within a TextClip. 
However, the rendering with ImageMagick fails:

```
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-5-9c706287e797> in <module>()
      5                          font=font,
      6                          fontsize=fontsize,
----> 7                          size=(W, H)).set_pos('center').set_duration(5))
      8     if vid != None:
      9         start, end = subsection

C:\Python27\lib\site-packages\moviepy\video\VideoClip.py in __init__(self, txt, size, color, bg_color, fontsize, font, stroke_color, stroke_width, method, kerning, align, interline, tempfilename, temptxt, transparent, remove_temp, print_cmd)
   1048                     os.write(temptxt_fd, bytes(txt,'UTF8'))
   1049                 except TypeError: # oops, fall back to Python2
-> 1050                     os.write(temptxt_fd, txt)
   1051                 os.close(temptxt_fd)
   1052             txt = '@'+temptxt

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 33: ordinal not in range(128)
```

There seems to be a possible workaround by doing the following:

```
#os.write(temptxt_fd, txt)
os.write(temptxt_fd, txt.encode('utf-8'))
```

But this won't get me any UTF-8 text on the picture. Instead, I get the classical encoding mismatched characters.

Any idea on how to fix this?

Thanks!

**Comment by AdamSerafini** [comment]
@flothesof The font matters: if the font doesn't support those characters you'll see question marks. See [this thread](http://www.imagemagick.org/discourse-server/viewtopic.php?t=18316) and [this one](http://www.imagemagick.org/discourse-server/viewtopic.php?t=16807) on the ImageMagick forum for more details.

**Comment by flothesof** [comment]
Hey thanks for writing this here. This might be it. I'm going to try this again and post the result here.

**Comment by kerstin** [comment]
@flothesof Did you ever get around to testing this with a different font? Was what @adamserafini suggested the solution to your problem?

If so, we could add a hint about that to the documentation.

**Comment by kerstin** [comment]
Ping @flothesof

**Comment by flothesof** [comment]
Hi everyone,

Thanks for helping me out on this.
I think I managed to get it working at the time.
I believe the issue can be closed, since the last time I tried this (which was with Python 3) it was working.

I'll close the issue now.

Best
Florian
