### ISSUE TITLE
How to call moviepy.video.fx.all.crop() ?

### ISSUE THREAD

**Issue by Swiffers** [Zulko/moviepy#760]
The script looks like the most basic:

```
from moviepy.editor import
clip = VideoFileClip('./video.mp4')
```

I would like to crop() this clip, how to do it?

**Comment by Swiffers** [comment]
The [documentation mention](https://zulko.github.io/moviepy/ref/videofx.html):
```
from moviepy.video.fx.scroll import crop
newclip = myclip.fx( vfx.crop, x1=15)
```
But I'm getting this error:
```
from moviepy.video.fx.scroll import crop
> ImportError: cannot import name crop
```

**Comment by TejasBob** [comment]
```
import moviepy.video.fx.all as vfx
new_clip = myclip.fx(vfx.crop, x1=15)
```
This works fine!

**Comment by Swiffers** [comment]
@TejasBob It didn't for me,

Could it be caused by my multiple imports?
```
import moviepy.video.fx.all as vfx
from moviepy.editor import *
```
But I fixed the issue by using: 

```
vfx.crop(original, x1=crop_w,y1=crop_h,x2=original.w-crop_w,y2=original.h-crop_h)
```

**Comment by tburrows13** [comment]
The recommended way is just with

```
from moviepy.editor import *
new_clip = clip.crop(x1=15)
```
Does this work?

**Comment by Swiffers** [comment]
Yes, it does

**Comment by LaksVister** [comment]
> The recommended way is just with
> 
> ```
> from moviepy.editor import *
> new_clip = clip.crop(x1=15)
> ```
> 
> Does this work?

Not any more
