### ISSUE TITLE
How can I include a moving 'arrow' in a clip?

### ISSUE THREAD

**Issue by Swiffers** [Zulko/moviepy#762]
I'm need to create and include inside my videos an animation with a moving arrow, like this
```
1. ->
2. -->
3.  -->
4.   -->
5.    -->
6.   -->
7.  -->
8. -->
9. ->
```
1 to 9 represents frames/or time.

What are your recommendations on how to do it ? For the moment my only idea would be to create an arrow image and add it using ImageClip('arrow.png') display it 1 second, move it 1 pixel, hide it, display it, etc. 

Your advices are welcome

**Comment by Zulko** [comment]
You could do it using a composite video clip with an arrow whose position depends on time. Something like this:

```
final_clip = CompositeVideoClip([
    background_clip,
    arrow_clip.set_pos(lambda t: (300 + 20 * np.sin(t), 400))
]).set_duration(background_clip.duration)
```

where arrow_clip was loaded using ``Imageclip("my_arrow.png", has_mask=True)``.
Apologies for any syntax mistake. written in a hurry.

**Comment by Swiffers** [comment]
@Zulko thanks. If I use a .gif with a transparent background and add it as an imageclip('') will it keep the transparency?

**Comment by Zulko** [comment]
cant remember exactly, certainly yes but you would need to say "with_alpha" or something when you load the GIF  with VideoFileClip

**Comment by Swiffers** [comment]
@Zulko I see *withmask*
> will save the clip’s mask (if any) as an alpha canal (PNGs only)

But where is the option to load the GIF using [VideoFileClip](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#videofileclip)() **with a transparent background ?**

```
class moviepy.video.io.VideoFileClip.VideoFileClip(filename, has_mask=False, audio=True, audio_buffersize=200000, target_resolution=None, resize_algorithm='bicubic', audio_fps=44100, audio_nbytes=2, verbose=False, fps_source='tbr')
```

**Comment by Zulko** [comment]
``has_mask`` ?

**Comment by Swiffers** [comment]
Perfect. 

Why is it called a mask? I'm new to video edition. I thought that a mask would be used to show a part of the video (i.e: the part under the mask).
