### ISSUE TITLE
Gif from pictures

### ISSUE THREAD

**Issue by ghost** [Zulko/moviepy#770]
How I can make gifs from pictures?
Better if I will can make gifs with PIL

**Comment by tburrows13** [comment]
I'll give you a more detailed example in less than 24 hours :)

**Comment by tburrows13** [comment]
Ok, you want

```
clip = ImageSequenceClip(sequence=file_list, duration=0.1)
clip.write_gif('mygif.gif')
```

`file_list` can either be a list of file names, or the name of a directory containing only images. Adjust the `duration` argument to whatever you like.

**Comment by Dominux** [comment]
Can I do that without save images
If program render their?

**Comment by Dominux** [comment]
I create folder with images only
Later I start the program:

import moviepy.editor as mpy
clip=mpy.ImageSequenceClip(sequence="C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация\\", durations=3)
clip.write_gif("Serpinsky_1.gif",fps=3)

And have got that:

Traceback (most recent call last):
  File "C:/Users/Im/Desktop/Питон/Файлы/Графон/Фракталы/анимация/Муви.py", line 2, in <module>
    clip = mpy.ImageSequenceClip(sequence="C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация", durations=3)
  File "C:\Users\Im\Desktop\Питон\lib\site-packages\moviepy\video\io\ImageSequenceClip.py", line 88, in __init__
    image1=imread(image)
  File "C:\Users\Im\Desktop\Питон\lib\site-packages\imageio\core\functions.py", line 206, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "C:\Users\Im\Desktop\Питон\lib\site-packages\imageio\core\functions.py", line 126, in get_reader
    'in mode %r' % mode)
ValueError: Could not find a format to read the specified file in mode 'i'

**Comment by tburrows13** [comment]
Can you run

```
import os
print(os.listdir("somedirectory"))
```

on the folder with all the pictures on and check that there are no hidden files that are messing it up?

**Comment by Dominux** [comment]
I get the empty list

**Comment by Dominux** [comment]
import os
print(os.listdir("C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация\\Serpinsky\\"))



2018-04-21 23:24 GMT+03:00 Tom Burrows <notifications@github.com>:

**Comment by tburrows13** [comment]
You've got an extra `Serpinsky` at the end that you didn't have back when you had the error...?

**Comment by Dominux** [comment]
What do you mean? I didn't really get it

**Comment by tburrows13** [comment]
When you got the error yesterday, you were running `ImageSequenceClip` on the folder `"C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация\\"`, not `"C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация\\Serpinsky\\"`. Try this code exactly:
```
import os
print(os.listdir("C:\\Users\\Im\\Desktop\\Питон\\Файлы\\Графон\\Фракталы\\анимация\\"))
```

**Comment by Dominux** [comment]
Output:
['0.jpg', '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg', 'Epic.py', 'proverka.py', 'Serpinsky', 'Дерево Пифагора Мега.py', 'Муви.py', 'Снежинка Коха в приближении.gif', 'Снежинка Коха.gif', 'Треугольник Серпинского Анимация 1.py']

**Comment by tburrows13** [comment]
Ok, so when you are calling `ImageSequenceClip`, the first argument needs to be a list of strings, or a string with the name of a folder containing _only_ pictures. You passed it the name of a folder containing lots of different files, so it didn’t work. You need to move all the pictures to a different folder and pass the name of that folder to `ImageSequenceClip`.

We should probably change the error message to be more explicit, or change it so that it can ignore non-images.

**Comment by tburrows13** [comment]
For future reference, `durations` must be a list of numbers, not a single number. I'm closing this because the thread is now 2 years old.
