### ISSUE TITLE
Video Background

### ISSUE THREAD

**Issue by lifeNrun** [Zulko/moviepy#774]
Hi, I want to add a background image to a video. The size of this video is 540\*960, I want to add a background image to this video to Integrate into a new video(1280\*720).  The size of this image is 1280\*720.
How can I use 'ImageClip' to achieve this goal?
Thanks.

**Comment by tburrows13** [comment]
Hi, I can’t give you complete code right now, but you’ll want to use a `CompositeVideoClip`.
Have a look at http://zulko.github.io/moviepy/getting_started/compositing.html and http://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#compositevideoclip.

**Comment by lifeNrun** [comment]
Thanks
