### ISSUE TITLE
SubtitlesClip

### ISSUE THREAD

**Issue by lifeNrun** [Zulko/moviepy#777]
Hi, When I use SubtitlesClip to set subtitle for video. I got these failed error message below:

```
Traceback (most recent call last):
  File "musicChina.py", line 67, in <module>
    subtitles = SubtitlesClip("./prepare/test.srt", generator)
  File "C:\Python36\lib\site-packages\moviepy\video\tools\subtitles.py", line 54, in __init__
    self.duration = max([tb for ((ta,tb), txt) in self.subtitles])
  File "C:\Python36\lib\site-packages\moviepy\video\tools\subtitles.py", line 54, in <listcomp>
    self.duration = max([tb for ((ta,tb), txt) in self.subtitles])
TypeError: 'NoneType' object is not iterable
```

This is my code:
```
    font="ArialUnicode"
    color='red'
    generator = lambda txt: TextClip(txt, font=font, fontsize=40, color=color)
    subtitles = SubtitlesClip("./prepare/test.srt", generator)
```

Thanks.

**Comment by lifeNrun** [comment]
Problem solved. The srt file has problem. Please igore this.

**Comment by jpaguilarc99** [comment]
Please tell me how did u fix the file

**Comment by MASSKAgithub** [comment]
Same error

**Comment by Souks** [comment]
and same here too

**Comment by MASSKAgithub** [comment]
**I FOUND A SOLUTION**

The spacing between EACH str block, should be 1 new line, and at the end of the file should be 2 new lines
ALSO Sometimes, in my generated SRT files, there are blocks that are for no reason: 00:00:00 in the middle of the file, so you have to remove them (with their number and text if it has, usually it doesn't have any text)

And so by applying this modifications the file becomes usable!

**Comment by Souks** [comment]
Thanks for the help, i had 3 new line at the end of the file and it was my error ;)
