### ISSUE TITLE
Built-in file downloader downloads files repeatedly?

### ISSUE THREAD

**Issue by zamirkhan** [Zulko/moviepy#779]
(preamble: I'm using moviepy in a side-project and I absolutely love it. Super happy with it and I hope to be able to contribute at some point, especially if the side-project has legs)

I'm using moviepy to stitch together videos in a CompositeVideoClip. The script runs on an EC2 instance on AWS and the clips are located in an S3 bucket (remote to the EC2 instance). I'm simply passing the publicly-accessible URLs into the VideoFileClip constructor for each clip and relying on the moviepy internals to do the downloading.

I was surprised to notice my AWS bill jumped significantly (nothing worrying financially, but relatively-speaking it was a many-times increase and something to be taken care of before scaling) after using this script. Using logging and usage reports, I traced things down to the download of the clips from this bucket. Although I expected each clip to be downloaded once, for 4 clips there were 17 GetObject calls logged (i.e. downloads). So about a 4x increase in expected bandwidth used. The user-agent starts with "Lavf" which I assume comes from libav or something of that nature?

Anyway, I understand clip downloading is not necessarily core to moviepy and is provided for convenience. I can work-around this issue by performing the downloads myself (using something like boto3) and then accessing the files locally, but I thought this should be noted.

**Comment by Zulko** [comment]
First, I had no idea you could actually do that, that's awesome, last time I checked you could only open local files. Does any other maintainer know if it's an improvement of FFMPEG or someone's contribution to MoviePy.

On to your question: when you run VideoFileClip, moviepy opens an ffmpeg instance which "connects" to the file. If you read the frames one by one, it keeps the initial connection, but every time you jump to a completely new time in the video (for instance if you use ``supclip`` to start 45minutes into the video) it closes the connection to the file, and opens a new FFMPEG process on the file using a quick-seeking method to start at 45 minutes. It may be what you are seeing.

Theoretically (not sure) it would mean that despite the calls logged, everytime only the necessary data is read from the video. In any case, if the number of calls is a problem, try downloading the video file locally.

Does that make sense ?

**Comment by zamirkhan** [comment]
Yes, it does make sense. Thank you for shedding some more light on how FFMPEG is involved.

As to your initial question, I was under the assumption that this module was involved (https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/downloader.py), but I could be wrong as I didn't delve too deeply into how it connects up.

**Comment by Zulko** [comment]
The downloader is meant to make it easy to for video creators download files from the web into their local machine, in particular youtube videos (it wraps Youtube-dl).

**Comment by zamirkhan** [comment]
I see - so it's a completely unrelated utility module. Thanks for clarifying.
