### ISSUE TITLE
VideoFile Clip Error for long videos

### ISSUE THREAD

**Issue by richard-warren** [Zulko/moviepy#784]
Hi,

I am importing large videos (>150,000 frames) recorded at very high frame rate (250 fps). If I run code to count the number of frames (shown below), the count is correct ~half the time, is one too many half the time, and was one short on one occasion. When the frame count is too high I get the following warning:

>  Warning: in file runTopBot.avi, 477576 bytes wanted but 0 bytes read,at frame 209782/209783, at time 839.13/839.13 sec. Using the last valid frame instead.

The error is always occurs in the second to last frame. Curiously, when I run the minimal code below I don't get the error message, but still get a count that is too high. The error message appears to occur only in the context of the full code. This issue is [similar to another](https://github.com/Zulko/moviepy/issues/49), but my problem was not fixed with an update of ffmpeg and moviepy.

```
from moviepy.editor import VideoFileClip
import numpy as np

clip = VideoFileClip("runTopBot.avi")
nframes = np.sum(1 for j in clip.iter_frames())
```
Any thoughts on how to solve this problem? I'm thinking the high frame rate and frame count is leading to precision errors. Is there a 'next_frame' sort of method that could be implemented that just grabs the next frame without have to index in by dividing time by frame rate? I'm a little unclear on how ffmpeg is asked to grab frames under the hood here.

Thank you!
Rick

**Comment by chaonan99** [comment]
This happens to me as well and I am processing 30s video clips. It happened to almost all my videos.

**Comment by keikoro** [comment]
@chaonan99 If the problem persists with the latest recommended version of MoviePy, I'd ask you to open a new issue following our issue template. Closing this otherwise very old issue due to a lack of info we'd need to try to reproduce the original problem.
