### ISSUE TITLE
'function' object has no attribute 'end' (CompositeVideoClip)

### ISSUE THREAD

**Issue by alekoz47** [Zulko/moviepy#787]
Running `CompositeVideoClip([...])` to compose five clips generates the error "AttributeError: 'function object has no attribute 'end'." This error locates to  `__init__`, of "anaconda3\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py." On line 85,
```python
ends = [c.end for c in self.clips]
```

**Comment by mgaitan** [comment]
@alekoz47 could you share more context? how are you generating those five clips?

**Comment by keikoro** [comment]
@alekoz47 Did you manage to solve this problem? Can we close the issue?

**Comment by tburrows13** [comment]
This is impossible to solve without seeing the clips used in the `CompositeVideoClip`.
