### ISSUE TITLE
TLS1.2 problem

### ISSUE THREAD

**Issue by leoleoasd** [Zulko/moviepy#789]
failed to download ffmpeg:
Imageio: 'ffmpeg-osx-v3.2.4' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719)>.

But i had already installed one from homebrew. (/usr/local/bin/ffmpeg), and i had already set the vars in config_default.py

**Comment by tburrows13** [comment]
Hi, did you set the var in config_default.py before installing moviepy?

If so, then this is definitely a problem in moviepy. Can you try commenting out lines 23-26 in editor.py, then importing moviepy.editor and creating a videoclip? https://github.com/Zulko/moviepy/blob/master/moviepy/editor.py#L23

**Comment by mgaitan** [comment]
@leoleoasd please, double check you are editing the right `config_default.py`. If you already set an custom executable, imageio shouldn't be trying to download its own ffmpeg. 

One way to verify it's the right module is to import and see the module's path

```python
In [1]: from moviepy import config_defaults
In [2]: config_defaults.__file__
Out[2]: '/home/tin/lab/moviepy/moviepy/config_defaults.py'
```
Alternatively, you could set the ffmpeg executable path via an enviroment variable.  From your console. 

```
   $ export FFMPEG_BINARY=path/to/ffmpeg
```

**Comment by focalhot** [comment]
Any updates here? I am having the same error:
```
Python 3.6.5
macOS 10.13.3
```

**Comment by leoleoasd** [comment]
@mgaitan i'm editing the correct file.
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moviepy/config_defaults.py

@focalhot I solve this problem by setting download url in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moviepy/fetching.py into my local machine's web server.

**Comment by tburrows13** [comment]
In v2.0, the path to a manually installed ffmpeg can be set with an environment variable.
