### ISSUE TITLE
config_defaults.py is a poor UX

### ISSUE THREAD

**Issue by mgaitan** [Zulko/moviepy#793]
Currently, the README recommends to manually edit `config_defaults.py` to set a custom FFMPEG path as imageio's alternative (to be used under an offline enviroment, experimental version, etc.) 
Altought 
This manual intervention is very weird, not only because it's no so easy to know where is this module (for instance, check #789 or #320)  but because a python package not necessarily keeps in its source format after be installed. But moreover, it ties the configuration to the code. Why?

Altought it's possible to use enviroment variables as an alternative, it's only mentioned in `config_defaults.py`'s docstring,. 

On https://github.com/Zulko/moviepy/issues/148#issuecomment-87778674 I proposed to use a user-level configuration file to override default (built-in) configuration. It could be a ini-style or json file

**Comment by Zulko** [comment]
Im just seing that now. I'm not sure why in #148 it is question of changing a file before installing, the original idea was to change the config from inside the code with something like:

```
from moviepy.config import change_settings
change_settings(FFMPEG_BINARY="path/to/ffmpeg/binary")
```

Looking back at the code it has been changed in a way that seems to also support a configuration file, [see here](https://github.com/Zulko/moviepy/blob/956c46256cac34fd8fa12930eed8bebc824e322e/moviepy/config.py#L81-L91). It looks like either my doing or @cclauss, I dont get the git blame, and I dont remember exactly. Should have commented it better at the time.

**Comment by keikoro** [comment]
Not sure what the status or next steps on this are, but I tagged it with `documentation` for now...
