### ISSUE TITLE
How to add audio track to MP4?

### ISSUE THREAD

**Issue by arekbulski** [Zulko/moviepy#794]
I need a quick advise: can I use this library to modify a MP4 by adding (or replacing) an audio track? If so, would it reencode?

**Comment by Zulko** [comment]
If this is the only thing you need to do, then ffmpeg will do that faster and without reencoding.

in moviepy you can do it with:

```
myclip.audio = AudioFileClip("some_soundtrack.mp3")
```

**Comment by arekbulski** [comment]
So the one-liner using moviepy would require re-encoding, right? Could you point me to some existing ffmpeg discussion/solution? I am not very proficient with ffmpeg options.

**Comment by Zulko** [comment]
yes the moviepy solution involves reencoding. I cant help you with ffmpeg but it should be easy enough to find out, it is a common use case.

Note that for this kind of questions forums like stackoverflow or reddit/moviepy are better than github issues (which we keep for bug reports or feature requests).

**Comment by arekbulski** [comment]
Thank you!
