### ISSUE TITLE
fl_time is slow to setup

### ISSUE THREAD

**Issue by RonanBBC** [Zulko/moviepy#801]
The `.fl_time` function calls the supplied function with `t=0` repeatedly during setup, this shouldn't be needed because at this point the video clip is just being setup and the work doesn't actually get done until you show or write out the video.

This means the `.subclip` method takes a long time to execute even before video rendering happens

**Comment by tburrows13** [comment]
I can't see this happening anywhere in the code, so I'm closing this for now.
