### ISSUE TITLE
Looping an image sequence create noise.

### ISSUE THREAD

**Issue by anandkpandey1** [Zulko/moviepy#805]
Hi,

I wrote a simple programme to create an image sequence from a set of 50 images (PNG with transparent Background) from a folder named "Teaching" and then loop it, the programme works without any error, but the video generated out of it has a lot of noise after the first iteration.

The first iteration of loop works perfectly fine, as it goes on to the second loop the image gets noisy and start leaving trails.

Code
============================
from moviepy.editor import *
import moviepy.video.fx.all as vfx

images_list="Teaching"
newclip = ImageSequenceClip(images_list, fps=30, load_images=True)
clip1 = newclip.fx(vfx.loop, duration=10)

clip2 = ImageClip("BG.jpg")
clip2 = clip2.set_duration(10)
video = CompositeVideoClip([clip1, clip2])
video.write_videofile("output.webm")

**Comment by keikoro** [comment]
Closing this issue as it's very old and it's unclear if the problem persists with the latest recommended version of MoviePy.

If so, feel free to reopen it – or open a new issue, referencing this older one – providing the info we ask for in our issue template (platform used etc.).
