### ISSUE TITLE
Resizing ImageClip

### ISSUE THREAD

**Issue by IsaacZanoria** [Zulko/moviepy#806]
I'm trying to resize an ImageClip for use as an adjustable width sidebar for a video. In the past, it looks like the ImageClip class had a "resize" attribute like many other of the clip classes, but it doesn't look like it has one anymore. Is there a clean way of doing this now that doesn't require saving a changed version of the image and using that to make an imageclip? (code segment that I'm trying to use is below; resolution[1] references the height of the video the sidebars are being added onto)

        if sidebar_width != 0:
            sidebar_left = sidebar_left.resize(resolution[1], sidebar_width)
            sidebar_right = sidebar_right.resize(resolution[1], sidebar_width)

**Comment by alexzach** [comment]
Resizing imageClip works fine for me.
What error do you get?
It looks like you passing wrong parameters. The resize(newsize, height, width) uses **only one** of those three arguments. If newsize given, the others are totally ignored.

**Comment by keikoro** [comment]
@IsaacZanoria Did the suggestion by @alexzach work for you? Can we close this issue?
