### ISSUE TITLE
Can we use CompositeVideoClip as part of another CompositeVideoClip?

### ISSUE THREAD

**Issue by anandkpandey1** [Zulko/moviepy#808]
Hi,

Can we use CompositeVideoClip as part of another CompositeVideoClip, I tried it with following code example but failed eith an error.

    intro_video = CompositeVideoClip([video1, video2])
    content_video = CompositeVideoClip([video3, video4])
    final_video = CompositeVideoClip([intro_video, content_video.crossfadein(1.5)])

Can this be achived with another way using Moviepy?

**Comment by Zulko** [comment]
Yes. Plaease post the error

**Comment by anandkpandey1** [comment]
@Zulko I modified few things and it works now, however with a glitch
In my code, content_video is a small clip which is repeated for few seconds. In the result I get after composing, intro_video works fine, while only one iteration of content_video is added rest is blank screen.

code:

    intro_video = CompositeVideoClip([video1, video2])
    content_video = CompositeVideoClip([video3, video4])
    content_video_looped = content_video.fx(vfx.loop, duration=10)
    final_video = CompositeVideoClip([intro_video, content_video_looped.crossfadein(1.5)])

**Comment by tburrows13** [comment]
Currently, it should work but it suffers from bad performance.
