### ISSUE TITLE
PermissionError after trying to delete a file after it's purpose is done

### ISSUE THREAD

**Issue by ZuperZee** [Zulko/moviepy#810]
### Expected Behavior
I want this code to convert a .mp4 file into a .mp3 file then delete the .mp4 file after it has been converted

### Actual Behavior
This code converts the .mp4 file into a .mp3 but It doesn't delete the .mp4 file after it has converted (The .mp4 file is still there after it has converted. I know it should, just clarifying).
I get this Error code

```
[MoviePy] Writing audio in Nightcore - Left Behind.mp3
100%|██████████| 442/442 [00:01<00:00, 302.50it/s]
[MoviePy] Done.
Traceback (most recent call last):
  File "C:/Users/Eier/PycharmProjects/ZuperProject/ZuperProjectPackage/TestingMusic3.py", line 10, in <module>
    os.remove("Nightcore - Left Behind.mp4")  # Removes
PermissionError: [WinError 32] : 'Nightcore - Left Behind.mp4'
```

### Steps to Reproduce the Problem
```
import moviepy.editor as mp
import os

song = "Nightcore - Left Behind.mp4"  # The video I want to convert
songSliced = song[:song.rfind(".")]  # Removes .mp4 from the video name I want to convert

clip = mp.VideoFileClip(song).subclip(0, 20)
clip.audio.write_audiofile(songSliced + ".mp3")  # Converts the .mp4 video into .mp3 sound

os.remove(song)  # Removes the .mp4 file
```

### Specifications

  - Python Version:  3.6.5
  - Moviepy Version:  0.2.3.5
  - Platform Name:  Windows 10
  - Platform Version: Version 1803

**Comment by tburrows13** [comment]
Hi,
What is happening is that you're trying to delete a file, but moviepy is still using it. Unfortunately, moviepy is not very good at properly releasing resources correctly. Try running `clip.close()` before deleting the mp4.

**Comment by ZuperZee** [comment]
I tried with the clip.close() before I try to delete the .mp4 file, but I still get the same 

##New code
import moviepy.editor as mp
import os

song = "Nightcore - Left Behind.mp4"  # The video I want to convert
songSliced = song[:song.rfind(".")]  # Removes .mp4 from the video name I want to convert

clip = mp.VideoFileClip(song).subclip(0, 20)
clip.audio.write_audiofile(songSliced + ".mp3")  # Converts the .mp4 video into .mp3 sound
clip.close()
os.remove(song)  # Removes the .mp4 file

##Error
C:\Users\Eier\PycharmProjects\ZuperProject\ZuperProject\Scripts\python.exe C:/Users/Eier/PycharmProjects/ZuperProject/ZuperProjectPackage/TestingMusic3.py
[MoviePy] Writing audio in Nightcore - Left Behind.mp3
100%|██████████| 442/442 [00:01<00:00, 239.31it/s]
[MoviePy] Done.
Traceback (most recent call last):
  File "C:/Users/Eier/PycharmProjects/ZuperProject/ZuperProjectPackage/TestingMusic3.py", line 10, in <module>
    os.remove(song)  # Removes the .mp4 file
PermissionError: [WinError 32] : 'Nightcore - Left Behind.mp4'

**Comment by tburrows13** [comment]
Ok, that's definitely a problem in moviepy. You could try something like `time.sleep(5)` before deleting the file, but I think that's unlikely to work.

What will almost certainly work is if you run the moviepy editing in a separate [process](https://docs.python.org/3.6/library/multiprocessing.html).

Try this:
```
import moviepy.editor as mp
import os
from multiprocessing import Process

song = "Nightcore - Left Behind.mp4"  # The video I want to convert
songSliced = song[:song.rfind(".")]  # Removes .mp4 from the video name I want to convert

def convert_mp4():
    clip = mp.VideoFileClip(song).subclip(0, 20)
    clip.audio.write_audiofile(songSliced + ".mp3")  # Converts the .mp4 video into .mp3 sound

converter = Process(target=convert_mp4)
converter.start()
converter.join()  # Waits until the function has finished executed before continuing

os.remove(song)  # Removes the .mp4 file
```

**Comment by ZuperZee** [comment]
Thank you. It worked with this code.

import moviepy.editor as mp
import os
from multiprocessing import Process

song = "Nightcore - Left Behind.mp4"  # The video I want to convert
songSliced = song[:song.rfind(".")]  # Removes .mp4 from the video name I want to convert


def convert_mp4():
    clip = mp.VideoFileClip(song).subclip(0, 20)
    clip.audio.write_audiofile(songSliced + ".mp3")  # Converts the .mp4 video into .mp3 sound


if __name__ == '__main__':
    converter = Process(target=convert_mp4)
    converter.start()
    converter.join()  # Waits until the function has finished executed before continuing
    os.remove(song)  # Removes the .mp4 file

**Comment by tburrows13** [comment]
Great! Thank you.

**Comment by dfvr1994** [comment]
You probably tried to run the same code many times and ended up having may instances of ffmpeg open like so:

![image](https://user-images.githubusercontent.com/45764991/175767454-e1e4ca58-3660-4b6b-9229-4c6cc56394da.png)

Try closing them, manually deleting the temp files, and making sure you put a clip.close() at the end of each operation
