### ISSUE TITLE
write_gif() output file size is large 

### ISSUE THREAD

**Issue by cna74** [Zulko/moviepy#811]
converted a first 10 seconds of a clip(50 mb) with write_gif() gave me a 46 mb gif 

```
clip = VideoFileClip("input.mp4").subclip('2:09:05', '2:09:17')
video = CompositeVideoClip([clip])
video.write_gif("output.gif", program='ffmpeg', fps=clip.fps)
```

i also test imageio but that is worse, gave me 76 mb

  - Python Version: 3.6
  - Moviepy Version: 0.2.3.2
  - Platform Name: windows 10

**Comment by tburrows13** [comment]
Hi,
Why are you using the middle line (`video = CompositeVideoClip([clip])`)? That shouldn't be needed for your purposes.

**Comment by cna74** [comment]
i know but `clip.write_gif("output.gif", program='ffmpeg', fps=clip.fps)` doesn't make any diffrent.

**Comment by cna74** [comment]
so is there any other solution to export gif from VideoFileClip, without file size problem !?

**Comment by dheerajmpai** [comment]
Using `ffmpeg` instead of `imageio` can significantly reduce the file size
For a seven second gif I got the following results.

`ffmpeg` : 19MB
`imageio` : 39MB

```
gif_clip.write_gif('gif_clip.gif',fps=25,program= 'ffmpeg')```

```
gif_clip.write_gif('gif_clip_imageio.gif',fps=25,program= 'imageio')
```

**Comment by siu3334** [comment]
Hi, I'm also having the said issue where resulting GIFs outputs to 5 to 6 times the size of original MP4 video even while using ffmpeg. Shouldn't the GIFs comes out with reduced lower size than MP4? Is there any solution to fix this issue?

**Comment by Zulko** [comment]
> Shouldn't the GIFs comes out with reduced lower size than MP4
No GIFs are generally heavier than MP4s (a 5-10x factor seems about right). One way to reduce the weight of a GIF is to reduce its dimensions (with clip.resize() in MoviePy). Another way is to use an online GIF optimizer (can give you a ~50% decrease).

**Comment by siu3334** [comment]
ok thanks for the insight. Is there anyway to significantly optimise gifs with moviepy like how some online gif optimiser do it? They help reduce the size of gif significantly, so I am wondering if same can be achieved with moviepy but I am not seeing anything relevant in documentation. using opt parameter in write_gif() barely optimise the final gif, no offense.

**Comment by tburrows13** [comment]
You can experiment with different `program` parameters that uses other programs than ImageMagick.

**Comment by mahendra94040** [comment]
Try this :

clip = VideoFileClip("input.mp4").subclip('2:09:05', '2:09:17').**resize(0.5)**
video = CompositeVideoClip([clip])
video.write_gif("output.gif", program='ffmpeg')

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years, and people have responded to other commenters in the thread with potential solutions.
