### ISSUE TITLE
getting frames between time intervals.

### ISSUE THREAD

**Issue by Flock1** [Zulko/moviepy#813]
### Specifications

  - Python Version: 3.6
  - Moviepy Version: 0.2.3.4
  - Platform Name: Ubuntu
  - Platform Version: 16.04

I have an array that contains time stamps in seconds, something like:
```
start_time = (346, 422, 497)
stop_time = (369, 432, 501)
```
As you can guess, I want the frames between the start and the corresponding stop time. All I find online is to get the frame at the frame at a specific time, instead of a time interval. One code I written is to create a sub clip and then store all the frames, which is obviously time consuming. So what should I do?

**Comment by Zulko** [comment]
try

```python
for frame in myclip.subclip(start, stop).iter_frames():
    # do something
```

Please let us know if this does what you want. You can refer to Reddit or stackoverflow for help questions in the future (we try to keep github for bug/issues/feature requests)

**Comment by Flock1** [comment]
Hey @Zulko, Thanks for the reply. I'm not able to post any questions on Stackoverflow because I have been banned. 
I tried your code, something like this:
```
img = np.copy(frame)
    img_cv2 = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.imwrite("/images/frame%d.jpg" %count, img_cv2)
    count+=1
```
It's not writing the images.

**Comment by keikoro** [comment]
@Flock1 Have you meanwhile been able to solve the issue? Should this remain open?

**Comment by keikoro** [comment]
Closing this as it's unclear if this is still an issue with newer versions of MoviePy.
