### ISSUE TITLE
Bad clip duration after adding overlay text to the video file.

### ISSUE THREAD

**Issue by heliplasticfish** [Zulko/moviepy#814]
### Bad clip duration after adding overlay text to the video file.
Hello, I have a problem. After adding text to video files, the length of the shots is change. Please advise how to reach the original length. I'm processing source video files from the quickTime - h264.
"""
 
    import glob
    from moviepy.editor import *
    
    
    class OverlayTest():
        def __init__(self):
            self.sourceMovePath = "e:/Bordel/999_TestLubos/SB999_10_TestLubos_01LR"# some folder with quicktime video file
    
            allVideoFile = glob.glob1(self.sourceMovePath, "*.mov")
            allVideoFullPath = [os.path.join(self.sourceMovePath, i) for i in allVideoFile]
            self.time_sorted_list = sorted(allVideoFullPath, key=os.path.getmtime)
    
    
        def printLenghtClip(self):
    
            for testVideo in self.time_sorted_list:
                videoFile = VideoFileClip(testVideo)
                print('Name videoFile is: %s    length: %s     fps: %s' % (testVideo, videoFile.duration, videoFile.fps))
    
        def overlayText(self):
    
            for testVideo in self.time_sorted_list:
                videoFile = VideoFileClip(testVideo)
    
                lengthClip = videoFile.duration
                print(lengthClip)
    
    
    
                textAll = TextClip(('ShotName/FileName/SeqName'), font='Arial', fontsize=30, color='black').set_position('center')
                txtAllPos = textAll.set_pos((0.010, 0.01), relative=True)
    
                final = CompositeVideoClip([videoFile, txtAllPos])
                fpsVideo = final.fps
    
                nameVideo = str(testVideo.split("scene-")[-1])
                length = videoFile.duration
                final.duration = videoFile.duration
    
                try:
                    final.write_videofile('%s/newQT-%s' % (self.sourceMovePath, nameVideo), fps=fpsVideo, codec='libx264')
                except:
                    pass
    
    
    if __name__ == '__main__':
        overlayTest = OverlayTest()
        #overlayTest.overlayText()          # write overlay text
        overlayTest.printLenghtClip()       # show length video file
### Actual Behavior
Bad clip duration
after adding overlay text to the text, the resulting clip duration is different from the source video
### Result python code:
source video file version:
001_scene-06Neplod-01.mov    length: 8.08     fps: 24.0
002_scene-06Neplod-02.mov    length: 3.92     fps: 24.0
003_scene-06Neplod-03.mov    length: 7.83     fps: 24.0
004_scene-06Neplod-04.mov    length: 2.38     fps: 24.0

After text overlay is new version quicktime video file longer:
newQT-06Neplod-01.mov    length: 8.13     fps: 24.0
newQT-06Neplod-02.mov    length: 3.97     fps: 24.0
newQT-06Neplod-03.mov    length: 7.86     fps: 24.0
newQT-06Neplod-04.mov    length: 2.43     fps: 24.0

### Specifications

  - Python Version: 2.7
  - Moviepy Version: 
  - Platform Name: windows
  - Platform Version: win 10

**Comment by keikoro** [comment]
Hi, is this still a problem today with the newest recommended version of MoviePy?

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.
