### ISSUE TITLE
Simple ImageClip Produces File With Incorrect Duration

### ISSUE THREAD

**Issue by JohnTravolski** [Zulko/moviepy#817]
I'm very new to moviepy, so please let me know if I'm doing something wrong, but observe the following example:

```
from moviepy.video.VideoClip import ImageClip

myclip = ImageClip("testing.jpg")
myclip = myclip.set_fps(10)
myclip = myclip.set_duration(10)
myclip.write_videofile("movie.mp4")

```
For some reason, the output file is missing exactly two frames, and I'm not sure why.  Instead of it containing 100 frames like it should, it only contains 98 (I was able to check this using Premiere Pro and After Effects).  If I change the duration to 1, it only contains 8 frames instead of 10.  Why is this?  What's going wrong here?

I'm running on Python 3.6.4 and moviepy 0.2.3.5.

**Comment by keikoro** [comment]
Closing this issue as it's old and based on an old MoviePy version, so impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
