### ISSUE TITLE
Incorrect frame number for high frame rate videos

### ISSUE THREAD

**Issue by richard-warren** [Zulko/moviepy#818]
Hi,

Thank you for your excellent toolbox. I am using moviepy to serially read every frame of videos captured at 250 fps, with >200,000 frames per video. Using clip.iter_frames for this purpose often results in estimates of frame number that are 1 frame too many or too few. I believe this is due to line 474 in Clip.py

> for t in np.arange(0, self.duration, 1.0/fps):

Because the time between frames is .004 seconds, and the resolution of the video duration measurement only has two decimals, it cannot correctly determine the number of frames (although perhaps there is another reason for the inaccuracy). To get around this issue I have been serially calling clip.read_frame until I reach the end of the video. This seems the safest way to ensure I don't miss frame, as even if the above framework did produce the correct estimate of frame number, I am concerned precision errors could lead the same frame to be called twice.

It would be great if clip.read_frame produced a flag, in addition to the frame, that tells whether or not the end of the video has been reached. This would allow users to simply check this flag to know whether they've reached the end of the video. Currently it just returns the last read frame in line 141 of ffmpeg_reader.py:

>result = self.lastread

Thanks,
Rick

**Comment by mattkahl** [comment]
I hope come back to this and provide more information, but I just wanted to add that I am also experiencing an off-by-one problem with the number of frames that `item_frames` returns. In my case, the frame rate (30 fps)  and frame count (451) are **much** lower.

**Comment by eigenbrot** [comment]
I have solved this problem by checking for a condition where `iter_frames` will be off by one and adjusting `self.duration` accordingly:
```
duration = SOMETHING
fps = SOMETHING
iter_nframes = np.arange(0, duration, 1.0 / fsp).size
wanted_nframes = int(duration * fps)
while iter_nframes > wanted_nframes:
    duration -= 1. / fps
    iter_nframes = np.arange(0, duration, 1.0 / fps).size
```
Then the new modified `duration` value is what I pass to moviepy objects. In my experience I've never seen the need to remove more than one frame's worth of duration to get this to work.

I've been trying to think of an alternative way to actually fix the `iter_frames` function, but this check is the best I can think of. One other possibility would be to use `np.linspace(0, duration, self.duration * fps)`, but then the same problem just manifests in the time steps being slightly off of what `1/fps` would suggest.

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.

Besides it looks like the last comment provided a potential solution.
