### ISSUE TITLE
Missing 'ffmpeg-win32-v3.2.4.exe'

### ISSUE THREAD

**Issue by DecaK** [Zulko/moviepy#821]
I tried to download moviepy by 'pip install moviepy', and there's no problem in cmd. When I execute program, Python start to download 'ffmpeg-win32-v3.2.4.exe', but download speed is about 10 bytes/second and I dont know why. How can I manually download ffmpeg and where should it be placed?

**Comment by DecaK** [comment]
I leave my computer whole night to download it, but when it come to 30%, it just restart IDLE and start downloading again...

**Comment by tburrows13** [comment]
I’ve had problems running moviepy through idle before. Try it through your system shell (type `python3` into the command line). Let me know if you have more questions.

**Comment by DecaK** [comment]
I let IDLE download it, and download was finally complete in ~5h. Probably was IDLE problem. Weird.

**Comment by tburrows13** [comment]
When I used to use IDLE, the writing of a video to a file would slow down until it was barely doing anything. I would stay away from IDLE if you can.
