### ISSUE TITLE
How to add audio tracks. not to replace it.

### ISSUE THREAD

**Issue by MuddyW** [Zulko/moviepy#822]
'clip.audio = audio'
'set_audio'
running these will just make my audio in original video disappear.
I want to add extra audio tracks to the video without replacing the original one.
How to do that?

**Comment by tburrows13** [comment]
https://stackoverflow.com/questions/41992335/mixing-audio-files-in-moviepy/42030489#42030489 answers this question.

**Comment by MuddyW** [comment]
Thanks.
