### ISSUE TITLE
Issue regarding findObjects() on the letter 'i'.

### ISSUE THREAD

**Issue by komjum6** [Zulko/moviepy#825]
### Expected Behavior
findObjects() should have worked on the letter 'i'.

### Actual Behavior
It showed nothing or the letters accompanying the letter 'i'.

My hypothesis is that it somehow sees the letter 'i' as two objects, which confuses the function.

### Steps to Reproduce the Problem
Use findObjects() on the letter 'i'.

### Specifications

  - Python Version: 3.6.4
  - Moviepy Version: 0.2
  - Platform Name: Windows
  - Platform Version: 10

EDIT: I found that the letter 'T' in papyrus also doesn't work. Above example used Amiri-Bold.

**Comment by keikoro** [comment]
We'd need to see some of your code to try to reproduce the problem. Closing this since it's an old issue, but feel free to reopen it with code samples if the problem persists.

**Comment by juliosouto** [comment]
I just found out the same issue. I worked on an algorithm to find the letters, sort them out according to the text I wrote, then change the color of specific letters or words. For some reason the letter "i" never appears as an image and I can't change their colors.
