### ISSUE TITLE
MoviePy doesn't see videos!

### ISSUE THREAD

**Issue by neurvanna** [Zulko/moviepy#830]
### Expected Behavior

Sample video displayed.

### Actual Behavior

OSError: MoviePy error: the file SampleVideo_1280x720_1mb.mp4 could not be found!
Please check that you entered the correct path.

### Steps to Reproduce the Problem

I have just installed a new version of moviepy and FFMPEG. 
I put a couple of sample video clips in the folder where I run python, but moviepy can't play any of them.
I tried multiple videos and I tried specifying the full path. Doesn't work.

python 
from moviepy.editor import*
clip = VideoFileClip("SampleVideo_1280x720_1mb.mp4").rotate(180)
clip.ipython_display(width = 280)

### Specifications

  - Python Version: 3.5.4
  - Moviepy Version: 0.2.3.5
  - Platform Name: Windows
  - Platform Version: 7

**Comment by raj6996** [comment]
G:\moviepy-master>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\moviepy-master\moviepy\editor.py", line 31, in <module>
    from .video.io.downloader import download_webfile
  File "G:\moviepy-master\moviepy\video\io\downloader.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>> video = VideoFileClip("M.mp4").subclip(50,60)

https://github.com/Zulko/moviepy/issues/832

**Comment by qingfenghcy** [comment]
I have the same problem. Have you solved it?

**Comment by qingfenghcy** [comment]
I have solved the problem, reinstall ffmpeg can solve it.
