### ISSUE TITLE
File "<stdin>", line 1 error

### ISSUE THREAD

**Issue by raj6996** [Zulko/moviepy#832]
### Expected Behavior
from moviepy.editor import

### Actual Behavior
G:\moviepy-master>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
>>> from moviepy.editor import
  File "<stdin>", line 1
    from moviepy.editor import
                             ^
SyntaxError: invalid syntax
>>>

### Specifications

  - Python Version: 3.7.0
  - Moviepy Version: Latest v0.2.3.5
  - Platform Name:Windows 10 Pro
  - Platform Version: 2017

**Comment by tburrows13** [comment]
You’re missing the `*` character. It should be `from moviepy.editor import *` or specify something specific to import.

PS you don’t need to run `imageio.plugins.ffmpeg.download()` anymore; moviepy does it automatically.

**Comment by raj6996** [comment]
G:\moviepy-master>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\moviepy-master\moviepy\editor.py", line 31, in <module>
    from .video.io.downloader import download_webfile
  File "G:\moviepy-master\moviepy\video\io\downloader.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>
I installed everything and variable path, can't figure out how to solve this error. thanks.

**Comment by raj6996** [comment]
G:\moviepy-master>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\moviepy-master\moviepy\editor.py", line 31, in <module>
    from .video.io.downloader import download_webfile
  File "G:\moviepy-master\moviepy\video\io\downloader.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>> video = VideoFileClip("M.mp4").subclip(50,60)

### Specifications
  - Python Version: 3.7.0
  - Moviepy Version: Latest v0.2.3.5
  - Platform Name:Windows 10 Pro
  - Platform Version: 2017
