### ISSUE TITLE
Videogrep can't works with Moviepy in Windows

### ISSUE THREAD

**Issue by raj6996** [Zulko/moviepy#834]
Kindly read it carefully>https://github.com/antiboredom/videogrep/issues/57
Maybe I need to discuss on that forum as I already opened.
### Expected Behavior
https://github.com/Zulko/moviepy/issues/832

### Actual Behavior
G:\moviepy-master>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

            from moviepy.editor import *
            Traceback (most recent call last):
            File "", line 1, in
            File "G:\moviepy-master\moviepy\editor.py", line 31, in
            from .video.io.downloader import download_webfile
            File "G:\moviepy-master\moviepy\video\io\downloader.py", line 7, in
            import requests
            ModuleNotFoundError: No module named 'requests'
            video = VideoFileClip("M.mp4").subclip(50,60)

sorry for making duplicate issue (as mods closed forever), I still can't figure out as I use first ever this python and moviepy.
I want to use videogrep script, but after I read thoroughly on videogrep, I figure out to run moviepy or learn it. but I got error after following step by step either from youtube or  https://stackoverflow.com, but 
no solution found for me. Kindly don't close asap until I solved properly.

### Specifications

  - Python Version: 3.7.0
  - Moviepy Version: v0.2.3.5
  - Platform Name: Windows
  - Platform Version: 10 pro

**Comment by tburrows13** [comment]
Run `pip3 install requests` :)

**Comment by raj6996** [comment]
finally moviepy works for me, no error! thanks man. I closed it now.
