### ISSUE TITLE
get_frame(tstamp) does not return accurate frame seeking

### ISSUE THREAD

**Issue by gregchu** [Zulko/moviepy#835]
I'm attempting to use the `get_frame(tstamp)` to seek to a specific frame and am testing the accuracy of the frame seeking. I first iterate over every frame and stop at an arbitrary frame, grab the frame and timestamp, then create a new VideoFileClip obj with the same URL, and use `get_frame` to seek to the previous timestamp. The two frames do not match up exactly. I subtract the two images and measure the pixel value differences.

OpenCV's video capture has a similar problem (https://github.com/opencv/opencv/issues/9053)

### Expected Behavior
```
import sys
import numpy as np
import cv2
import pytest
import moviepy.editor as mpy

def test_frame_seek_moviepy():
    video_url = "https://s3.amazonaws.com/temp-bug/movie.mp4"
    arbitrary_frame_nr = 1200
    vid = mpy.VideoFileClip(video_url)
    src_tstamp = 0
    src_frame = None
    for i, (tstamp, frame) in enumerate(vid.iter_frames(with_times=True)):
        if i >= arbitrary_frame_nr:
            src_tstamp = tstamp
            src_frame = frame
            print("breaking at tstamp: {}".format(src_tstamp))
            break

    vid2 = mpy.VideoFileClip(video_url)
    print("measuring against get_frame({})".format(src_tstamp))
    frame = vid2.get_frame(src_tstamp)
    pixel_diff = np.sum(frame-src_frame)
    print("{}==0 ? : {}".format(pixel_diff, pixel_diff==0))
    #cv2.imshow('src', src_frame) #for debugging
    #cv2.imshow('seek', frame)
    #cv2.waitKey(0)

```
Output:
```
breaking at tstamp: 40.10695187165775
measuring against get_frame(40.10695187165775)
0==0 ? : True
```
### Actual Behavior

Output:
```
breaking at tstamp: 40.10695187165775
measuring against get_frame(40.10695187165775)
131060698==0 ? : False
```

### Steps to Reproduce the Problem

See above code snippet.

### Specifications

  - Python Version: 3.5
  - Moviepy Version: 0.2.3.5
  - Platform Name: Ubuntu 
  - Platform Version: 16.04
  - ffmpeg Version: 2.8.14-0ubuntu0.16.04.1 built with gcc 5.4.0
  - OpenCV Version: 3.3.0-rc

**Comment by keikoro** [comment]
Closing this issue as it's old and based on an old MoviePy version, so impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
