### ISSUE TITLE
ffmpeg_reader has problem getting duration of videos > 100 hours long. 

### ISSUE THREAD

**Issue by jaic231** [Zulko/moviepy#838]
### Expected Behavior
When making a VideoFileClip object, clip.duration should return the correct duration of the video in seconds. 
### Actual Behavior
However, if the video is over 100 hours long, the regular expression on line 286 (ffmpeg_reader.py) only reads the last 2 digits of the duration string. 

### Steps to Reproduce the Problem

```
from moviepy.editor import VideoFileClip
clip = VideoFileClip(some_video)
print(clip.duration)
# if the duration of the video is > 99:99:99.99 then the duration will be incorrect!
# in order to fix this, simply change line 286 from 
# match = re.findall("([0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
# to
# match = re.findall("([0-9]+:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
# thanks!
```

### Specifications

  - Python Version: 3.6
  - Moviepy Version:0.2.3.5
  - Platform Name: Ubuntu 
  - Platform Version: 18.06

**Comment by keikoro** [comment]
Closing this issue as it's old and based on an old MoviePy version, so impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
