### ISSUE TITLE
get video and audio bitrates

### ISSUE THREAD

**Issue by jinyus** [Zulko/moviepy#843]
How do I get the bitrates of the input video files? I would like to export the video with the same bitrates of the original file.

**Comment by crazyxw** [comment]
I also had this problem.

**Comment by crazyxw** [comment]
This problem has been solved in [my PR](https://github.com/Zulko/moviepy/pull/930)

**Comment by keikoro** [comment]
Closing this based on the above answer referencing #930

**Comment by ratannahn1** [comment]
Its not working as of now
I tried this:
videoclip = VideoFileClip(fname)
b = videoclip.video_bitrate

**Comment by keikoro** [comment]
Please open a new issue instead of commenting on this old, closed one. You can always reference other existing issues by using hashtag + issue number.
