### ISSUE TITLE
Preview, show and concatenate_videoclips documentation?

### ISSUE THREAD

**Issue by chuski1212** [Zulko/moviepy#844]
Where is the Preview, show and concatenate_videoclips documentation? I can't find it

**Comment by tburrows13** [comment]
Rather late, but for future reference:

[preview and show](https://zulko.github.io/moviepy/getting_started/efficient_moviepy.html?highlight=preview#clip-show-and-clip-preview)
[concatenate_videoclips](https://http://zulko.github.io/moviepy/getting_started/compositing.html?highlight=concatenate#stacking-and-concatenating-clips)

Definitely could be easier to find though.
