### ISSUE TITLE
simple problem on the first step: importing moviepy.editor

### ISSUE THREAD

**Issue by fitipe** [Zulko/moviepy#852]
hi there!

I'm new to python ( and to any programming languages, actually ). but I'd really like to learn ( already taking online lessons and following tutorials here and there ).

I'm inside a video-art project and would like to create a simple program to edit videos randomly. or, when and if I get the skills for it, a machine learning program which would have reasons to chose one video from another. anyways, that's future. 

the present is:

I found this wonderful package that is probably gonna help me a lot into this process. I installed it through pip and tried to do as the first example tutorial says - "from moviepy.editor import *" ( so I should be able to use its commands through python, right? )

but when I do so ( and I tried many times ) I allways get the same:

" Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from moviepy.editor import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/editor.py", line 31, in <module>
    from .video.io.downloader import download_webfile
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/downloader.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests' "

I tried it running Python 3.6.5 on its IDLE shell, on a Jupyter Notebook and also on the terminal. the return is allways the same ... do someone know what I shoul do?

thanks a lot!!

![captura de tela 2018-09-24 as 21 11 58](https://user-images.githubusercontent.com/39530456/45986301-0f7c1f00-c041-11e8-9aa4-dad1fb8d73c6.png)

**Comment by Zulko** [comment]
Sorry it is an issue with the current version. The error you see means that you should install the "requests" library. It must be installed the same way you installed moviepy, I am not sure which method you used. Once requests is installed it should work.

**Comment by fitipe** [comment]
hi zulko,
thanks a lot for the quick answer!

I installed moviepy simply writing "pip install moviepy" on the terminal. how would you recomend me to install the "requests" library?

**Comment by Zulko** [comment]
``pip install requests`` ;)

**Comment by fitipe** [comment]
thanks! hahaha
I'll try that out :)

**Comment by fitipe** [comment]
woooorks! thanks a lot :))

but now I got stuck in something else, lol
when I try to use VideoFileClip, I get this:

" ---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-2aa9cd5d991e> in <module>()
----> 1 clip = VideoFileClip("6.mov").rotate(180)
      2 clip.ipython_display(width=500)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py in __init__(self, filename, has_mask, audio, audio_buffersize, target_resolution, resize_algorithm, audio_fps, audio_nbytes, verbose, fps_source)
     89                                          target_resolution=target_resolution,
     90                                          resize_algo=resize_algorithm,
---> 91                                          fps_source=fps_source)
     92 
     93         # Make some of the reader's attributes accessible from the clip

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py in __init__(self, filename, print_infos, bufsize, pix_fmt, check_duration, target_resolution, resize_algo, fps_source)
     31         self.proc = None
     32         infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
---> 33                                    fps_source)
     34         self.fps = infos['video_fps']
     35         self.size = infos['video_size']

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    258     proc.stdout.readline()
    259     proc.terminate()
--> 260     infos = proc.stderr.read().decode('utf8')
    261     del proc
    262 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 2162: invalid start byte

 "

**Comment by keikoro** [comment]
@fitipe I'm going to close this issue as the original question got solved. Please open a new issue if the problem described later on persists and it's not already being discussed in another open issue.

**Comment by dionathantborges** [comment]
Hello
I have a similar problem, but with a different error message.

I tried to install the "request" but was unsuccessful


>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from moviepy.editor import *
  File "C:\PYTHON\lib\site-packages\moviepy\editor.py", line 24, in <module>
    import imageio
  File "C:\PYTHON\lib\site-packages\imageio\__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "C:\PYTHON\lib\site-packages\imageio\core\__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "C:\PYTHON\lib\site-packages\imageio\core\util.py", line 19, in <module>
    import numpy as np
  File "C:\PYTHON\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\PYTHON\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\PYTHON\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by tburrows13** [comment]
@dionathantborges, that is an issues with numpy, not moviepy. Did you try to follow the link and see what was suggested there?

**Comment by WachasWps** [comment]
Traceback (most recent call last):
  File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\app2.py", line 6, in <module>
    from moviepy.editor import VideoFileClip, AudioFileClip
ModuleNotFoundError: No module named 'moviepy.editor'


I am getting this issue

**Comment by tburrows13** [comment]
> Traceback (most recent call last): File "C:\Users\wacha\OneDrive\Desktop\Storage\avatar wav2lip\app2.py", line 6, in from moviepy.editor import VideoFileClip, AudioFileClip ModuleNotFoundError: No module named 'moviepy.editor'
> 
> I am getting this issue

https://github.com/Zulko/moviepy/issues/2240
moviepy.editor doesn’t exist in 2.0.

**Comment by AbouAnesY** [comment]
### 

> 

> 

> [`__`](`[url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url]([url](url)))))))))))))))))`)

[ ] @ ### [**#/[](url)**]([url]([url](`url`)))
