### ISSUE TITLE
Silence parts cut/extract from movies/clips?

### ISSUE THREAD

**Issue by raj6996** [Zulko/moviepy#854]
Is there anyway cut/extract silence Silence (Actually speechless scenes) parts from movies or clips using moviepy.
I am total novice with CLI based moviepy. thanks.
### Specifications

  - Python Version: 64bit 3.7.0
  - Moviepy Version: Latest
  - Platform Name: Windows
  - Platform Version: 10 Pro

**Comment by keikoro** [comment]
I suppose you were asking if MoviePy can _detect_ (and subsequently remove) silence, in which case I would suggest the answer is no? Feel free to reopen the issue if you find anything in the docs that suggests otherwise.
