### ISSUE TITLE
Even after commenting out that one line in /etc/ImageMagick-6/policy.xml, I still get "that" error.

### ISSUE THREAD

**Issue by neatville** [Zulko/moviepy#855]
It's more or less the same issue as #693. The line of code that triggers it:  
`txt_clip = TextClip("example", fontsize=50,color='white')`  
Error summary:
```
OSError: convert-im6.q16: not authorized `@/tmp/tmpxnbqj8cq.txt' @ error/property.c/InterpretImageProperties/3516.
convert-im6.q16: no images defined `PNG32:/tmp/tmpblh_ia5s.png' @ error/convert.c/ConvertImageCommand/3258.
```
My system is a ubuntu derivative. I installed ImageMagick from the Ubuntu repositories with apt-get. It made me wonder if any cache would need to get cleared somehow, but I still got this error after a system reboot.  
If this makes any difference, `print(get_setting("FFMPEG_BINARY")` gives me this: `/home/me/.imageio/ffmpeg/ffmpeg-linux64-v3.3.1`, and `which convert` returned a positive result.

**Comment by Rub21** [comment]
I am using moviepy and  ImageMagick  in docker, I get the same error after commenting the line

**Comment by keikoro** [comment]
Closing this issue as it's rather old and missing info we require now via the issue template.

The docker issue was apparently addresssed in #1165 (in case it persists, please open a new issue, thanks).
