### ISSUE TITLE
The last frame in iter_frames doubles, creating another redundant one.

### ISSUE THREAD

**Issue by oltodosel** [Zulko/moviepy#857]
```python
print(len([frame for frame in VideoFileClip('z.mkv').iter_frames()]))
```
Shows actual number of frames+1
The last frame in iteration is identical to the one before it.

`ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 z.mkv`

### Specifications

  - Python Version: 3.7.0
  - Moviepy Version: python-moviepy 0.2.3.5-1
  - Platform Name: Linux
  - Platform Version:  4.18.12-arch1-1-ARCH x86_64

**Comment by keikoro** [comment]
It's unclear to me what the issue was/is, please feel free to reopen it following the issue template, thanks.
