### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by boyunli** [Zulko/moviepy#858]
### Specifications

  - Python Version:
  - Moviepy Version:
  - Platform Name:
  - Platform Version:

**Comment by boyunli** [comment]
when I run `video = mp.VideoFileClip('test.mp4')`
then will raise a exception:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-9fff6170af5e> in <module>
----> 1 video = mp.VideoFileClip('test.mp4')

~/.virtualenvs/video_post/lib/python3.5/site-packages/moviepy/video/io/VideoFileClip.py in __init__(self, filename, has_mask, audio, audio_buffersize, target_resolution, resize_algorithm, audio_fps, audio_nbytes, verbose, fps_source)
     89                                          target_resolution=target_resolution,
     90                                          resize_algo=resize_algorithm,
---> 91                                          fps_source=fps_source)
     92 
     93         # Make some of the reader's attributes accessible from the clip

~/.virtualenvs/video_post/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py in __init__(self, filename, print_infos, bufsize, pix_fmt, check_duration, target_resolution, resize_algo, fps_source)
     31         self.proc = None
     32         infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
---> 33                                    fps_source)
     34         self.fps = infos['video_fps']
     35         self.size = infos['video_size']

~/.virtualenvs/video_post/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    267 
    268     lines = infos.splitlines()
--> 269     if "No such file or directory" in lines[-1]:
    270         raise IOError(("MoviePy error: the file %s could not be found!\n"
    271                       "Please check that you entered the correct "

IndexError: list index out of range
```
I am sure the file exists，I have install FFMPEG manually again, Still reporting same error

when I run `ffmpeg -i test.mp4`
```
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: 
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2018-10-05T03:23:03.000000Z
  Duration: 00:00:10.00, start: 0.000000, bitrate: 1890 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x544, 1628 kb/s, 25 fps, 25 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2018-10-05T03:23:03.000000Z
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2018-10-05T03:23:03.000000Z
      handler_name    : Core Media Audio
```
My Development environment：
Python Version:  3.5
Moviepy Version:  0.2.3.5
ffmpeg Version:  4.0.2
Platform Name: ubuntu
Platform Version: 16.04

**Comment by Smekac** [comment]
I have same problem !!

**Comment by lucasguerreiro** [comment]
I have the same problem when running `video = mp.VideoFileClip('test.mp4')`
I am running it on a Kubernetes Engine and it returns the following traceback:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 287, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range`

**Comment by consciousgaze** [comment]
I have the same problem!

> Traceback (most recent call last):
>   File "/home/hollyworrier/.local/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
>     line = [l for l in lines if keyword in l][index]
> IndexError: list index out of range

**Comment by Dipesh79** [comment]
> I have the same problem when running `video = mp.VideoFileClip('test.mp4')`
> I am running it on a Kubernetes Engine and it returns the following traceback:
> 
> `Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 287, in ffmpeg_parse_infos line = [l for l in lines if keyword in l][index] IndexError: list index out of range`

**Comment by Mafin-dev** [comment]
@tburrows13 closed this thread but it is not fixed? Wait what? I did a clean install today and still got the problem.

**Comment by tburrows13** [comment]
#1195 (which presumably fixes it) isn't in a stable release yet. Can you replicate it in v2.0.0.dev2?

**Comment by Mafin-dev** [comment]
> #1195 (which presumably fixes it) isn't in a stable release yet. Can you replicate it in v2.0.0.dev2?

lol. U fast boiii. I upgraded to v2.0.0.dev2 and tried again. It works now. It fixes the problem. N1ce! 10/10

**Comment by tburrows13** [comment]
Great! We close threads when they've been fixed even if the fix isn't pip-installable yet. This is an unusually long wait in-between stable versions :)

**Comment by Ahmedk-n** [comment]
> File "C:\Users\dipes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 285, in ffmpeg_parse_infos line = [l for l in lines if keyword in l][index] IndexError: list index out of range

I have the same issue!

**Comment by LiamGallagher737** [comment]
> `Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 287, in ffmpeg_parse_infos line = [l for l in lines if keyword in l][index] IndexError: list index out of range`

Also having this issue

**Comment by ImNitro** [comment]
Am still having this issue
