### ISSUE TITLE
Handling of the ffmpeg dependency

### ISSUE THREAD

**Issue by superseed** [Zulko/moviepy#859]
I just started using this package, trying out [an example from a blog post](http://zulko.github.io/blog/2014/09/20/vector-animations-with-python/) that uses both **Gizeh** and **MoviePy**.

When I executed the first example, a download started for **ffmpeg**, followed by an error about the **requests** package missing from the env. This second problem seems to have been resolved with 006b376 however (though I would suggest to use **urllib** from the standard lib for this single HTTP request to avoid a new dependency, but that's not the point of the issue).

The thing is that I do have ffmpeg installed and up-to-date and getting a binary downloaded in my home dir without asking feels wrong to me. I would have preferred the application to error out on not finding the binary. I looked at the `README` in the repo and saw that I could set the binary location in `config_defaults.py`, so I tried that but it didn't change anything (i.e. it kept downloading ffmpeg). I looked around the code to find that since b8fcf45, the environment variable `FFMPEG_BINARY` is checked on import of `editor.py` and if unset or equal to `ffmpeg-imageio`, is downloaded through **imageio**'s primitives.

I see three problems with this approach:
- It checks _the environment variable_ `FFMPEG_BINARY` instead of the global python variable defined in `config_defaults.py`, which is unwieldy anyway since it's a build-time conf (aka a 'sneaky edit in the `lib/python*` directory' type of conf). However note that setting the environment variable to the binary's path before using the package does work! It's just kinda undocumented.
- It doesn't really check for ffmpeg by itself, which is the bigger pain point.
- When it doesn't find it, it tries downloading it by itself.

There a few potential solutions:
- Keep things this way and document the need to set the environment variable, maybe homogenize the behavior by using the environment var everywhere else
- Check the variable set in `config_defaults.py` instead of the environment variable
- Allow for a runtime configuration file somehow
- Actually check for a valid ffmpeg binary. To me this is the better solution: it can be done easily -- check if it is available in the PATH with `shutil.which('ffmpeg')`, possibly `subprocess.run()` it to get the version number and check compatibility. If it's not found, two possibilities:
  - Download it to the homedir automatically (and get frowned upon by me :smile:)
  - Error out with a warning and handy tips for the user. Possibly with a lot of user-friendliness, e.g. ship a little script with the MoviePy package linked to a `console_scripts` entry in `setup.py` to setup the needed dependencies.

Does any of this sound reasonable? I could send a PR your way if you think it could be useful.

(This package and Gizeh are really good, by the way! :tada:)

**Comment by tburrows13** [comment]
It is all rolled into `imageio_ffmpeg` now, so hopefully not an issue.
