### ISSUE TITLE
suppress ffmpeg warnings in ipython notebook

### ISSUE THREAD

**Issue by reidoda** [Zulko/moviepy#86]
I'm getting output that looks like what's below when I write a movie file to disk. I've tried setting verbose to false. How can I suppress this? 

```
|####------| 584/1197  48% [elapsed: 00:45 left: 00:47, 12.79 iters/sec]Warning: in file /Users/roda/Documents/REFERENCE/000_ACTIVE/gopro_mountain_biking_footage/02_clips/02_start_race.mp4, 2764800 bytes wanted but 0 bytes read,at frame 247/249, at time 4.12/4.14 sec. Using the last valid frame instead.
|#####-----| 710/1197  59% [elapsed: 00:58 left: 00:40, 12.15 iters/sec]Warning: in file /Users/roda/Documents/REFERENCE/000_ACTIVE/gopro_mountain_biking_footage/02_clips/03_start_of_run.mp4, 2764800 bytes wanted but 0 bytes read,at frame 318/320, at time 5.31/5.33 sec. Using the last valid frame instead.
```

**Comment by roddicki** [comment]
I'm having a similar issue, with similar warnings - hoping you might be able to help:
```
WARNING:py.warnings:/Library/Python/2.7/site-packages/moviepy/video/io/ffmpeg_reader.py:116:     UserWarning: Warning: in file /Users/admin/Sites/repos/ramm1.8/videos/videocliplibrary/0whole/pan-super-detail.mp4, 6220800 bytes wanted but 0 bytes read,at frame 3417/3419, at time 114.01/114.05 sec. Using the last valid frame instead.
  UserWarning)
```
Is there a recommended codec or particular video export settings that can format the file so that moviepy / ffmpeg likes it?

**Comment by keikoro** [comment]
This is a very old issue which hasn't seen any updates in years, so it's dubious/impossible to tell if it's still relevant.

Closing for this reason, but do report back if the issue persists when you try with the latest master (_not_ the last PyPI release).

**Comment by AM-ash-OR-AM-I** [comment]
> This is a very old issue which hasn't seen any updates in years, so it's dubious/impossible to tell if it's still relevant.
> 
> Closing for this reason, but do report back if the issue persists when you try with the latest master (_not_ the last PyPI release).

Still facing the same issue even after using latest master branch, any solution?
