### ISSUE TITLE
Create subclips from edit points

### ISSUE THREAD

**Issue by russellaugust** [Zulko/moviepy#870]
I'm looking for a way to take a video clip and create subclips at edit points.  So if there's an edit in the visual, then it creates a subclip.  I know that avid and resolve can do this, and i believe it's just looking for extreme difference between frames A and B.  

Any way to do this in moviepy?  I'd love to keep it within this library, but definitely willing to hear other ways to do it.

**Comment by ishandutta2007** [comment]
well there is a  [cutout](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html?highlight=cutout#moviepy.video.io.VideoFileClip.VideoFileClip.cutout
) API .
I agree we should have a reverse API ie keep the cup part and discard the rest. currently to keep between (t1, t2) . I am doing concatinate(cutout(0,t1) , cutout(t2, video_duration))

**Comment by ishandutta2007** [comment]
Oh My mistake there is [subclip](https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html?highlight=subclip#moviepy.video.io.VideoFileClip.VideoFileClip.subclip) API as well
`subclip = vidio_clip.subclip(t_start=6, t_end=9)`

**Comment by tburrows13** [comment]
I believe that @russellaugust is actually looking for `detect_scenes()` https://github.com/Zulko/moviepy/blob/8d14ef94b384b062a1c08400ecf66b475ca46891/moviepy/video/tools/cuts.py#L290
