### ISSUE TITLE
How do you run a single unit test?

### ISSUE THREAD

**Issue by ishandutta2007** [Zulko/moviepy#872]
How do you run a single unit test.
I am trying to contribute to this repo, to get started I can't follow how to run individual tests.
None of the tricks mentioned here seems to work:
https://stackoverflow.com/questions/21167516/does-unittest-allow-single-case-suite-testing-through-setup-py-test

**Comment by ishandutta2007** [comment]
something like `python setup.py test -a tests.test_fx.py ` works but that's still full file, I want to run a single test function.

**Comment by declension** [comment]
@ishandutta2007 you can use [Pytest's syntax for this](https://docs.pytest.org/en/latest/usage.html#nodeids), e.g. 

```bash
pytest tests/test_fx.py::test_blackwhite
```
