### ISSUE TITLE
TextClip positioning does not work

### ISSUE THREAD

**Issue by TowelDude** [Zulko/moviepy#886]
I have written the following function to add a timestamp to a video:
```

def stamp_clip(clip, start_t=0):
    clips = []
    for x in range(int(clip.duration)):
        txtclip = TextClip(str(timedelta(seconds=x + start_t)),
                           font='Arial-Black', fontsize=50, stroke_color='black', stroke_width=2, color='white')

        txtclip.duration = 1
        txtclip.set_position((100, 200))
        sub = clip.subclip(x, x+1)
        # clip.add_mask()
        comp = CompositeVideoClip([sub, txtclip])
        comp.duration = 1
        clips.append(comp)

    return concatenate_videoclips(clips)

```

### Expected Behavior
A time stamp will appear at `(100,200)`.

### Actual Behavior
The timestamp does not move.

I have tried many overloads of this function `"center","right"`, `0.2,0.5` etc.  and nothing worked

### Steps to Reproduce the Problem
The function above.

### Specifications

  - Python Version: 2.7.15
  - Moviepy Version: 0.2.3.5
  - Platform Name: Windows 
  - Platform Version: 10

**Comment by TowelDude** [comment]
Update:

Changing the line:
```
  txtclip = TextClip(str(timedelta(seconds=x + start_t)),
                           font='Arial-Black', fontsize=50, stroke_color='black', stroke_width=2, color='white')
```

To the following:


```
  txtclip = TextClip(str(timedelta(seconds=x + start_t)),
                           font=font, fontsize=font_size, color='white', stroke_color='black', stroke_width=1) \
                           .set_duration(1) \
                           .set_pos(('left', 'bottom'))
```

and, of course, removing redundant rows, solves the issue. 

I really have no idea what caused the issue, but the solution might give some hints for where the bug is.

Cheers

**Comment by Sv3n** [comment]
All functions that have an `@outplace` decorator return a new modified clip, so you need to store their return value. See: https://zulko.github.io/moviepy/getting_started/effects.html for some documentation on this behavior.

**Comment by Zulko** [comment]
Sorry for the confusion, I understand that "with_duration", "with_position" would have been better names than "set_duration", "set_pos", to indicate that the transformations are not in-place, but hey I was young at the time.

**Comment by c4llous** [comment]
the correct syntax will be txt.clip((100,200))
