### ISSUE TITLE
os.getenv('FFMPEG_BINARY') is looked up at two locations

### ISSUE THREAD

**Issue by yurivict** [Zulko/moviepy#888]
Settings are driven by:
https://github.com/Zulko/moviepy/blob/master/moviepy/config_defaults.py#L53

But then there is another ad-hoc lookup here:
https://github.com/Zulko/moviepy/blob/master/moviepy/editor.py#L25

It seems that the second place should use ```get_setting("FFMPEG_BINARY")``` instead.

**Comment by tburrows13** [comment]
Obsolete by #1109.
