### ISSUE TITLE
[0.2.4.0] Garbled audio when exporting mp3 from mp4?

### ISSUE THREAD

**Issue by MaZZly** [Zulko/moviepy#891]
### Expected Behavior
Audio extracted to mp3 should sound like in video

### Actual Behavior
Low volume and weird sounds.
Video: https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4
Extracted audio: https://www.dropbox.com/s/czytk0pudmn4xj7/bad-audio.mp3?dl=1

### Steps to Reproduce the Problem

```python
with VideoFileClip('big_buck_bunny_720p_30mb.mp4') as clip:
   clip.audio.write_audiofile('out.mp3')
``` 

### Specifications

  - Python Version: 2.7.12
  - Moviepy Version: 0.2.4.0
  - Platform Name: Ubuntu
  - Platform Version: 18.04

**Comment by MaZZly** [comment]
Does not happen on 0.2.3.5

**Comment by MaZZly** [comment]
Same thing also happens if opening a working mp3 as  `AudioFileClip` and doing `write_audiofile()`

**Comment by Zulko** [comment]
Yes it is the same system at play.

What happened here is that Numpy was throwing warnings that "np.fromstring" is deprecated and should be replaced by "np.frombuffer" when converting a blob to an array. I must have broken something in the convertion.
