### ISSUE TITLE
Transition of postion lost while trying to concatinate two TextClips

### ISSUE THREAD

**Issue by ishandutta2007** [Zulko/moviepy#904]
If I do the following I loose the transition that I created in each `TextClip` with `lambda t: (20-20*(t-1)` 

```
txt_clip = TextClip(name.title(), fontsize=title_font_size, color=text_col)\
                       .set_position(lambda t: (20-20*(t-1), 'top'))\
                       .set_duration(5)
txt_clip2 = TextClip(caption.title(), fontsize=caption_font_size, color=text_col)\
                       .set_position(lambda t: (20-20*(t-1), 'top'))\
                       .set_duration(5)
txt_clips = concatenate([txt_clip, txt_clip2], method="chain")
image_clip = CompositeVideoClip([image_clip, txt_clips])
```
I tried concatinating with `method="compose"` too.

if I just compose video clip with just one text_clip ie either `txt_clip` or `txt_clip2`, the transition is preserved. 

` image_clip = CompositeVideoClip([image_clip, txt_clip2])`

**Comment by petargyurov** [comment]
A year later, I am facing the same issue 😢

**Comment by keikoro** [comment]
Closing this issue as it's missing information/specs we ask for when creating new issues.

Do report back – following our issue templates – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
