### ISSUE TITLE
Segmentation Error on VPS

### ISSUE THREAD

**Issue by zilton7** [Zulko/moviepy#912]
Hey,
I get segmentation error every time I import moviepy.editor on my ubuntu 16 VPS
any ideas?

**Comment by Zulko** [comment]
Is it something that didnt happen before but happens now or is it your first use ? Can you post a pip freeze showing what else is installed? (could be pygame)

**Comment by zilton7** [comment]
first time running. 
Pip freeze:

```
cachetools==2.1.0
certifi==2018.8.24
chardet==3.0.4
click==6.7
decorator==4.3.0
Flask==1.0.2
google-api-python-client==1.7.4
google-auth==1.5.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
httplib2==0.11.3
idna==2.7
imageio==2.3.0
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
moviepy==0.2.3.5
MyApplication==0.1.0
numpy==1.15.1
oauth2client==4.1.2
oauthlib==2.1.0
opencv-python==3.4.2.17
Pillow==5.4.1
progressbar2==3.38.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycurl==7.43.0
pygobject==3.20.0
python-apt==1.1.0b1+ubuntu0.16.4.2
python-utils==2.3.0
pytube==9.2.2
requests==2.19.1
requests-oauthlib==1.0.0
rsa==3.4.2
six==1.11.0
tqdm==4.25.0
unattended-upgrades==0.1
uritemplate==3.0.0
urllib3==1.23
Werkzeug==0.14.1
```

**Comment by Zulko** [comment]
Can you "pip install --upgrade moviepy" to the latest version and see if you still have the problem. Which python version are you using ?

**Comment by zilton7** [comment]
I still get it after updating. I am using python 3.7

**Comment by zilton7** [comment]
sorry for that

**Comment by zilton7** [comment]
the same script works flawlessly on my mac, but not VPS...

**Comment by zilton7** [comment]
upgrading and reinstalling VPS fixed the issue
