### ISSUE TITLE
Format error while reading video file

### ISSUE THREAD

**Issue by Flock1** [Zulko/moviepy#913]
I am trying to run a video and process it through a CNN. I even ran ```ffmpeg <path/to/video>``` and it ran the video. I have written the following code:
```
clip = VideoFileClip(video_file)
video_clip = clip.fl_image(process_vid)
video_clip.write_videofile(output_vid2)
````
I get the error in line ```clip = VideoFileClip(video_file)```
### Expected Behavior
It's supposed to save the processed video.

### Actual Behavior
The error:
`OSError: [Errno 8] Exec format error
`
### Specifications

  - Python Version: 3.5
  - Moviepy Version: 0.2.3.5
  - Platform Name: NVIDIA TX2, Ubuntu 16.04

Let me know what am I supposed to do.

**Comment by Zulko** [comment]
please provide more infos, the excerpts of the script and the error may not be enough to understand what is going on.

**Comment by Flock1** [comment]
This is the full error I'm getting:
```
Traceback (most recent call last):
  File "img_test.py", line 117, in <module>
    clip = VideoFileClip(video_file)
  File "/home/nvidia/.local/lib/python3.5/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/nvidia/.local/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/home/nvidia/.local/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 256, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```
The video file I'm trying to process is in `.avi` format. 

What other information do you need? let me know

**Comment by Flock1** [comment]
@Zulko @keikoro, can you help me with the issue?

**Comment by keikoro** [comment]
This is a very old issue based on a very old MoviePy version, so it's dubious/impossible to tell if it's still relevant.

Closing for this reason, but do report back if the issue persists when you try with the latest master (_not_ the last PyPI release).
