### ISSUE TITLE
crop missing from moviepy.video.fx.all

### ISSUE THREAD

**Issue by omsrisagar** [Zulko/moviepy#914]
### Expected Behavior
```from moviepy.video.fx.all import crop``` should not result in error

### Actual Behavior
```from moviepy.video.fx.all import crop``` results in "cannot find reference crop in __init.py__"

### Steps to Reproduce the Problem

```from moviepy.video.fx.all import crop```. Please mention where the crop is located in v1.0

### Specifications

  - Python Version: 3.6.8
  - Moviepy Version: 1.0.0
  - Platform Name: Windows 10 64 bit 
  - Platform Version: Windows 10 64 bit

**Comment by dror-weiss** [comment]
`from moviepy.video.fx import crop`

**Comment by omsrisagar** [comment]
Thank you, it works now!
