### ISSUE TITLE
No release notes for 1.0.0?

### ISSUE THREAD

**Issue by dmyersturnbull** [Zulko/moviepy#917]
### Expected Behavior
Prominent release notes for a major version number change. Is the new release even backwards compatible?

### Actual Behavior
I wasn't able to find any documentation on the moviepy website, Github, or pypi.

**Comment by Zulko** [comment]
Sorry for that, it is a release done in a real hurry (I am completely under the water and other maintainers look busy too) to reflect two changes:

- imageio changed its API and is basically dropping python2 support. this broke moviepy
- there are new backwards-incompatible changes regarding progress bars logging (see "New in 1.0.0" in the readme).

This is not a prominent release (it's not like we have a development cycle or anything), the major version bump is just there to signal backwards incompatibility.

**Comment by tburrows13** [comment]
Basic release notes added. See #1020 for v1.0.0-specific documentation needs.
