### ISSUE TITLE
Segfault for import moviepy.editor, but not for import moviepy

### ISSUE THREAD

**Issue by aarslan** [Zulko/moviepy#92]
Hi,
It's actually as simple as the title says. I made sure that the ffmpeg is the most recent version (downloaded from http://www.ffmpeg.org/download.html), and it is installed in working condition.
Importing moviepy is fine, but import moviepy.editor results in segmentation fault without any other output on the command line.
I made sure numpy, decorator and tqdm are also up to date using pip install --upgrade.
I'm running Ubuntu 14.04.1 LTS and python 2.7.

Is there a way to understand where is the segfault coming from?

$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import moviepy
> > > import moviepy.editor
> > > Segmentation fault (core dumped)

**Comment by anntzer** [comment]
It seems that moviepy.editor segfaults with OpenCV3 (which may be the limitation seen by the OP).  Any chance OpenCV3 can be supported, or this limitation indicated in the docs?
Thanks.

**Comment by wackywendell** [comment]
@anntzer

I see no trouble with opencv 3.1.0.

I'm on Arch Linux, with `moviepy` installed via `pip --user`. If you're still having issues, could you please open a new issue, with a more complete description of the error you saw, and why you suspect its OpenCV3?

**Comment by anntzer** [comment]
The issue seems to be fixed with opencv 3.1.0 indeed (I suspected opencv3 because importing moviepy would segfault when it was installed (Arch Linux AUR opencv-git) but not when opencv2 was installed (Arch Linux standard repos)).

**Comment by wackywendell** [comment]
@anntzer: Could you open a new issue for this, and report the full error you're seeing?

Also, opencv 3.1.0 is in the Arch standard repos, and with it, I have had no issues with `moviepy`. We can't do anything for you on this issue without more information!

**Comment by anntzer** [comment]
I was exactly saying that the issue is solved by 3.1.0, so it's not a problem anymore except if you also want to maintain compatibility with 3.0.0.

**Comment by wackywendell** [comment]
Oh, sorry! I completely misread. Thanks for the update!
