### ISSUE TITLE
Clips Freeze in The Begining

### ISSUE THREAD

**Issue by zilton7** [Zulko/moviepy#920]
Hey there,
After extracting clips with "ffmpeg_extract_subclip" each clip freezes for like 5 secs in the beginning. I was researching online and added '-ss' and '-i' parameters (not even sure what they do) what seemed to help at first, but now it seems to freeze again... what to do? :)

Here exactly what I use to extract:
`    ffmpeg_extract_subclip(video_source, "-ss", float(time1), float(time2), "-i", targetname=f"{dir}/clips/{file_count}_clip.mp4")
`

### Expected Behavior
No frozen seconds before the clip starts playing.

### Actual Behavior
Some clips are frozen at the beginning for 3-5 seconds

### Steps to Reproduce the Problem
`    ffmpeg_extract_subclip(video_source, "-ss", float(time1), float(time2), "-i", targetname=f"{dir}/clips/{file_count}_clip.mp4")
`

### Specifications

  - Python Version: 3.7.2
  - Moviepy Version: 0.2.3.5
  - Platform Name: Linux
  - Platform Version: Ubuntu 16.04

**Comment by Jack-Collins** [comment]
seeing this also

**Comment by halesyy** [comment]
+1

**Comment by keikoro** [comment]
Closing this issue as it's based on an old MoviePy version, so impossible to tell if it's still relevant.

Do report back – following our issue template – if the problem persists when you try with the latest master (not the last PyPI release).
