### ISSUE TITLE
ffmpeg_parse_infos silently hangs on Windows when MP4 file contains enough metadata

### ISSUE THREAD

**Issue by Overdrivr** [Zulko/moviepy#926]
Loading any mp4 file with enough chapters in metadata causes a silent hang without error.

After investigating a little bit, I have found that the silent hanging is caused by the process opened to call FFMPEG when retrieving file metadata. If the metadata is too large (caused by having many chapters in the video for instance), FFMEPG will print all this metadata to STDOUT/STDERR and my hypothesis is that somehow the pipe's buffer gets filled up entirely causing the hanging. _(Not sure about this explanation though, if someone has more experience with Processes/Pipes feedback would be welcomed.)_ 

### Steps to Reproduce the Problem

```
from moviepy.editor import *
audio = AudioFileClip('new_sintel.mp4')
```

To reproduce, please find attached a zip containing a trailer of the [open Sintel movie](https://download.blender.org/durian/trailer/), where I have [manually added chapters using FFMPEG](https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687). With ~10 chapters, moviepy loads metadata successfully, but with ~15 chapters it hangs. The ZIP contains the version where it hangs:

[new_sintel.zip](https://github.com/Zulko/moviepy/files/2982581/new_sintel.zip)

Just in case, this is the dummy metadata I have placed in the file:

[chapters.txt](https://github.com/Zulko/moviepy/files/2982602/chapters.txt)

I can provide a fix, I hope it can get released pretty quickly because I need to fix this for work.

### Specifications

  - Python Version: 3.6
  - Moviepy Version: 1.0.0 (ffmpeg: 4.1)
  - Platform: Win10

**Comment by Overdrivr** [comment]
This seems to be Windows-specific. Unit tests fail on my Windows machine but passes in the CI (Unix-based).

**Comment by bertwagner** [comment]
I am experiencing this same problem on Windows.

**Comment by MagnifierSun** [comment]
@Overdrivr this is because the linux PIPE full so that it hang on .change the config  "stderr": sp.PIPE  -> 
"stderr":None   to avoid use pipe so this problem will not happen
