### ISSUE TITLE
OSError: MoviePy Error: creation of None failed because of the following error:

### ISSUE THREAD

**Issue by richardjohnson23** [Zulko/moviepy#928]
convert: not authorized `@/tmp/tmpv7ojzua0.txt' @ error/constitute.c/ReadImage/454.
convert: no images defined `PNG32:/tmp/tmpmw9aikq2.png' @ error/convert.c/ConvertImageCommand/3046.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

I'm using Python 3.6.8, CentOS 6, Version: ImageMagick 6.7.8-9 2019-02-01 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

I tried removing the line from policy.xml. The tmp folder got 777 (permission)

**Comment by TFDeeplearner** [comment]
I met the sampe quesetion. does it have a solution?

**Comment by baiyuxiong** [comment]
Check ImageMagick permissions on "/etc/ImageMagick-6/policy.xml" you should change the none to read,write, maybe run: cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g'> /etc/ImageMagick-6/policy.xml

**Comment by tburrows13** [comment]
See #1472 - TextClips are being re-implemented in v2.0 so this will no longer be an issue.

**Comment by trunkey2003** [comment]
> cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g'> /etc/ImageMagick-6/policy.xml

This work for me when I get to policy.xml and edit <policy domain="path" rights="none" pattern="@*"/> to <policy domain="path" rights="read,write" pattern="@*"/>

**Comment by trunkey2003** [comment]
This method work for me when I get to policy.xml and edit from "policy domain="path" rights="none" pattern="@"" to "policy domain="path" rights="read,write" pattern="@""

**Comment by dhrm1k** [comment]
Changing the policy.xml to `<policy domain="path" rights="read|write" pattern="@*"/>` worked for me too.
