### ISSUE TITLE
Issue with ffmpeg version

### ISSUE THREAD

**Issue by AWAS666** [Zulko/moviepy#934]
Problem:
After installing ffmpegversion 20190331-27c94c5 moviepy couldn't export any audio

Solution:
Installed ffmpeg 4.1.1 Release Build and that got it working again

[ffmpeg source](https://ffmpeg.zeranoe.com/builds/)

just a heads up for you guys even though it is more ffmpeg related
have a nice day :)

**Comment by tburrows13** [comment]
Should be fixed in #968.
