### ISSUE TITLE
ImageClip.write_videofile() outputs black screen

### ISSUE THREAD

**Issue by EthanThatOneKid** [Zulko/moviepy#935]
### Expected Behavior
Create a video slideshow of images being played along with a respective audio file.

### Actual Behavior
The output plays the audio, but the images do not show, leaving only a black screen.

### Steps to Reproduce the Problem

```
from moviepy.editor import *

# Main Process
fps = 24
clip1PhotoPath = "path/to/img0.jpeg"
clip1AudioPath = "path/to/audio0.mp3"
clip2PhotoPath = "path/to/img1.jpeg"
clip2AudioPath = "path/to/audio1.mp3"

audClip1 = AudioFileClip(clip1AudioPath)
audClip2 = AudioFileClip(clip2AudioPath)
clips = [
    ImageClip(clip1PhotoPath).set_fps(fps).set_duration(audClip1.duration).set_audio(audClip1),
    ImageClip(clip2PhotoPath).set_fps(fps).set_duration(audClip2.duration).set_audio(audClip2)
]

final_video = concatenate_videoclips(clips, method='chain')
final_video.write_videofile("test.mp4", fps=fps)
```
Considerations: I have tested this where `final_video` has been `concatenate()`, `concatenate_videoclips()`,  and with just a single `ImageClip`. All of them result in a black screen. I have also tested this with and without `set_fps()`; also same result. I have also tested this with many different image formats (png, jpg, and jpeg). I'm confused...

### Specifications

  - Python Version: 3.7.2
  - Moviepy Version: current version (as of 4/3/19)

**Comment by hzhijin** [comment]
I encountered the same problem, and finally I figured it out: check the size of the image you clip. If one of the dimensions of the image's size is odd, then resize it to the even and the image will show up in the video. Will this can help you.

**Comment by rawadtraboulsi** [comment]
I am facing a similar issue with a video.
I simply load the video with `VideoFileClip`, and use `my_video.write_videofile` with the following params:
- codec='mpeg4'
- audio_codec='aac'

On android the video does not play, on iOS and desktop (FLV) it plays well. did you face such an issue on different devices?
