### ISSUE TITLE
How to read an mp4 file from s3 bucket directly into moviepy without writing local temp file

### ISSUE THREAD

**Issue by racket99** [Zulko/moviepy#942]
Any idea how to read an S3 mp4 file directly into moviepy?

I have tried,

    import boto3
    from io import BytesIO
    from moviepy.editor import *

    client = boto3.client('s3')
    obj =  client.get_object(Bucket='some-bucket', Key='some-file')
    VideoFileClip(BytesIO(obj['Body'].read())) 

but I am getting,

     Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/<path>/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__fps_source=fps_source)
     File "/<path>/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__fps_source)
     File "/<path>/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 243, in ffmpeg_parse_infos
     is_GIF = filename.endswith('.gif')
    AttributeError: '_io.BytesIO' object has no attribute 'endswith'

where <path> is my virtual environment. All I want to do is get some clip duration and other info on an mp4 in an s3 bucket without downloading.

**Comment by keikoro** [comment]
@racket99 I feel more information is needed for anyone to try to reproduce your problem. I'd ask you to add the info we ask for in our issue template (like platform used etc.)

Closing this for now, but feel free to reopen the issue/ping me to reopen it for you.

Same goes for anyone else interested in a solution (I'm aware of the reacjis on this post indicating interest).

**Comment by pooya-mohammadi** [comment]
@keikoro Hi, I believe the following example would make it easy for you to test:
```
from io import BytesIO
with open("video.mp4", mode="rb") as f:
    file = f.read()
VideoFileClip(BytesIO(file))
```
Consider a video.mp4 is a video. Read it as bytes, convert it to bytesio pass it to VideoFileClip. You'll get the following error:

```
AttributeError                            Traceback (most recent call last)
Cell In[43], line 1
----> 1 VideoFileClip(BytesIO(file))

File ~\miniconda3\envs\tf2_gpu\lib\site-packages\moviepy\video\io\VideoFileClip.py:88, in VideoFileClip.__init__(self, filename, has_mask, audio, audio_buffersize, target_resolution, resize_algorithm, audio_fps, audio_nbytes, verbose, fps_source)
     86 # Make a reader
     87 pix_fmt = "rgba" if has_mask else "rgb24"
---> 88 self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
     89                                  target_resolution=target_resolution,
     90                                  resize_algo=resize_algorithm,
     91                                  fps_source=fps_source)
     93 # Make some of the reader's attributes accessible from the clip
     94 self.duration = self.reader.duration

File ~\miniconda3\envs\tf2_gpu\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:35, in FFMPEG_VideoReader.__init__(self, filename, print_infos, bufsize, pix_fmt, check_duration, target_resolution, resize_algo, fps_source)
     33 self.filename = filename
     34 self.proc = None
---> 35 infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
     36                            fps_source)
     37 self.fps = infos['video_fps']
     38 self.size = infos['video_size']

File ~\miniconda3\envs\tf2_gpu\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:244, in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    231 """Get file infos using ffmpeg.
    232 
    233 Returns a dictionnary with the fields:
   (...)
    239 
    240 """
    243 # open the file in a pipe, provoke an error, read output
--> 244 is_GIF = filename.endswith('.gif')
    245 cmd = [get_setting("FFMPEG_BINARY"), "-i", filename]
    246 if is_GIF:

AttributeError: '_io.BytesIO' object has no attribute 'endswith'
```

**Comment by davidbernat** [comment]
cc: @Zulko @OsaAjani c.f. making as requested improvement.

AudioFileClip and VideoFileClip do not allow BytesIO, or in memory files; the underlying root limitation is the `cmd` process `FFMPEG_BINARY` requires a path, which in this case is run to access metadata. It is a very common design pattern limitation, and so I think a good one to represent improvements to how `moviepy` and `FFMPEG_BINARY` interact, which is the core of `moviepy`. There is great benefit of operating in a pure-RAM environment in which secure data never touches disk, even though the improvement in speed may be marginal, depending on how `moviepy` returns to memory to read intervals of data. This issue is not restricted to only cloud buckets, so I would like to re-open this issue by moving this to a new ticket marked improvement. Quorum? Thoughts? 

(P.S. as a matter of security I do not use S3 buckets)
