### ISSUE TITLE
HEIC format not supported

### ISSUE THREAD

**Issue by hassanrazakhalid** [Zulko/moviepy#944]
Hi 
I am using moviePy 0.2.3.5. It is working but when i try to open .HEIC which new IOS image format i get value error. <class 'tuple'>: ("Could not find a format to read the specified file in mode 'i'",). Can some please help why it is not working with .HEIC

**Comment by keikoro** [comment]
@hassanrazakhalid We'll need more info to help debug the issue.

I'm closing this for now but feel free to reopen it with the info we ask for via our issue template (platform used etc.) if the problem persists with the latest recommended version of MoviePy. Please also reference the parts of the docs that point in the direction of what you're trying to do, thanks.
