### ISSUE TITLE
Broken Audio When Running write_videofile

### ISSUE THREAD

**Issue by bananakiu** [Zulko/moviepy#947]
When I run write_videofile() on a concatenated video flip, there will be times I have a looping audio issue within one of those clips. I have to rerun write_videofile() (and thus overwrite my existing file) to fix the issue. It seems like it's a lottery.

**Comment by keikoro** [comment]
We need more information to try to reproduce the problem.
Please add the info we ask for in our issue template (platform used etc.).

Closing this for now.
