### ISSUE TITLE
TextClip.list('font') raises UnicodeDecodeError in python3

### ISSUE THREAD

**Issue by rickey-yao** [Zulko/moviepy#948]
### Expected Behavior

TextClip.list('font')

### Actual Behavior

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8: invalid start byte

### Specifications

  - Python Version: python3.7.3
  - Moviepy Version:1.0.0
  - Platform Name:Windows
  - Platform Version:Windows10

**Comment by fulb** [comment]
将:
` "D:\Anaconda3\envs\test\lib\site-packages\moviepy\video\VideoClip.py", line 1201, in list
    return [l.decode('UTF-8')[8:] for l in lines if l.startswith(b"  Font:")]`
修改为:
` "D:\Anaconda3\envs\test\lib\site-packages\moviepy\video\VideoClip.py", line 1201, in list
    return [l.decode('GBK')[8:] for l in lines if l.startswith(b"  Font:")]`
解决

**Comment by brainstormot** [comment]
`[l.decode('CP949')[8:] for l in lines if l.startswith(b"  Font:")]`
The above code works in Windows. But It is better to make variable whcih indicates OS encoding.

**Comment by keikoro** [comment]
Following the chain of linked issues, it appears this issue was resolved in #1119. Feel free to reopen if that's not the case.
