### ISSUE TITLE
"ValueError: Attribute 'duration' not set" when using fl_time

### ISSUE THREAD

**Issue by Extemma** [Zulko/moviepy#949]
I'm trying to use the fl_time function to change the video time rate.

### Expected Behavior
A video preview should play with a time rate of change of t+sin(t)

### Actual Behavior
Ends up with "ValueError: Attribute 'duration' not set" instead

### Steps to Reproduce the Problem
```
import moviepy.editor as mp
import numpy as np

video = mp.VideoFileClip('wow.mp4')

video2 = video.fl_time(lambda t: t+np.sin(t))
video2.preview()
```

### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.0.0
  - Platform Name: Windows
  - Platform Version: 10

**Comment by Zulko** [comment]
After using fl_time you must set the duration of the result manually, for instance:

video2.duration = video.duration

**Comment by tburrows13** [comment]
Even better, use `video2 = video2.set_duration(video.duration)`.
