### ISSUE TITLE
hangup on line 'proc.stdout.readline()' when open mp3

### ISSUE THREAD

**Issue by DaveScream** [Zulko/moviepy#952]
Program hangs when Im trying to open MP3 file (link https://yadi.sk/d/NvxwqHVRg4wEnQ)

track = AudioFileClip(track_path)

Hang location:
file: moviepy/video/io/ffmpeg_reader.py
function: ffmpeg_parse_infos
line: proc.stdout.readline()

mp3 file is correct, foobar2000 can play and read tags, other mp3 files from this folder/album are similar and work okay with moviepy.

### Specifications

  - Python Version: 3.7.2
  - Moviepy Version: 1.0.0
  - Platform Name: Windows 10 x64
  - Platform Version:

**Comment by DaveScream** [comment]
The problem is fixed in latest version of file from repository
proc.stdout.readline
was replaced by
(output, error) = proc.communicate()

how to Install latest version of moviepy from github? 

pip install git+https:// what next?

**Comment by tburrows13** [comment]
Looks like this was fixed in v1.0.1.
