### ISSUE TITLE
Is per-pixel, partial transparency possible in MoviePy?

### ISSUE THREAD

**Issue by zamirkhan** [Zulko/moviepy#955]
I'm trying to create some text effects with Moviepy (and gizeh, at the moment). I understand how I can use a mask to set binary transparency (fully transparent or opaque) on a per-pixel level. I also understand how I can use `set_opacity` to set a partial transparency (between 0 and 1) but for an entire video clip. 

I'm looking for a way to add partial transparency (between 0 and 1) but on a per-pixel level (like a mask). I can create a RGBA image in gizeh that does this, but then I am unable to combine this together with a video clip that only has 3 channels. I've tried using `has_mask=True` to force the clip to have 4 channels, but this did not work. 

Is it possible to do per-pixel, partial transparency with moviepy? (doesn't have to be with gizeh)

Bonus question: is it possible to animate transparency with `set_opacity`, the same way that we can animate position with `set_pos`, but using a lambda function? Based on my preliminary look at the documentation, this doesn't appear to be possible because `set_opacity` does not accept a lambda function, but I'm curious if anyone has achieved this.

Thanks!

**Comment by ODtian** [comment]
it's pretty easy:
`   @add_mask_if_none
    @outplace
    def set_opacity(self, op):
        """Set the opacity/transparency level of the clip.

        Returns a semi-transparent copy of the clip where the mask is
        multiplied by ``op`` (any float, normally between 0 and 1).
        """
        self.mask = self.mask.fl_image(lambda pic: op * pic)`
so you can just replace the origin mask,here is my code:
`def opacity(clip):
    def d(t, k=1, m=4):
        return -1/(1+k*t**m)+1
    mask_clip = clip.mask.fl(lambda gf, t: gf(t)*d(t))
    return clip.set_mask(mask_clip)`

**Comment by keikoro** [comment]
@zamirkhan Did the above help solve your issue?

**Comment by keikoro** [comment]
Closing this due to lack of response after a potential solution was proposed.
