### ISSUE TITLE
Concatenating VideoFileClip is too slow 

### ISSUE THREAD

**Issue by sandeepbalagopal09** [Zulko/moviepy#961]
In our django project we are receiving a text from the user and integrating the text to 6 different parts of the the video. Below is the code we are using. It is very slow, takes more than 1 minute to load the page. Is there any way to load it faster ?  

```
def videoView(request):
    if request.method == "POST":
        brand=request.POST["brand"]
        video = VideoFileClip("video.mp4").subclip(0,3)
        
        txt_clip = ( TextClip(brand,fontsize=40,color='black', font="Helvetica-Bold")
                     .set_position((1325,670))
                     .set_duration(3) )
        result1 = CompositeVideoClip([video, txt_clip])

        video = VideoFileClip("video.mp4").subclip(3.01,6)        
        txt_clip = ( TextClip(brand,fontsize=40,color='black')
                     .set_position((450,450))
                     .set_duration(3) )
        result2 = CompositeVideoClip([video, txt_clip]) # Overlay text on video

        video = VideoFileClip("video.mp4").subclip(6.01,9)
        txt_clip = ( TextClip(brand,fontsize=40,color='black')
                     .set_position((1305,590))
                     .set_duration(3) )
        result3 = CompositeVideoClip([video, txt_clip]) # Overlay text on video

        video = VideoFileClip("video.mp4").subclip(9.01,12)
        txt_clip = ( TextClip(brand,fontsize=40,color='black')
                     .set_position((1235,520))
                     .set_duration(3) )
        result4 = CompositeVideoClip([video, txt_clip]) # Overlay text on video

        video = VideoFileClip("video.mp4").subclip(12.01,15)
        txt_clip = ( TextClip(brand,fontsize=40,color='black')
                     .set_position((470,500))
                     .set_duration(3) )

        result5 = CompositeVideoClip([video, txt_clip]) # Overlay text on video

        video = VideoFileClip("video.mp4").subclip(15.01,18.08)
        txt_clip = ( TextClip(brand,fontsize=40,color='black')
                     .set_position((1250,510))
                     .set_duration(3) )
        result6 = CompositeVideoClip([video, txt_clip]) # Overlay text on video

        result = concatenate([result1, result2, result3, result4, result5, result6]) # Overlay text on video
        result.resize(width=480).write_videofile("media/{}.webm".format(brand) ,
        fps=5,threads=4,logger=None, audio=False) # Many options...

    else:
        brand=None
        print("Sorry,Something went wrong.")
    return render(request, 'video/video_display.html',{'brand':brand})
```

**Comment by Zulko** [comment]
I can't see anything unusual here. How big is the videoclip? Around 1600x900? What kind of machine (CPU rate etc.) does this run on?

**Comment by sandeepimpressads** [comment]
It runs on a 1GB Amazon lightsail instance. Video file has size  1920 x 1080

**Comment by Zulko** [comment]
Ok that might be the problem. Video editing is expensive. The only thing worth trying would be to tune the quality of the output., or try installing OpenCV so that the "resize" operation is faster.

Just a comment, here is a much easier way of doing what you are trying to do (It should also make it very slightly faster):

```python
def txt_position(t):
    if t < 3: return (1325,670)
    elif t < 6: return (450,450)
    elif t < 9: return (1305,590)
    # etc...
video = VideoFileClip("video.mp4").subclip(0,18)
txt = TextClip(brand,fontsize=40,color='black').set_position((txt_position)
final_clip = CompositeVideoClip([video, text]).set_duration(video.duration)
final_clip.resize(width=480).write_videofile(...)
```

**Comment by sandeepimpressads** [comment]
Thank you for putting your effort on looking into this issue. We were able to improve the speed by reducing the video size. 

Thanks for the code as well :) It reduced the code size in a big way. But the loading time is almost same.

**Comment by sandeepimpressads** [comment]
Even though it is fine for us loading the video in 12s, the site's memory overflows when we have more visits to the website. Our 1GB instance crashed just with 5 concurrent users. Any suggestions to improve ? Using a 4GB or 8 GB instance going to work ? We are expecting atleast 1000 concurrent visits.

**Comment by sandeepimpressads** [comment]
@Zulko We have an issue with write_videofile(), It seems that write_videofile is waiting for some resource to be released to write new. When we have one request we get response in 10s, but when there is 5 concurrent requests, we get response in 50s for each.

**Comment by Beadsworth** [comment]
I am also experiencing prohibitively slow video-writing.  See below for simple code example -- 10 second clip with low-def resolution, 1FPS, ultrafast setting takes 40 seconds to render.  This is on a computer with 4.0 GHz, 4 core CPU & 32GB RAM.

```
import moviepy.editor

input_path = r'some\input\path.mp4'
output_path = r'some\output\path.mp4'

clip1 = moviepy.editor.VideoFileClip(filename=input_path).subclip(t_start=0, t_end=10)

clip1.write_videofile(output_path, preset='ultrafast', fps=1, audio=False)
```

**Comment by bode135** [comment]
maybe u can use cuda accelerate...<br>
It's work for me , on Win10 and ffmpeg 4.2.3 version, NVIDA GPU, and speeded up 5~10 times..

```
'''
here is concat videos with cuda accelerate.
so you can subclip the video fragment and clip them, then concat with others.
'''


import os

def save_flist(files):
    f_data = 'file \'' + '\'\nfile \''.join(files) + '\''
    print(f_data)

    f_list = 'list.txt'
    with open(f_list, 'w', encoding='gbk') as f:
        f.write(f_data)
    return f_list

video_path = r'E:\py\mkv\\'
os.chdir(video_path)

output_path = 'output.mkv'

files = ['1.mkv', '2.mkv', '3.mkv', '4.mkv']
print(files)        # your video_names.

f_list = save_flist(files)

call = f'ffmpeg -f concat -safe 0 -i {f_list} -c copy {output_path} -y'         # only supporte the same video_format, copy and not recode.

call = f'ffmpeg -f concat -safe 0 -i {f_list} -vcodec h264_nvenc output.mkv -y'    # cuda accelerate.

print(call)

os.system(call)

os.remove(f_list)
```
hope it can help you.

**Comment by Beadsworth** [comment]
@bode135 thanks for the tip.

Yes, I also used a direct ffmpeg call for simple concatenation, and the execution time dropped drastically (x100 improvement).  It seems movie.py creates a lot of overhead for concatenation.

For others looking to do simple concatenation, where file types are all the same, I suggest you use ffmpeg directly.

**Comment by keikoro** [comment]
Closing this issue as we haven't heard back from OP since 2019 and the suggestions above sound like useful workarounds.
