### ISSUE TITLE
Frame rate issue in CompositeVideoClip

### ISSUE THREAD

**Issue by zamirkhan** [Zulko/moviepy#962]
I'm creating a `CompositeVideoClip` composed of 3 clips (as a test, the number of videos is not relevant). Let's call them clips A, B, and C. However, in the final output, clip C renders with the video track playing very fast, but the audio track playing at the correct speed. This means that the video portion of clip C ends prematurely and you just see the final freeze frame while the audio finishes.

This happens to clip C regardless of where it appears in the sequence (first, second, or third). All 3 clips are `VideoFileClip`. The interesting thing is that when I inspect these video files with a 3rd party tool (e.g. VLC, or Handbrake), they all report the same numbers for FPS (e.g. clip B is 25 fps, clip C is 29.6fps), but when I load them as `VideoFileClip`s in moviepy, it seems to think that clip B is 29.9fps (instead of 25) and clip C is 50fps (instead of 29.6). I thought that perhaps using `.set_fps(30)` on all of the clips would help, but it does not. It almost seems as if clip C's video track is playing at exactly double speed, which makes some sense (50/25 = 2x). I thought the `CompositeVideoClip` was supposed to handle different frame rates, is that incorrect?

Any ideas as to what's going wrong?

**Comment by zamirkhan** [comment]
After looking at Clip C in more detail with `ffprobe`, I see that the fps (29.9) and the tbr (50) were quite different. Changing the `fps_source` to be `fps` did not help, but it made me think that this particular file was unusual, as most of my clips have either `fps == tbr` or the values are at least quite close. It's interesting, when I play the video clip in any player alone, the video and audio are perfectly synced. However, if I run them through moviepy (or perhaps FFMPEG), it becomes distorted and I suspect it's due to this weirdness in the metadata.

**Comment by keikoro** [comment]
Closing this as there's a probability the original issue was due to a problem with the file (see above).
