### ISSUE TITLE
ImageSequenceClip not supporting masks for Numpy arrays

### ISSUE THREAD

**Issue by cyberh49** [Zulko/moviepy#963]
Hi,

I'm trying to use ImageSequenceClip with numpy arrays of png images I created using a script.

When trying to save a video, I noticed that, according to the documentation -
"A list of Numpy arrays representing images. In this last case, masks are not supported currently."

Is it going to change anytime soon? I think it is a crucial feature for many users.

Would appreciate a reply, even if it is a negative one.

Thanks a lot for the wonderful work with this package.

**Comment by keikoro** [comment]
Closing this issue as it's old and missing information needed to try to reproduce the problem.

Do report back – following our issue template – if the problem persists when you try with the latest master of MoviePy (not the last PyPI release).
