### ISSUE TITLE
ModuleNotFoundError: No module named 'bab

### ISSUE THREAD

**Issue by escoiq** [Zulko/moviepy#965]
Hello everyone , 
i am installing Odoo 12 on Ubuntu 19 
i am following this (https://linuxize.com/post/how-to-deploy-odoo-12-on-ubuntu-18-04/)
and faced an error when installing python 
the error says (Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qnttnat5/psycopg2/)
when i decide to go forward and complete the steps i got this error 
(
odoo12.service - Odoo12    Loaded: loaded (/etc/systemd/system/odoo12.service; disabled; vendor preset:    Active: failed (Result: exit-code) since Wed 2019-05-29 21:51:44 PDT; 6s ago   Process: 25161 ExecStart=/opt/odoo12/odoo-venv/bin/python3 /opt/odoo12/odoo/o  Main PID: 25161 (code=exited, status=1/FAILURE)
)

pls advice 

  - Python Version:
  - Moviepy Version:
  - Platform Name:
  - Platform Version:

**Comment by Zulko** [comment]
Are you sure this error is caused by Moviepy?

**Comment by husamobaid** [comment]
Hello Zulko, 
its appear in one of the steps of installing Odoo that i shared with you 
and i will share a snapshot if you like to have better idea about the error 

Regards,

**Comment by flothesof** [comment]
I just went through the linked article and the Odoo requirements.txt and could not find anything there about moviepy. This seems like a false positive. I therefore think this issue can be closed.
