### ISSUE TITLE
Add support for pathlib

### ISSUE THREAD

**Issue by fepegar** [Zulko/moviepy#966]
It would be nice to add support [`pathlib`](https://www.python.org/dev/peps/pep-0428/), as others (such as NumPy or PIL) do. Converting all input path arguments to `str` would probably be enough.

**Comment by Zulko** [comment]
Sorry I didnt get it can you elaborate?

**Comment by fepegar** [comment]
Sure.
```python
In [1]: from pathlib import Path                                                                                                                                           
In [2]: from moviepy.video.io.VideoFileClip import VideoFileClip                                                                                                           
In [3]: video_path = Path('~/20080324143707A_Groom_14205-14235.mp4').expanduser()                                                                             
In [4]: clip = VideoFileClip(video_path)  
```

Currently, that code raises an Exception as `video_path` is a `pathlib.Path` object instead of a string. It's becoming more and more common to use `pathlib` for path handling in Python 3. For example, this is how Pillow added support for it: https://github.com/python-pillow/Pillow/pull/1372

I think moviepy should have support for this objects as well.

**Comment by anisayari** [comment]
Same request here. Any news on that ? 
Translate a pathlib to string to be able to use moviepyis not really efficient while using pathlib lib.

**Comment by anisayari** [comment]
Update : I was able to use `pathlib` with just the `as_posix()` method : 

`avi_files_list = pathlib.Path('path_to_my_avi_files_folder').glob('*.abi')
for anv_file in avi_files_list:
    clip = VideoFileClip(anv_file.as_posix())`

**Comment by tburrows13** [comment]
Done in #1137. At the moment, moviepy just converts the path object to a string as soon as it receives it. In the future it would be nice if it internally used Path objects until as late as possible down the pipeline, but that would require a larger rewrite which seems unnecessary seeing as it works fine currently.
