### ISSUE TITLE
i dont understand this question

### ISSUE THREAD

**Issue by jtop7128** [Zulko/moviepy#967]
this question is related to Markov Chains.

I need to know the answer that presents the search results in order of the final collection and final calculation of A, B, and C respectively and the order of the final collection.

def A_colculate(A,B,C):
    while True:
        k=0
        for i in range(A, A+k):
            k+=1
        return "0.1*A+0.6*B+0.4*C=", 0.1*(A+k)+0.6*(B+k)+0.4*(C+k), k

def B_colculate(A,B,C):
    while True:
        k=0
        for i in range(B, B+k):
            k+=1
        return "0.5*A+0.1*B+0.5*C=", 0.5*(A+k)+0.1*(B+k)+0.5*(C+k), k

def C_colculate(A,B,C):
    while True:
        k=0
        for i in range(C, C+k):
            k+=1
        return "0.4*A+0.3*B+0.1*C=", 0.4*(A+k)+0.3*(B+k)+0.1*(C+k), k

A0=float(input("A0값을 입력하시오"))
B0=float(input("B0값을 입력하시오"))
C0=float(input("C0값을 입력하시오"))

print(A_colculate(A0,B0,C0))
print(B_colculate(A0,B0,C0))
print(C_colculate(A0,B0,C0))

if A_colculate(A0,B0,C0)==B_colculate(A0,B0,C0)==C_colculate(A0,B0,C0):
    print(k)

A0값을 입력하시오0.333
B0값을 입력하시오0.333
C0값을 입력하시오0.333
Traceback (most recent call last):
  File "C:\Users\PJJ\Desktop\123.py", line 26, in <module>
    print(A_colculate(A0,B0,C0))
  File "C:\Users\PJJ\Desktop\123.py", line 4, in A_colculate
    for i in range(A, A+k):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by Zulko** [comment]
Sorry this is not the right place to ask!

**Comment by jtop7128** [comment]
> Sorry this is not the right place to ask!

Then where should I post the question?

**Comment by Zulko** [comment]
stackoverflow?

**Comment by jtop7128** [comment]
> stackoverflow?

what? can u speak easily? sorry im korean i dont understand

**Comment by Zulko** [comment]
Sorry. You should only ask questions here if you find bugs in the Moviepy Python library, or if you have questions about the Moviepy library. If your question is about something else, like Markov Chains, you should ask on another website. For instance the website Stackoverflow.
