### ISSUE TITLE
Examples resources videos directory missing 

### ISSUE THREAD

**Issue by meiry** [Zulko/moviepy#975]
I clone the latest code , install all dependencies , even 88 tests passed , 
but now i trying to execute the examples scripts , but there is no videos directory .
from where all the resources are loaded .
this is how my dir tree looks like :
![image](https://user-images.githubusercontent.com/1107316/59569056-d97a4180-908c-11e9-943d-2c64ad9f54ac.png)

**Comment by mondeja** [comment]
Closing as duplicate of #338.
