### ISSUE TITLE
there is a black background video, how can set this video's black to hyaline and mix to other video

### ISSUE THREAD

**Issue by zheyejs** [Zulko/moviepy#979]
### Specifications

  - Python Version:
  - Moviepy Version:
  - Platform Name:
  - Platform Version:

**Comment by zheyejs** [comment]
clips = list()
clip0 = VideoFileClip('../data/dream_writer.mp4').subclip(1, 20)
clips.append(clip0)
clip1 = VideoFileClip('../data/video.mp4')

clip1 = vfx.mask_color(clip1, color=[0, 0, 0])
clips.append(clip1.loop(duration=4).resize(0.3))
finalclip = CompositeVideoClip(clips, use_bgclip=True)
finalclip.write_videofile('out.mp4')


# this is my code, but black in video.mp4 is not all hyaline.

**Comment by keikoro** [comment]
Closing this issue as it's old and missing informationen needed to try to reproduce the problem.

Feel free to reopen it once you can provide the info we request via the issue template (the filelds you didn't fill out in the first post), in which case I'd also ask you to reformat your comments so code and regular text are distinguishable.
