### ISSUE TITLE
Pygame pollutes stdio with spammy message

### ISSUE THREAD

**Issue by Julian-O** [Zulko/moviepy#985]
Unfortunately, the maintainer of the PyGame repository has decided to add a spammy message that gets printed to stdio the first time `pygame` is imported. [Complaints about it](https://github.com/pygame/pygame/issues/542) have been dismissed with feeble justifications.

MoviePy will import pygame if it is installed, meaning command-line MoviePy applications will start up with an unrelated message about PyGame, which is likely to confuse most users.

Fortunately, a [workaround has now been included](https://github.com/pygame/pygame/commit/165bf99d1f3660287ee8a0d923da8de4d97e773b):

If the ``PYGAME_HIDE_SUPPORT_PROMPT `` environment variable is present, the message is not displayed.

Asking direct clients to create this variable before importing pygame is onerous, but expecting a client of MoviePy to understand what they need to do to suppress it is worse.

Therefore, I recommend that in each of the places that PyGame is imported, the environment variable be set first. 

(Perhaps a single shim file that does this work-around and imports PyGame in one place would be better. Then the shim could be imported instead of pygame in each location.)

### Expected Behavior

     >>> from moviepy.editor import VideoFileClip
     >>>

### Actual Behavior

     >>> from moviepy.editor import VideoFileClip
     pygame 1.9.6
     Hello from the pygame community. https://www.pygame.org/contribute.html
     >>>

### Steps to Reproduce the Problem

Install `pygame>=1.9.5` and `moviepy`, and run ` import moviepy.editor` for example.

**Comment by Julian-O** [comment]
>  Perhaps a single shim file that does this work-around and imports PyGame in one place would be better. 

I became so enamoured with this idea, I have made it its own package:

https://github.com/Julian-O/pygamesilent

Hasn't hit PyPi yet.

**Comment by Oj18** [comment]
You can just put:
```python
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
```

Before importing `moviepy`. It does require importing `os` though, I suppose.

**Comment by Julian-O** [comment]
Yes, you can do that. With sufficient commenting to explain the intent of this magic incantation, and repeated in every location that pygame is imported. 

I have gone with a shim based on DRY principles.

**Comment by tburrows13** [comment]
I'd agree with @Oj18, which is just a one-liner inside `moviepy.editor`

**Comment by Julian-O** [comment]
I am not going to the mat on this one, but it is at least three lines repeated identically in three files.

**Comment by tburrows13** [comment]
Yes, fair point. I'll let someone else decide between #985 and #1017.

**Comment by tburrows13** [comment]
#1017 has been merged 👍🏼
