### ISSUE TITLE
cross fade-in effects on duration

### ISSUE THREAD

**Issue by arianaa30** [Zulko/moviepy#986]
A general question on how cross fade-in affects total duration of video. I'm concanetating 5 sub-videos as below, each 3 seconds:

```
final = concatenate([sub[0],
                 sub[1].crossfadein(.5),
                 sub[2].crossfadein(.5),
                 sub[3].crossfadein(.5),
                 sub[4].crossfadein(.5)],
         padding=-1, method="compose")
```
Why the final length of video is 10 seconds? Given 4 times 0.5s affecting each side (so 4x0.5x2), I was expecting 15 - 4 so 11 seconds.

**Comment by vielleicht** [comment]
I thinks it is because you specified `padding=-1` which sets the next overlapping one second on the previous.

**Comment by arianaa30** [comment]
Ummm so just removing it should solve the issue?
I'm using it for a project where the output timing need to be exact.

**Comment by vielleicht** [comment]
no, depends on the result you expect. If you want the crossfade of 0.5 you have specify `padding=-0.5`
