### ISSUE TITLE
problem of using ffmpeg to read&write video and audio

### ISSUE THREAD

**Issue by a5680737** [Zulko/moviepy#989]
Dear Zulko and developers here，I have some questions about the use of ffmpeg, I hope you can help answer, thank you in advance!
I have read your article on how to use ffmpeg to read and write audio and video data (📷http://zulko.github.io/blog/2013/10/04/read-and-write-audio-files-in-python-using-ffmpeg/http://zulko.github.io/blog/2013/09/27/read-and-write-video-frames-in-python-using-ffmpeg/)

I think it benefits a lot. There are some questions though. In your article, the audio and video read&write process of the same file are separated. Can I read the audio and video data in the video file at the same time, write the audio and video data synchronously after certain processing, and generate the video file with audio?
This is the problem I face: I need to read live streams through http, and then get the audio and video data, analyze the frames, recognize the key frames to determine whether they meet the specific conditions, and then intercept the video clips that meet the specific conditions to generate short video files((It's like recognizing and intercepting goals in football live streams)). In short, I need to read the streaming data continuously, and then uninterruptedly recognizing and generating short video files, I wonder if these processes (mainly audio and video reading and writing, the recognition part has been completed) can be completed at one time through ffmpeg? Or is there a more elegant way than to download live video, read&write audio and video data separately, and then synthesize them? After all, this is not real-time enough.
Thank you for watching! and I'm looking forward to your generous answers.

**Comment by a5680737** [comment]
i don't know how to contact the author directly, so it's a issue have nothing to do with moviepy, sorry for that.

**Comment by keikoro** [comment]
@a5680737 Did you find anything in the MoviePy or FFMPEG docs that relates to your questions?

**Comment by keikoro** [comment]
Closing this issue as it's old and hasn't seen any response from OP in several years.
