### ISSUE TITLE
Possibility to avoid code duplication

### ISSUE THREAD

**Issue by almarklein** [Zulko/moviepy#99]
A while back I took some code from moviepy and used it to create an ffmpeg plugin for imageio. Since then I suppose both pieces of code for this purpose have diverged, which is a bit sad. Similarly, both projects now have code for gif. I was hoping we could explore a bit the possibilities for avoiding code duplication related to reading and writing of movie data.

I suppose to start off, we need a clear idea of the purpose of both projects. Imageio is intended to provide easy reading/saving of all sorts of image data. From simple images to volume, and including movie data. Imageio currently has plugins for ffmpeg, avbin, animated gif and swf (flash). The purpose of moviepy is (correct me if I'm wrong) to allow editing/processing of movie data (which is precisely what imageio does not want to do). 

One option would be to make imageio a dependency of moviepy, but I can imagine you're not waiting for another dependency. Also, I suppose you need dealing with sound, which imageio does not support. Similarly, I'm reluctant for an extra dependency for imageio.

Another option could be to write the code for ffmpeg and gif in a way that we could both use it in our projects. We'd have to agree on which library holds the reference, or at least be consistent with backporting. Not sure if it would work well in practice, but it might be worth a try ...

WDYT? Is this worth looking into, or would it be more pain than gain?

**Comment by kerstin** [comment]
Since imageio was integrated into MoviePy a long time ago, this can be closed.
