### ISSUE TITLE
大量视频合并时会造成内存超出

### ISSUE THREAD

**Issue by lianghongjie** [Zulko/moviepy#998]
问题： 大量视频时会内存超出，而且会是真实视频大小的十倍以上增长
eg: 100条6M视频 会占用10G内存

**Comment by x931890193** [comment]
每次操作完事以后，把clip close掉？

**Comment by ODtian** [comment]
一样的问题，linux上爆了，吃了12g，但是win上就没事，吃的内存也不多，迷惑

**Comment by keikoro** [comment]
Please resubmit your issue in English if you want us maintainers or the wider community of moviepy users to be able to help you. Closing this for now, but feel free to reopen for an EN version.
