### ISSUE TITLE
Use as a drop in replacement of Jumpcutter by CaryKH

### ISSUE THREAD

**Issue by DonaldTsang** [Zulko/moviepy#999]
See https://github.com/carykh/jumpcutter and https://www.youtube.com/watch?v=DQ8orIurGxw

**Comment by Zulko** [comment]
Hey I was unaware of this tool and it looks like it could benefit from MoviePy to avoid writing all the sound and images in separate files. See here for the same effect with MoviePy (25 lines of code!):

http://zulko.github.io/blog/2014/07/04/automatic-soccer-highlights-compilations-with-python/

**Comment by DonaldTsang** [comment]
Also would it be possible to add in other "visual markers" into the system like using machine learning or just standard OpenCV techniques? That would allow for greater variety of editing tricks.
See https://github.com/carykh/jumpcutter/issues/123

**Comment by Zulko** [comment]
Theoretically that's possible, but that's not something I would add to moviepy, you would need to build your project around it.
